import { expect, test } from '@playwright/test';

test.beforeEach(async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('unwashed.onboarding.v1','complete');localStorage.setItem('forge.settings.v1',JSON.stringify({appearance:{mode:'algo',theme:'dark'},learning:{course:'algo',language:'python'},watch:{autoplay:false,muted:true,engine:'system'}}));});
 await page.goto('/');
 if((page.viewportSize()?.width??1000)<=860) await page.getByLabel('Open menu').click();
 await page.getByTitle('Algo').click();
});

test('filter menus support keyboard navigation and aligned results',async({page},info)=>{
 const trigger=page.getByRole('button',{name:'Filter by topic',exact:true});
 await trigger.click();
 await expect(page.getByRole('listbox')).toBeVisible();
 await page.keyboard.press('ArrowDown');
 await page.keyboard.press('Enter');
 await expect(page.locator('.problem-topic-head')).toHaveCount(1);
 await expect(trigger).toContainText('Arrays & Hashing');
 await trigger.click();
 await page.screenshot({path:info.outputPath('filter-menu.png')});
 await page.keyboard.press('Escape');
 await expect(trigger).toBeFocused();
 const rows=page.locator('.problem-library .lesson-title');
 const left=await rows.first().evaluate(el=>el.getBoundingClientRect().left);
 expect(await rows.nth(1).evaluate(el=>el.getBoundingClientRect().left)).toBe(left);
 await expect(page.getByRole('listbox')).toBeHidden();
});

test('whiteboard draws, edits, exports and keeps a separate draft per problem',async({page},info)=>{
 await page.getByRole('button',{name:'Two Sum',exact:false}).first().click();
 await page.getByRole('button',{name:'Open whiteboard'}).click();
 const board=page.getByRole('dialog',{name:'Two Sum whiteboard'});
 await expect(board).toBeVisible();
 const rect=await board.boundingBox();
 expect(Math.round(rect!.width)).toBe(page.viewportSize()!.width);
 expect(Math.round(rect!.height)).toBe(page.viewportSize()!.height);
 const canvas=page.getByRole('img',{name:'Drawing canvas'});
 const bounds=(await canvas.boundingBox())!;
 const x=bounds.x+bounds.width*.35,y=bounds.y+bounds.height*.55;
 await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+60,y-30,{steps:12});await page.mouse.move(x+90,y+20,{steps:12});await page.mouse.up();
 await expect(board.locator('[data-stroke]')).toHaveCount(1);
 await board.getByRole('button',{name:'Undo',exact:true}).click();
 await expect(board.locator('[data-stroke]')).toHaveCount(0);
 await board.getByRole('button',{name:'Redo',exact:true}).click();
 await expect(board.locator('[data-stroke]')).toHaveCount(1);
 await board.getByRole('button',{name:'Rectangle',exact:true}).click();
 await page.mouse.move(x,y+50);await page.mouse.down();await page.mouse.move(x+100,y+100,{steps:5});await page.mouse.up();
 await expect(board.locator('[data-stroke]')).toHaveCount(2);
 await board.getByLabel('Custom ink color').fill('#239b78');
 await board.getByLabel('Brush size').fill('8');
 await board.getByRole('button',{name:'Arrow',exact:true}).click();
 await page.mouse.move(x,y+130);await page.mouse.down();await page.mouse.move(x+90,y+130,{steps:5});await page.mouse.up();
 await expect(board.locator('[data-stroke]').last()).toHaveAttribute('stroke','#239b78');
 await expect(board.locator('[data-stroke]').last()).toHaveAttribute('stroke-width','8');
 await board.getByRole('button',{name:'Text',exact:true}).click();
 await page.mouse.click(x,y-40);
 await board.getByLabel('Add a label or note').fill('left → right');
 await board.getByRole('button',{name:'Add text',exact:true}).click();
 await expect(board.locator('text[data-stroke]')).toContainText('left → right');
 await board.getByRole('button',{name:'Undo',exact:true}).click();
 await board.getByRole('button',{name:'Zoom in',exact:true}).click();
 await expect(board.locator('.board-view-controls')).toContainText('120%');
 await board.getByRole('button',{name:'Zoom out',exact:true}).click();
 await board.getByRole('button',{name:'Stroke eraser',exact:true}).click();
 await page.mouse.click(x+50,y+50);
 await expect(board.locator('[data-stroke]')).toHaveCount(2);
 await board.getByRole('button',{name:'Undo',exact:true}).click();
 await board.getByRole('button',{name:'Background #191c24'}).click();
 await board.getByRole('button',{name:'Dots',exact:true}).click();
 await page.screenshot({path:info.outputPath('whiteboard.png')});
 const download=page.waitForEvent('download');await board.getByRole('button',{name:'Export PNG'}).click();
 expect((await download).suggestedFilename()).toBe('py.nc.two-sum-whiteboard.png');
 await board.getByRole('button',{name:'Clear drawing',exact:true}).click();
 await page.getByRole('alertdialog').getByRole('button',{name:'Clear drawing',exact:true}).click();
 await expect(board.locator('[data-stroke]')).toHaveCount(0);
 await page.keyboard.press('Control+z');
 await expect(board.locator('[data-stroke]')).toHaveCount(3);
 await page.getByRole('button',{name:'Close whiteboard'}).click();
 await expect(page.getByRole('button',{name:'Open whiteboard'})).toBeFocused();
 await page.getByRole('button',{name:'Open whiteboard'}).click();
 await expect(board.locator('[data-stroke]')).toHaveCount(3);
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('hyzr.whiteboard.v1.py.nc.two-sum')!).strokes.length)).toBe(3);
 await page.keyboard.press('Escape');
 await expect(board).toBeHidden();
 // Return to the library and ensure the next problem has its own empty canvas.
 await page.reload();
 if((page.viewportSize()?.width??1000)<=860) await page.getByLabel('Open menu').click();
 await page.getByTitle('Algo').click();
 await page.getByRole('button',{name:'Contains Duplicate',exact:false}).first().click();
 await page.getByRole('button',{name:'Open whiteboard'}).click();
 await expect(page.getByRole('dialog').locator('[data-stroke]')).toHaveCount(0);
});
