import type { MathLecture } from "./lectures";

/** First course in algebraic structure, with explicit maps and quotients. */
export const MATH_ABSTRACT_ALGEBRA: MathLecture[] = [
  {
    lesson: "math.m22.l1", title: "Groups and homomorphisms",
    premise: "A group abstracts reversible composition. A homomorphism preserves that composition while possibly collapsing some elements.",
    idea: "A group (G,·) has an associative operation, identity e, and an inverse for each element. Commutativity is optional; groups satisfying it are abelian. A subgroup is a nonempty subset closed under products and inverses. A homomorphism φ:G→H satisfies φ(ab)=φ(a)φ(b), forcing identity to identity and inverses to inverses. Its kernel consists of elements sent to H's identity and its image is a subgroup of H. A homomorphism is injective exactly when its kernel contains only the identity. Always identify the operation: integers under addition form a group; integers under multiplication do not, because 2 has no integer multiplicative inverse.",
    worked: "Let φ:Z→Z/5Z send n to its residue class [n]. Then φ(a+b)=[a+b]=[a]+[b], so it is a group homomorphism for addition. Its kernel is 5Z, all multiples of 5, and its image is every residue class. The map is surjective but not injective because 0 and 5 have the same image.",
    interpretation: "The kernel records precisely which integers become indistinguishable after passing to residues.",
    trap: "Do not test subgroup closure under the product alone and forget inverses. A monoid can satisfy the first two group axioms without being a group.",
    practice: "Is φ:R→R_{>0}, φ(x)=e^x, a homomorphism from addition to multiplication? Find kernel and image.",
    solution: "Yes: e^{x+y}=e^x e^y. Kernel consists of x with e^x=1, namely {0}; image is all positive reals. Hence it is an isomorphism of (R,+) with positive reals under multiplication.",
    checks: [["Must a group be commutative?", ["No", "Yes", "Only if finite"], 0, "Nonabelian groups are common."], ["What does a homomorphism preserve?", ["The group operation", "Every element label", "Set order only"], 0, "φ(ab)=φ(a)φ(b)."], ["What kernel condition implies injectivity?", ["Only the identity is in the kernel", "The kernel equals G", "The image is empty"], 0, "Equal images then imply equal inputs."]],
  },
  {
    lesson: "math.m22.l2", title: "Cosets and quotient groups",
    premise: "Cosets partition a group into equally sized copies of a subgroup. A quotient group exists when multiplying cosets is independent of the chosen representatives.",
    idea: "For subgroup H≤G, left coset gH={gh:h∈H}. Cosets either coincide or are disjoint, so they partition G. In a finite group, Lagrange's theorem gives |G|=[G:H]|H|. A subgroup N is normal if gN=Ng for all g; only then is (gN)(hN)=ghN a well-defined group operation on cosets. Every subgroup of an abelian group is normal, but not in every nonabelian group. The quotient G/N treats all members of each coset as one element; the kernel of any homomorphism is normal.",
    worked: "In additive Z, take H=3Z. Its cosets are 3Z, 1+3Z, and 2+3Z. Because Z is abelian, H is normal and the quotient Z/3Z has three elements. Coset addition follows residue arithmetic, such as (1+3Z)+(2+3Z)=0+3Z.",
    interpretation: "A quotient forgets differences by elements of H while retaining a consistent operation.",
    trap: "Do not assume every subgroup gives a quotient group in a nonabelian setting. Verify normality or representative independence.",
    practice: "List cosets of 4Z in Z and compute (3+4Z)+(3+4Z).",
    solution: "The four cosets are 0+4Z,1+4Z,2+4Z,3+4Z. Their sum is 6+4Z=2+4Z. Addition is well-defined because 4Z is normal in the abelian group Z.",
    checks: [["What condition allows a quotient group G/N?", ["N is normal", "N is merely nonempty", "G is infinite"], 0, "Coset multiplication needs representative independence."], ["What do cosets of a subgroup do?", ["Partition the group", "Overlap arbitrarily", "Contain only identity"], 0, "Two cosets are equal or disjoint."], ["What does Lagrange say for finite G?", ["|H| divides |G|", "Every subgroup is normal", "G is abelian"], 0, "Cosets all have |H| elements."]],
  },
  {
    lesson: "math.m22.l3", title: "Isomorphism theorems",
    premise: "An isomorphism theorem says a homomorphism's image is exactly what remains after collapsing its kernel.",
    idea: "First isomorphism theorem: for φ:G→H, G/ker φ is isomorphic to im φ via g ker φ↦φ(g). Well-definedness follows because inputs in the same kernel coset have equal images; injectivity and surjectivity onto im φ follow directly. The second theorem relates H/(H∩N) with HN/N when N is normal, under the appropriate subgroup setting. The third says if N≤K are normal in G, then (G/N)/(K/N) is isomorphic to G/K. These theorems organize structure-preserving maps; always check normality and identify the actual image rather than assuming the whole codomain.",
    worked: "Let φ map integers to their classes modulo 6. Its kernel is 6Z and its image is the entire residue group. The induced quotient map sends the coset n+6Z to the residue class [n]. This is a well-defined bijective homomorphism, recovering the familiar residue group from the kernel.",
    interpretation: "The quotient is not arbitrary notation: it identifies exactly the inputs a map cannot distinguish.",
    trap: "Do not write G/ker φ≅H unless φ is surjective. The theorem identifies the quotient with im φ.",
    practice: "For φ:Z→Z/10Z, φ(n)=[2n], find kernel, image, and quotient isomorphism type.",
    solution: "[2n]=[0] modulo 10 exactly when 10 divides 2n, or 5 divides n, so kernel is 5Z. The image is the five even residue classes {0,2,4,6,8}. The first theorem gives Z/5Z isomorphic to that image, not to all ten residue classes.",
    checks: [["What is G/ker φ isomorphic to?", ["im φ", "The full codomain always", "The kernel itself"], 0, "Surjectivity onto the image is automatic."], ["Why is the induced quotient map well-defined?", ["Same coset implies same φ image", "All cosets have one member", "H is abelian"], 0, "Kernel differences vanish under φ."], ["When may im φ be replaced by H?", ["When φ is surjective", "Always", "Only when G is finite"], 0, "The image must fill the codomain."]],
  },
  {
    lesson: "math.m22.l4", title: "Group actions",
    premise: "A group action realizes abstract group elements as symmetries of a set. Orbits describe reachability; stabilizers describe what leaves a point fixed.",
    idea: "A left action G×X→X satisfies e·x=x and (gh)·x=g·(h·x). The orbit G·x={g·x:g∈G}; the stabilizer G_x={g:g·x=x} is a subgroup. For finite G, orbit-stabilizer says |G·x|=|G|/|G_x|. Burnside's lemma counts orbits of a finite action as the average over g∈G of the number of points fixed by g. Verify an action before invoking these formulas. Actions connect permutation groups, geometric symmetry, graph automorphisms, and equivalence classes.",
    worked: "Let the cyclic rotation group C₄ act on the four vertices of a square. The orbit of one vertex contains all four vertices. Only the identity rotation fixes that vertex, so stabilizer size is 1 and orbit-stabilizer gives 4=4/1. The action is transitive on vertices.",
    interpretation: "A small stabilizer means many distinct positions are reachable from one point; symmetry and orbit size balance exactly.",
    trap: "Do not confuse the orbit of a point with the whole set unless the action is transitive. A group can have several orbits.",
    practice: "Let C₄ rotations act on square corners and the center. How many orbits are there, and what is the center's stabilizer size?",
    solution: "The four corners form one orbit, while the center forms a singleton orbit, so there are two orbits. Every rotation fixes the center, so its stabilizer is all of C₄ with size 4. Orbit-stabilizer gives 1=4/4 for the center.",
    checks: [["What is a stabilizer?", ["Group elements fixing a point", "All points reachable from it", "Only the identity in every action"], 0, "It is a subgroup."], ["What does orbit-stabilizer give for finite G?", ["|orbit|=|G|/|stabilizer|", "|orbit|=|G|+|stabilizer|", "Every orbit has size |G|"], 0, "Cosets of the stabilizer correspond to orbit points."], ["Must an action have one orbit?", ["No", "Yes", "Only if finite"], 0, "Transitivity is an additional property."]],
  },
  {
    lesson: "math.m22.l5", title: "Rings, ideals, and quotients",
    premise: "A ring has addition and multiplication; an ideal is the kind of subset that can be collapsed while keeping both operations well-defined.",
    idea: "A commutative ring with identity has an abelian additive group and associative, distributive multiplication with 1; conventions vary for general rings. An ideal I is an additive subgroup closed under multiplication by arbitrary ring elements. Quotient R/I consists of additive cosets with multiplication (a+I)(b+I)=ab+I, which is well-defined precisely because I absorbs products with ring elements. An integral domain has no zero divisors; a field allows division by every nonzero element. A maximal ideal yields a field quotient in a commutative ring with 1; a prime ideal yields an integral-domain quotient.",
    worked: "In Z, I=5Z is an ideal. The quotient Z/5Z has classes [0] through [4]. Because 5 is prime, every nonzero class has a multiplicative inverse: for example [2][3]=[1]. Thus Z/5Z is a field. In Z/6Z, [2][3]=[0] even though both factors are nonzero, so it has zero divisors and is not a field.",
    interpretation: "The arithmetic properties of a quotient depend on the ideal being collapsed, not just on the number of residue classes.",
    trap: "A subgroup of the additive group need not be an ideal in an arbitrary ring; multiplication by all ring elements must preserve it.",
    practice: "Why is 4Z an ideal of Z, and is Z/4Z an integral domain?",
    solution: "4Z is closed under integer addition and additive inverses, and r(4k)=4(rk) stays in 4Z for every integer r. In the quotient, [2][2]=[0] although [2] is nonzero, so it has a zero divisor and is not an integral domain.",
    checks: [["What extra closure defines an ideal?", ["Absorbs multiplication by ring elements", "Has every multiplicative inverse", "Contains only zero"], 0, "That makes quotient multiplication well-defined."], ["What does a maximal ideal quotient give in a commutative ring with 1?", ["A field", "Always the zero ring", "A group only"], 0, "Every nonzero coset becomes invertible."], ["Is Z/6Z a field?", ["No", "Yes", "Only under addition"], 0, "It contains nonzero zero divisors."]],
  },
  {
    lesson: "math.m22.l6", title: "Polynomial rings",
    premise: "Polynomials behave like arithmetic objects whose coefficients live in a chosen ring or field. Their factorization depends on that coefficient system.",
    idea: "R[x] contains finite sums a₀+a₁x+…+a_nx^n with coefficients in R. If coefficients lie in a field F, division by a nonzero polynomial gives quotient and remainder of smaller degree. The Euclidean algorithm then finds polynomial greatest common divisors. A root a∈F corresponds to factor x-a by the factor theorem. Irreducibility depends on F: x²+1 is irreducible over R but factors over C. Over an integral domain, deg(fg)=deg f+deg g for nonzero polynomials. Over rings with zero divisors, leading coefficients can multiply to zero and this degree rule may fail.",
    worked: "Over R, divide x³-1 by x-1 to obtain x²+x+1 with remainder zero. Hence x³-1=(x-1)(x²+x+1). The quadratic has discriminant 1-4=-3 and no real roots, so it is irreducible over R. Over C it further factors into linear factors involving the nonreal cube roots of unity.",
    interpretation: "The same formal expression has different factorization behavior as the coefficient field changes.",
    trap: "Do not apply polynomial long division with arbitrary leading-coefficient division in a coefficient ring where that coefficient is not invertible.",
    practice: "Factor x²-4 over R and identify its roots.",
    solution: "Use the difference of squares: x²-4=(x-2)(x+2). The roots are 2 and -2, as verified by substitution. Both factors lie in R[x], so the polynomial is reducible over R.",
    checks: [["What does a root a imply over a field?", ["x-a divides the polynomial", "The polynomial is constant", "All coefficients vanish"], 0, "This is the factor theorem."], ["Can irreducibility depend on coefficient field?", ["Yes", "No", "Only for cubics"], 0, "x²+1 differs over R and C."], ["When does polynomial division with remainder work generally?", ["Over a field for nonzero divisor", "Over every ring without conditions", "Only for monomials"], 0, "Leading coefficients must be invertible for the usual algorithm."]],
  },
  {
    lesson: "math.m22.l7", title: "Fields and extensions",
    premise: "A field extension adds new elements while retaining valid arithmetic. Minimal polynomials describe the algebraic relation those elements satisfy.",
    idea: "An extension K/F means F is a subfield of K. An element α∈K is algebraic over F when it satisfies a nonzero polynomial in F[x]; otherwise it is transcendental. Its monic minimal polynomial is the unique irreducible polynomial over F that vanishes at α. If minimal polynomial has degree d, then F(α) has F-basis 1,α,…,α^{d-1} and extension degree d. For finite towers F⊆K⊆L, degrees multiply: [L:F]=[L:K][K:F]. Quotients F[x]/(p) by irreducible p construct fields containing a root of p.",
    worked: "Let α=sqrt(2). Its minimal polynomial over Q is x²-2, irreducible because it has no rational root. Every element of Q(sqrt(2)) is a+b sqrt(2) with rational a,b, so extension degree is 2. Multiplication reduces α² to 2, keeping that two-dimensional form.",
    interpretation: "A seemingly new number enlarges the field by a controlled finite-dimensional vector-space extension.",
    trap: "Do not call every polynomial vanishing at α the minimal polynomial. It must be monic, irreducible over the base field, and of least degree.",
    practice: "Find the degree of Q(i) over Q and give a basis.",
    solution: "i satisfies x²+1, which is irreducible over Q because it has no rational root. Therefore [Q(i):Q]=2, with basis {1,i}. Every element is a+bi for rationals a,b.",
    checks: [["What is an algebraic element over F?", ["A root of a nonzero polynomial in F[x]", "Any complex number", "Only an element already in F"], 0, "Polynomial relations define algebraicity."], ["What is [F(α):F] for algebraic α?", ["Degree of its minimal polynomial", "Always one", "Number of roots in F"], 0, "Powers below the degree form a basis."], ["What is the tower degree law?", ["[L:F]=[L:K][K:F]", "[L:F]=[L:K]+[K:F]", "All degrees are equal"], 0, "Extend a basis of K over F and one of L over K."]],
  },
  {
    lesson: "math.m22.l8", title: "Finite fields",
    premise: "Finite fields exist only at prime-power sizes. Their arithmetic supports coding theory, cryptography, and exact algebraic computation.",
    idea: "A finite field has characteristic p for some prime p, so it contains F_p. As a vector space over F_p it has some finite dimension n and therefore p^n elements. Conversely, for each prime power p^n there is a field of that size, unique up to isomorphism. Construct one as F_p[x]/(q(x)) with irreducible q of degree n. Every nonzero element lies in the finite multiplicative group and has an inverse; its size is p^n-1. Not every quotient by a degree-n polynomial is a field: irreducibility is essential. Finite-field arithmetic is exact modulo the defining relations, unlike floating-point approximation.",
    worked: "Construct a field with four elements as F₂[x]/(x²+x+1). The quadratic has no roots at 0 or 1 in F₂, so it is irreducible. Let α be the class of x; then α²=α+1 because x²+x+1=0 in characteristic 2. Elements are 0,1,α,α+1. Since α(α+1)=α²+α=1, α+1 is the inverse of α.",
    interpretation: "The relation α²=α+1 keeps every calculation within a two-dimensional F₂ vector space while preserving field inverses.",
    trap: "There is no field with six elements because six is not a prime power, even though Z/6Z is a ring with six elements.",
    practice: "Is F₃[x]/(x²+1) a field? Test irreducibility and state its size.",
    solution: "Evaluate x²+1 at 0,1,2 modulo 3: values are 1,2,2, none zero. A quadratic over a field is irreducible exactly when it has no root. Thus the quotient is a field with 3²=9 elements represented by a+bα for a,b∈F₃.",
    checks: [["What sizes can finite fields have?", ["Prime powers", "Any positive integer", "Only primes"], 0, "A finite field is a finite-dimensional vector space over F_p."], ["What condition on q makes F_p[x]/(q) a field?", ["q irreducible", "q monic only", "q has a root in F_p"], 0, "The ideal must be maximal."], ["Does a field of size six exist?", ["No", "Yes", "Only as Z/6Z"], 0, "Six is not a prime power."]],
  },
];
