import type { MathLecture } from "./lectures";

/** Optimization beyond introductory gradients, with assumptions and counterchecks. */
export const MATH_ADVANCED_OPTIMIZATION: MathLecture[] = [
  {
    lesson: "math.m26.l1", title: "Convex duality",
    premise: "A dual problem supplies lower bounds for a minimization problem and sometimes a more useful route to its solution.",
    idea: "For min f(x) subject to g_i(x)≤0 and h_j(x)=0, form L(x,λ,ν)=f(x)+Σλ_i g_i(x)+Σν_j h_j(x) with λ_i≥0. The dual function q(λ,ν)=inf_x L is a lower bound on every feasible objective, so maximizing q gives the dual problem and weak duality d*≤p*. Strong duality needs additional hypotheses, such as convexity plus Slater's strictly feasible point for appropriate inequalities. A primal-dual gap certifies suboptimality when both sides are feasible. Equality of values does not imply every multiplier or minimizer is unique.",
    worked: "Minimize x² subject to x≥1. Write g(x)=1-x≤0 and L=x²+λ(1-x). Infimum over x occurs at x=λ/2, giving q(λ)=λ-λ²/4 for λ≥0. Its maximum is at λ=2 with value 1. The primal minimizer x=1 also has value 1, so the gap is zero.",
    interpretation: "The best dual lower bound meets the primal value in this convex, strictly feasible example.",
    trap: "Do not assert strong duality for an arbitrary nonconvex constraint set merely because a Lagrangian can be written.",
    practice: "For min x² subject to x≥2, write the Lagrangian and find the optimal multiplier and primal-dual value.",
    solution: "L=x²+λ(2-x), λ≥0. Its infimum is q=2λ-λ²/4, maximized at λ=4 with value 4. The primal minimizer x=2 has objective 4, so strong duality holds here.",
    checks: [["What bound does a feasible dual point provide for minimization?", ["A lower bound", "An upper bound", "Always exact optimum"], 0, "That is weak duality."], ["What sign must inequality multipliers have for g≤0?", ["Nonnegative", "Negative", "Any sign"], 0, "It preserves the lower-bound argument."], ["Does convexity alone cover every strong-duality assertion?", ["No; a constraint qualification may be needed", "Yes without exceptions", "Only if x is one-dimensional"], 0, "State assumptions such as Slater's condition."]],
  },
  {
    lesson: "math.m26.l2", title: "Proximal operators and composite objectives",
    premise: "A proximal step handles a nonsmooth penalty by solving a small local optimization problem rather than differentiating where no derivative exists.",
    idea: "For convex g, prox_{αg}(v)=argmin_x[g(x)+(1/(2α))||x-v||²]. Proximal-gradient descent for F(x)=f(x)+g(x), with differentiable f, updates x⁺=prox_{αg}(x-α∇f(x)). When g(x)=λ||x||₁, the prox is coordinatewise soft thresholding: sign(v_i)max(|v_i|-αλ,0). The step can produce exact zeros, unlike ordinary smooth gradient descent. Standard convergence statements need convexity and a step size tied to Lipschitz continuity of ∇f; a nonconvex g or overlarge step requires separate analysis.",
    worked: "Let f(x)=(x-3)²/2 and g(x)=|x|. Starting at x=0 with α=1, the gradient is -3, so v=3. Soft-threshold v by αλ=1 to get x⁺=2. Indeed F(2)=.5+2=2.5, while F(0)=4.5.",
    interpretation: "The proximal map encodes the geometry of a penalty exactly within each iteration.",
    trap: "Do not differentiate |x| at zero as if it were smooth; use a subgradient or proximal formulation.",
    practice: "Compute prox_{2|·|}(v) for v=-3, using α=1 in the displayed definition.",
    solution: "The threshold is αλ=2. Soft thresholding gives sign(-3)max(3-2,0)=-1. This is the minimizer of 2|x|+(x+3)²/2.",
    checks: [["What is the prox of an L1 penalty?", ["Soft thresholding", "Squaring", "Ordinary differentiation at zero"], 0, "It shrinks magnitudes and may set them to zero."], ["What is the smooth part used for in proximal gradient?", ["A gradient step", "Only a constraint", "A matrix inverse always"], 0, "The nonsmooth part is handled by prox."], ["Can the prox create exact zeros?", ["Yes", "No", "Only with negative λ"], 0, "Thresholding clips small coordinates."]],
  },
  {
    lesson: "math.m26.l3", title: "Accelerated first-order methods",
    premise: "Momentum can improve worst-case convergence for smooth convex optimization, but its guarantee depends on a precise update and assumptions.",
    idea: "Gradient descent on an L-smooth convex objective has a standard O(1/k) objective-gap bound with suitable step size. Nesterov-type accelerated methods combine a gradient step from a look-ahead point with a momentum recurrence and achieve O(1/k²) in that setting. These are worst-case bounds, not predictions for every dataset. Strong convexity permits geometric rates with condition-number dependence. Momentum parameters and restarting matter; an arbitrary extrapolation is not automatically accelerated. In nonconvex problems, monotonic objective decrease can fail even when eventual stationary-point results exist.",
    worked: "Consider f(x)=x²/2 with L=1. A gradient step of size 1 from x=3 reaches x=0 immediately; no acceleration can improve this already exact result. On an ill-conditioned quadratic with different eigenvalue scales, momentum can help overcome slow directions, but a too-large step can destabilize them.",
    interpretation: "Rate theorems compare worst cases under stated smoothness and convexity, not each easy example.",
    trap: "Do not promise O(1/k²) for a nonsmooth or nonconvex objective merely because the code includes momentum.",
    practice: "State what must be checked before quoting the O(1/k²) accelerated objective-gap guarantee.",
    solution: "Verify a convex objective with L-Lipschitz gradient, the appropriate accelerated update and step rule, and a defined minimizer or finite optimal value under the theorem used. If the objective is nonsmooth, use a matching proximal accelerated theorem instead.",
    checks: [["What is the classic smooth-convex accelerated gap rate?", ["O(1/k²)", "O(k²)", "Always zero in one step"], 0, "Compare with basic gradient descent's O(1/k) bound."], ["Does a momentum term alone prove acceleration?", ["No", "Yes", "Only for deep learning"], 0, "The update and assumptions matter."], ["Can strongly convex objectives admit geometric rates?", ["Yes", "No", "Only in one dimension"], 0, "Strong curvature improves guarantees."]],
  },
  {
    lesson: "math.m26.l4", title: "Newton and quasi-Newton methods",
    premise: "Second-order methods use curvature to choose a direction and scale a step, but curvature must be safe to invert or regularize.",
    idea: "Newton's step solves H(x)p=-∇f(x), then x⁺=x+αp. Near a nondegenerate minimizer with smooth Hessian and full steps, local convergence is quadratic. If H is indefinite, p may not be a descent direction; damping, trust regions, or Hessian modification can help. BFGS updates an approximate inverse Hessian from gradient differences rather than forming exact second derivatives. Its positive-definiteness and convergence results require curvature conditions and suitable line search. Computational cost matters: dense Hessian factorizations scale poorly in high dimensions.",
    worked: "For f(x)=4(x-2)², gradient is 8(x-2) and Hessian is 8. From x=7, Newton solves 8p=-40, so p=-5 and a full step lands at x=2. For a nonquadratic objective, the Hessian changes and line search may be needed.",
    interpretation: "Newton rescales the gradient by local curvature; exact one-step behavior is special to quadratic models.",
    trap: "Do not invert a singular Hessian or interpret every stationary point as a minimum.",
    practice: "Take one full Newton step from x=1 for f(x)=x²+2x+5.",
    solution: "f'(x)=2x+2 and f''(x)=2. At x=1, p=-4/2=-2, so x⁺=-1. That is the unique minimum of this positive-curvature quadratic.",
    checks: [["Which equation defines Newton's direction?", ["Hp=-gradient", "Hp=gradient squared", "p=H gradient"], 0, "It minimizes the local quadratic model."], ["What can an indefinite Hessian cause?", ["A non-descent Newton direction", "Guaranteed convexity", "A zero objective"], 0, "Curvature may point toward a saddle."], ["What does BFGS approximate?", ["Curvature information", "Only the function value", "The data loader"], 0, "It updates an inverse-Hessian approximation."]],
  },
  {
    lesson: "math.m26.l5", title: "Stochastic approximation",
    premise: "Noisy gradient estimates save work per iteration but add variance that changes the convergence story.",
    idea: "If g_k is an unbiased estimate of ∇f(x_k) conditional on x_k, stochastic gradient descent uses x_{k+1}=x_k-α_k g_k. Under common convex assumptions and bounded variance, diminishing steps can drive expected error down; a constant step often leaves a noise neighborhood. Mini-batches reduce gradient variance roughly inversely with batch size when samples are independent, but correlated data change that calculation. Sampling without replacement, momentum, and adaptive learning rates require their own assumptions. Reproducibility includes seed, data order, and evaluation protocol, not just the update equation.",
    worked: "For f(x)=E[(x-Z)²/2] with E[Z]=3, a sampled gradient is g=x-Z. Conditional expectation E[g|x]=x-3=∇f(x). At x=0, if one sampled Z is 5 and α=.1, the noisy step is x⁺=.5; the full-gradient step would be .3. Both point toward the minimizer on average, but individual steps vary.",
    interpretation: "Unbiasedness is an expectation statement, not a guarantee for any one batch.",
    trap: "Do not claim every stochastic step decreases the true objective; noise can make it rise temporarily.",
    practice: "Suppose Z is equally likely to be 2 or 4. Compute E[g|x] for g=x-Z and one step from x=0 when Z=4 and α=.25.",
    solution: "E[Z]=3, so E[g|x]=x-3. For the sampled Z=4 at x=0, g=-4 and x⁺=0-.25(-4)=1. The expected gradient at zero is -3, giving expected one-step location .75 if the same step rule is used.",
    checks: [["Does an unbiased stochastic gradient equal the true gradient every step?", ["No", "Yes", "Only at the optimum"], 0, "Equality holds in conditional expectation."], ["What does independent mini-batching generally reduce?", ["Variance", "Data dimension", "Objective definition"], 0, "Averages cancel independent noise."], ["Does a constant step necessarily converge exactly under persistent noise?", ["No", "Yes", "Only if the batch is odd"], 0, "It may remain in a noise neighborhood."]],
  },
  {
    lesson: "math.m26.l6", title: "Constrained nonconvex optimization",
    premise: "Constraints and nonconvexity turn stationarity into a candidate condition, not a certificate of global optimality.",
    idea: "For differentiable constraints, KKT conditions combine primal feasibility, dual feasibility for inequalities, stationarity, and complementary slackness under a constraint qualification. In a nonconvex problem, they are generally necessary for a local optimum under regularity but not sufficient for a global optimum. Second-order necessary conditions examine the Hessian of the Lagrangian on feasible tangent directions; sufficient conditions can certify a strict local minimum under stronger assumptions. Boundary candidates, disconnected components, and failed constraint qualifications need separate consideration.",
    worked: "Minimize f(x)=x⁴-x² over [-1,1]. Interior stationarity gives f'=4x³-2x=2x(2x²-1)=0, so candidates are 0 and ±1/sqrt(2); endpoints ±1 are also candidates. Values are 0 at 0 and endpoints, and -1/4 at ±1/sqrt(2), so the global minimum on this compact interval is -1/4. Stationarity alone would also admit x=0, a local maximum.",
    interpretation: "Compactness lets us compare all valid candidates in this one-dimensional case, while higher-dimensional problems may remain hard.",
    trap: "Do not relabel a KKT point as a global solution without convexity or a separate global argument.",
    practice: "Find and classify stationary points of f(x)=x⁴-2x² on [-2,2], then compare endpoints.",
    solution: "f'=4x(x²-1), so stationary points are 0, ±1. f(0)=0; f(±1)=-1; f(±2)=16-8=8. Thus global minima on the interval occur at ±1 with value -1; x=0 is a local maximum, and endpoints are high-valued boundary candidates.",
    checks: [["Are KKT conditions generally sufficient for global optimality in nonconvex problems?", ["No", "Yes", "Only with one constraint"], 0, "They usually identify candidates."], ["What points must an interval optimization compare?", ["Interior critical points and endpoints", "Only derivative zeros", "Only endpoints"], 0, "Boundary minima are possible."], ["What can a second-order condition certify under assumptions?", ["A local minimum", "A global minimum always", "A unique dataset"], 0, "Global claims need more."]],
  },
  {
    lesson: "math.m26.l7", title: "Saddle points and game dynamics",
    premise: "In a minimax problem, one player descends while the other ascends; simultaneous gradients can rotate rather than settle.",
    idea: "A saddle point (x*,y*) of L satisfies L(x*,y)≤L(x*,y*)≤L(x,y*) for all feasible x,y, when x minimizes and y maximizes. Convexity in x and concavity in y support minimax theory under suitable domain conditions. For bilinear L(x,y)=xy, simultaneous gradient descent-ascent gives x⁺=x-αy, y⁺=y+αx. The update matrix has eigenvalues 1±iα with magnitude sqrt(1+α²)>1, so iterates spiral outward for any fixed α>0. Extragradient or optimistic methods evaluate a predictive point to control such rotation under their assumptions.",
    worked: "At (x,y)=(1,0) with α=.1, simultaneous update gives (1,.1). Next gives (.99,.2). The distance from the origin grows because each update multiplies squared radius by 1+α², even though (0,0) is the saddle of xy over the full plane.",
    interpretation: "A zero-gradient equilibrium can be unstable under a naive discrete-time algorithm.",
    trap: "Do not treat descent-ascent as ordinary minimization of a single scalar objective in both variables.",
    practice: "For L(x,y)=xy and α=.2, compute the update from (0,1) and its new squared radius.",
    solution: "x⁺=0-.2(1)=-.2; y⁺=1+.2(0)=1. The new squared radius is .04+1=1.04, up from 1, matching the factor 1+α²=1.04.",
    checks: [["What does the maximizing player do to its gradient?", ["Ascends", "Descends", "Ignores it"], 0, "The two variables have opposite objectives."], ["What happens under simultaneous fixed-step updates for xy?", ["Radius grows", "Radius shrinks", "Converges in one step"], 0, "Eigenvalue magnitude exceeds one."], ["Is a stationary saddle automatically stable under an algorithm?", ["No", "Yes", "Only when bilinear"], 0, "Algorithm dynamics need analysis."]],
  },
  {
    lesson: "math.m26.l8", title: "Optimization research-paper reading",
    premise: "A rate claim is meaningful only together with its objective, oracle model, assumptions, metric, and proof dependencies.",
    idea: "When reading an optimization paper, write down the exact optimization problem, feasible domain, information available per iteration, and target guarantee: objective gap, gradient norm, regret, feasibility violation, or last-iterate behavior. Translate O-notation into an explicit comparison of k, dimension, condition number, stochastic variance, and constants. Identify which lemma uses each assumption, then test a boundary case such as a nonsmooth objective, degenerate Hessian, or biased gradient. Reproduce a small baseline with controlled seed and tolerance; compare equal computational budgets, not just iteration counts. An empirical curve does not prove a theorem, and a theorem does not guarantee the implementation realizes its assumptions.",
    worked: "A paper claiming E||∇f(x_R)||²≤C/sqrt(T) controls expected squared stationarity after T steps. It does not say the final iterate is globally optimal, nor that every run has that gradient size. To reach bound ε, its stated scaling requires T≥(C/ε)², subject to any hidden setup assumptions and constants.",
    interpretation: "Careful reading converts a headline into a checkable claim with a specific success metric.",
    trap: "Do not compare O(1/k²) objective gap to O(1/sqrt(k)) gradient norm as if they measured the same quantity.",
    practice: "A method guarantees expected objective gap at most 8/k². How many iterations suffice for a bound of .02, and what does the guarantee not say?",
    solution: "Solve 8/k²≤.02, so k²≥400 and k≥20. The theorem bounds an expectation under its assumptions; it does not promise every run achieves the bound or that all iterates are globally optimal.",
    checks: [["Must optimization rates name a metric?", ["Yes", "No", "Only for graphics"], 0, "Objective gap and stationarity are different."], ["Can iteration counts alone compare methods with unequal oracle cost?", ["No", "Yes", "Only for SGD"], 0, "Compare computational budgets and assumptions."], ["Does an expected bound guarantee every run?", ["No", "Yes", "Only after many plots"], 0, "Expectation is not a per-run statement."]],
  },
];
