import type { MathLecture } from "./lectures";

/** Numerical methods, PDEs, and optimization follow the rigorous core. */
export const MATH_ADVANCED_APPLIED: MathLecture[] = [
  {
    lesson: "math.m24.l1", title: "Floating-point arithmetic and conditioning",
    premise: "A computer stores a nearby representable number, not an arbitrary real number. We must separate input sensitivity from rounding introduced by the algorithm.",
    idea: "In the usual floating-point model, fl(a op b)=(a op b)(1+δ), |δ|≤u, provided no underflow or overflow occurs. The unit roundoff u depends on the format. A condition number describes sensitivity of the mathematical problem; for a differentiable scalar f it is approximately |x f'(x)/f(x)| in relative terms. A backward-stable algorithm returns the exact answer to a nearby problem. Even a stable algorithm cannot guarantee accurate forward answers for ill-conditioned data.",
    worked: "For f(x)=1/(1-x) near x=1, f'(x)=1/(1-x)², so the relative condition number is |x/(1-x)|. At x=.999 it is about 999: a small relative input error can be magnified roughly a thousandfold. Subtracting two nearly equal stored numbers may expose earlier rounding, even though the subtraction itself is correctly rounded.",
    interpretation: "Diagnose the problem before blaming code: sensitivity and algorithm error are separate quantities.",
    trap: "Do not conclude every cancellation is unstable; cancellation is dangerous when inaccurate operands erase meaningful digits.",
    practice: "Compute the relative condition number of f(x)=x² at nonzero x and compare it with 1/(1-x) at x=.99.",
    solution: "For x², x f'(x)/f(x)=x(2x)/x²=2. For 1/(1-x), the number is |x/(1-x)|=99 at .99. The second problem is far more sensitive to relative input perturbations there.",
    checks: [["What does conditioning describe?", ["Sensitivity of the mathematical answer to input changes", "Runtime only", "Number of code lines"], 0, "It belongs to the problem."], ["What does backward stability guarantee?", ["An exact answer for nearby input", "Perfect forward accuracy for every problem", "No floating-point operations"], 0, "Conditioning connects backward and forward error."], ["Can a well-designed algorithm eliminate intrinsic ill-conditioning?", ["No", "Yes", "Only with recursion"], 0, "It cannot remove input sensitivity."]],
  },
  {
    lesson: "math.m24.l2", title: "Root finding and convergence rates",
    premise: "Numerical root finding replaces an exact symbolic answer with a sequence of approximations, and the convergence guarantee depends on the method's hypotheses.",
    idea: "Bisection maintains a sign-changing bracket for continuous f; after n steps the interval width is initial width divided by 2^n. Newton iteration is x_{n+1}=x_n-f(x_n)/f'(x_n). Near a simple root, with enough smoothness and a suitable initial guess, its error is locally quadratic: e_{n+1} is approximately C e_n². It can fail or leave the region if the derivative is tiny, the guess is poor, or the root is multiple. A stopping rule should consider both residual |f(x)| and step or bracket size, because a small residual need not imply a small root error on a flat function.",
    worked: "Solve x²-2=0 from x₀=1.5. Newton gives x₁=1.5-(2.25-2)/3=1.4166667, then x₂≈1.4142157. Bisection on [1,2] retains a root because f(1)<0<f(2); after ten steps the bracket width is 1/1024.",
    interpretation: "Bisection offers a robust enclosure; Newton is faster locally when its assumptions hold.",
    trap: "Do not quote quadratic convergence for a multiple root or from an arbitrary starting point.",
    practice: "For f(x)=x²-3, compute one Newton step from x₀=2 and a bisection bracket after one step on [1,2].",
    solution: "Newton gives 2-(4-3)/4=1.75. Bisection midpoint is 1.5, with f(1.5)<0 and f(2)>0, so the new bracket is [1.5,2]. Both approximations remain above or around sqrt(3)≈1.732, but only the bracket certifies enclosure.",
    checks: [["What does bisection require?", ["Continuity and opposite endpoint signs", "A derivative", "A polynomial"], 0, "The intermediate value theorem supplies the root."], ["What is the Newton update?", ["x-f(x)/f'(x)", "x+f'(x)", "f(x)/x"], 0, "It uses a tangent-line zero."], ["Is Newton globally quadratic from any initial value?", ["No", "Yes", "Only for negative roots"], 0, "The guarantee is local under assumptions."]],
  },
  {
    lesson: "math.m24.l3", title: "Interpolation and approximation",
    premise: "Interpolation matches chosen samples exactly; approximation may trade exact fit for lower error across a region.",
    idea: "Distinct nodes x₀,...,x_n determine a unique degree-at-most-n interpolation polynomial. Its Lagrange form is Σ y_i L_i(x), where L_i(x)=∏_{j≠i}(x-x_j)/(x_i-x_j). If f has n+1 derivatives, the pointwise interpolation error is f^{(n+1)}(ξ)/(n+1)! times ∏(x-x_i) for some ξ in the interval. Equally spaced high-degree interpolation can oscillate near endpoints; Chebyshev nodes reduce the worst polynomial product. Least-squares approximation solves a different objective and need not pass through every sample.",
    worked: "Given (0,1) and (2,5), the degree-one interpolant is 1+2x. At x=1 it predicts 3. For f(x)=x², matching its values at 0 and 2 gives interpolant 2x, whose error at x=1 is 1-2=-1; the error formula gives f''(ξ)/2!·x(x-2)=1·(-1)=-1.",
    interpretation: "Exact fit at observed nodes does not guarantee reliable behavior between them or beyond their interval.",
    trap: "Do not use interpolation-error bounds outside the node interval or with an unbounded required derivative.",
    practice: "Interpolate f(x)=x² at nodes 0 and 1 with a line. Find its prediction and error at x=.5.",
    solution: "The samples are (0,0) and (1,1), so p(x)=x. At .5, p=.5 whereas f=.25. Signed error f-p=-.25; magnitude is .25. The second-derivative remainder is x(x-1)=-.25.",
    checks: [["How many distinct nodes determine a degree-at-most-n interpolant?", ["n+1", "n", "2n"], 0, "Uniqueness holds for distinct nodes."], ["Must least squares hit every data point?", ["No", "Yes", "Only with two nodes"], 0, "It minimizes aggregate squared error."], ["Where can high-degree equally spaced interpolation oscillate badly?", ["Near interval endpoints", "Only at nodes", "Nowhere"], 0, "This is Runge-type behavior."]],
  },
  {
    lesson: "math.m24.l4", title: "Numerical differentiation and quadrature",
    premise: "Finite differences and quadrature have truncation error, while very small steps can amplify rounding error.",
    idea: "Taylor expansion gives the forward difference [f(x+h)-f(x)]/h=f'(x)+O(h) and centered difference [f(x+h)-f(x-h)]/(2h)=f'(x)+O(h²), assuming sufficient smoothness. Rounding often contributes roughly O(u/h), so blindly shrinking h eventually hurts. The trapezoid rule averages endpoint values over each interval; Simpson's rule integrates a quadratic interpolant and requires an even number of equal subintervals in its composite form. Smoothness assumptions control error bounds, and an adaptive scheme refines where estimated error is high.",
    worked: "For f(x)=x² at x=1, the forward difference is [(1+h)²-1]/h=2+h, while the centered difference is [(1+h)²-(1-h)²]/(2h)=2 exactly in exact arithmetic. On [0,1], the trapezoid rule for x² gives (0+1)/2=.5, versus exact integral 1/3.",
    interpretation: "The centered stencil cancels the leading odd Taylor error; quadrature quality depends on how well its local polynomial represents the integrand.",
    trap: "Do not claim h→0 improves a floating-point derivative indefinitely; subtraction of nearby rounded values can dominate.",
    practice: "Approximate ∫₀¹ x² dx with Simpson's rule using two equal panels and compare with the exact value.",
    solution: "With h=.5 and values f(0)=0, f(.5)=.25, f(1)=1, Simpson gives h/3[0+4(.25)+1]=(.5/3)·2=1/3. It is exact because Simpson integrates polynomials through degree three exactly.",
    checks: [["What is the leading truncation order of a centered derivative?", ["O(h²)", "O(h)", "O(1)"], 0, "Odd terms cancel."], ["Does h→0 always reduce floating-point derivative error?", ["No", "Yes", "Only for polynomials"], 0, "Rounding is magnified by division by h."], ["How many equal subintervals does composite Simpson require?", ["An even number", "An odd number", "Exactly one"], 0, "Panels are paired."]],
  },
  {
    lesson: "math.m24.l5", title: "Iterative methods for linear systems",
    premise: "For large sparse systems, repeated matrix-vector products may be cheaper than storing a dense factorization.",
    idea: "A stationary iteration x_{k+1}=Gx_k+c converges for every starting vector exactly when the spectral radius ρ(G)<1. Jacobi uses the diagonal of A; Gauss-Seidel also uses newly updated coordinates. For symmetric positive-definite A, conjugate gradients minimizes the A-norm of error over successive Krylov spaces in exact arithmetic and terminates within at most n steps, though rounding changes this. Preconditioning replaces the system with an equivalent one whose spectrum is friendlier, but the preconditioner itself has cost. Always monitor residual r=b-Ax and understand that a small residual is not automatically a small forward error for ill-conditioned A.",
    worked: "For A=[[4,1],[1,3]] and b=[1,2], Jacobi from x₀=[0,0] gives x₁=[1/4,2/3]. The residual is b-Ax₁=[-2/3,-1/4], not zero, so another iteration is needed. Strict diagonal dominance here supports Jacobi convergence.",
    interpretation: "The iteration's matrix controls convergence; the residual reports equation satisfaction, not all uncertainty in the solution.",
    trap: "Do not run conjugate gradients on an arbitrary nonsymmetric or indefinite matrix and assume its standard guarantee applies.",
    practice: "For A=[[2,0],[0,5]] and b=[4,10], compute one Jacobi step from zero and the residual.",
    solution: "Each diagonal equation is independent: x₁=[4/2,10/5]=[2,2]. Then Ax₁=[4,10]=b, so r=[0,0]; Jacobi solves this diagonal system in one step.",
    checks: [["When does a stationary iteration converge from every start?", ["Its iteration matrix has spectral radius below 1", "Its determinant is positive", "It has any diagonal"], 0, "Error evolves by G."], ["What matrix class supports standard conjugate gradients?", ["Symmetric positive definite", "Any square matrix", "Only diagonal matrices"], 0, "The A-inner product must be valid."], ["What is the residual?", ["b-Ax", "x-b", "A squared"], 0, "It measures equation mismatch."]],
  },
  {
    lesson: "math.m24.l6", title: "Numerical eigenvalue methods",
    premise: "Eigenvalue algorithms approximate invariant directions without explicitly solving a high-degree characteristic polynomial.",
    idea: "Power iteration repeatedly normalizes Av. If A is diagonalizable with a unique dominant eigenvalue in magnitude and the initial vector has a component in its eigendirection, the vector approaches that direction at a rate related to |λ₂/λ₁|. A Rayleigh quotient vᵀAv/(vᵀv) estimates an eigenvalue for symmetric A. Near ties make convergence slow; a zero initial component in the dominant eigenspace prevents discovery. Inverse iteration with a shift targets an eigenvalue near the shift by solving linear systems. Practical dense eigensolvers commonly reduce to Hessenberg or tridiagonal form and use QR iterations, with numerical stability analysis beyond the basic power method.",
    worked: "Let A=diag(4,1) and v₀=[1,1]. Then A^k v₀=[4^k,1], whose normalized direction tends to [1,0]. At k=2 the vector [16,1] already points close to the first coordinate. Starting instead at [0,1] stays in the second eigenspace forever despite the dominant eigenvalue 4.",
    interpretation: "Convergence depends on spectral separation and on what the starting vector can see.",
    trap: "Do not infer the largest algebraic eigenvalue from power iteration when a negative eigenvalue has larger absolute value.",
    practice: "For A=diag(3,-1) and v=[1,1], compute one power step and the Rayleigh quotient of the original v.",
    solution: "Av=[3,-1], so after Euclidean normalization the next vector is [3,-1]/sqrt(10). The original Rayleigh quotient is ([1,1]·[3,-1])/([1,1]·[1,1])=2/2=1. Its value is an estimate, not either exact eigenvalue for this non-eigenvector.",
    checks: [["What determines simple power-iteration speed?", ["The magnitude ratio of subdominant to dominant eigenvalues", "Matrix size alone", "The sign of every entry"], 0, "A small ratio gives fast directional convergence."], ["What if the start has no dominant-eigenvector component?", ["Power iteration cannot reveal it", "It appears automatically", "The matrix becomes singular"], 0, "Invariant subspaces stay invariant."], ["What does a Rayleigh quotient estimate?", ["An eigenvalue", "A determinant", "A matrix inverse"], 0, "It is exact on an eigenvector."]],
  },
  {
    lesson: "math.m24.l7", title: "Stiff ODEs and stability",
    premise: "A stiff ODE can force an explicit integrator to take tiny steps for numerical stability even when the solution changes slowly.",
    idea: "For the test equation y'=λy with negative real λ, explicit Euler gives y_{n+1}=(1+hλ)y_n. Stability requires |1+hλ|<1. Backward Euler gives y_{n+1}=y_n/(1-hλ); for negative real λ it remains stable for any positive h, though it introduces discretization error and requires an implicit solve in nonlinear problems. Stability is not accuracy: a giant stable step may miss transients. In multi-timescale systems, eigenvalues with widely separated negative real parts produce fast-decaying modes that constrain explicit steps even after those modes are small.",
    worked: "For y'=-100y, explicit Euler with h=.1 multiplies by -9, so its numerical values grow wildly although the exact solution decays. The stability condition |1-100h|<1 requires h<.02. Backward Euler with h=.1 multiplies by 1/11, stable but only an approximation to e^{-10}.",
    interpretation: "Step size can be limited by the solver's stability region rather than by the visible timescale of the output.",
    trap: "Do not describe implicit Euler as exact or unconditionally accurate; unconditional stability for this decay test is a separate claim.",
    practice: "For y'=-20y, find the explicit-Euler stability range of positive h and its multiplier at h=.2.",
    solution: "Require |1-20h|<1, equivalent to -1<1-20h<1 and 0<h<.1. At h=.2 the multiplier is 1-4=-3, whose magnitude exceeds one, so iterates grow in magnitude instead of decay.",
    checks: [["What is explicit Euler's test-equation multiplier?", ["1+hλ", "1/(1-hλ)", "e^{hλ} exactly"], 0, "Substitute y'=λy into the update."], ["Does stable imply accurate?", ["No", "Yes", "Only for implicit methods"], 0, "A stable large step can miss dynamics."], ["Why can stiffness force tiny explicit steps?", ["Fast decaying modes constrain the stability region", "The solution must always grow", "No derivative exists"], 0, "Numerical stability can dominate."]],
  },
  {
    lesson: "math.m24.l8", title: "Verification against analytic benchmarks",
    premise: "A plausible plot is not validation. Numerical results need known solutions, convergence studies, and independently checked residuals.",
    idea: "Verification asks whether code solves the stated equations; validation asks whether the equations model reality. For a method of theoretical order p, compute errors at h, h/2, and h/4 against an exact benchmark; in the asymptotic regime the error ratio E(h)/E(h/2) approaches 2^p. Manufactured solutions choose a smooth u, compute the forcing that makes u an exact solution, then test the numerical implementation. Compare residuals, conserved quantities, and boundary conditions separately. Grid convergence can be spoiled by roundoff, wrong boundary data, non-smooth solutions, or time error dominating space error.",
    worked: "Suppose a second-order scheme produces errors .04 at h=.2 and .01 at h=.1. Their ratio is four, consistent with order two, though a third grid and implementation audit are needed for confidence. If errors instead plateau at .01, a coding defect or another error source may dominate.",
    interpretation: "Evidence for a solver comes from predicted behavior under controlled refinement, not a single output.",
    trap: "Do not call agreement on one sample a proof of correctness; test different scales and independent properties.",
    practice: "Errors are .008 at h=.2 and .002 at h=.1. Estimate the observed convergence order.",
    solution: "The ratio is .008/.002=4. Solve 2^p=4 to obtain p=2. This is an observed order estimate between two grids, not a universal guarantee for all h.",
    checks: [["What does verification ask?", ["Whether code solves its equations", "Whether the equations describe nature", "Whether plots are attractive"], 0, "Validation is a distinct modeling question."], ["What error ratio suggests second order when h halves?", ["About 4", "About 2", "About 1"], 0, "Second-order error scales like h²."], ["Can one grid result establish convergence?", ["No", "Yes", "If it is smooth"], 0, "Refinement behavior is necessary evidence."]],
  },
];
