import type { MathLecture } from "./lectures";

/** Discrete counting tools used in probability and algorithm analysis. */
export const MATH_COMBINATORICS: MathLecture[] = [
  {
    lesson: "math.m17.l1", title: "Counting principles and bijections",
    premise: "Counting a large set is easier when you decompose choices without overlap or pair its objects one-to-one with something already countable.",
    idea: "The addition principle applies to disjoint cases: |A∪B|=|A|+|B| when A∩B is empty. The multiplication principle applies to ordered stages: if each first choice permits the same number of second choices, multiply the counts; with varying options, sum over first-stage choices. A bijection f:A→B proves |A|=|B| by pairing each object exactly once. State whether order matters, whether repetitions are allowed, and whether objects are distinguishable. Pigeonhole principle says placing more than n objects into n boxes forces some box to contain at least two; a generalized version guarantees a box with at least ceil(N/n) objects.",
    worked: "A three-character code uses uppercase letters first, then two digits, and repetition is allowed. There are 26·10·10=2600 codes. If all three characters had to be distinct even across different alphabets, the condition would not matter here because a letter cannot equal a digit; but distinct digits would change the count to 26·10·9=2340.",
    interpretation: "The sample space is an ordered product of choices. Writing the stages prevents both undercounting and double-counting.",
    trap: "Do not add stage counts when the choices occur together in sequence. Add only mutually exclusive alternatives.",
    practice: "How many binary strings of length 5 contain exactly one 1? Give a bijection argument.",
    solution: "Choose the unique position of the 1 among five positions. The map from a string to that position is a bijection with {1,2,3,4,5}, so there are 5 strings. The other four bits are forced to zero.",
    checks: [["When do counts multiply?", ["For successive independent choice stages", "For disjoint alternatives only", "Whenever two numbers appear"], 0, "Count ordered construction stages."], ["What does a bijection establish?", ["Equal cardinality", "Equal numerical labels", "Identical objects"], 0, "Each object on each side is paired once."], ["What does 11 objects in 10 boxes guarantee?", ["Some box has at least two", "Every box has two", "One box is empty"], 0, "Pigeonhole principle forbids all boxes having at most one."]],
  },
  {
    lesson: "math.m17.l2", title: "Permutations and combinations",
    premise: "The same selection can have many orders. Decide whether order matters before choosing a counting formula.",
    idea: "For n distinct objects, the number of ordered arrangements of k without replacement is n!/(n-k)!. Unordered k-element subsets number C(n,k)=n!/[k!(n-k)!], because each subset has k! orders. With replacement, ordered k-tuples from n choices number n^k. For a multiset with n total objects and repeated multiplicities m₁,…,m_r, distinct full arrangements number n!/(m₁!…m_r!). These formulas depend on distinguishability and constraints. A denominator is justified by a specific overcounting multiplicity, not inserted because the answer seems too large.",
    worked: "From 8 people choose a president, vice-president, and treasurer: order of roles matters, giving 8·7·6=336. A three-person committee without roles has 336/3!=56 possibilities. The difference is the six assignments of roles to each chosen trio.",
    interpretation: "The underlying selection is the same, but the object being counted includes role labels in one problem and not the other.",
    trap: "Do not use combinations for rankings or distinct offices. Conversely, do not count each unordered committee in all k! orders.",
    practice: "How many distinct permutations of the letters in LEVEL are there?",
    solution: "There are five letters with L appearing twice and E appearing twice. The count is 5!/(2!2!)=30. Dividing removes rearrangements of identical copies that do not produce a new word.",
    checks: [["Does choosing a president and vice-president depend on order?", ["Yes", "No", "Only if candidates repeat"], 0, "The offices are distinct."], ["What does C(n,k) count?", ["Unordered k-subsets", "Ordered lists with replacement", "All permutations"], 0, "Each selected set is counted once."], ["Why divide LEVEL permutations by 2!2!?", ["Repeated identical letters", "Two offices", "Five positions"], 0, "Swapping identical copies changes no visible arrangement."]],
  },
  {
    lesson: "math.m17.l3", title: "Binomial coefficients and identities",
    premise: "Binomial coefficients count subsets and also appear as coefficients when a sum is raised to a power.",
    idea: "The binomial theorem states (a+b)^n=Σ_{k=0}^n C(n,k)a^{n-k}b^k for nonnegative integer n. To form a term, select which k of n factors contribute b. Pascal's identity C(n,k)=C(n-1,k-1)+C(n-1,k) partitions k-subsets by whether they contain a fixed item. Symmetry C(n,k)=C(n,n-k) follows by choosing a subset or its complement. Summing all coefficients gives 2^n by setting a=b=1, also the number of all subsets. State index bounds; expressions such as C(n,-1) require a declared zero convention.",
    worked: "Expand (x+2)^3. The terms are C(3,0)x³, C(3,1)x²·2, C(3,2)x·2², and C(3,3)2³. Thus the result is x³+6x²+12x+8. The coefficient 3 in the middle cases counts which of three factors supply the 2.",
    interpretation: "The algebraic identity and subset count are the same selection process viewed in two settings.",
    trap: "Do not confuse the exponent on a with the number of selected b terms: they add to n, so the a exponent is n-k.",
    practice: "Prove Σ_{k=0}^n C(n,k)=2^n by counting subsets, and verify it for n=3.",
    solution: "Every subset of an n-element set has a unique size k, so partitioning all subsets by size gives the sum. Each element is either included or excluded, yielding 2^n subsets. At n=3 the sum is 1+3+3+1=8=2³.",
    checks: [["What does C(n,k) count inside (a+b)^n?", ["Ways to choose k factors that contribute b", "Number of factors total", "The exponent of a"], 0, "Choose positions for the b term."], ["What is Σ C(n,k) over k=0,…,n?", ["2^n", "n!", "n²"], 0, "Count all subsets."], ["Why does Pascal's identity hold?", ["Split subsets by membership of a fixed item", "Divide by n!", "Differentiate x^n"], 0, "The two cases are disjoint and exhaustive."]],
  },
  {
    lesson: "math.m17.l4", title: "Inclusion-exclusion",
    premise: "Adding overlapping sets counts shared elements more than once. Inclusion-exclusion corrects that overlap systematically.",
    idea: "For two finite sets, |A∪B|=|A|+|B|-|A∩B|. For three, add single-set sizes, subtract pair intersections, then add the triple intersection. In general, alternate signs over nonempty intersections. To count objects satisfying none of several properties, subtract the union of the bad-event sets from the total. Sketch a Venn diagram for small cases, but use a clear universe and exact intersection definitions in larger problems. If overlap data are conditional or incomplete, do not invent the missing intersection count.",
    worked: "Among integers 1 through 100, multiples of 2 number 50 and multiples of 3 number 33. Multiples of both are multiples of 6, numbering 16. Thus 50+33-16=67 integers are divisible by 2 or 3, and 100-67=33 are divisible by neither.",
    interpretation: "The 16 multiples of 6 were counted twice by simple addition and must be removed once.",
    trap: "For three sets, subtracting all pair overlaps also removes the triple intersection three times; add it back once to achieve net count one.",
    practice: "Among integers 1 through 30, how many are divisible by 2 or 5?",
    solution: "Multiples of 2: floor(30/2)=15. Multiples of 5: 6. Intersection multiples of 10: 3. Therefore the union contains 15+6-3=18 integers.",
    checks: [["What is subtracted in the two-set union formula?", ["The intersection", "The entire universe", "Both sets twice"], 0, "Shared members were added twice."], ["How do you count neither of two properties?", ["Universe size minus union size", "Add both sizes", "Subtract only intersection"], 0, "Neither is the complement of the union."], ["What happens to a triple intersection in the three-set formula?", ["It is added back", "It is ignored", "It is subtracted twice more"], 0, "Alternating correction restores net count one."]],
  },
  {
    lesson: "math.m17.l5", title: "Recurrences and generating functions",
    premise: "A recurrence defines each value from earlier ones. A generating function packages the entire sequence so algebra can reveal a closed form.",
    idea: "A recurrence needs sufficient initial values to determine a unique sequence. For a_n=c a_{n-1}, the solution is geometric; for linear constant-coefficient recurrences, characteristic roots play a role like those of differential equations. The ordinary generating function A(x)=Σ_{n≥0}a_n x^n can turn shifted recurrences into algebraic equations for A(x), interpreted formally or analytically where convergent. Coefficient extraction recovers a_n. Generating functions also encode combinatorial constructions: multiplying series convolves coefficients, corresponding to splitting a total size between two independent components.",
    worked: "Let a₀=1 and a_n=2a_{n-1} for n≥1. Then a_n=2^n by induction. For A(x)=Σa_nx^n, the recurrence gives A(x)-1=2xA(x), so A(x)=1/(1-2x). Its geometric expansion has coefficient 2^n at x^n, confirming the formula for |x|<1/2 analytically or as a formal series.",
    interpretation: "The generating-function equation captures every recurrence step at once; the initial condition supplies the standalone constant term.",
    trap: "Do not drop initial terms while shifting an indexed sum. For example Σ_{n≥1}a_nx^n=A(x)-a₀, not A(x).",
    practice: "With a₀=0 and a_n=a_{n-1}+1 for n≥1, find a_n and its generating function.",
    solution: "The recurrence gives a_n=n. Let A(x)=Σ_{n≥0}a_nx^n. Then A(x)=xA(x)+Σ_{n≥1}x^n=xA(x)+x/(1-x). Solving yields A(x)=x/(1-x)², whose x^n coefficient is n for n≥1.",
    checks: [["What extra data does a recurrence require?", ["Initial values", "Only a variable name", "An unrelated limit"], 0, "Earlier values anchor the sequence."], ["What does multiplying generating functions do to coefficients?", ["Convolution", "Entrywise subtraction", "No change"], 0, "A coefficient sums all size splits."], ["What is Σ_{n≥1}a_nx^n if A starts at n=0?", ["A(x)-a₀", "A(x)", "xA(x) always"], 0, "Remove the omitted constant term."]],
  },
  {
    lesson: "math.m17.l6", title: "Graphs and trees",
    premise: "Graphs model pairwise connections. Trees are connected graphs with no cycles, giving a unique simple path between any two vertices.",
    idea: "A simple undirected graph has vertices and unordered edges without loops or parallel copies. The sum of vertex degrees equals twice the edge count because each edge contributes to two endpoints. A tree on n vertices has n-1 edges, and equivalently is minimally connected or maximally acyclic. Breadth-first search discovers shortest paths by edge count in an unweighted graph; depth-first search helps explore components and detect cycles. State whether a graph is directed or weighted before using these facts. A connected graph with n-1 edges is a tree only under the usual finite undirected simple-graph setting.",
    worked: "Consider vertices A,B,C,D with edges AB,BC,CD. Degrees are 1,2,2,1, totaling 6=2·3 edges. The graph is connected and has no cycle, so it is a tree. The unique simple path from A to D is A-B-C-D and uses three edges.",
    interpretation: "Removing any edge disconnects this tree, while adding any new edge between existing vertices creates a cycle.",
    trap: "Do not use edge count n-1 alone to call a disconnected graph a tree; a disconnected graph can have a cycle and still have n-1 total edges.",
    practice: "A finite tree has 12 vertices. How many edges does it have? Could every vertex have degree 2?",
    solution: "A tree with 12 vertices has 11 edges, so degree sum is 22. If every vertex had degree 2, the sum would be 24, contradicting the handshake lemma; also a finite connected 2-regular graph would be a cycle rather than a tree.",
    checks: [["What is the degree sum in an undirected graph?", ["Twice the edge count", "The vertex count", "Half the edge count"], 0, "Every edge meets two endpoints."], ["How many edges does an n-vertex tree have?", ["n-1", "n", "2n"], 0, "Connected acyclic structure uses exactly n-1 edges."], ["What path property does a tree have?", ["A unique simple path between each vertex pair", "No paths", "Two paths between every pair"], 0, "Two distinct simple paths would create a cycle."]],
  },
  {
    lesson: "math.m17.l7", title: "Discrete probability foundations",
    premise: "Counting outcomes becomes probability only after assigning a valid distribution. Equally likely outcomes are a model assumption, not a universal fact.",
    idea: "A discrete sample space Ω has nonnegative masses p(ω) summing to one. For event A, P(A)=Σ_{ω∈A}p(ω). If all N outcomes are equiprobable, P(A)=|A|/N; otherwise use the weights. Complements satisfy P(Aᶜ)=1-P(A), and disjoint unions add. For arbitrary events, P(A∪B)=P(A)+P(B)-P(A∩B). Independence means P(A∩B)=P(A)P(B), a property to verify rather than assume from different event names. A probability tree can expose sequential conditional choices and avoid double-counting.",
    worked: "Roll two fair six-sided dice. The sample space has 36 ordered pairs, not 21 unordered pairs, because dice roles distinguish outcomes. The event ‘sum is 7’ has six pairs: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1). Each has probability 1/36, so P(sum 7)=6/36=1/6.",
    interpretation: "The sample-space representation determines whether simple counting ratios are valid; the 36 pairs have equal probability under independent fair dice.",
    trap: "Do not divide by the number of visible sum values 2 through 12; those sums have unequal probabilities.",
    practice: "A biased coin has P(H)=0.7 and is tossed twice independently. Find the probability of exactly one head.",
    solution: "Exactly one head consists of HT or TH. Each has probability 0.7·0.3=0.21 by independence, so the total is 0.42. Dividing by four outcomes would be invalid because they are not equally likely.",
    checks: [["When is P(A)=|A|/|Ω| valid?", ["When elementary outcomes are equiprobable", "For every discrete model", "Only for infinite spaces"], 0, "Otherwise sum individual masses."], ["Are two dice sums equally likely?", ["No", "Yes", "Only for fair dice"], 0, "Different sums have different numbers of ordered pairs."], ["What equation defines independence of A and B?", ["P(A∩B)=P(A)P(B)", "P(A)=P(B)", "A and B are disjoint"], 0, "Independent events can occur together."]],
  },
];
