import type { MathLecture } from "./lectures";

/** First complex-analysis sequence, from local analyticity to residues. */
export const MATH_COMPLEX_ANALYSIS: MathLecture[] = [
  {
    lesson: "math.m23.l1", title: "Complex differentiability",
    premise: "A complex derivative demands the same limit from every direction in the plane. That makes complex differentiability far more restrictive than differentiability along two real axes.",
    idea: "For f:C→C, f'(z₀)=lim_{h→0}[f(z₀+h)-f(z₀)]/h if the complex limit exists, independent of the direction of h. A function holomorphic on an open set is complex differentiable at every point there. Analyticity means it has a local convergent power series; in complex analysis holomorphic functions are analytic, a deep result rather than the definition of one-point differentiability. Standard polynomials are entire. Complex conjugation is not complex differentiable anywhere because its difference quotient is conjugate(h)/h, equal to 1 along real h and -1 along imaginary h.",
    worked: "For f(z)=z², the quotient [(z+h)²-z²]/h=2z+h for nonzero complex h, so the limit is 2z regardless of direction. For g(z)=conjugate(z), the quotient along real h is 1 and along purely imaginary h is -1, so no complex derivative exists at any z.",
    interpretation: "Directional agreement is essential. Real-coordinate partial derivatives existing separately do not establish a complex derivative.",
    trap: "Do not call a function holomorphic because it is differentiable along the real axis; test arbitrary complex increments or use a justified theorem.",
    practice: "Find the complex derivative of f(z)=3z²+2z+1 from the difference quotient.",
    solution: "Expand f(z+h)-f(z)=6zh+3h²+2h. Divide by nonzero h to obtain 6z+3h+2, which tends to 6z+2 as complex h approaches zero. Thus the polynomial is holomorphic everywhere.",
    checks: [["From which directions must the complex difference quotient agree?", ["Every complex direction", "Only real increments", "Only positive increments"], 0, "The limit is two-dimensional."], ["Is complex conjugation holomorphic?", ["No", "Yes", "Only on the real line as an open domain"], 0, "Real and imaginary increments give different quotients."], ["What is the complex derivative of z²?", ["2z", "2 conjugate(z)", "Zero"], 0, "The algebraic quotient tends to 2z."]],
  },
  {
    lesson: "math.m23.l2", title: "Cauchy-Riemann equations",
    premise: "The Cauchy-Riemann equations encode the directional agreement required for a complex derivative in real coordinates.",
    idea: "Write f(x+iy)=u(x,y)+iv(x,y). If f is complex differentiable at a point and u,v have appropriate real partials there, then u_x=v_y and u_y=-v_x. If u,v have continuous first partials on an open neighborhood and satisfy these equations there, f is holomorphic there. At one isolated point, satisfying the equations without sufficient differentiability assumptions is not a general converse. The equations express that the real Jacobian has shape [[a,-b],[b,a]], a rotation-dilation when a+ib≠0. Harmonicity of u and v follows with sufficient second-derivative regularity.",
    worked: "For f(z)=z²=(x²-y²)+i(2xy), u_x=2x and v_y=2x; u_y=-2y and -v_x=-2y. The equations hold everywhere, consistent with f'(z)=2z. For conjugation u=x,v=-y, u_x=1 while v_y=-1, so they fail everywhere.",
    interpretation: "The equations connect a complex derivative to a specific local linear geometry in the real plane.",
    trap: "Do not apply the Cauchy-Riemann converse from equations at a single point without checking the regularity required by the theorem being used.",
    practice: "For f(z)=e^x(cos y+i sin y), verify the Cauchy-Riemann equations and identify f(z).",
    solution: "u=e^x cos y and v=e^x sin y. Then u_x=e^x cos y=v_y and u_y=-e^x sin y=-v_x. These first partials are continuous everywhere, so f is holomorphic; it is e^{x+iy}=e^z.",
    checks: [["What equations relate u and v?", ["u_x=v_y and u_y=-v_x", "u_x=u_y and v_x=v_y", "u=v always"], 0, "They encode complex linearity of the derivative."], ["What added hypothesis supports the neighborhood converse?", ["Continuous first partials on an open neighborhood", "Only values at one point", "Positive real part"], 0, "Regularity prevents isolated-point pathologies."], ["What is the real Jacobian shape of complex multiplication by a+ib?", ["[[a,-b],[b,a]]", "[[a,b],[b,a]]", "Always diagonal"], 0, "Multiplication rotates and scales."]],
  },
  {
    lesson: "math.m23.l3", title: "Contour integration",
    premise: "A contour integral accumulates a complex-valued function along an oriented path, using complex displacement rather than ordinary arc length.",
    idea: "For a piecewise smooth path γ from [a,b] into the complex plane, define its contour integral by integrating f(γ(t))γ'(t) over t from a to b. Reversing orientation negates the integral. Bounds include |∫_γ f dz|≤(sup_γ|f|)·length(γ), useful for vanishing-arc arguments. If f has a holomorphic primitive F on the path's region, the integral depends only on endpoints: F(γ(b))-F(γ(a)). Holomorphicity on a path alone does not guarantee a global primitive on a punctured domain. A contour may be closed, in which case endpoint difference is zero whenever a primitive exists across the relevant region.",
    worked: "Integrate f(z)=z around the unit circle γ(t)=e^{it}, 0≤t≤2π. Since z has primitive F(z)=z²/2 on all C, the closed integral is zero. Directly, f(γ)γ'=e^{it}·ie^{it}=ie^{2it}, whose integral over a full period is zero.",
    interpretation: "Parametrization computes any contour integral, while a primitive can collapse the work to endpoints.",
    trap: "Do not replace dz with |dz|: the latter is arc length and loses orientation and complex cancellation.",
    practice: "Integrate f(z)=1 along the straight segment from 1+i to 3+2i.",
    solution: "A primitive is F(z)=z, so the integral is (3+2i)-(1+i)=2+i. Equivalently, γ(t)=1+i+t(2+i), 0≤t≤1, has derivative 2+i and integrates to 2+i.",
    checks: [["What factor appears in a parametrized contour integral?", ["γ'(t)", "Only |γ'(t)|", "The curvature"], 0, "Complex displacement is directional."], ["What does path reversal do?", ["Negates the integral", "Leaves it unchanged", "Squares it"], 0, "Orientation reverses dz."], ["What does a primitive make the integral depend on?", ["Endpoints", "Only path length", "The number of turns always"], 0, "Use the chain rule along the path."]],
  },
  {
    lesson: "math.m23.l4", title: "Cauchy's integral theorem",
    premise: "Holomorphic functions have zero integral around suitable closed contours when the function is holomorphic throughout the enclosed region.",
    idea: "One standard form says a holomorphic function on a simply connected open set has zero integral around every closed piecewise smooth contour there. For a Jordan curve, holomorphicity on a neighborhood of its interior and boundary also gives zero boundary integral. The topology and domain matter: f(z)=1/z is holomorphic on C\{0}, but the unit circle encloses the excluded origin and its integral is 2πi. Under stronger results, contour deformation is permitted through regions where the integrand remains holomorphic. Do not quote the theorem merely because the curve itself avoids singularities; inspect the entire swept or enclosed region.",
    worked: "For f(z)=z³+2 on the unit circle, the integrand is entire. A primitive z⁴/4+2z exists globally, so the integral is zero. By contrast, 1/z has no primitive on the punctured plane and direct parametrization z=e^{it} gives (1/z)dz=i dt, totaling 2πi.",
    interpretation: "The nonzero 1/z integral detects the hole in the domain. The circle avoids zero as a path but surrounds it.",
    trap: "Do not apply zero-integral reasoning across a singularity inside the contour; contour avoidance alone is insufficient.",
    practice: "Evaluate ∮ around |z|=2 of 1/(z-3) dz counterclockwise, and explain why.",
    solution: "The singularity z=3 lies outside the closed disk |z|≤2. The function is holomorphic on a neighborhood of that disk, so Cauchy's theorem gives integral zero. No residue lies inside the contour.",
    checks: [["What must be checked for a closed-contour zero theorem?", ["Holomorphicity on an appropriate enclosed region", "Only smoothness on the curve", "A positive radius"], 0, "Interior singularities matter."], ["What is ∮_{|z|=1}1/z dz counterclockwise?", ["2πi", "0", "1"], 0, "The origin is an excluded enclosed point."], ["Can topology affect existence of a global primitive?", ["Yes", "No", "Only in real calculus"], 0, "The punctured plane is the classic example."]],
  },
  {
    lesson: "math.m23.l5", title: "Cauchy's integral formula",
    premise: "Values and derivatives of a holomorphic function inside a contour are determined by its boundary values.",
    idea: "If f is holomorphic on a neighborhood of a positively oriented simple closed contour C and its interior, with a inside, then f(a)=(1/(2πi))∮_C f(z)/(z-a) dz. More generally f^{(n)}(a)=n!/(2πi)∮_C f(z)/(z-a)^{n+1} dz. The formula implies holomorphic functions have derivatives of all orders and gives estimates such as |f^{(n)}(a)|≤n! M/R^n on a radius-R circle where |f|≤M. These estimates help prove Liouville's theorem: a bounded entire function is constant. Orientation and inclusion of a determine the result.",
    worked: "Evaluate ∮_{|z|=2} e^z/z dz counterclockwise. The function e^z is entire and a=0 lies inside. Cauchy's formula gives 2πi e^0=2πi. If the same contour were clockwise, orientation would reverse the sign.",
    interpretation: "The apparent singularity of e^z/z encodes evaluation of e^z at zero; the boundary integral recovers that interior value.",
    trap: "Do not apply the formula if a lies outside C or if f has other singularities inside that violate the holomorphicity hypothesis.",
    practice: "Evaluate ∮_{|z|=3} cos z/(z-1)² dz counterclockwise.",
    solution: "The derivative formula with n=1 and a=1 gives 2πi f'(1) where f(z)=cos z. Since f'(1)=-sin 1, the integral is -2πi sin 1. The circle contains a=1 and cos z is entire.",
    checks: [["What does ∮ f(z)/(z-a) dz recover?", ["2πi f(a)", "f'(a) without constants", "Always zero"], 0, "Cauchy's integral formula evaluates the interior value."], ["What does a squared denominator recover?", ["First derivative times 2πi", "Second derivative", "Only f(a)"], 0, "Use the n=1 formula."], ["Does clockwise orientation keep the same sign?", ["No", "Yes", "Only for real f"], 0, "It negates the contour integral."]],
  },
  {
    lesson: "math.m23.l6", title: "Laurent series and isolated singularities",
    premise: "A Laurent series includes negative powers and reveals what kind of isolated singularity a complex function has.",
    idea: "On an annulus around a, a holomorphic function has a Laurent expansion Σ_{n=-∞}∞c_n(z-a)^n. If all negative coefficients vanish, the singularity is removable after defining the missing value. If finitely many negative powers occur with lowest exponent -m, it is a pole of order m. If infinitely many negative powers occur, it is essential. The coefficient c_{-1} is the residue. Classification concerns an isolated singularity: the function must be holomorphic on some punctured disk. Different annuli can have different Laurent expansions, so state the region of convergence.",
    worked: "At zero, f(z)=e^z/z² expands as z^{-2}+z^{-1}+1/2+z/6+… . There are two negative powers, so zero is a pole of order 2. The coefficient of z^{-1} is 1, hence residue 1. In contrast sin z/z has a removable singularity because its series begins 1-z²/6+… .",
    interpretation: "The principal part records the singular behavior; the residue is the one coefficient that controls a contour integral around the isolated point.",
    trap: "Do not call an accumulation point of singularities an isolated singularity; the Laurent classification requires a punctured disk free of other singularities.",
    practice: "Classify the singularity at zero of f(z)=1/z³+2/z+5 and find its residue.",
    solution: "The finite principal part begins with z^{-3}, so zero is a pole of order 3. The coefficient of z^{-1} is 2, so its residue at zero is 2. The constant 5 does not affect the residue.",
    checks: [["What distinguishes a pole from an essential singularity?", ["Finitely many negative Laurent powers", "No positive powers", "A nonzero value only"], 0, "An essential singularity has infinitely many negative powers."], ["Which coefficient is the residue?", ["c_{-1}", "c_0", "The leading positive coefficient"], 0, "It multiplies (z-a)^{-1}."], ["What does a removable singularity have in its Laurent principal part?", ["No negative powers", "Infinitely many negative powers", "A nonzero z^{-2} term"], 0, "Extend by the constant coefficient."]],
  },
  {
    lesson: "math.m23.l7", title: "Residues and real integrals",
    premise: "The residue theorem turns a contour integral into a finite sum of local singularity data. Carefully chosen contours can then evaluate real integrals.",
    idea: "If f is meromorphic in a region and C is a positively oriented contour avoiding poles, ∮_C f dz=2πi times the sum of residues inside C, counting winding number for more general contours. At a simple pole a of g/h with h(a)=0 and h'(a)≠0, residue is g(a)/h'(a). For real improper integrals, choose a contour whose extra arcs vanish; this requires an explicit bound, not a sketch. Upper-half-plane closure may depend on exponential factors and decay. Check poles on the real axis separately using indentations or principal values where appropriate.",
    worked: "Evaluate ∮_{|z|=2}1/(z-1) dz counterclockwise. The only simple pole inside is z=1 with residue 1, so the integral is 2πi. For ∫_{-∞}∞1/(x²+1)dx, the upper-half-plane pole is i with residue 1/(2i). The upper semicircle contribution tends to zero because the integrand is O(1/R²) over arc length O(R), yielding π for the real integral.",
    interpretation: "The real result comes from both a local residue and a global arc estimate. Omitting either step leaves the argument incomplete.",
    trap: "Do not include a pole merely because it is near the contour; only enclosed poles contribute, and a pole on the path needs a modified argument.",
    practice: "Find ∮_{|z|=1}1/(z-2) dz and state the residue-theorem reason.",
    solution: "The pole z=2 lies outside the unit circle, so there are no enclosed poles. The residue sum is zero and the contour integral is zero. The function is holomorphic on a neighborhood of the closed unit disk.",
    checks: [["What multiplies the enclosed residue sum?", ["2πi for a simple positive contour", "π only", "The contour radius"], 0, "This is the residue theorem."], ["What else is required when deriving a real integral by contour closure?", ["A vanishing-arc estimate or its actual contribution", "Only a diagram", "Equal real and complex variables"], 0, "The extra contour pieces must be accounted for."], ["Does a pole outside C contribute to its residue sum?", ["No", "Yes", "Only if simple"], 0, "Enclosure or winding number controls contribution."]],
  },
  {
    lesson: "math.m23.l8", title: "Conformal maps",
    premise: "A holomorphic map with nonzero derivative preserves angles locally, though it may bend and rescale the entire region.",
    idea: "At z₀, a holomorphic f with f'(z₀)≠0 is locally a complex multiplication by f'(z₀) plus smaller-order error, hence a rotation and positive scale. It is conformal there: oriented angles between smooth curves are preserved. If f'(z₀)=0, this local conformality conclusion fails. A Möbius transformation (az+b)/(cz+d) with ad-bc≠0 maps generalized circles to generalized circles on the Riemann sphere, with a pole where cz+d=0. Domain and branch cuts matter for maps such as log z or z^α. A globally conformal bijection is stronger than local angle preservation.",
    worked: "For f(z)=z² at z₀=1+i, derivative is 2+2i, nonzero. Its local scale is |2+2i|=2sqrt(2), and its rotation angle is π/4. At z₀=0, derivative is zero, so the map is not locally conformal there even though it is holomorphic.",
    interpretation: "The derivative encodes local geometry, but global behavior can fold the plane: z² maps z and -z to the same value.",
    trap: "Do not infer global one-to-one behavior from f'(z)≠0 at each individual point; local invertibility and global injectivity differ.",
    practice: "For f(z)=3iz+2, give its local scale and rotation, and decide whether it is globally bijective on C.",
    solution: "Derivative is constant 3i, so every local piece scales by 3 and rotates by π/2. The map is affine with nonzero slope and inverse z=(w-2)/(3i), hence globally bijective on C.",
    checks: [["When is a holomorphic map locally conformal?", ["Where f'(z)≠0", "Where f(z)=0", "At every point automatically"], 0, "Nonzero derivative is a local rotation-dilation."], ["Does local conformality imply global injectivity?", ["No", "Yes", "Only for polynomials"], 0, "Different distant points may share an image."], ["What does multiplication by 3i do geometrically?", ["Scale 3 and rotate π/2", "Only reflect", "Collapse to zero"], 0, "Magnitude and argument determine the local map."]],
  },
];
