import type { MathLecture } from "./lectures";

/** Improper integrals and sequences introduce convergence as a claim to prove. */
export const MATH_CONVERGENCE_LECTURES: MathLecture[] = [
  {
    lesson: "math.m9.l1",
    title: "Infinite-interval integrals",
    premise: "An integral over an unbounded interval is defined by a limit of ordinary integrals. A finite antiderivative expression at finite bounds does not by itself prove the infinite limit exists.",
    idea: "Define ∫ₐ^∞ f(x)dx as lim from b to infinity of ∫ₐᵇ f(x)dx, when that limit is finite. If the limit fails to exist or is infinite, the improper integral diverges. For f(x)=1/x^p on [1,∞), integration shows convergence exactly when p>1: for p≠1, the finite integral equals (b^(1-p)-1)/(1-p), and b^(1-p) tends to zero precisely when p>1. At p=1, the finite result ln b grows without bound. An integrand tending to zero is necessary for many positive examples but is not enough by itself; 1/x is the standard warning.",
    worked: "For ∫₁^∞ 1/x² dx, integrate to [-1/x]₁ᵇ=1-1/b. Its limit is 1, so the integral converges. For ∫₁^∞ 1/x dx, the finite integral is ln b, which grows without bound; it diverges despite 1/x approaching zero.",
    interpretation: "Convergence is a statement about accumulated tail area, not merely pointwise height. A decreasing height can still accumulate without limit over an infinite width.",
    trap: "Do not substitute infinity as an ordinary number into an antiderivative or assume every decaying positive function has finite area.",
    practice: "Classify ∫₂^∞ x^(-3/2) dx and compute its value. Explain why changing the lower bound from 1 to 2 does not change the convergence classification.",
    solution: "For finite b, ∫₂ᵇ x^(-3/2)dx=[-2x^(-1/2)]₂ᵇ=-2/sqrt(b)+2/sqrt(2). Taking b to infinity gives sqrt(2). The p-value is 3/2>1, and removing or adding a finite interval away from the singularity changes the integral's value but not its tail convergence.",
    checks: [
      ["For which p does ∫₁^∞1/x^p converge?", ["p>1", "p≥0", "p≤1"], 0, "Test the limiting antiderivative."],
      ["Does f(x)→0 imply ∫₁^∞ f converges?", ["No", "Yes", "Only for 1/x"], 0, "The harmonic integral is a counterexample."],
      ["How is an infinite upper bound defined?", ["As a limit of finite upper bounds", "By substituting infinity as a number", "By taking absolute value"], 0, "Improper integration is a limit operation."],
    ],
  },
  {
    lesson: "math.m9.l2",
    title: "Unbounded-integrand integrals",
    premise: "A finite interval can still produce an improper integral when the integrand blows up at an endpoint or inside the interval. Each singular side needs its own one-sided limit.",
    idea: "If f is unbounded as x approaches a from the right, define ∫ₐᵇ f as lim from c down to a of ∫𝒸ᵇ f, if finite. At an interior singularity c, split into ∫ₐᶜ f and ∫𝒸ᵇ f and require both one-sided pieces to converge. Opposite infinities do not cancel into convergence; a symmetric principal value is a different notion. For x^(-p) on (0,1], direct integration yields convergence exactly when p<1. The p-threshold differs from the infinite-interval case because the difficulty lies near zero rather than far away.",
    worked: "For ∫₀¹ x^(-1/2)dx, start at ε>0. The finite integral [2sqrt(x)]ε¹=2-2sqrt(ε) tends to 2, so it converges. For ∫₀¹1/x dx, the finite integral -ln ε grows without bound as ε approaches zero, so it diverges.",
    interpretation: "The interval is short, but a tall singularity can still accumulate infinite area. Convergence depends on how sharply the integrand rises near the forbidden point.",
    trap: "Do not apply the fundamental theorem across an undefined interior point. A symmetric cancellation of two divergent one-sided pieces does not make the ordinary improper integral converge.",
    practice: "Classify ∫₋₁¹ 1/x dx as an ordinary improper integral. Then classify ∫₀¹ x^(-2/3)dx and compute the convergent value.",
    solution: "Split the first integral at zero. Both one-sided pieces diverge in magnitude, so the ordinary improper integral diverges; a symmetric principal value of zero would be a separate definition. For the second, integrate from ε to 1: [3x^(1/3)]ε¹=3-3ε^(1/3), whose limit is 3. Since p=2/3<1, it converges near zero.",
    checks: [
      ["For which p does ∫₀¹x^(-p) converge?", ["p<1", "p>1", "p=1 only"], 0, "Examine the antiderivative near zero."],
      ["What happens at an interior singularity?", ["Split and require both one-sided integrals to converge", "Let infinities cancel", "Ignore the point"], 0, "An ordinary improper integral needs two finite limits."],
      ["Is a principal value the same as ordinary improper convergence?", ["No", "Yes", "Only on positive intervals"], 0, "Symmetric cancellation is a different definition."],
    ],
  },
  {
    lesson: "math.m9.l3",
    title: "Comparison for improper integrals",
    premise: "When an antiderivative is inaccessible, comparison with a known positive function can prove convergence or divergence. The inequality must point in the direction that supports the conclusion.",
    idea: "For 0≤f≤g on a troublesome tail, convergence of ∫g implies convergence of ∫f; divergence of ∫f implies divergence of ∫g. If the ratio of f to g tends to a positive finite constant, limit comparison shows the two positive integrals share a convergence classification, provided both functions are eventually positive. Compare only near the improper endpoint; behavior on a bounded region away from singularities does not control tail convergence. When the functions change sign, direct positive comparison may fail, and absolute convergence may need separate analysis.",
    worked: "For x≥1, 0≤1/(x²+1)≤1/x². Since ∫₁^∞1/x² converges, the smaller integral ∫₁^∞1/(x²+1) converges too. Conversely, 1/sqrt(x²+1) behaves like 1/x at infinity. Its ratio to 1/x tends to 1, so its integral diverges by limit comparison.",
    interpretation: "A small function below a convergent majorant has finite total tail area. Being below a divergent function gives no conclusion by itself.",
    trap: "Do not reverse the comparison direction: f≤g and divergence of ∫g says nothing about ∫f. Check eventual positivity before using limit comparison.",
    practice: "Classify ∫₁^∞ (3x+2)/(x³+1) dx by comparison with a power of x. State the limit comparison ratio.",
    solution: "For large x the integrand is positive and behaves like 3/x². Divide by 1/x²: x²(3x+2)/(x³+1) tends to 3, a positive finite constant. Because ∫₁^∞1/x² converges and the integrand is continuous on [1,∞), the given integral converges.",
    checks: [
      ["If 0≤f≤g and ∫g converges, what follows?", ["∫f converges", "∫f diverges", "No conclusion"], 0, "A smaller positive tail is bounded by a finite one."],
      ["What limit supports positive limit comparison?", ["A finite positive nonzero ratio", "Only zero", "Only infinity"], 0, "Both tails have comparable size."],
      ["Does a bounded interval away from the singularity decide tail convergence?", ["No", "Yes", "Only for rational functions"], 0, "Focus on the improper endpoint."],
    ],
  },
  {
    lesson: "math.m9.l4",
    title: "Sequences and convergence",
    premise: "A sequence is an ordered list indexed by integers. To say its terms converge means that eventually every term lies as close as desired to one fixed limit, not merely that early terms look settled.",
    idea: "The formal definition that aₙ approaches L is: for every ε>0 there is an integer N such that n≥N implies |aₙ-L|<ε. This is an eventual condition; finitely many unusual first terms do not affect convergence. Familiar limit laws apply when component sequences converge, but a denominator limit must be nonzero for quotient laws. A sequence can be bounded and still fail to converge, such as (-1)^n. It can be unbounded and therefore cannot converge to a finite real number. Looking at a graph or a few values can suggest L, but the argument must control all sufficiently large n.",
    worked: "For aₙ=(2n+1)/(n+3), divide numerator and denominator by n to see that (2+1/n)/(1+3/n) approaches 2. More explicitly, |aₙ-2|=5/(n+3). Given ε>0, any integer N>5/ε ensures n≥N makes this distance less than ε.",
    interpretation: "The epsilon argument explains why every requested tolerance is eventually met. The choice of N may depend on ε, but not on which later n is tested.",
    trap: "Do not infer convergence from boundedness alone or from a handful of decimal approximations. Alternation can persist forever inside a bounded range.",
    practice: "Determine whether bₙ=(-1)^n+1/n converges. Explain using even and odd subsequences rather than a numerical table.",
    solution: "For even n, bₙ=1+1/n→1. For odd n, bₙ=-1+1/n→-1. A convergent sequence would force every subsequence to the same limit, so bₙ does not converge.",
    checks: [
      ["What does aₙ→L require?", ["All sufficiently late terms meet every positive tolerance", "Only the first ten terms are near L", "Terms are bounded"], 0, "Convergence is an eventual all-terms statement."],
      ["Is every bounded sequence convergent?", ["No", "Yes", "Only if positive"], 0, "The alternating sequence is bounded but divergent."],
      ["What happens to subsequences of a convergent sequence?", ["They share its limit", "They diverge", "They have arbitrary limits"], 0, "Subsequences cannot escape an eventual bound."],
    ],
  },
  {
    lesson: "math.m9.l5",
    title: "Monotone bounded sequences",
    premise: "A sequence that moves only upward and cannot pass a fixed ceiling must converge. The monotone convergence theorem turns order and bounds into a rigorous existence result.",
    idea: "If aₙ is nondecreasing and bounded above, its supremum L exists by completeness of the real numbers. For any ε>0, L-ε cannot be an upper bound, so some term exceeds L-ε; monotonicity keeps every later term between L-ε and L. Thus aₙ approaches L. A nonincreasing sequence bounded below has the analogous infimum result. For recursively defined sequences, prove an invariant bound and monotonicity before solving a fixed-point equation. A fixed-point equation produces candidates for a limit only after convergence has been established.",
    worked: "Define a₁=1 and aₙ₊₁=sqrt(2+aₙ). Since 1≤a₁≤2 and sqrt(2+x) maps [1,2] into [sqrt(3),2], induction keeps 1≤aₙ≤2. Also sqrt(2+x)≥x on [1,2] because 2+x≥x² there, so the sequence is nondecreasing. It converges to some L in [1,2], and continuity gives L=sqrt(2+L). Solving L²-L-2=0 yields L=2, since the other root -1 is outside the interval.",
    interpretation: "The bound and monotonicity establish that a limit exists; only then is passing to the recursion justified. A negative algebraic root is not automatically an attainable limit.",
    trap: "Do not solve aₙ₊₁=aₙ and claim convergence without proof. Oscillating recursions can have fixed points that their actual sequences never approach.",
    practice: "Let a₁=0 and aₙ₊₁=(aₙ+2)/3. Prove the sequence is increasing and bounded above by 1, then find its limit.",
    solution: "The map (x+2)/3 preserves [0,1], so every term remains bounded there. Since aₙ₊₁-aₙ=2(1-aₙ)/3≥0, the sequence increases. It therefore converges, and L=(L+2)/3 gives L=1.",
    checks: [
      ["What guarantees a nondecreasing real sequence converges?", ["An upper bound", "A lower bound only", "A fixed point alone"], 0, "Monotonicity plus a ceiling gives a supremum limit."],
      ["When may a recursion be passed to a fixed-point equation?", ["After convergence is established", "Before checking any bounds", "Only for polynomials"], 0, "A candidate equation does not prove a limit exists."],
      ["What real-number property underlies the monotone theorem?", ["Completeness", "Periodicity", "Differentiability"], 0, "Bounded nonempty sets have a supremum."],
    ],
  },
  {
    lesson: "math.m9.l6",
    title: "Mixed convergence problems",
    premise: "A convergence problem is solved by locating the difficult endpoint, choosing an appropriate test, and explaining exactly which hypotheses justify it.",
    idea: "For an improper integral, first find every infinite interval and every point where the integrand is unbounded; split so each troublesome endpoint has its own limit. Try an exact antiderivative when available, then positive comparison or limit comparison with a known power. A finite value on one side cannot rescue divergence on another. For a sequence, inspect algebraic dominant terms, subsequences, monotonicity, and bounds. Never transfer a series test to a sequence or an integral without its own hypotheses. A classification should include both the conclusion and the reason, not merely a named test.",
    worked: "Consider ∫₀^∞1/(1+x²)dx. Split at 1. The piece on [0,1] is ordinary and finite. The tail behaves like 1/x² and converges; in fact the antiderivative arctan x gives [arctan x]₀^∞=π/2. By contrast, ∫₀^∞1/x dx fails at both zero and infinity; neither failure can be hidden by writing an ambiguous combined expression.",
    interpretation: "Classifying each endpoint prevents false cancellation. Finding an exact value is useful but not necessary once a valid convergence proof is available.",
    trap: "Do not write one limit across two singular endpoints, or use an eventually true comparison to justify a separate near-zero singularity without checking it.",
    practice: "Classify ∫₀^∞ x^(-1/2)/(1+x) dx without finding an antiderivative. Explain the comparison near zero and near infinity separately.",
    solution: "Split at 1. On (0,1], 0≤x^(-1/2)/(1+x)≤x^(-1/2), whose integral converges near zero because the exponent 1/2 is below 1. For x≥1, 0≤x^(-1/2)/(1+x)≤x^(-3/2), whose integral converges at infinity because 3/2>1. Both improper pieces converge, so the whole integral converges.",
    checks: [
      ["What if an improper integral has two troublesome endpoints?", ["Split and check both limits", "Let divergent pieces cancel", "Check only infinity"], 0, "Each improper piece needs its own finite limit."],
      ["What power is suitable near infinity for x^(-1/2)/(1+x)?", ["x^(-3/2)", "x^(-1/2)", "x²"], 0, "The denominator behaves like x there."],
      ["What power is suitable near zero for the same integrand?", ["x^(-1/2)", "x^(-3/2)", "x²"], 0, "The denominator approaches one near zero."],
    ],
  },
];
