import type { MathLecture } from "./lectures";

/** A complete applications unit: establish hypotheses, choose a model, then
 * interpret a derivative in the original setting. */
export const MATH_DERIVATIVE_APPLICATIONS: MathLecture[] = [
  {
    lesson: "math.m5.l1",
    title: "Rolle's theorem and the mean value theorem",
    premise: "A derivative describes a local slope. The mean value theorem connects one of those slopes to the average change across an entire interval, provided the function is continuous on the closed interval and differentiable inside it.",
    idea: "Rolle's theorem says that if f(a)=f(b), then some c strictly between a and b has f'(c)=0. Geometrically, a smooth trip that starts and ends at the same height must have a horizontal tangent somewhere. The mean value theorem follows by subtracting the secant line: g(x)=f(x)-[f(a)+(f(b)-f(a))(x-a)/(b-a)]. The new function has equal endpoint values, so Rolle's theorem yields f'(c)=(f(b)-f(a))/(b-a). Check both hypotheses before invoking either theorem. A corner or a jump can invalidate the conclusion.",
    worked: "For f(x)=x² on [1,3], the secant slope is (9-1)/(3-1)=4. The function is continuous and differentiable, so the theorem guarantees c in (1,3) with 2c=4; c=2. For h(x)=|x| on [-1,1], the endpoint values match, but the corner at zero violates differentiability, and h' is never zero where it exists.",
    interpretation: "The theorem guarantees at least one matching instantaneous rate, not that every rate matches or that the point is unique. Its value is a logical guarantee even when c cannot be solved exactly.",
    trap: "Do not apply the theorem to an open interval without checking endpoint continuity, or to a function with a corner, hole, or vertical tangent inside the interval.",
    practice: "Verify the mean value theorem for f(x)=x³ on [0,2] and find every guaranteed c. Then explain why f(x)=1/x on [-1,1] is ineligible.",
    solution: "The polynomial is continuous on [0,2] and differentiable on (0,2). Its secant slope is (8-0)/2=4. Solve 3c²=4 to obtain c=2/sqrt(3); the negative solution is outside (0,2). The reciprocal is undefined at zero, so it is not continuous on [-1,1] and the theorem cannot be applied there.",
    checks: [
      ["What hypotheses does the mean value theorem require?", ["Closed-interval continuity and interior differentiability", "Only differentiability at the endpoints", "Only equal endpoint values"], 0, "State both hypotheses before finding c."],
      ["What additional condition gives Rolle's conclusion f'(c)=0?", ["f(a)=f(b)", "f(a)=0", "f'(a)=f'(b)"], 0, "The secant slope must be zero."],
      ["For f(x)=x² on [1,3], which c matches the secant slope?", ["2", "1", "3"], 0, "The secant slope is 4 and f'(c)=2c."],
    ],
  },
  {
    lesson: "math.m5.l2",
    title: "Monotonicity and critical points",
    premise: "The sign of f' tells whether a differentiable function rises or falls on an interval. Critical points are candidates where that behavior can change, not automatic maxima or minima.",
    idea: "A critical point is a domain point where f'=0 or f' does not exist. To make a sign chart, locate those points and any domain breaks, then test one input in each resulting open interval. The mean value theorem justifies the conclusion: if f'>0 throughout an interval, then f(b)-f(a)=f'(c)(b-a)>0 whenever a<b. Likewise f'<0 gives decreasing behavior. A local maximum can occur when the sign moves from positive to negative; a local minimum when it moves from negative to positive. On a closed interval, compare all critical values and endpoints to find absolute extrema.",
    worked: "Let f(x)=x³-3x. Then f'(x)=3(x-1)(x+1). The derivative is positive for x<-1, negative for -1<x<1, and positive for x>1. Thus f rises, falls, then rises. The change at -1 gives a local maximum f(-1)=2; the change at 1 gives a local minimum f(1)=-2.",
    interpretation: "A zero derivative signals a candidate. Its neighboring signs determine the local behavior; endpoints matter for absolute comparisons on a bounded interval.",
    trap: "Do not call every f'=0 point an extremum. For x³, f'(0)=0 but the function increases on both sides. A point outside the function's domain is never a critical point.",
    practice: "For g(x)=x³-12x on [-3,3], find increasing and decreasing intervals, all interior local extrema, and the absolute maximum and minimum on the stated interval.",
    solution: "g'=3(x-2)(x+2). It is positive on (-3,-2), negative on (-2,2), and positive on (2,3). The local maximum is g(-2)=16 and the local minimum is g(2)=-16. At endpoints g(-3)=9 and g(3)=-9, so the absolute maximum and minimum remain 16 and -16.",
    checks: [
      ["If f'>0 throughout an interval, what follows?", ["f increases there", "f is concave up there", "f has a maximum there"], 0, "Use the mean value theorem on two points."],
      ["Is a zero of f' automatically an extremum?", ["No", "Yes", "Only for polynomials"], 0, "Check the signs on both sides."],
      ["What extra values must be compared for absolute extrema on [a,b]?", ["Endpoint values", "Only second derivatives", "Only asymptotes"], 0, "Absolute extrema can occur at endpoints."],
    ],
  },
  {
    lesson: "math.m5.l3",
    title: "Concavity and inflection points",
    premise: "The first derivative measures slope; the second derivative measures how that slope changes. Concavity is about the trend in slopes, not whether the graph is above the x-axis.",
    idea: "Where f''>0 on an interval, slopes increase and the graph is concave up. Where f''<0, slopes decrease and the graph is concave down. Find candidates for inflection where f''=0 or f'' is undefined, but retain only domain points across which concavity actually changes. Construct a second-derivative sign chart rather than substituting a candidate into one formula. A stationary point with f''=0 might be an inflection, a flat minimum, or neither.",
    worked: "For f(x)=x³-3x, f'(x)=3x²-3 and f''(x)=6x. The second derivative is negative on x<0 and positive on x>0, so f changes from concave down to concave up at (0,0). For h(x)=x⁴, h''(x)=12x² vanishes at zero but stays nonnegative on both sides; zero is not an inflection point.",
    interpretation: "A changing sign of f'' is sufficient evidence here. At a smooth inflection the tangent can be horizontal, but it need not be; x³-3x has slope -3 at its inflection.",
    trap: "Do not infer inflection from f''(c)=0 alone, and do not label a discontinuity as an inflection just because signs differ across a gap.",
    practice: "Analyze concavity and inflection points of p(x)=x⁴-2x². Give exact coordinates and explain why both candidate roots of p'' qualify or fail.",
    solution: "p''(x)=12x²-4=4(3x²-1). It is positive for |x|>1/sqrt(3) and negative for |x|<1/sqrt(3). Concavity changes at both x=±1/sqrt(3), so both are inflection points. At either input x²=1/3 and x⁴=1/9, giving p=1/9-2/3=-5/9. The coordinates are (±1/sqrt(3),-5/9).",
    checks: [
      ["What does f''>0 on an interval describe?", ["Increasing slopes and concave-up shape", "A positive function value", "A local maximum everywhere"], 0, "The second derivative tracks change in slope."],
      ["Is f''(c)=0 enough to prove an inflection?", ["No, concavity must change", "Yes", "Only if f'(c)=0"], 0, "x⁴ is a counterexample at zero."],
      ["Where can an inflection point occur?", ["At a point in the function's domain", "At any vertical asymptote", "Only where f'=0"], 0, "The graph must contain the point."],
    ],
  },
  {
    lesson: "math.m5.l4",
    title: "First- and second-derivative tests",
    premise: "An extremum test is a decision rule with hypotheses. The first-derivative test looks at behavior on both sides; the second-derivative test gives a shorter conclusion only when it is decisive.",
    idea: "At an interior critical point c, if f' changes from positive to negative, f has a local maximum; negative to positive gives a local minimum. No sign change means neither under this test. If f'(c)=0 and f''(c)>0, the second-derivative test gives a strict local minimum; if f''(c)<0, a strict local maximum. When f''(c)=0 or does not exist, the test is inconclusive, not a declaration of no extremum. Return to a first-derivative sign chart or compare nearby function values. A critical point caused by an undefined first derivative can still be an extremum.",
    worked: "For f(x)=x⁴, f'(0)=0 and f''(0)=0. The second-derivative test says nothing, but f'=4x³ changes from negative to positive, proving a local minimum at zero. For g(x)=x³, the same two derivative values occur, yet g'=3x² is positive on both sides, so zero is not an extremum.",
    interpretation: "The two examples have identical values of f' and f'' at zero. Behavior around the point, rather than those two numbers alone, resolves the difference.",
    trap: "Never turn an inconclusive second-derivative test into a negative conclusion. Also do not use f''(c)>0 without first checking that c is a stationary point.",
    practice: "Classify x=0 for h(x)=-x⁴ and k(x)=x³+x². State which test you use and why it is valid.",
    solution: "For h, h'(0)=h''(0)=0, so the second-derivative test is inconclusive. h'=-4x³ switches from positive to negative, giving a local maximum. For k, k'(0)=0 and k''(0)=2>0, so the second-derivative test gives a strict local minimum at zero. The first-derivative test would agree.",
    checks: [
      ["What does f''(c)=0 mean in the second-derivative test?", ["The test is inconclusive", "There is no extremum", "There is an inflection"], 0, "Inspect nearby behavior instead."],
      ["A change of f' from negative to positive signals what?", ["A local minimum", "A local maximum", "No critical point"], 0, "The function falls, then rises."],
      ["What prerequisite is needed for the usual second-derivative extremum test?", ["f'(c)=0", "f(c)=0", "f''(c)=0"], 0, "The point must be stationary."],
    ],
  },
  {
    lesson: "math.m5.l5",
    title: "Optimization with constraints",
    premise: "Optimization begins with the quantity you want to maximize or minimize and the constraints that make choices feasible. Differentiating before defining those relationships solves the wrong problem efficiently.",
    idea: "Name variables and units, write the objective, use every independent constraint to reduce it to one variable, and determine the feasible interval. Differentiate the reduced objective and find interior critical points. Compare their objective values with feasible endpoints; if an endpoint is excluded, use a limit to understand what is approached. Then check that the answer has the requested units and is physically possible. When a constraint is an equality, using it to eliminate a variable also prevents treating dependent quantities as independent.",
    worked: "A rectangle has 20 meters of fencing for its perimeter. Let one side be x meters and the other 10-x, so 0≤x≤10. Its area is A(x)=x(10-x)=10x-x². The derivative 10-2x is zero at x=5; A''=-2<0, and endpoint areas are zero. The maximum area is 25 square meters, achieved by a 5-by-5 square.",
    interpretation: "The optimum is a configuration, not just the number x=5. Reporting area without dimensions or comparing feasibility would leave the modeling question unanswered.",
    trap: "Do not assume every stationary point is the global optimum. An algebraic solution outside the feasible interval is not a candidate, and a perimeter equation must count every fenced side.",
    practice: "A farmer has 60 meters of fencing for three sides of a rectangle against a straight wall. Find dimensions maximizing area, and state why the wall changes the constraint.",
    solution: "Let x be each side perpendicular to the wall and y the fenced side parallel to it. The fence condition is 2x+y=60, so y=60-2x and 0≤x≤30. Area A=x(60-2x), with A'=60-4x. At x=15, y=30 and A=450 square meters; A''=-4 and both endpoint areas are zero. The fourth side lies against the wall and consumes no fence.",
    checks: [
      ["What must be specified before differentiating an objective?", ["The constraint and feasible domain", "Only the units", "Only a graph"], 0, "Optimization is over allowed choices."],
      ["Why compare endpoints after finding interior critical points?", ["The absolute optimum may occur there", "Derivatives never exist there", "Endpoint values are always zero"], 0, "A closed feasible interval includes endpoints."],
      ["How much fence counts for a wall-backed rectangle?", ["Three exposed sides", "All four sides", "Only one side"], 0, "The wall supplies one boundary."],
    ],
  },
  {
    lesson: "math.m5.l6",
    title: "Related rates",
    premise: "Related-rates problems connect quantities that change together. Differentiate the relationship with respect to time before inserting a snapshot's measurements.",
    idea: "Draw or describe the geometry, assign time-dependent variables, and write one equation true throughout the motion. Apply the chain rule to both sides with respect to t; each varying variable contributes its own derivative, such as d(x²)/dt=2x·dx/dt. Only after differentiating should you substitute the stated moment. A measurement at one time is a value, not a constant function. Choose signs according to direction and carry units through every rate.",
    worked: "A circle's radius increases at 2 cm/s. Its area is A=πr², so dA/dt=2πr·dr/dt. When r=3 cm, dA/dt=12π square centimeters per second. Substituting r=3 before differentiating would falsely turn A into a constant and erase the change.",
    interpretation: "Area growth depends on current radius: the same radial speed sweeps more area when the circle is larger. The unit of dA/dt is area per time, not length per time.",
    trap: "Do not differentiate a time-varying x as though it were the independent variable in a static x derivative and omit dx/dt. Keep approaching distances negative and receding distances positive when the variable is defined as a distance.",
    practice: "A 10-meter ladder leans against a wall. Its foot moves away from the wall at 1 m/s. When the foot is 6 meters from the wall, how fast is the top moving?",
    solution: "With foot distance x and height y, x²+y²=100 at all times. Differentiate: 2x·dx/dt+2y·dy/dt=0. When x=6, y=8. Substitute dx/dt=1 to obtain 12+16·dy/dt=0, so dy/dt=-3/4 m/s. The negative sign means the top moves downward.",
    checks: [
      ["When should snapshot measurements be substituted?", ["After differentiating the time relation", "Before writing the relation", "Before applying the chain rule"], 0, "The quantities vary before and after the snapshot."],
      ["What is d(x²)/dt when x varies with time?", ["2x·dx/dt", "2x", "2·dx/dt"], 0, "Use the chain rule."],
      ["What does a negative dy/dt mean when y is height?", ["The height is falling", "Time is negative", "The ladder length changes"], 0, "Interpret the sign using the variable definition."],
    ],
  },
  {
    lesson: "math.m5.l7",
    title: "Linearization and differentials",
    premise: "Near a differentiable point, the tangent line is a useful local approximation. The derivative supplies the conversion rate from a small input change to an approximate output change.",
    idea: "At x=a, linearization is L(x)=f(a)+f'(a)(x-a). If x=a+Δx, the differential df=f'(a)Δx estimates the actual change Δf=f(a+Δx)-f(a). Differentiability means the error is small relative to |Δx| as Δx approaches zero; it does not mean the tangent line stays accurate far away. Curvature helps anticipate error: for a concave-down function, its tangent lies above the graph locally. Use a nearby anchor with easy values and state whether you report an approximation or an exact value.",
    worked: "Approximate sqrt(4.1) using f(x)=sqrt(x) at a=4. Since f(4)=2 and f'(4)=1/4, L(4.1)=2+(1/4)(0.1)=2.025. The true square root is slightly below 2.025 because sqrt(x) is concave down for x>0.",
    interpretation: "An input increase of 0.1 produces an estimated output increase of 0.025 at this anchor. The derivative carries output-units per input-unit, so multiplying by Δx yields output-units.",
    trap: "Do not use f'(x)·Δx without specifying the base point or claim a tangent approximation is exact. The approximation can deteriorate as |x-a| grows.",
    practice: "Use linearization at x=8 to estimate cubert(8.24). Give the approximation and explain why 8 is a sensible anchor.",
    solution: "Let f(x)=x^(1/3). Then f(8)=2 and f'(x)=(1/3)x^(-2/3), so f'(8)=1/12. With Δx=0.24, L(8.24)=2+(1/12)(0.24)=2.02. Eight is a nearby perfect cube with an easy function and derivative value.",
    checks: [
      ["What is the tangent approximation at a?", ["f(a)+f'(a)(x-a)", "f'(a)+f(a)x", "f(x)+f'(x)"], 0, "Use the point and slope at a."],
      ["What does df=f'(a)Δx estimate?", ["The change in f", "The exact value of f everywhere", "The second derivative"], 0, "It is a local change approximation."],
      ["When is linearization generally most reliable?", ["Near its base point", "At arbitrarily large distances", "Only at zeros of f"], 0, "Differentiability is a local statement."],
    ],
  },
  {
    lesson: "math.m5.l8",
    title: "Graph sketching from derivatives",
    premise: "A useful graph sketch combines domain, intercepts, limits, monotonicity, and concavity. No single derivative sign chart tells the whole story.",
    idea: "First mark the domain and discontinuities, then evaluate convenient intercepts and end behavior. Find critical points from f' and build a sign chart for increasing and decreasing intervals. Find candidates from f'' and test for concavity changes. Plot key coordinates and asymptotes before connecting smooth pieces consistently with all the evidence. For a rational function, excluded denominator zeros can split the graph into separate branches; never connect across an asymptote. A sketch is a consistency argument, not a claim that finitely many sample points determine a curve.",
    worked: "For f(x)=x³-3x, the domain is all real, roots are -sqrt(3), 0, and sqrt(3), and the ends go down-left and up-right. Since f'=3(x-1)(x+1), the graph rises on (-infinity,-1), falls on (-1,1), and rises on (1,infinity). The local maximum is (-1,2) and local minimum (1,-2). Since f''=6x, concavity switches at (0,0). These facts determine the familiar smooth S-shape with its turning points.",
    interpretation: "Each feature answers a different question: f' controls direction, f'' controls bending, and limits control behavior where the visible window ends.",
    trap: "Do not connect across a hole or asymptote. A critical value at which f'=0 need not be an extremum, and an f'' zero need not be an inflection.",
    practice: "Sketch y=x⁴-2x² from derivative evidence: give intercepts, stationary points and their types, concavity intervals, and end behavior.",
    solution: "The zeros are x=0 and x=±sqrt(2). f'=4x(x²-1), so the function decreases on (-infinity,-1), increases on (-1,0), decreases on (0,1), and increases on (1,infinity). Local minima occur at (±1,-1), and a local maximum at (0,0). f''=12x²-4 changes sign at x=±1/sqrt(3), yielding inflections with y=-5/9. It is concave down between those points and up outside. Both ends rise to positive infinity; the graph is symmetric about the y-axis.",
    checks: [
      ["Which derivative primarily controls increasing intervals?", ["The first derivative", "The second derivative", "The function's sign"], 0, "The sign of f' controls direction."],
      ["What should be checked before connecting graph branches?", ["Domain gaps and asymptotes", "Only the y-intercept", "Only the second derivative"], 0, "A missing input cannot support a continuous bridge."],
      ["What does f'' reveal in a sketch?", ["Concavity intervals", "The exact zeros of f", "The function's domain by itself"], 0, "It describes the change in slope."],
    ],
  },
  {
    lesson: "math.m5.l9",
    title: "Modeling and mixed application problems",
    premise: "Real applications combine several ideas: create a model, state its domain and units, use derivatives appropriately, and check that the mathematical answer resolves the original question.",
    idea: "A complete solution has four layers. Translate the setting into quantities and constraints, solve the resulting mathematical problem, test candidates and boundaries, then interpret in the setting. For a changing quantity, distinguish an instantaneous rate from a total amount. For an optimization problem, a stationary point is only a candidate. For approximation, specify an anchor and expected error direction. If the model ignores an important effect, state that limitation rather than reporting spurious precision. Use dimensional checks to catch errors that symbolic algebra might miss.",
    worked: "A product has price p(q)=50-q dollars per unit for 0≤q≤50 units. Revenue is R(q)=q(50-q)=50q-q² dollars. Its marginal revenue is R'(q)=50-2q dollars per additional unit; it is zero at q=25. Since R''=-2 and R(0)=R(50)=0, revenue is maximized at q=25 with R=$625. At q=10, marginal revenue is $30 per extra unit, while total revenue is $400; confusing those quantities would misstate the business result.",
    interpretation: "The derivative is a local sensitivity. It does not by itself include production costs, discrete unit sizes, or uncertainty in the demand model.",
    trap: "Do not label an optimum without comparing feasible alternatives, and do not report a derivative in the same units as a total quantity. Check whether your independent variable is continuous or counts whole objects.",
    practice: "Suppose a rectangular garden uses 40 meters of fence and both sides must be at least 4 meters. Find its greatest possible area. Then estimate the area change if the width increases by 0.1 meter from width 6 while perimeter stays fixed.",
    solution: "Let width w and length 20-w, with 4≤w≤16. Area A=20w-w², so A'=20-2w and A''=-2. The feasible stationary point w=10 gives length 10 and area 100 square meters; both endpoints give 64 square meters. At w=6, A'=8 square meters per meter, so increasing width by 0.1 meter changes area by approximately 0.8 square meters. The exact change is A(6.1)-A(6)=0.79 square meters, showing the local approximation error.",
    checks: [
      ["What units does marginal revenue R'(q) have if q counts units?", ["Dollars per additional unit", "Dollars squared", "Units per dollar"], 0, "Differentiate dollars with respect to units."],
      ["What follows after solving R'(q)=0 in a bounded model?", ["Compare feasible candidates and endpoints", "Declare a maximum immediately", "Discard the domain"], 0, "Stationarity alone is not a global conclusion."],
      ["What does a linearized change represent?", ["A local estimate, with possible error", "An exact global identity", "A new constraint"], 0, "State the approximation's scope."],
    ],
  },
];
