import type { MathLecture } from "./lectures";

/** Geometry on smooth manifolds, through curvature and applied directions. */
export const MATH_DIFFERENTIAL_GEOMETRY: MathLecture[] = [
  {
    lesson: "math.m30.l1", title: "Riemannian metrics",
    premise: "A Riemannian metric gives each tangent space an inner product that varies smoothly across the manifold.",
    idea: "At p, g_p(v,w) is symmetric, bilinear, and positive definite; in coordinates it is represented by a positive-definite matrix g_ij(p). Curve length is ∫sqrt(g_{γ(t)}(γ',γ'))dt, and distance is the infimum of lengths of connecting curves. The metric converts a differential df into a gradient through g(grad f,v)=df(v). A coordinate formula may vary while the geometric length remains invariant. On a sphere, the metric induced from Euclidean R³ restricts the dot product to tangent planes. A metric is extra structure: smooth manifolds need not come with one specified, even though paracompact smooth manifolds admit metrics.",
    worked: "In polar coordinates on the punctured plane, ds²=dr²+r²dθ². A circle r=R has tangent velocity with dr=0, so its length from θ=0 to 2π is ∫R dθ=2πR. The coefficient r² is the metric's angular entry, not a new physical radius.",
    interpretation: "The metric tells us what a unit step, angle, and steepest direction mean at each point.",
    trap: "Do not take a Euclidean coordinate norm in a curvilinear chart as the manifold's length formula without using g_ij.",
    practice: "Under metric ds²=dx²+4dy² on R², find the length of γ(t)=(t,t), 0≤t≤1.",
    solution: "Velocity is (1,1), whose metric squared norm is 1+4=5. The speed is sqrt(5) for the entire parameter interval, so length is ∫₀¹sqrt(5)dt=sqrt(5). The ordinary Euclidean length sqrt(2) would use a different metric.",
    checks: [["What property must g_p have on nonzero tangent vectors?", ["Positive squared length", "Negative determinant", "Zero length always"], 0, "Positive definiteness is required."], ["What defines curve length?", ["Integrate metric speed", "Count chart points", "Only subtract endpoints"], 0, "Length depends on the tangent norm."], ["Does a smooth manifold specify a unique metric by itself?", ["No", "Yes", "Only spheres"], 0, "A metric is additional structure."]],
  },
  {
    lesson: "math.m30.l2", title: "Connections and covariant derivatives",
    premise: "Vectors at different manifold points live in different tangent spaces, so differentiating a vector field requires a rule for comparison.",
    idea: "A connection ∇ assigns ∇_X Y, the covariant derivative of vector field Y along X, with linearity and the product rule ∇_X(fY)=X(f)Y+f∇_XY. In coordinates, ∇_{∂i}∂j=Γ^k_{ij}∂k. The Levi-Civita connection is uniquely torsion-free and metric-compatible for a Riemannian metric. Christoffel symbols depend on coordinates and can be nonzero even in flat Euclidean space in polar coordinates; curvature is a tensor and distinguishes genuine geometric bending. Parallel transport along a curve solves ∇_{γ'}V=0, preserving metric length under Levi-Civita transport.",
    worked: "In flat R² with Cartesian coordinates, all Levi-Civita Christoffel symbols vanish, so covariant differentiation of a vector field follows component derivatives. In polar coordinates, Γ^r_{θθ}=-r and Γ^θ_{rθ}=1/r are nonzero, reflecting coordinate basis changes, not nonzero curvature of the plane.",
    interpretation: "A connection describes how directions evolve; coordinate coefficients are bookkeeping, not standalone geometry.",
    trap: "Do not infer nonzero curvature solely because a chart has nonzero Christoffel symbols.",
    practice: "For Euclidean R² in Cartesian coordinates, compute ∇_{∂x}(x²∂x+y∂y).",
    solution: "The connection coefficients vanish in Cartesian coordinates, so differentiate components in x: ∂x(x²)=2x and ∂x(y)=0. Therefore the result is 2x∂x.",
    checks: [["What is a covariant derivative for?", ["Comparing vector fields along directions", "Only integrating scalars", "Choosing a topology"], 0, "Tangent spaces differ across points."], ["Are Christoffel symbols coordinate invariant individually?", ["No", "Yes", "Only on spheres"], 0, "They can be nonzero on a flat plane."], ["What characterizes Levi-Civita connection?", ["Metric compatible and torsion-free", "Arbitrary coefficients", "Zero in every chart"], 0, "Those conditions determine it uniquely."]],
  },
  {
    lesson: "math.m30.l3", title: "Geodesics and exponential maps",
    premise: "Geodesics are curves whose velocity transports parallel to itself, generalizing straight lines locally.",
    idea: "A geodesic satisfies ∇_{γ'}γ'=0, or ẍ^k+Γ^k_{ij}ẋ^i ẋ^j=0 in coordinates. Given p and tangent v, the exponential map exp_p(v) is the point reached at parameter time one by the geodesic with γ(0)=p, γ'(0)=v, where defined. On a complete Riemannian manifold it is defined for all tangent vectors; local definition holds near zero more generally. Geodesics minimize distance only locally before cut points, not indefinitely. On a sphere, great circles are geodesics, but the longer great-circle arc between two points is not globally shortest.",
    worked: "On a unit sphere, start at north pole with unit tangent along the x direction. The geodesic is γ(t)=(sin t,0,cos t), moving along a great circle. At t=π it reaches south pole. Continuing beyond π follows a geodesic but ceases to be a shortest route back toward nearby points.",
    interpretation: "Geodesic describes a differential equation; shortest-path claims add global geometry and can fail.",
    trap: "Do not conflate every geodesic segment with a globally minimizing path.",
    practice: "In Euclidean R² with its standard metric, find exp_p(v) and the geodesic from p=(1,2), v=(3,-1).",
    solution: "Christoffel symbols vanish, so γ''=0 and γ(t)=p+tv=(1+3t,2-t). At t=1, exp_p(v)=p+v=(4,1). Straight lines minimize between their endpoints in Euclidean space.",
    checks: [["What equation defines an affine-parameter geodesic?", ["∇_{γ'}γ'=0", "γ'=0 always", "Curvature=0 everywhere"], 0, "Velocity is parallel along the curve."], ["Are geodesics globally minimizing forever?", ["No", "Yes", "Only on spheres"], 0, "Cut loci can intervene."], ["What is exp_p(v) in Euclidean space?", ["p+v", "p-v", "v alone"], 0, "The geodesic is a straight line."]],
  },
  {
    lesson: "math.m30.l4", title: "Curvature tensors",
    premise: "Curvature measures how parallel transport and second covariant derivatives fail to behave like flat Euclidean geometry.",
    idea: "For a connection, R(X,Y)Z=∇_X∇_Y Z-∇_Y∇_X Z-∇_[X,Y]Z under one sign convention. Sectional curvature of a two-plane spanned by independent u,v is g(R(u,v)v,u)/(||u||²||v||²-g(u,v)²), with sign tied to the R convention. The unit sphere has constant positive sectional curvature; Euclidean space has zero. Ricci curvature contracts R and summarizes directional volume distortion, while scalar curvature contracts Ricci. Curvature is intrinsic to the metric, unlike how a surface happens to sit in a particular ambient space. Coordinate formulas require second derivatives of the metric and must respect index and sign conventions.",
    worked: "A cylinder is curved in R³ as an embedded surface, but intrinsically its standard metric can be unrolled locally to a flat plane. Its Gaussian curvature is zero away from the seam because local lengths and angles match the plane. A sphere cannot be flattened this way without distortion; its Gaussian curvature is positive.",
    interpretation: "Extrinsic bending and intrinsic curvature are different questions.",
    trap: "Do not label a cylinder intrinsically curved merely because its picture bends in three-space.",
    practice: "Compare the intrinsic Gaussian curvature of a Euclidean plane, a standard cylinder away from its seam, and a unit sphere.",
    solution: "The plane has curvature zero. The cylinder has zero intrinsic Gaussian curvature locally because it is isometric to a planar strip. The unit sphere has constant Gaussian curvature +1 under the usual radius-one metric.",
    checks: [["Is cylinder Gaussian curvature nonzero because it looks bent?", ["No", "Yes", "Only at the center"], 0, "Intrinsic geometry can be flat."], ["What is unit-sphere sectional curvature?", ["Positive one", "Zero", "Negative one"], 0, "For its standard metric it is constant +1."], ["Are curvature tensor sign conventions universal?", ["No", "Yes", "Only in dimension two"], 0, "State the definition used."]],
  },
  {
    lesson: "math.m30.l5", title: "Submanifolds and embeddings",
    premise: "A submanifold sits inside another manifold with locally controlled tangent directions and dimensions.",
    idea: "If F:R^n→R^k is smooth and c is a regular value, meaning DF has rank k at every point of F^{-1}(c), then the level set F^{-1}(c) is an (n-k)-dimensional embedded submanifold. Its tangent space is ker DF_p. An immersion has injective differential; an embedding is an immersion that is also a homeomorphism onto its image with the subspace topology. Immersions may self-intersect, so they need not be embeddings. A coordinate parametrization supplies tangent columns, while a regular implicit equation supplies normal rows. These descriptions agree when ranks are correct.",
    worked: "Take F(x,y,z)=x²+y²+z². On F^{-1}(1)=S², gradient 2(x,y,z) is nonzero, so 1 is a regular value. The sphere has dimension 3-1=2, and tangent vectors satisfy DF_p(v)=2p·v=0.",
    interpretation: "A rank calculation turns a pictured surface into a theorem about local dimension.",
    trap: "Do not use a level-set dimension formula at a critical point where the required derivative rank fails.",
    practice: "For F(x,y)=x²+y², is F^{-1}(0) a one-dimensional regular level set?",
    solution: "No. F^{-1}(0) contains only (0,0), where DF=(0,0) has rank zero rather than one. The regular-value theorem does not apply, and the actual set is a zero-dimensional point, not a circle.",
    checks: [["What is tangent space to a regular level set?", ["Kernel of DF_p", "Image of F", "All ambient vectors"], 0, "First-order changes remain in the level."], ["What rank gives an n-k dimensional level set?", ["Rank k", "Rank zero", "Any rank"], 0, "It is the regular-value condition."], ["Is every immersion an embedding?", ["No", "Yes", "Only in R²"], 0, "Self-intersection or topology can obstruct it."]],
  },
  {
    lesson: "math.m30.l6", title: "Optimization on manifolds",
    premise: "Constrained optimization can be treated as unconstrained movement along valid tangent directions of a manifold.",
    idea: "The Riemannian gradient grad_M f is the unique tangent vector satisfying g(grad_M f,v)=df(v) for all tangent v. For an embedded manifold with induced metric, project the ambient Euclidean gradient onto the tangent space. A retraction R_p(v) maps a tangent step back to the manifold and agrees with the exponential map to first order near zero; algorithms can use retractions when exact geodesics are expensive. Critical points have zero Riemannian gradient. Curvature, nonconvexity, step size, and choice of metric affect convergence. A tangent projection that omits the retraction can drift off the constraint set.",
    worked: "On unit sphere S^{n-1}, tangent space at x is vectors orthogonal to x. Project ambient gradient a onto tangent: grad_S f=a-(a·x)x for f(x)=a·x. At x=a/||a|| the tangent gradient vanishes, identifying a maximum; at x=-a/||a|| it also vanishes, identifying a minimum.",
    interpretation: "A zero tangent gradient detects constrained stationarity, which still needs classification.",
    trap: "Do not read a zero Riemannian gradient as proof of a minimum; maxima and saddles also satisfy it.",
    practice: "On unit circle, let f(x,y)=x. Compute the tangent gradient at p=(0,1).",
    solution: "Ambient gradient is a=(1,0). Since a·p=0, tangent projection is a-(a·p)p=(1,0). It points along the circle's tangent toward increasing x at the top point.",
    checks: [["Where does a manifold optimizer step initially live?", ["Tangent space", "Ambient normal space only", "Outside all coordinates"], 0, "The gradient is projected tangent."], ["What maps a tangent step back to the manifold?", ["Retraction or exponential map", "An arbitrary linear sum only", "A p-value"], 0, "The constraint must be restored."], ["Does zero tangent gradient prove a minimum?", ["No", "Yes", "Only on spheres"], 0, "It is a stationarity condition."]],
  },
  {
    lesson: "math.m30.l7", title: "Information geometry",
    premise: "A family of probability distributions can be viewed as a geometric space whose distances reflect statistical distinguishability.",
    idea: "For a smooth parametric family p(x|θ), the score is ∂_θ log p(x|θ). Under regularity allowing differentiation under the integral, its expectation is zero. Fisher information is I(θ)=E_θ[score scoreᵀ], a positive semidefinite metric tensor; it is positive definite when parameters are locally identifiable. For nearby parameters, KL(p_θ||p_{θ+dθ}) is approximately (1/2)dθᵀI(θ)dθ under smoothness. This local quadratic approximation is not a global metric identity because KL is asymmetric. Natural gradient uses I^{-1}∇_θ L where invertible, adjusting parameter steps for distributional rather than coordinate distance. Singular information requires regularization or a restricted identifiable subspace.",
    worked: "For X drawn from N(μ,σ²) with known σ, score in μ is (X-μ)/σ². Its expectation is zero and variance is σ²/σ⁴=1/σ², so Fisher information per observation is 1/σ². Smaller observation noise makes nearby means more distinguishable.",
    interpretation: "The geometry measures changes in distributions, not arbitrary numerical changes in parameter labels.",
    trap: "Do not replace KL by its local Fisher approximation for distant parameter values without an error argument.",
    practice: "For n independent N(μ,σ²) observations with known σ, what is Fisher information about μ?",
    solution: "Scores add across independent observations. Their means are zero and variances add, giving I_n(μ)=n/σ². This is n times the one-observation information under the regular normal model.",
    checks: [["What is Fisher information built from?", ["Expected score outer product", "Raw parameter magnitude", "Only sample size"], 0, "It quantifies local distinguishability."], ["Is KL a symmetric global distance?", ["No", "Yes", "Only for normal families"], 0, "Its local quadratic form is a separate statement."], ["What happens if Fisher information is singular?", ["A direct inverse is unavailable", "The model is always invalid", "All scores vanish"], 0, "Restrict or regularize as appropriate."]],
  },
  {
    lesson: "math.m30.l8", title: "Geometric methods research problems",
    premise: "A geometric research claim must be invariant under coordinate changes and tested on both simple and pathological examples.",
    idea: "Start with a precise object: manifold, metric, connection, objective, and class of maps. State a conjecture as quantified claim, not as a picture. Test it on Euclidean space, spheres, a flat cylinder, and spaces with cut loci or nontrivial topology. If an algorithm is proposed, specify its retraction, step rule, and whether convergence is to a local stationary point or a global optimum. Derive a coordinate-free statement when possible; if coordinates are used, verify transition behavior. For a computational experiment, report discretization, numerical tolerance, and the curvature range sampled. A counterexample is a result when it identifies the missing hypothesis.",
    worked: "Conjecture: every geodesic on a complete manifold minimizes distance for all time. Euclidean lines support it, but a great circle on the complete unit sphere ceases to minimize after passing an antipodal point. The sphere is a counterexample, showing completeness guarantees extension of geodesics, not global minimizing behavior.",
    interpretation: "A small counterexample can sharpen a theorem more than many supporting plots.",
    trap: "Do not generalize from flat-space simulations to all manifolds without addressing curvature and topology.",
    practice: "Repair the false conjecture 'every geodesic minimizes forever' into a defensible local statement.",
    solution: "For any point p in a smooth Riemannian manifold, sufficiently short geodesic segments lying in a normal neighborhood minimize length between their endpoints. This local claim needs a normal-neighborhood existence theorem; it does not claim minimization beyond cut points.",
    checks: [["Does geodesic completeness imply global shortest paths?", ["No", "Yes", "Only for compact spaces"], 0, "Great circles are counterexamples."], ["What should a coordinate formula survive?", ["Chart changes", "Only one chart", "A change of font"], 0, "Geometry is invariant."], ["Can a counterexample improve a conjecture?", ["Yes", "No", "Only if numerical"], 0, "It reveals a missing hypothesis."]],
  },
];
