import type { MathLecture } from "./lectures";

/** Change laws, solution families, and numerical limits of models. */
export const MATH_DIFFERENTIAL_EQUATIONS: MathLecture[] = [
  {
    lesson: "math.m15.l1", title: "Separable first-order equations",
    premise: "A separable differential equation lets the unknown state and time be integrated on opposite sides. Initial conditions select one trajectory from the solution family.",
    idea: "For y'=g(t)h(y), write dy/h(y)=g(t)dt only where h(y)≠0, then integrate and solve for y when possible. Constant equilibrium solutions where h(y)=0 must be checked separately because division removes them. Apply the initial condition and state the interval where the formula is valid. A logarithm introduces absolute values and possible branches; a blow-up time can limit the maximal interval even when the differential equation is smooth locally.",
    worked: "Solve y'=2ty with y(0)=3. On a nonzero branch, dy/y=2t dt, so ln|y|=t²+C and y=Ce^{t²}. The initial value gives C=3, hence y=3e^{t²} for all real t. The equilibrium y=0 is also a solution of the original equation but does not match this initial condition.",
    interpretation: "A positive initial state stays positive because the exponential factor is positive. The time-dependent rate 2t switches sign at zero.",
    trap: "Do not divide by y or h(y) and then declare there are no equilibrium solutions. Test the divided-out zeros in the original equation.",
    practice: "Solve y'=y² with y(0)=1 and identify the maximal interval containing zero.",
    solution: "For y≠0, dy/y²=dt gives -1/y=t+C. With y(0)=1, C=-1, so y=1/(1-t). It is defined on the maximal interval (-infinity,1) containing zero and blows up as t approaches 1 from below. The equilibrium y=0 exists but fails the initial condition.",
    checks: [["What can dividing by h(y) discard?", ["Equilibrium solutions", "The initial time", "All integration constants"], 0, "Zeros of h may solve the original equation."], ["What selects one member of an ODE solution family?", ["An initial condition", "The variable name", "A graph color"], 0, "The initial state determines the integration constant."], ["Why state an interval of validity?", ["A formula can blow up or cross a forbidden branch", "All ODEs last forever", "It changes the derivative rule"], 0, "Solutions need not extend globally."]],
  },
  {
    lesson: "math.m15.l2", title: "Linear first-order equations",
    premise: "A first-order linear ODE has a standard integrating factor that turns its left side into one product derivative.",
    idea: "Write y'+p(t)y=q(t) on an interval where p and q are continuous. The integrating factor μ(t)=exp(∫p(t)dt) is nonzero and satisfies μ'=pμ. Multiplying gives (μy)'=μq, so y=μ^{-1}(∫μq dt+C). Choosing a different constant in the antiderivative defining μ only rescales μ and does not change the solution family. The homogeneous response solves y'+py=0; a particular solution supplies the forced response. Check the final formula by substitution and specify the interval where coefficients are defined.",
    worked: "Solve y'+2y=4 with y(0)=1. The factor is μ=e^{2t}. Then (e^{2t}y)'=4e^{2t}, so e^{2t}y=2e^{2t}+C and y=2+Ce^{-2t}. The initial value gives C=-1, hence y=2-e^{-2t}.",
    interpretation: "The transient term decays while the constant forcing sets the long-run equilibrium at 2.",
    trap: "The integrating factor multiplies both sides of the equation. Multiplying only the y terms invalidates the product derivative.",
    practice: "Solve y'+y=t with y(0)=0.",
    solution: "Use μ=e^t. Then (e^ty)'=te^t, whose antiderivative is e^t(t-1)+C. Thus y=t-1+Ce^{-t}. The initial condition 0=-1+C gives C=1, so y=t-1+e^{-t}. Differentiate and substitute to check y'+y=t.",
    checks: [["What does μ=e^{∫p} accomplish?", ["It creates the derivative (μy)'", "It removes q", "It makes y constant"], 0, "Because μ'=pμ."], ["What is the homogeneous response for y'+2y=4?", ["Ce^{-2t}", "2", "4t"], 0, "Set the forcing to zero."], ["Must μ multiply q as well?", ["Yes", "No", "Only if q is constant"], 0, "Multiply the entire equation."]],
  },
  {
    lesson: "math.m15.l3", title: "Second-order constant-coefficient equations",
    premise: "A constant-coefficient second-order ODE reduces its homogeneous solutions to roots of a characteristic polynomial.",
    idea: "For ay''+by'+cy=0 with a≠0, try y=e^{rt}, giving ar²+br+c=0. Distinct real roots r₁,r₂ yield C₁e^{r₁t}+C₂e^{r₂t}; a repeated root r gives (C₁+C₂t)e^{rt}; complex roots α±iβ give e^{αt}(C₁cos βt+C₂sin βt). Two independent initial conditions usually determine the two constants. Damping and oscillation arise from the signs of the root parts, but the equation's physical interpretation requires units and modeling assumptions.",
    worked: "Solve y''-3y'+2y=0 with y(0)=1 and y'(0)=0. The characteristic factors (r-1)(r-2), so y=C₁e^t+C₂e^{2t}. Conditions C₁+C₂=1 and C₁+2C₂=0 give C₁=2,C₂=-1. Therefore y=2e^t-e^{2t}.",
    interpretation: "Both modes grow exponentially; the initial velocity makes them cancel at time zero but not at later times.",
    trap: "A repeated root does not supply two independent copies of e^{rt}; multiply one by t to obtain a second independent solution.",
    practice: "Find the real general solution of y''+4y=0 and impose y(0)=0,y'(0)=2.",
    solution: "Roots are ±2i, so y=C₁cos(2t)+C₂sin(2t). Initial position gives C₁=0. Derivative y'=2C₂cos(2t) gives 2C₂=2, hence y=sin(2t).",
    checks: [["What equation gives characteristic roots?", ["ar²+br+c=0", "a+b+c=0", "y(0)=0"], 0, "Insert e^{rt} into the ODE."], ["What accompanies a repeated-root e^{rt}?", ["t e^{rt}", "Another identical e^{rt}", "e^{-rt} always"], 0, "The second solution must be independent."], ["What do roots ±2i produce as real solutions?", ["cos(2t) and sin(2t)", "e^{2t} only", "Constant functions"], 0, "Euler's identity connects complex exponentials to oscillations."]],
  },
  {
    lesson: "math.m15.l4", title: "Forcing and variation of parameters",
    premise: "A forced ODE combines its natural homogeneous behavior with a response to the input. Variation of parameters constructs that response when guessing fails.",
    idea: "For y''+p(t)y'+q(t)y=g(t), first find independent homogeneous solutions y₁,y₂ on an interval. Their Wronskian W=y₁y₂'-y₁'y₂ must be nonzero there. Variation of parameters seeks y_p=u₁y₁+u₂y₂ with u₁'=-y₂g/W and u₂'=y₁g/W for this normalized equation. Integrate these derivatives, then add homogeneous terms and apply initial conditions. Undetermined coefficients can be quicker for constant coefficients with polynomial, exponential, or sinusoidal forcing, but resonance requires multiplying a trial by enough powers of t. Variation of parameters is more general; it still depends on a known fundamental homogeneous pair.",
    worked: "For y''+y=1, homogeneous solutions are cos t and sin t. Here W=1, so u₁'=-sin t and u₂'=cos t. Choose u₁=cos t and u₂=sin t; then y_p=cos²t+sin²t=1. Thus y=C₁cos t+C₂sin t+1. Substituting y_p=1 directly also verifies the forced response.",
    interpretation: "The constants inside u₁,u₂ only add homogeneous solutions, so they can be chosen conveniently.",
    trap: "Do not use the displayed u-derivative formulas before normalizing the coefficient of y'' to one, and check that W stays nonzero.",
    practice: "Find the general solution of y''+y=sin t by a resonant trial, then verify it.",
    solution: "Because sin t solves the homogeneous equation, try y_p=A t cos t. Its second derivative plus itself is -2A sin t. Set -2A=1, so A=-1/2. The general solution is C₁cos t+C₂sin t-(t/2)cos t. Direct differentiation confirms the forcing sin t.",
    checks: [["What does a nonzero Wronskian establish locally?", ["Independent homogeneous solutions", "Zero forcing", "Constant coefficients"], 0, "It makes the fundamental solution matrix invertible."], ["What adjustment handles resonance in a trial solution?", ["Multiply by a suitable power of t", "Drop the forcing", "Use the same homogeneous term unchanged"], 0, "A trial in the homogeneous span cannot produce the forcing."], ["What must be normalized before standard variation formulas?", ["Coefficient of y''", "Initial condition", "Wronskian to one"], 0, "The formulas assume leading coefficient one."]],
  },
  {
    lesson: "math.m15.l5", title: "Systems of ODEs and matrix exponentials",
    premise: "A linear system x'=Ax evolves every initial vector under a single matrix-valued exponential.",
    idea: "Define e^{At}=Σ_{k=0}∞(At)^k/k!. It satisfies d(e^{At})/dt=Ae^{At} and e^{A0}=I, so x(t)=e^{At}x₀ solves x'=Ax. If A=PDP^{-1}, then e^{At}=Pe^{Dt}P^{-1}, with e^{Dt} obtained by exponentiating diagonal entries. For a forced system x'=Ax+f(t), variation of constants gives x(t)=e^{At}x₀+∫₀ᵗe^{A(t-s)}f(s)ds. Matrix order matters when matrices vary in time; simply integrating A(t) inside one exponential is not generally valid when A(t) at different times fails to commute.",
    worked: "Let A=diag(-1,2) and x(0)=(3,4). Then e^{At}=diag(e^{-t},e^{2t}), giving x(t)=(3e^{-t},4e^{2t}). Differentiate each component to see x₁'=-x₁ and x₂'=2x₂. One mode decays while the other grows.",
    interpretation: "The eigen-directions act as independent modes in this diagonal example; an initial state containing a growing-mode component eventually follows that mode.",
    trap: "Do not exponentiate each entry of an arbitrary matrix. The matrix exponential is defined by a power series, not entrywise exponentiation.",
    practice: "For A=[[0,-1],[1,0]], solve x'=Ax with x(0)=(1,0).",
    solution: "A rotates vectors by a quarter turn and A²=-I. Grouping even and odd power-series terms gives e^{At}=I cos t+A sin t. Applying it to (1,0) yields x(t)=(cos t,sin t). Its derivative (-sin t,cos t) equals Ax(t).",
    checks: [["What solves x'=Ax with x(0)=x₀?", ["e^{At}x₀", "Entrywise e^A times t", "A^{-1}x₀ always"], 0, "The matrix exponential is the fundamental solution."], ["How is e^{At} defined generally?", ["A convergent matrix power series", "Entrywise exponentiation", "A determinant"], 0, "The power series respects matrix multiplication."], ["Can a diagonal system have both growing and decaying modes?", ["Yes", "No", "Only if complex"], 0, "Eigenvalue signs control each mode."]],
  },
  {
    lesson: "math.m15.l6", title: "Phase portraits and stability",
    premise: "A phase portrait shows how nearby states move, not merely a formula for one trajectory. Stability asks what small perturbations do over time.",
    idea: "For an autonomous system x'=F(x), an equilibrium xₑ satisfies F(xₑ)=0. Linearize near it: δ'=J_F(xₑ)δ plus higher-order terms. If all Jacobian eigenvalues have negative real part, the equilibrium is locally asymptotically stable; if any eigenvalue has positive real part, it is unstable. Zero real parts make the linearization test inconclusive in general. In one dimension, sign arrows on either side show whether trajectories approach or flee. A phase portrait describes state-space motion, not a time series plot. Nonlinear behavior far from equilibrium may differ from the local linear picture.",
    worked: "For x'=x(1-x), equilibria are 0 and 1. On 0<x<1, x'>0, so states move right; for x>1, x'<0, so they move left. Just below zero, x'<0 and states move further left. Thus 1 attracts nearby states while 0 repels them. The derivative F'(x)=1-2x is +1 at 0 and -1 at 1, matching the sign-arrow analysis.",
    interpretation: "The logistic model has a locally stable capacity level 1, but that conclusion refers to the model's state interval and assumptions.",
    trap: "A Jacobian eigenvalue with zero real part does not by itself prove stability. Examine nonlinear terms or another method.",
    practice: "Classify the equilibrium x=0 for x'=-x³ using sign arrows and compare with linearization.",
    solution: "For x>0, -x³<0 points left toward zero; for x<0, -x³>0 points right. Thus zero is asymptotically stable. But F'(0)=0, so the linearized equation δ'=0 is inconclusive; the cubic term decides behavior.",
    checks: [["What defines an equilibrium?", ["F(x*)=0", "F'(x*)=0 always", "x*=0 only"], 0, "The state stops changing there."], ["What does a positive-real-part eigenvalue imply locally?", ["Instability", "Asymptotic stability", "No conclusion ever"], 0, "A perturbation grows in that mode."], ["What if linearized eigenvalues have zero real part?", ["The simple test is inconclusive", "Always stable", "Always unstable"], 0, "Nonlinear terms can decide."]],
  },
  {
    lesson: "math.m15.l7", title: "Numerical Euler and Runge–Kutta methods",
    premise: "Most ODEs cannot be solved in elementary form. Numerical methods approximate the trajectory in controlled time steps, with errors that depend on method and step size.",
    idea: "For y'=f(t,y), forward Euler uses y_{n+1}=y_n+h f(t_n,y_n). Its local truncation error is typically O(h²) and global error O(h) over a fixed interval under standard smoothness and stability assumptions. Classical RK4 evaluates four staged slopes and combines them with weights 1,2,2,1 divided by 6; its global error is O(h⁴) for smooth problems under suitable conditions. Smaller steps improve truncation accuracy but increase work and can expose roundoff. Stiff equations may force tiny explicit steps for stability even when the desired accuracy is modest; implicit methods can help.",
    worked: "For y'=y, y(0)=1, one Euler step of h=0.1 gives y₁=1+0.1·1=1.1. The exact value e^{0.1}≈1.10517, so the step undershoots by about 0.00517. Two Euler steps of 0.05 give (1.05)²=1.1025, closer to the exact endpoint.",
    interpretation: "Halving the step improves this example, but convergence claims need assumptions and should be checked across multiple step sizes.",
    trap: "Do not confuse local per-step error with accumulated global error, or assume a higher-order explicit method is stable for every stiff problem.",
    practice: "Use two Euler steps of size 0.1 for y'=2t, y(0)=0. Compare with the exact y=t² at t=0.2.",
    solution: "At t=0, slope 0 gives y₁=0. At t=0.1, slope 0.2 gives y₂=0+0.1(0.2)=0.02. Exact y(0.2)=0.04, so Euler underestimates by 0.02. The slope grows across each step, explaining the underestimate.",
    checks: [["What is a forward Euler update?", ["y_n+h f(t_n,y_n)", "y_n+f(t_n,y_n)/h", "The exact future state"], 0, "Use the slope at the current state."], ["What is Euler's typical global order?", ["First", "Fourth", "Zero"], 0, "Global error is generally proportional to h."], ["Can explicit methods struggle with stiffness?", ["Yes", "No", "Only with constant solutions"], 0, "Stability can dictate a very small step."]],
  },
  {
    lesson: "math.m15.l8", title: "Existence, uniqueness, and modeling assumptions",
    premise: "Before trusting an ODE prediction, ask whether a solution exists, whether the initial condition determines it uniquely, and whether the model's assumptions fit the situation.",
    idea: "For y'=f(t,y) with initial data y(t₀)=y₀, continuity of f near the point guarantees a local solution under standard existence theorems. A local Lipschitz condition in y is a common sufficient condition for uniqueness; continuous differentiability in y locally is sufficient. These local results do not guarantee a solution for all time. Physical models require unit consistency, appropriate state constraints, data for parameters, and validation against observations. Fitting parameters to all observed data and then evaluating on the same data can overstate predictive power; separate estimation from validation.",
    worked: "Consider y'=2sqrt(|y|) with y(0)=0. Both y(t)=0 for all t and a solution that waits until some a≥0 then follows y(t)=(t-a)² for t≥a satisfy the equation on t≥0. The derivative with respect to y is not locally bounded at zero, and uniqueness fails there. By contrast, y'=y with y(0)=0 has the unique solution y=0 locally and globally.",
    interpretation: "An initial value alone does not always determine one future. Nonuniqueness is a mathematical property of the stated change law, not a numerical solver's mistake.",
    trap: "Do not invert the theorem: failure of a sufficient Lipschitz condition does not automatically mean nonuniqueness. Construct or analyze solutions directly.",
    practice: "Explain why y'=y² with y(0)=1 is locally unique yet fails to exist as a finite solution for all future times.",
    solution: "The right side y² is smooth in y, hence locally Lipschitz and locally unique. Separation gives y=1/(1-t), which diverges at t=1. Thus local existence and uniqueness do not imply global finite existence.",
    checks: [["What is a common sufficient condition for local uniqueness?", ["Local Lipschitz in y", "Continuity of f alone", "A positive initial value"], 0, "It controls how nearby states separate."], ["Does local uniqueness imply a global solution?", ["No", "Yes", "Only for scalar equations"], 0, "A solution may blow up later."], ["Does failure of a sufficient hypothesis prove nonuniqueness?", ["No", "Yes", "Only if f is continuous"], 0, "A sufficient condition is not necessary in every case."]],
  },
];
