import type { MathLecture } from "./lectures";

/** First graduate functional-analysis sequence. */
export const MATH_FUNCTIONAL_ANALYSIS: MathLecture[] = [
  {
    lesson: "math.m28.l1", title: "Normed and Banach spaces",
    premise: "An infinite-dimensional vector space needs a notion of size and convergence before calculus or optimization can work on it.",
    idea: "A norm satisfies positivity, absolute homogeneity, and the triangle inequality. A normed space is Banach when every Cauchy sequence converges in that space. Finite-dimensional normed spaces are complete and all their norms are equivalent; infinite-dimensional spaces can be incomplete or have inequivalent norms. The continuous functions C([0,1]) are Banach under the supremum norm because uniform limits of continuous functions remain continuous. Smooth functions under that same norm are not complete: smooth approximants may converge uniformly to a nonsmooth continuous limit. Completeness matters when iterative algorithms produce only a Cauchy sequence, not an explicit point.",
    worked: "The polynomials p_n(x)=Σ_{k=0}^n x^k/2^k converge uniformly on [0,1] to 1/(1-x/2), so their limit stays continuous. By contrast, smooth approximations sqrt((x-.5)²+1/n) converge uniformly to |x-.5|, which is not differentiable at .5; smooth functions are not closed in the sup norm.",
    interpretation: "A convergence theorem is only useful if its limit remains in the function space being studied.",
    trap: "Do not assume a Cauchy sequence converges in every normed space; completeness is an extra property.",
    practice: "Explain why the sequence f_n(x)=sqrt((x-.5)²+1/n) disproves completeness of differentiable functions on [0,1] under the sup norm.",
    solution: "Each f_n is differentiable and the sequence converges uniformly to |x-.5| because 0≤sqrt(a²+1/n)-|a|≤1/sqrt(n). Thus it is Cauchy in the sup norm, but its limit is not differentiable at .5 and leaves the space.",
    checks: [["What makes a normed space Banach?", ["Every Cauchy sequence converges within it", "Every element is bounded pointwise", "It is finite only"], 0, "Completeness is the defining property."], ["Are all finite-dimensional norms equivalent?", ["Yes", "No", "Only Euclidean norms"], 0, "They generate the same convergence."], ["Does uniform convergence preserve differentiability?", ["Not in general", "Always", "Only for polynomials"], 0, "Derivative control needs stronger hypotheses."]],
  },
  {
    lesson: "math.m28.l2", title: "Hilbert spaces and projection",
    premise: "A Hilbert space is a complete inner-product space, so geometry such as orthogonality and projection survives in infinite dimensions.",
    idea: "The inner product induces ||x||=sqrt(⟨x,x⟩). For a closed linear subspace M of a Hilbert space H, every x has a unique nearest point P_Mx in M, characterized by x-P_Mx orthogonal to M. Closedness matters: a dense proper subspace may have distance zero to x but no nearest point inside it. In L², functions equal almost everywhere represent the same vector. An orthonormal basis permits Fourier coefficients ⟨x,e_n⟩ and Parseval's identity when the basis is complete. Infinite sums converge in Hilbert norm, not necessarily pointwise everywhere.",
    worked: "In R², project x=(3,4) onto the line spanned by e=(1,1)/sqrt(2). The coefficient is ⟨x,e⟩=7/sqrt(2), so the projection is (7/2,7/2). The residual (-.5,.5) is perpendicular to (1,1), verifying the minimizing condition.",
    interpretation: "Least squares and Fourier approximation are both orthogonal projection problems.",
    trap: "Do not infer pointwise convergence from L² norm convergence without extra assumptions.",
    practice: "Project (2,1) onto the x-axis in R² and verify the residual is orthogonal.",
    solution: "The nearest vector is (2,0); the residual is (0,1). Its inner product with every x-axis vector (a,0) is zero, so the characterization holds. The squared distance is 1.",
    checks: [["What condition characterizes an orthogonal projection residual?", ["It is perpendicular to the subspace", "It is parallel to every vector", "It has zero coordinates always"], 0, "This proves nearest-point optimality."], ["Must the projected subspace be closed for the general theorem?", ["Yes", "No", "Only finite dimensional"], 0, "Otherwise a minimizer may be absent."], ["Does L² convergence automatically imply pointwise convergence?", ["No", "Yes", "Only for bounded functions"], 0, "The modes of convergence differ."]],
  },
  {
    lesson: "math.m28.l3", title: "Bounded linear operators",
    premise: "A linear map between normed spaces is continuous exactly when it has a finite operator norm.",
    idea: "For linear T:X→Y, boundedness means ||Tx||≤C||x|| for all x; the least C is ||T||=sup_{||x||≤1}||Tx||. Linearity makes continuity at zero equivalent to continuity everywhere and boundedness. In finite dimensions every linear map is bounded, but infinite-dimensional differentiation on C¹([0,1]) with the sup norm is unbounded: functions can have tiny height and large derivative. Integration T f(x)=∫₀ˣ f(t)dt on C([0,1]) with the sup norm is bounded with ||T||≤1. The space B(X,Y) of bounded operators is itself Banach when Y is Banach.",
    worked: "Let f_n(x)=sin(nx)/n on [0,1]. Its sup norm is at most 1/n, tending to zero, while f_n'(x)=cos(nx) has sup norm 1. Thus derivative output does not tend to zero with the input in sup norm, proving differentiation is not continuous in that norm.",
    interpretation: "An operator's domain and norm are part of its definition; the same formula can be bounded under a stronger norm.",
    trap: "Do not describe a map as bounded without naming its input and output norms.",
    practice: "Bound the operator norm of T f(x)=∫₀ˣf(t)dt on C([0,1]) under sup norm, then show the bound is sharp.",
    solution: "For each x, |Tf(x)|≤x||f||∞≤||f||∞, so ||T||≤1. Taking f≡1 gives Tf(x)=x with sup norm 1 and input norm 1, so ||T||=1.",
    checks: [["When is a linear map continuous?", ["When it is bounded in the specified norms", "Only when injective", "Only when finite-dimensional"], 0, "Continuity at zero and boundedness agree."], ["Can differentiation be unbounded under sup norm?", ["Yes", "No", "Only on constants"], 0, "High-frequency functions show it."], ["What is an operator norm?", ["Supremum of output norm over input unit ball", "Determinant", "Number of coordinates"], 0, "It is the best Lipschitz constant."]],
  },
  {
    lesson: "math.m28.l4", title: "Hahn–Banach theorem",
    premise: "Hahn–Banach extends bounded linear functionals without increasing their norm, making dual-space separation possible.",
    idea: "A standard normed-space form says a bounded linear functional f on a subspace M⊆X extends to F on all X with ||F||=||f||. More general real versions use domination by a sublinear functional; complex versions need the appropriate extension argument. A consequence: every nonzero real vector admits a norm-one functional attaining its norm. Thus the dual separates points and can recover the norm. The theorem is existential; it need not give a constructive formula.",
    worked: "In R² with Euclidean norm, define f(t,0)=t on the x-axis. It has norm 1. The extension F(x,y)=x has norm 1, so it preserves both its values on the line and its bound. Other extensions F(x,y)=x+cy have norm sqrt(1+c²)>1 unless c=0.",
    interpretation: "The theorem guarantees enough linear measurements to distinguish vectors and support separation results.",
    trap: "Do not infer that the extension is unique; the theorem guarantees existence and norm preservation, not uniqueness.",
    practice: "On span{(1,0)} in R² define f(t,0)=2t. Give a norm-preserving extension for Euclidean norm and its norm.",
    solution: "Set F(x,y)=2x. On the x-axis it equals f, and its operator norm is 2 because |2x|≤2sqrt(x²+y²), with equality at (1,0). Thus it extends with no norm increase.",
    checks: [["What does Hahn–Banach preserve in its normed-space form?", ["The functional's norm", "Its unique formula", "The dimension"], 0, "The extension has the same norm."], ["Is the extension necessarily unique?", ["No", "Yes", "Only over R"], 0, "Values off the subspace may vary."], ["What does the dual separate?", ["Distinct points", "Only orthogonal vectors", "Only matrices"], 0, "A suitable functional distinguishes them."]],
  },
  {
    lesson: "math.m28.l5", title: "Uniform boundedness and open mapping",
    premise: "Completeness turns pointwise or surjectivity information into global norm bounds and continuous inverses.",
    idea: "Uniform boundedness: if X is Banach and a family of bounded linear maps T_i:X→Y is pointwise bounded, meaning sup_i||T_i x||<∞ for every x, then sup_i||T_i||<∞. The completeness of X is essential in the standard theorem. Open mapping: a surjective bounded linear map between Banach spaces sends open sets to open sets. Consequently a bijective bounded linear map between Banach spaces has bounded inverse. Closed graph: for Banach X,Y, a linear map with closed graph is bounded. These theorems are related through the Baire category theorem; none says an arbitrary nonlinear bijection is well conditioned.",
    worked: "On the incomplete normed space c₀₀ of finitely supported sequences with sup norm, let T_n(x)=n x_n. Each fixed x has only finitely many nonzero coordinates, so sup_n|T_n(x)|<∞. Yet ||T_n||=n, unbounded. This shows why completeness cannot be omitted from uniform boundedness.",
    interpretation: "The theorem bridges quantifier order: pointwise bounds for each x become a common bound on operator norms.",
    trap: "Do not switch 'for each x, a bound exists' into 'one bound works for all x' without Banach hypotheses.",
    practice: "Explain why T_n(x)=n x_n on c₀₀ violates the conclusion but not the hypotheses of uniform boundedness as a Banach-space theorem.",
    solution: "Each T_n is bounded with norm n, and the family is pointwise bounded on finitely supported vectors. But c₀₀ under sup norm is incomplete: its completion is c₀. Therefore the Banach-domain hypothesis fails, so no contradiction occurs.",
    checks: [["What does uniform boundedness conclude?", ["A common operator-norm bound", "All operators are equal", "Every map is invertible"], 0, "It changes pointwise to uniform control."], ["What key property must the domain have?", ["Completeness as a Banach space", "Finite cardinality", "A determinant"], 0, "The c00 counterexample lacks it."], ["When does open mapping give a bounded inverse?", ["For a bijective bounded linear map between Banach spaces", "For any nonlinear injection", "For any map with a graph"], 0, "Surjectivity and Banach hypotheses matter."]],
  },
  {
    lesson: "math.m28.l6", title: "Compact operators",
    premise: "A compact operator sends bounded sets to relatively compact sets, behaving in some ways like a finite-dimensional map.",
    idea: "A bounded linear T:X→Y is compact if the image of the unit ball has compact closure, equivalently every bounded sequence has a subsequence whose images converge. Finite-rank operators are compact; norm limits of compact operators are compact. The identity on an infinite-dimensional Banach space is not compact, because its unit ball is not relatively compact. An integral operator with a continuous kernel on a compact interval often maps a bounded set to an equicontinuous family, so Arzelà–Ascoli gives compactness in a continuous-function norm. Compactness is stronger than boundedness and depends on the normed spaces chosen.",
    worked: "On ℓ² define T(x₁,x₂,...)= (x₁,x₂/2,x₃/3,...). Truncating after N coordinates yields a finite-rank T_N. The operator-norm difference ||T-T_N||=1/(N+1), tending to zero; hence T is compact. The identity would have truncation error 1 for every N and is not compact.",
    interpretation: "Small tail singular values make compact operators approximable by finite-dimensional pieces.",
    trap: "Do not conclude every bounded operator is compact; infinite-dimensional identity is the basic counterexample.",
    practice: "Is the diagonal operator S on ℓ² with coefficients 1/sqrt(n) compact? Justify using finite-rank truncation.",
    solution: "Yes. Let S_N retain the first N diagonal entries. It is finite rank and ||S-S_N||=sup_{n>N}1/sqrt(n)=1/sqrt(N+1), tending to zero. Therefore S is a norm limit of compact operators and is compact.",
    checks: [["What does compactness require of bounded sequences?", ["Images have convergent subsequences", "Inputs all converge", "Every image is zero"], 0, "This is sequential relative compactness."], ["Is the identity on infinite-dimensional ℓ² compact?", ["No", "Yes", "Only if diagonal"], 0, "Its unit vectors have no convergent subsequence."], ["Are finite-rank operators compact?", ["Yes", "No", "Only if invertible"], 0, "Bounded sets in finite-dimensional ranges have compact closure."]],
  },
  {
    lesson: "math.m28.l7", title: "Spectral theory",
    premise: "Spectral theory extends eigenvalue ideas to operators where an eigenbasis or even eigenvectors may not exist in the naive form.",
    idea: "The spectrum σ(T) of a bounded operator contains λ for which T-λI lacks a bounded everywhere-defined inverse. In finite dimensions it is exactly the eigenvalues; in infinite dimensions the spectrum can include continuous or residual spectrum without ordinary eigenvectors. A compact self-adjoint operator on a Hilbert space has real nonzero eigenvalues of finite multiplicity that can accumulate only at zero, and an orthonormal eigenbasis for the closure of its range, together with its kernel. The spectral theorem for bounded self-adjoint operators is more general and may require projection-valued measures rather than a countable eigenvector list.",
    worked: "For T on ℓ² with T e_n=(1/n)e_n, every 1/n is an eigenvalue, and zero is also in the spectrum because inverse multiplication by n is unbounded, even though T has no nonzero vector with eigenvalue zero. This T is compact and self-adjoint, and 1/n accumulates at zero.",
    interpretation: "Spectrum records failures of bounded invertibility, not only solutions of Tv=λv.",
    trap: "Do not assume every spectral value in an infinite-dimensional space is an eigenvalue.",
    practice: "For the same diagonal T, explain why λ=0 is spectral but not an eigenvalue.",
    solution: "Tx=0 implies x_n/n=0 for every n, hence x=0, so zero is not an eigenvalue. Yet T^{-1} on its range would multiply the nth coordinate by n, which is unbounded; zero fails the bounded-inverse criterion and belongs to the spectrum.",
    checks: [["What defines spectrum for a bounded operator?", ["Failure of a bounded everywhere-defined inverse of T-λI", "Only a nonzero eigenvector", "Only negative λ"], 0, "Infinite-dimensional spectrum is broader."], ["Where can nonzero eigenvalues of a compact self-adjoint operator accumulate?", ["Only at zero", "At any positive number", "Nowhere ever"], 0, "This is its spectral structure."], ["Can zero be spectral without being an eigenvalue?", ["Yes", "No", "Only in finite dimensions"], 0, "The diagonal example shows it."]],
  },
  {
    lesson: "math.m28.l8", title: "Distributions and weak derivatives",
    premise: "A distribution acts on test functions, extending differentiation to rough functions and objects such as point masses.",
    idea: "A locally integrable f defines a distribution T_f(φ)=∫fφ for smooth compactly supported tests φ. Its distributional derivative is T_f'(φ)=-T_f(φ'), motivated by integration by parts with no boundary term. A weak derivative g of f exists when ∫fφ'=-∫gφ for all tests. The Heaviside step H(x)=1 for x>0, zero for x<0, has derivative δ₀ as a distribution: -∫Hφ'=-∫₀∞φ'=φ(0). Delta is not an ordinary function in L¹_loc. Sobolev spaces collect functions with weak derivatives in L^p, enabling weak PDE formulations.",
    worked: "For f(x)=|x|, its classical derivative fails at zero, but g(x)=sign(x) for x≠0 is its weak derivative. Split ∫|x|φ' at zero, integrate by parts on each side, and the boundary terms at zero vanish because |0|=0. The resulting integral is -∫sign(x)φ.",
    interpretation: "The test-function identity retains differentiation even when pointwise formulas break at isolated locations.",
    trap: "Do not identify δ₀ with an infinite ordinary function value; it is a linear functional on tests.",
    practice: "Compute the distributional derivative of H(x-2), the step that turns on at x=2.",
    solution: "For a test φ, derivative action is -∫₂∞φ'(x)dx=φ(2). This is δ₂, the point-evaluation distribution at 2. No ordinary L¹_loc function has this action.",
    checks: [["How is distributional derivative defined?", ["T'(φ)=-T(φ')", "T'(φ)=T(φ)²", "Only by pointwise slopes"], 0, "Integration by parts moves the derivative."], ["What is the derivative of a unit step at zero?", ["Dirac delta", "Zero as a distribution", "Infinity as an ordinary number"], 0, "It evaluates tests at the jump."], ["Can |x| have a weak derivative despite a corner?", ["Yes", "No", "Only if smoothed"], 0, "Its sign function is a weak derivative."]],
  },
];
