import type { MathLecture } from "./lectures";

/** Advanced algebra: modules, fields, representations, geometry, and proof practice. */
export const MATH_GRADUATE_ALGEBRA: MathLecture[] = [
  {
    lesson: "math.m34.l1", title: "Modules over rings",
    premise: "A module generalizes a vector space by letting scalars come from a ring rather than a field.",
    idea: "An R-module M has an abelian addition and scalar action satisfying distributivity and associativity, with 1m=m for unital rings. Vector spaces are modules over fields, but modules may have torsion and need not have bases. An abelian group is a Z-module by repeated addition. A submodule is closed under addition and scalar multiplication; a module homomorphism preserves both. The quotient M/N exists for a submodule N, and the first isomorphism theorem gives M/ker f isomorphic to im f. Over a PID, finitely generated modules have a structure theorem splitting free and torsion parts. Over a general ring, free and projective modules differ.",
    worked: "Z/6Z is a Z-module. Element [2] has torsion because 3[2]=[0]. It cannot be a vector space over Z, since Z is not a field and [2] has no independent-coordinate basis as a free Z-module. The map Z to Z/6Z by reduction has kernel 6Z and image all Z/6Z.",
    interpretation: "Torsion is a structural possibility that field-based linear algebra excludes.",
    trap: "Do not assume every finitely generated module admits a basis; that is special to free modules.",
    practice: "Find the kernel and image of f:Z to Z/4Z defined by f(n)=[n].",
    solution: "Every residue class occurs, so image is Z/4Z. The kernel is all multiples of four, 4Z. The first isomorphism theorem identifies Z/4Z with Z/ker f.",
    checks: [["What differs between a module and vector space?", ["Scalars may form a ring rather than a field", "Addition is forbidden", "Every module is finite"], 0, "Division by nonzero scalars may fail."], ["Can a module have torsion?", ["Yes", "No", "Only over fields"], 0, "Z/6Z is an example."], ["Must every module have a basis?", ["No", "Yes", "Only over Z"], 0, "Only free modules do."]],
  },
  {
    lesson: "math.m34.l2", title: "Tensor products",
    premise: "A tensor product converts bilinear maps into linear maps with a universal property.",
    idea: "For R-modules M,N over a commutative ring, M⊗_R N comes with bilinear map (m,n) to m⊗n such that every R-bilinear map M×N to P factors uniquely through a linear map M⊗N to P. Tensors obey (m+m')⊗n=m⊗n+m'⊗n and (rm)⊗n=m⊗(rn). They are sums of simple tensors, not necessarily one simple tensor. Over a field, bases of dimensions a,b give tensor-product dimension ab. Over Z, torsion can collapse: (Z/2Z)⊗_Z(Z/3Z)=0 because both 2 and 3 annihilation force each simple tensor to vanish. Tensor products are right exact but not generally left exact; flatness identifies when tensoring preserves injections.",
    worked: "For vector spaces R² and R³, elementary tensors e_i⊗f_j for i=1,2 and j=1,2,3 form six basis elements. A general tensor is a sum of these six with coefficients. The dimension is 2·3=6, not 2+3=5.",
    interpretation: "The universal property explains tensor operations independently of a particular coordinate array.",
    trap: "Do not assume every tensor is decomposable as one m⊗n; many require sums.",
    practice: "What is dim(R²⊗R⁴), and give the form of a basis?",
    solution: "The dimension is 2·4=8. If e₁,e₂ and f₁,...,f₄ are bases, the eight e_i⊗f_j form a tensor-product basis.",
    checks: [["What kind of maps does tensor product linearize?", ["Bilinear maps", "Only constant maps", "Set intersections"], 0, "This is its universal property."], ["What is dim(V⊗W) for finite vector spaces?", ["dim V times dim W", "dim V plus dim W", "Always one"], 0, "Basis pairs enumerate it."], ["Is every tensor simple?", ["No", "Yes", "Only over fields"], 0, "Sums may be essential."]],
  },
  {
    lesson: "math.m34.l3", title: "Field extensions and Galois theory",
    premise: "Field extensions add roots of polynomials, while Galois theory records how automorphisms permute those roots.",
    idea: "For algebraic α over F, the minimal polynomial m_α is irreducible over F and F(α) is isomorphic to F[x]/(m_α), with degree [F(α):F]=deg m_α. Tower law multiplies degrees: [K:F]=[K:E][E:F]. A splitting field contains all roots of a polynomial. For a finite Galois extension, the Galois group consists of F-fixing field automorphisms, and intermediate fields correspond contravariantly to subgroups. Separability and normality are needed for the full correspondence. A polynomial's roots in a larger field do not automatically imply every adjoining step has the same degree.",
    worked: "For F=Q and α=sqrt(2), minimal polynomial x²-2 is irreducible by rational-root reasoning. Q(sqrt(2)) has basis {1,sqrt(2)} over Q, degree two, and its two Q-automorphisms send sqrt(2) to ±sqrt(2). Its Galois group has two elements.",
    interpretation: "Polynomial irreducibility controls extension dimension; root symmetries control field structure.",
    trap: "Do not call an arbitrary finite extension Galois without checking normality and separability.",
    practice: "Find [Q(sqrt(3)):Q] and the images of sqrt(3) under its Q-automorphisms.",
    solution: "x²-3 is irreducible over Q, so the degree is two. An automorphism fixing Q must send sqrt(3) to another root of its minimal polynomial, either +sqrt(3) or -sqrt(3); both choices define automorphisms of the field.",
    checks: [["What determines [F(α):F] for algebraic α?", ["Degree of its minimal polynomial", "Number of written generators", "Field characteristic always"], 0, "Power basis has that length."], ["What does an F-automorphism preserve?", ["Elements of F", "Only zero", "Every complex number"], 0, "It fixes the base field."], ["What hypotheses support finite Galois correspondence?", ["Normal and separable extension", "Any ring", "Only positive characteristic"], 0, "They define a Galois extension."]],
  },
  {
    lesson: "math.m34.l4", title: "Representation theory basics",
    premise: "A representation studies a group by making each group element act as an invertible linear transformation.",
    idea: "A representation of G on vector space V is homomorphism ρ:G to GL(V). An invariant subspace W satisfies ρ(g)W⊆W for every g; a representation with no nontrivial invariant subspace is irreducible. Over a characteristic-zero field such as C, every finite-group representation decomposes into irreducibles by Maschke's theorem. A character χ(g)=tr ρ(g) is constant on conjugacy classes and helps distinguish representations. Over fields whose characteristic divides |G|, complete reducibility can fail. The regular representation acts on basis vectors indexed by G by permutation and contains every irreducible with multiplicity tied to its dimension over C.",
    worked: "For G=C₂={e,s}, define ρ(s) on R² as diagonal(1,-1). It obeys ρ(s)²=I. The x-axis and y-axis are invariant, so the representation splits into trivial and sign one-dimensional representations. Its character is χ(e)=2, χ(s)=0.",
    interpretation: "Decomposition isolates the basic symmetry modes of a linear group action.",
    trap: "Do not apply Maschke's complete-reducibility conclusion when field characteristic divides the group order.",
    practice: "For G=C₂ acting on R by ρ(s)=-1, compute its character and decide irreducibility.",
    solution: "The one-dimensional matrices are ρ(e)=1, ρ(s)=-1, so χ(e)=1 and χ(s)=-1. A one-dimensional nonzero representation has no proper nonzero subspace, hence is irreducible.",
    checks: [["What is a representation?", ["Group homomorphism into invertible linear maps", "Any set map", "Only a scalar norm"], 0, "Group multiplication must be respected."], ["What is a character?", ["Trace of representation matrices", "Determinant only", "Group size"], 0, "It is constant on conjugacy classes."], ["When can Maschke fail?", ["Characteristic divides group order", "Over C for finite G", "When V is finite dimensional"], 0, "The averaging proof needs division by |G|."]],
  },
  {
    lesson: "math.m34.l5", title: "Commutative algebra foundations",
    premise: "Commutative algebra studies ideals and localization, the algebraic language behind local geometric behavior.",
    idea: "An ideal I of commutative ring R is closed under addition and absorption by all r∈R. A prime ideal p has ab∈p implying a∈p or b∈p; R/p is an integral domain. A maximal ideal m yields a field R/m. Localization S^{-1}R formally inverts elements of multiplicative set S; at prime p, R_p inverts all elements outside p, focusing on behavior near p. Noetherian rings have ascending-chain stabilization for ideals, equivalently every ideal is finitely generated. Polynomial rings over fields are Noetherian by Hilbert's basis theorem. Local properties can be easier than a global ring description, but denominators from S must be tracked.",
    worked: "In Z, ideal (6) is not prime because 2·3∈(6) but neither 2 nor 3 is in (6); Z/(6) has zero divisors. Ideal (5) is maximal, and Z/(5) is a field. Localizing Z at (5) permits fractions a/b with b not divisible by 5.",
    interpretation: "Ideal type predicts quotient algebra, while localization selects which denominators become legal.",
    trap: "Do not infer a prime ideal is always maximal; in Z[x], (0) is prime but not maximal.",
    practice: "Is (x) prime or maximal in Q[x,y]? Describe the quotient.",
    solution: "Q[x,y]/(x) is isomorphic to Q[y], an integral domain, so (x) is prime. Q[y] is not a field, so (x) is not maximal.",
    checks: [["What quotient characterizes a prime ideal?", ["Integral domain", "Always a field", "Zero ring only"], 0, "Zero divisors are excluded."], ["What quotient characterizes a maximal ideal?", ["Field", "Only group", "Any finite ring"], 0, "No proper intermediate ideals remain."], ["What does localization do?", ["Inverts a chosen multiplicative set", "Deletes all ideals", "Forces every element zero"], 0, "It adds controlled denominators."]],
  },
  {
    lesson: "math.m34.l6", title: "Algebraic varieties and ideals",
    premise: "Polynomial equations define geometric sets, and ideals capture all polynomial consequences of those equations.",
    idea: "For ideal I⊆k[x₁,...,x_n], V(I) is the common zero set over k; for a set S, I(S) is polynomials vanishing on S. Inclusion reverses: I⊆J implies V(J)⊆V(I). Over an algebraically closed field, Hilbert's Nullstellensatz gives I(V(I))=rad(I), so geometry sees the radical rather than nilpotent multiplicities. The affine coordinate ring is k[x]/I for a scheme-like algebraic object; for a reduced variety use radical ideals. A singular point may have tangent dimension larger than local geometric dimension; use Jacobian rank to inspect smoothness. Over R, the simple algebraically closed correspondence needs modification.",
    worked: "In C[x], I=(x²) and J=(x) have the same zero set {0}. Their radicals coincide, rad(I)=(x), but quotient C[x]/(x²) retains a nonzero nilpotent class of x. Thus the same point set can hide different algebraic structures.",
    interpretation: "The ideal can remember multiplicity that a bare list of points forgets.",
    trap: "Do not apply complex-field Nullstellensatz verbatim over R; real algebraic geometry needs different conditions.",
    practice: "Find V(xy) in C² and decide whether ideal (xy) is radical.",
    solution: "V(xy) is the union of coordinate axes {x=0}∪{y=0}. Since xy is squarefree in C[x,y], the principal ideal (xy) is radical, equivalently (xy)=(x)∩(y). The axes intersect at a singular point at the origin.",
    checks: [["How does ideal inclusion affect zero sets?", ["It reverses inclusion", "It preserves inclusion", "No relation"], 0, "More equations mean fewer solutions."], ["What does I(V(I)) equal over an algebraically closed field?", ["rad(I)", "I always exactly", "The whole ring"], 0, "Nullstellensatz removes nilpotent multiplicity."], ["Can distinct ideals have the same point set?", ["Yes", "No", "Only over R"], 0, "(x) and (x²) do."]],
  },
  {
    lesson: "math.m34.l7", title: "Category-theoretic language",
    premise: "Category theory expresses constructions by how they interact with maps rather than by choosing a coordinate implementation.",
    idea: "A category has objects, morphisms, associative composition, and identities. A functor maps objects and morphisms while preserving identity and composition. A natural transformation connects functors compatibly with every morphism. A universal property characterizes an object through uniquely factoring maps: a product P of X,Y has projections such that any pair of maps Z to X and Z to Y factors uniquely through Z to P. Such a product is unique up to unique isomorphism, not literal equality. Tensor products and free objects have analogous universal properties. This language is powerful when it unifies examples, but abstract vocabulary alone does not replace proving the required factorization.",
    worked: "In Set, product of X,Y is X×Y with coordinate projections. Given f:Z to X and g:Z to Y, the unique mediating map h:Z to X×Y is h(z)=(f(z),g(z)). Projection after h recovers f,g, and any other map with those coordinates agrees pointwise with h.",
    interpretation: "The uniqueness clause is what makes an abstract construction invariant under presentation.",
    trap: "Do not cite a universal property without verifying both existence and uniqueness of the mediating map.",
    practice: "In Set, what map mediates f:Z to A and g:Z to B into the product A×B?",
    solution: "Define h(z)=(f(z),g(z)). Its first projection equals f and second equals g. Any map k with those projections has k(z)=(f(z),g(z)) for every z, so k=h uniquely.",
    checks: [["What are two requirements for a product universal property?", ["Existence and uniqueness of mediating maps", "Only a diagram", "Only a cardinality"], 0, "Both characterize the product."], ["What does a functor preserve?", ["Identity and composition", "Only object names", "Numerical norms"], 0, "It maps categorical structure."], ["Are universal objects literally equal across constructions?", ["Not necessarily; uniquely isomorphic", "Always identical sets", "Never related"], 0, "Presentation can vary."]],
  },
  {
    lesson: "math.m34.l8", title: "Research-paper proof workshop",
    premise: "Reading advanced algebra means reconstructing prerequisites and checking that every quotient, factorization, and universal claim has its hypotheses.",
    idea: "Take a theorem from a paper and rewrite it as a dependency graph: ring or field assumptions, finiteness or Noetherian conditions, exactness, and base-change behavior. Reprove one lemma from definitions, then test a finite or low-degree example in a computer algebra system without treating output as proof. Search for counterexamples by relaxing one hypothesis at a time: replace field with ring, characteristic zero with p, prime ideal with arbitrary ideal, or flat module with torsion module. Track notation for kernels, images, radicals, and localization carefully. Write a proof that a peer can check line by line, and distinguish a gap in exposition from a false theorem.",
    worked: "False claim: tensoring every injective map preserves injectivity. Take injection Z to Z by multiplication by 2, then tensor with Z/2Z. The induced map Z/2Z to Z/2Z is multiplication by 2, hence zero, not injective. The missing hypothesis is flatness of the tensor factor.",
    interpretation: "A tiny module counterexample can pinpoint why a categorical-sounding theorem needs an exactness condition.",
    trap: "Do not infer a theorem holds over all rings because a computation over a field succeeds.",
    practice: "Repair the false tensor-injectivity statement by naming a sufficient property of the tensor factor.",
    solution: "If N is flat over R, then tensoring an injective R-module map M' to M with N preserves injectivity. This is a defining characterization of flatness; without it, the Z/2Z counterexample applies.",
    checks: [["What can fail when tensoring an injection?", ["Injectivity", "All bilinearity", "Every quotient"], 0, "Torsion can collapse maps."], ["What property repairs this in general?", ["Flatness", "Finite dimension only", "A negative scalar"], 0, "Flat modules preserve exactness."], ["Does one symbolic example prove a universal theorem?", ["No", "Yes", "Only over fields"], 0, "It is a test, not a proof."]],
  },
];
