import type { MathLecture } from "./lectures";

/** Measure-theoretic probability: models, conditioning, convergence, and limits. */
export const MATH_GRADUATE_PROBABILITY: MathLecture[] = [
  {
    lesson: "math.m31.l1", title: "Probability spaces and random variables",
    premise: "A probability model is a measure space of total mass one, and a random variable is a measurable map out of it.",
    idea: "A probability space (Ω,F,P) has a sigma-algebra F and P(Ω)=1. An event belongs to F; P is countably additive on disjoint events. A real random variable X is F-to-Borel measurable, so {X≤x} is an event for every x. Its law is the pushforward P_X(B)=P(X∈B). Different underlying sample spaces can produce the same law, but joint dependence requires a shared model. Independence of variables means P(X∈A,Y∈B)=P_X(A)P_Y(B) for all measurable A,B, not merely zero covariance.",
    worked: "Roll a fair die with Ω={1,...,6}, all subsets measurable, and X=1 if the result is even. Then P_X({1})=3/6 and P_X({0})=3/6. A second indicator Y of divisibility by three is independent of X: P(X=1,Y=1)=1/6 equals P(X=1)P(Y=1)=1/2·1/3. For two binary indicators, the other event pairs follow by subtraction.",
    interpretation: "The pushforward describes one variable; independence is a statement about its joint law with another.",
    trap: "Do not infer independence from one matching event pair or from uncorrelatedness alone.",
    practice: "On a fair die, let X indicate even and Z indicate result at most three. Are X and Z independent?",
    solution: "P(X=1)=1/2 and P(Z=1)=1/2. Their intersection is only outcome 2, with probability 1/6, not 1/4. They are not independent. Both indicators are measurable on the finite full sigma-algebra.",
    checks: [["What must a random variable be?", ["Measurable map", "A continuous map always", "A scalar with no sample space"], 0, "Preimages of Borel sets must be events."], ["What is a variable's law?", ["Pushforward probability measure", "Its code name", "Only its mean"], 0, "It assigns probabilities to target sets."], ["Does zero covariance imply independence in general?", ["No", "Yes", "Only for indicators"], 0, "Dependence can survive zero linear association."]],
  },
  {
    lesson: "math.m31.l2", title: "Expectation as integration",
    premise: "Expectation is a Lebesgue integral of a random variable, so convergence and change-of-variable theorems apply directly.",
    idea: "For nonnegative X, E[X]=∫Ω X dP may be infinite. For signed X, expectation is finite when E|X|<∞; otherwise subtracting infinite positive and negative parts is invalid. If X has law μ, E[g(X)]=∫g dμ whenever the integral is defined, the law-of-the-unconscious-statistician identity. Linearity holds for integrable variables without independence. Jensen says φ(E[X])≤E[φ(X)] for convex φ under suitable integrability. Tonelli allows nonnegative sums inside expectation, while dominated convergence requires an integrable bound.",
    worked: "For a fair die, E[X]=Σ_{k=1}^6 k/6=3.5. If Y=X², E[Y]=Σk²/6=91/6, not (E[X])²=12.25. Jensen predicts E[X²]≥(E[X])²; the difference is variance 35/12.",
    interpretation: "Expectation measures an average under the whole law, not simply a transformation of the mean.",
    trap: "Do not assert E[g(X)]=g(E[X]) except for special affine g or degenerate circumstances.",
    practice: "Let P(X=0)=.75 and P(X=4)=.25. Compute E[X], E[X²], and Var(X).",
    solution: "E[X]=0(.75)+4(.25)=1. E[X²]=16(.25)=4. Variance is E[X²]-(E[X])²=4-1=3. Independence plays no role because only one variable is involved.",
    checks: [["What is expectation mathematically?", ["Integral against probability measure", "Only an arithmetic average of observed data", "A median"], 0, "Discrete sums are a special case."], ["Does linearity need independence?", ["No", "Yes", "Only for finite variables"], 0, "Integrability is the key condition."], ["Is E[X²] always (E[X])²?", ["No", "Yes", "Only for positive X"], 0, "Their gap is variance."]],
  },
  {
    lesson: "math.m31.l3", title: "Modes of convergence",
    premise: "Almost-sure, probability, distribution, and L-p convergence assert different kinds of closeness.",
    idea: "X_n tends to X almost surely if P({ω:X_n(ω) tends to X(ω)})=1. In probability means P(|X_n-X|>ε) tends to zero for every ε>0. In L^p means E|X_n-X|^p tends to zero. In distribution means expectations of bounded continuous test functions converge, or CDFs converge at continuity points of the limit CDF. Almost-sure and L^p convergence imply convergence in probability; convergence in probability implies convergence in distribution. Reverse implications fail without extra assumptions. Uniform integrability helps upgrade probability convergence to L¹ convergence. Convergence in distribution is weakest and does not couple variables pointwise by itself.",
    worked: "On [0,1] with uniform measure, X_n=n·1_(0,1/n). Then X_n tends to zero almost surely and in probability because the nonzero event has probability 1/n. Yet E|X_n|=1, so there is no L¹ convergence. The spikes demonstrate why almost-sure convergence does not control integrals.",
    interpretation: "Choose a convergence mode that matches the theorem or engineering quantity actually needed.",
    trap: "Do not replace distributional convergence with convergence in probability unless the variables are coupled and more is proved.",
    practice: "For X_n=1/n deterministically, identify whether X_n tends to 0 almost surely, in probability, in L², and in distribution.",
    solution: "All four hold. Pointwise values tend to zero on every sample, the probability of a fixed-size deviation is eventually zero, E|X_n|²=1/n² tends to zero, and deterministic laws converge to the point mass at zero.",
    checks: [["Does L¹ convergence imply convergence in probability?", ["Yes", "No", "Only on finite Ω"], 0, "Apply Markov's inequality."], ["Does almost-sure convergence always imply L¹?", ["No", "Yes", "Only for bounded X"], 0, "Moving spikes are a counterexample."], ["Which mode is generally weakest here?", ["Distribution", "Almost sure", "L²"], 0, "It need not use a common coupling."]],
  },
  {
    lesson: "math.m31.l4", title: "Conditional expectation",
    premise: "Conditional expectation is the best measurable summary of a random quantity given a specified information sigma-algebra.",
    idea: "For integrable X and sub-sigma-algebra G⊆F, E[X|G] is G-measurable and satisfies ∫_A E[X|G]dP=∫_A XdP for every A∈G; it is unique almost surely. In L² it is the orthogonal projection of X onto the closed subspace of G-measurable square-integrable variables. The tower property E[E[X|H]|G]=E[X|G] holds when G⊆H. If X is independent of G, E[X|G]=E[X]. Conditioning on an event of zero probability needs a more careful regular-conditional framework, not elementary division by zero.",
    worked: "Roll a fair die and let G reveal only odd versus even. For X equal to the die value, E[X|G] is 3 on odd outcomes (mean of 1,3,5) and 4 on even outcomes (mean of 2,4,6). Its overall expectation is (3+4)/2=3.5, matching E[X].",
    interpretation: "The answer is itself a random variable: its value changes with the information revealed.",
    trap: "Do not confuse E[X|G] with a single scalar unless G contains no nontrivial information.",
    practice: "A fair die reveals only whether its value is at most three. Find E[X|G].",
    solution: "On outcomes 1,2,3, conditional mean is (1+2+3)/3=2. On 4,5,6 it is (4+5+6)/3=5. Thus E[X|G]=2 on the lower event and 5 on its complement; its mean is 3.5.",
    checks: [["What must E[X|G] be measurable with respect to?", ["G", "Every subset of real numbers", "Only the trivial sigma-algebra"], 0, "It uses the available information."], ["Is conditional expectation a random variable?", ["Yes", "No", "Only for discrete models"], 0, "It can take different values on information cells."], ["What is the tower rule for nested information?", ["Conditioning twice down to G equals conditioning on G", "The result always doubles", "Information reverses"], 0, "G⊆H is required."]],
  },
  {
    lesson: "math.m31.l5", title: "Characteristic functions",
    premise: "A characteristic function is a Fourier transform of a probability law and records the whole distribution.",
    idea: "For real X, φ_X(t)=E[e^{itX}] exists for every real t because the integrand has magnitude one. It satisfies φ(0)=1 and |φ(t)|≤1; independent sums multiply characteristic functions: φ_{X+Y}=φ_Xφ_Y. When moments exist, derivatives at zero encode them, but differentiability cannot be assumed blindly. Lévy's continuity theorem connects pointwise convergence of characteristic functions to convergence in distribution when the limiting function is continuous at zero and is a characteristic function. Inversion and uniqueness show that equal characteristic functions imply equal laws. This is useful when CDFs are hard to convolve directly.",
    worked: "If X is Bernoulli(p), then φ_X(t)=E[e^{itX}]=(1-p)+p e^{it}. For two independent Bernoulli(p) variables, the sum has φ(t)=((1-p)+p e^{it})², whose expansion yields binomial probabilities (1-p)², 2p(1-p), p².",
    interpretation: "Multiplication in frequency space corresponds to convolution of independent distributions.",
    trap: "Do not multiply characteristic functions for a sum unless independence or another valid factorization is established.",
    practice: "Find φ_X(t) for X equally likely to be -1 or 1.",
    solution: "φ_X(t)=(e^{-it}+e^{it})/2=cos t. It equals 1 at zero and has magnitude at most one. Its derivative at zero is zero, consistent with E[X]=0.",
    checks: [["Does every real random variable have a characteristic function?", ["Yes", "Only integrable ones", "Only continuous ones"], 0, "The complex exponential is bounded."], ["What happens for independent sums?", ["Characteristic functions multiply", "They add", "They vanish"], 0, "Expectation factors under independence."], ["Does φ determine the law?", ["Yes", "No", "Only for Gaussian laws"], 0, "Uniqueness is fundamental."]],
  },
  {
    lesson: "math.m31.l6", title: "Martingales",
    premise: "A martingale models fair updates relative to growing information, with its defining equality expressed by conditional expectation.",
    idea: "For filtration F₀⊆F₁⊆..., an integrable adapted process M_n is a martingale if E[M_{n+1}|F_n]=M_n. A submartingale uses ≥ and a supermartingale uses ≤. Independent mean-zero increments generate a martingale by partial sums. Optional stopping can identify E[M_τ]=E[M₀] only under appropriate conditions on the stopping time and process; arbitrary stopping can break the equality. Doob's maximal inequalities and convergence theorems provide control when integrability or boundedness hypotheses hold. A martingale may fluctuate wildly on individual paths despite fair conditional expectation.",
    worked: "Let ξ_k be independent fair ±1 variables and M_n=Σ_{k=1}^n ξ_k. Given F_n, M_n is known and E[ξ_{n+1}|F_n]=0, so E[M_{n+1}|F_n]=M_n. Its mean stays zero, but its variance is n, so path magnitudes typically grow.",
    interpretation: "Fairness is conditional, not a promise that each next step is zero or that paths remain bounded.",
    trap: "Do not apply optional stopping at an unbounded hitting time without verifying a valid stopping theorem's hypotheses.",
    practice: "Let ξ_k be independent with P(ξ=1)=.6 and P(ξ=-1)=.4. Find a centered partial-sum martingale.",
    solution: "E[ξ]=.6-.4=.2. Define M_n=Σ_{k=1}^n(ξ_k-.2). Each centered increment has conditional mean zero given past F_n, so E[M_{n+1}|F_n]=M_n.",
    checks: [["What equality defines a martingale?", ["E[M_{n+1}|F_n]=M_n", "M_{n+1}=M_n every path", "Variance always zero"], 0, "It is conditional fairness."], ["Can martingale variance grow?", ["Yes", "No", "Only for continuous time"], 0, "Fair random walks spread out."], ["Can optional stopping be used without hypotheses?", ["No", "Yes", "Only for symmetric walks"], 0, "Stopping times need conditions."]],
  },
  {
    lesson: "math.m31.l7", title: "Concentration inequalities",
    premise: "Concentration bounds quantify how unlikely a large deviation is under stated independence or tail conditions.",
    idea: "Markov: for nonnegative X and a>0, P(X≥a)≤E[X]/a. Chebyshev applies to squared centered deviations: P(|X-μ|≥t)≤Var(X)/t². Hoeffding gives exponential tails for sums of independent bounded variables: if a_i≤X_i≤b_i, P(S-E[S]≥t)≤exp(-2t²/Σ(b_i-a_i)²). Independence is crucial for this form. Chernoff bounds use exponential moments and optimize over a parameter. A loose upper bound is still mathematically valid; compare its scale with a target error and confidence level.",
    worked: "For 100 independent Bernoulli trials with success probability .5, the sample average has mean .5 and variance .25/100=.0025. Chebyshev bounds P(|average-.5|≥.2)≤.0025/.04=.0625. Hoeffding gives a two-sided bound 2exp(-2·100·.2²)≈.00067, much tighter here.",
    interpretation: "Assumptions buy stronger tails: variance alone gives polynomial decay, independence and boundedness permit exponential decay.",
    trap: "Do not use an independent-sample Hoeffding bound on strongly dependent observations without modification.",
    practice: "If X≥0 and E[X]=3, use Markov to bound P(X≥12).",
    solution: "Markov gives P(X≥12)≤E[X]/12=3/12=.25. The true probability may be smaller; this is a universal upper bound under nonnegativity and finite expectation.",
    checks: [["What assumption does Markov need?", ["Nonnegative variable", "Independence of 100 samples", "Normality"], 0, "It bounds one variable by its mean."], ["What does Hoeffding's standard sum form need?", ["Independent bounded terms", "Only finite mean", "Unbounded Cauchy terms"], 0, "Its exponential tail uses both conditions."], ["Is a concentration bound an exact probability?", ["Not generally", "Always", "Only if exponential"], 0, "It is usually an inequality."]],
  },
  {
    lesson: "math.m31.l8", title: "Limit theorems",
    premise: "Laws of large numbers and central limit theorems describe different limits: averages stabilize, while scaled fluctuations approach a distribution.",
    idea: "For i.i.d. integrable X_i with mean μ, the strong law gives sample average tending to μ almost surely. Under i.i.d. finite nonzero variance σ², the classical CLT gives sqrt(n)(average-μ)/σ converging in distribution to standard normal. The CLT does not assert that raw observations become normal, nor that the approximation is accurate at every finite n. A Lindeberg condition extends CLT behavior to certain independent nonidentical arrays; heavy tails or strong dependence can require different scaling or limits. Slutsky's theorem permits replacing a parameter by a consistent estimator under its conditions. Finite-sample error estimates, such as Berry–Esseen with finite third moment, need stronger assumptions.",
    worked: "For independent Bernoulli(.5) variables, μ=.5 and σ=.5. At n=100, the standardized sample mean is 20(average-.5). The CLT says its distribution is approximately N(0,1) for sufficiently large n, while the strong law says the unscaled average tends to .5 almost surely.",
    interpretation: "The LLN answers 'where is the average heading?'; the CLT answers 'how do its residual fluctuations scale?'.",
    trap: "Do not apply a finite-variance CLT to a distribution whose variance is infinite without a replacement theorem.",
    practice: "For i.i.d. observations with mean 10 and variance 4, write the classical CLT-standardized sample mean.",
    solution: "The standard deviation is σ=2, so Z_n=sqrt(n)(average-10)/2 converges in distribution to N(0,1) under the i.i.d. finite-variance assumptions. The unstandardized average tends to 10 by the strong law if integrable.",
    checks: [["What converges almost surely in a strong LLN?", ["Sample average to the mean", "Each observation to the mean", "Variance to zero always"], 0, "It concerns averages."], ["What does the CLT scale by?", ["sqrt(n) over standard deviation", "n²", "No scaling"], 0, "Fluctuations are order 1/sqrt(n)."], ["Does the CLT make individual observations normal?", ["No", "Yes", "Only for Bernoulli"], 0, "It concerns a normalized sum."]],
  },
];
