import type { MathLecture } from "./lectures";

/** Technique selection is taught through structure and verification. */
export const MATH_INTEGRATION_METHODS: MathLecture[] = [
  {
    lesson: "math.m8.l1",
    title: "Integration by parts",
    premise: "Integration by parts reverses the product rule. It is useful when differentiating one factor simplifies it while the other factor can be integrated.",
    idea: "From (uv)'=u'v+uv', integrate both sides and rearrange: ∫u dv=uv-∫v du. Choose u and dv so v is available and the new integral is simpler. Typical choices differentiate a polynomial and integrate an exponential or trigonometric factor. For definite integrals, evaluate the boundary term [uv]ₐᵇ and retain the same bounds in the remaining integral. Sometimes a second application returns to the original integral; solve the resulting algebraic equation. Check an indefinite result by differentiation.",
    worked: "Find ∫x e^x dx. Choose u=x and dv=e^x dx, so du=dx and v=e^x. Then ∫x e^x dx=x e^x-∫e^x dx=(x-1)e^x+C. Differentiating gives e^x+(x-1)e^x=x e^x. For ∫₀¹x e^x dx, evaluate [(x-1)e^x]₀¹=0-(-1)=1.",
    interpretation: "The method trades a product for a boundary term and a simpler integral. It does not guarantee every arbitrary choice of u will help.",
    trap: "Do not forget the minus sign or the boundary term. A proposed dv must include its dx, and v must be an antiderivative of that entire dv.",
    practice: "Evaluate ∫x cos x dx and verify by differentiating. Then evaluate the definite integral from 0 to π/2.",
    solution: "Take u=x, dv=cos x dx, so du=dx and v=sin x. The antiderivative is x sin x-∫sin x dx=x sin x+cos x+C. Its derivative is sin x+x cos x-sin x=x cos x. At π/2 the value is π/2; at 0 it is 1, so the definite integral is π/2-1.",
    checks: [
      ["Which derivative rule underlies integration by parts?", ["The product rule", "The chain rule only", "The quotient rule only"], 0, "Differentiate uv and rearrange."],
      ["Which sign separates uv from ∫v du in the integration-by-parts formula?", ["Minus", "Plus", "Neither"], 0, "Move the second product-rule term to the other side."],
      ["How should an indefinite result be checked?", ["Differentiate it", "Square it", "Reverse the bounds"], 0, "Its derivative must recover the integrand."],
    ],
  },
  {
    lesson: "math.m8.l2",
    title: "Trigonometric integrals",
    premise: "Trigonometric integrals become manageable when identities expose a derivative pair or reduce powers. The method depends on the parity and functions present.",
    idea: "For products sin^m x cos^n x, an odd sine power can leave one sin x dx for u=cos x; an odd cosine power can leave cos x dx for u=sin x. If both powers are even, use half-angle identities such as sin²x=(1-cos 2x)/2 and cos²x=(1+cos 2x)/2. For tan and sec, use sec²x=1+tan²x and d(tan x)=sec²x dx, or d(sec x)=sec x tan x dx. Check domains: an antiderivative involving tan or sec is valid only on intervals without cosine zeros. Identities must be algebraically valid before substitution.",
    worked: "Integrate sin³x cos x. Set u=sin x and du=cos x dx, giving u⁴/4+C=sin⁴x/4+C. For ∫sin²x dx, use sin²x=(1-cos 2x)/2, so the antiderivative is x/2-sin(2x)/4+C. Differentiating the latter yields 1/2-cos(2x)/2=sin²x.",
    interpretation: "Parity suggests which factor to reserve for du. The goal is an exact derivative match, not simply reducing every trigonometric expression at random.",
    trap: "Do not use sin²x+cos²x=1 as though sin²x=1-cos x. The squared cosine is essential. Keep chain factors when integrating cos(2x).",
    practice: "Evaluate ∫cos³x sin x dx and ∫₀^π sin²x dx. Explain why each uses a different technique.",
    solution: "For the first, u=cos x and du=-sin x dx, so the result is -cos⁴x/4+C. For the second, sin²x=(1-cos 2x)/2, and [x/2-sin(2x)/4]₀^π=π/2. The first has a derivative pair; the second has an even power requiring reduction.",
    checks: [
      ["What is a useful substitution for sin³x cos x dx?", ["u=sin x", "u=x²", "u=cos² x without a factor"], 0, "Cos x dx is the derivative of sin x."],
      ["Which identity reduces sin²x?", ["(1-cos 2x)/2", "1-cos x", "sin 2x/2"], 0, "Use the half-angle identity."],
      ["Why must interval restrictions be retained for tan and sec?", ["Cosine can vanish", "Sine is never defined", "Their derivatives are zero"], 0, "Both contain division by cosine."],
    ],
  },
  {
    lesson: "math.m8.l3",
    title: "Trigonometric substitution",
    premise: "A square root of a quadratic expression may simplify when a trigonometric identity turns it into a perfect square. Choosing the substitution also requires an interval that controls the sign of the root.",
    idea: "For sqrt(a²-x²), use x=a sin θ with θ in [-π/2,π/2], so the root becomes a cos θ≥0. For sqrt(a²+x²), use x=a tan θ, giving a sec θ when sec θ is chosen positive. For sqrt(x²-a²) with x≥a, x=a sec θ can help. Convert dx, simplify, integrate in θ, then return to x using a right triangle or an inverse trigonometric function. State the domain branch; sqrt(cos²θ)=|cos θ|, not automatically cos θ. Sometimes a simpler substitution or known derivative works better than trigonometric substitution.",
    worked: "Evaluate ∫sqrt(4-x²) dx for -2<x<2. Let x=2sin θ with θ in (-π/2,π/2). Then dx=2cos θ dθ and sqrt(4-x²)=2cos θ. The integral becomes 4∫cos²θ dθ=2θ+sin(2θ)+C. Since θ=arcsin(x/2) and sin(2θ)=2sin θ cos θ=x sqrt(4-x²)/2, the result is 2arcsin(x/2)+(x/2)sqrt(4-x²)+C.",
    interpretation: "The substitution works because 1-sin²θ=cos²θ, while the chosen interval makes the square root's nonnegative sign explicit.",
    trap: "Do not drop an absolute value without a domain argument. Also transform dx; replacing only the radical leaves an invalid mixed-variable integral.",
    practice: "Evaluate ∫₀¹ x/sqrt(4-x²) dx. Decide whether trigonometric substitution is needed and verify your result.",
    solution: "A direct u-substitution is shorter: let u=4-x², so du=-2x dx. The bounds x=0 and x=1 become u=4 and u=3. Thus the integral is -(1/2)∫₄³u^(-1/2)du=[-sqrt(u)]₄³=2-sqrt(3). Differentiating -sqrt(4-x²) gives x/sqrt(4-x²). The radical shape alone does not force trigonometric substitution.",
    checks: [
      ["What substitution fits sqrt(a²-x²)?", ["x=a sin θ", "x=a sec θ always", "x=a e^θ"], 0, "Use 1-sin²θ=cos²θ."],
      ["What is sqrt(cos²θ)?", ["|cos θ|", "cos θ on every interval", "cos²θ"], 0, "A square root is nonnegative."],
      ["What else must change besides the radical?", ["dx and eventually the variable of the answer", "Only the constant C", "Nothing"], 0, "The whole integral uses one variable at a time."],
    ],
  },
  {
    lesson: "math.m8.l4",
    title: "Partial fractions",
    premise: "A rational function can often be integrated by decomposing it into simpler fractions whose antiderivatives are logarithmic or arctangent functions.",
    idea: "First perform polynomial division if the numerator degree is at least the denominator degree. Factor the denominator over the reals. Each distinct linear factor gets a numerator constant; repeated linear factors need a term for every power. An irreducible quadratic factor needs a linear numerator, and repeated quadratics likewise need all powers. Solve for coefficients by clearing denominators and comparing polynomial coefficients or using valid evaluation points. Integrate each piece on an interval that avoids denominator zeros. A logarithm from 1/(x-a) requires ln|x-a|; a quadratic such as x²+a² may produce arctan.",
    worked: "Integrate 1/(x²-1) on an interval excluding ±1. Write 1/[(x-1)(x+1)]=A/(x-1)+B/(x+1). Clearing denominators gives 1=A(x+1)+B(x-1), so A=1/2 and B=-1/2. Therefore the integral is (1/2)ln|x-1|-(1/2)ln|x+1|+C. Differentiation combines the fractions back to 1/(x²-1).",
    interpretation: "The decomposition is an algebraic identity on the original domain. The resulting antiderivative constant can differ across disconnected intervals.",
    trap: "Do not omit a term for a repeated factor or a linear numerator above an irreducible quadratic. Do not cancel an excluded point into the domain.",
    practice: "Decompose and integrate (3x+5)/(x²+3x+2). State the excluded inputs and check your coefficients.",
    solution: "Factor the denominator as (x+1)(x+2), excluding -1 and -2. Set (3x+5)/[(x+1)(x+2)]=A/(x+1)+B/(x+2). Then 3x+5=A(x+2)+B(x+1), so A+B=3 and 2A+B=5, giving A=2, B=1. The integral is 2ln|x+1|+ln|x+2|+C on each domain interval.",
    checks: [
      ["What precedes decomposition for an improper rational function?", ["Polynomial division", "Changing bounds", "Taking absolute value"], 0, "Reduce numerator degree first."],
      ["What antiderivative matches 1/(x-a)?", ["ln|x-a|", "1/(x-a)²", "arctan(x-a)"], 0, "Differentiate the logarithm."],
      ["What does a repeated factor (x-a)² require?", ["Terms for both (x-a) and (x-a)²", "Only one constant term", "No decomposition"], 0, "Include each power up to the multiplicity."],
    ],
  },
  {
    lesson: "math.m8.l5",
    title: "Numerical integration and error",
    premise: "Some definite integrals have no convenient elementary antiderivative. Numerical rules estimate accumulation from samples, and a responsible estimate includes a justified error bound or convergence check.",
    idea: "With n equal subintervals of width h=(b-a)/n, the midpoint rule uses h times the sum of values at subinterval midpoints. The trapezoid rule uses h times a weighted sum of endpoint values, with half weight at the two outer endpoints. Simpson's rule requires even n and weights 1,4,2,4,…,2,4,1 multiplied by h/3. For a twice differentiable f with |f''|≤M₂, composite midpoint error is at most M₂(b-a)h²/24 and trapezoid error at most M₂(b-a)h²/12. For |f⁽⁴⁾|≤M₄, composite Simpson error is at most M₄(b-a)h⁴/180. State assumptions and an interval bound before quoting an error guarantee.",
    worked: "Estimate ∫₀¹x²dx with two equal subintervals. Midpoints 1/4 and 3/4 give M₂=(1/2)[(1/4)²+(3/4)²]=5/16=0.3125. The exact value is 1/3, so the error is 1/48≈0.0208. Since f''=2, the midpoint bound is 2·1·(1/2)²/24=1/48, exact for this quadratic example.",
    interpretation: "Refining h usually improves these rules at their stated orders when smoothness holds. Comparing two refinements is useful evidence but is not by itself a rigorous universal error bound.",
    trap: "Do not use Simpson's rule with odd n or cite derivative-based error formulas when the needed derivative is unbounded on the interval.",
    practice: "Use the composite trapezoid rule with n=2 for ∫₀¹x²dx. Find its actual error and the bound from |f''|≤2.",
    solution: "With h=1/2 and samples f(0)=0, f(1/2)=1/4, f(1)=1, T₂=h[f(0)/2+f(1/2)+f(1)/2]=(1/2)(0+1/4+1/2)=3/8. The actual error is 3/8-1/3=1/24. The bound is M₂(b-a)h²/12=2·1·(1/2)²/12=1/24, again exact for this quadratic.",
    checks: [
      ["Which n does composite Simpson's rule require?", ["An even number", "An odd number", "Only n=1"], 0, "Its basic panel spans two subintervals."],
      ["What must be bounded for the usual midpoint error formula?", ["The second derivative", "Only f itself", "The fifth derivative"], 0, "The curvature controls second-order error."],
      ["What is the midpoint rule's width for n equal pieces?", ["(b-a)/n", "n/(b-a)", "b-a"], 0, "Divide the interval length by n."],
    ],
  },
  {
    lesson: "math.m8.l6",
    title: "Strategy for mixed integrals",
    premise: "Integration is a recognition problem with verification. A long catalog of techniques helps only when you can diagnose the integrand's structure and know when to change methods.",
    idea: "First simplify algebraically and check the domain. Look for a direct antiderivative, then a composite function with a matching inner derivative for substitution. For products where one factor simplifies on differentiation, try parts; for rational functions, consider division and partial fractions. Trigonometric identities may expose a derivative pair; a quadratic radical may invite trig substitution, though direct substitution might still be shorter. For a definite integral, symmetry or numerical approximation can be better than a closed form. After every technique, differentiate a candidate antiderivative or compare a numerical value for a definite integral. A method can fail because its replacement integral is no simpler; step back rather than adding symbolic complexity.",
    worked: "Consider three superficially similar expressions. ∫2x/(1+x²)dx uses u=1+x² and becomes ln(1+x²)+C. ∫x e^x dx uses parts and becomes (x-1)e^x+C. ∫1/(x²-1)dx uses partial fractions and becomes (1/2)ln|x-1|-(1/2)ln|x+1|+C on its domain. The decisive feature is, respectively, a matched inner derivative, a differentiable polynomial factor, and a factorable rational denominator.",
    interpretation: "Technique choice is explainable from structure. Verification is the final stage, not an optional decoration.",
    trap: "Do not force substitution when the proposed du is missing, or apply partial fractions before reducing an improper rational function. Never present a logarithmic antiderivative across a denominator zero.",
    practice: "Choose and carry out a method for ∫₀¹ 2x e^(x²)dx and ∫₀¹x²dx. Explain why the second does not need a special technique.",
    solution: "For the first, set u=x² and du=2x dx. The original lower and upper bounds, zero and one, both stay zero and one after the substitution. The integral from zero to one of e^u du is e-1. For the second, the power rule gives [x³/3]₀¹=1/3 directly. Differentiating e^(x²) gives 2x e^(x²), and differentiating x³/3 gives x².",
    checks: [
      ["What is a strong signal for u-substitution?", ["A composite expression and its inner derivative", "Any product at all", "Any denominator at all"], 0, "The chain rule must be reversible."],
      ["What should follow an indefinite integration result?", ["Differentiate to check", "Drop the domain", "Change the bounds"], 0, "Recover the original integrand."],
      ["When may numerical integration be appropriate?", ["When a useful closed form is unavailable", "Only for polynomials", "Only when the integrand is constant"], 0, "A controlled estimate can be the intended result."],
    ],
  },
];
