import type { MathLecture } from "./lectures";

/** Geometric and physical integrals: model the slice before evaluating. */
export const MATH_INTEGRATION_APPLICATIONS: MathLecture[] = [
  {
    lesson: "math.m7.l1",
    title: "Area between curves",
    premise: "Area between two curves is the accumulation of thin positive strips. The correct strip length comes from comparing the curves over the interval, not from subtracting their formulas in a fixed order everywhere.",
    idea: "For vertical strips on [a,b], determine which graph is above the other and integrate top minus bottom. If they cross, solve for intersections and split the interval so the order is correct on each piece. For horizontal strips, integrate right minus left with respect to y; this can be simpler when x is easy to express as a function of y. Check that each strip length is nonnegative. The integral of f-g without splitting is signed area and may cancel regions. Draw a sketch to choose the variable and bounds before doing algebra.",
    worked: "Between y=x and y=x² on 0≤x≤1, x≥x², so area is ∫₀¹(x-x²)dx=[x²/2-x³/3]₀¹=1/6. For y=x and y=x³ on [-1,1], the curves cross at -1, 0, and 1. Their vertical order reverses at zero, so the total area is 2∫₀¹(x-x³)dx=2(1/2-1/4)=1/2; integrating x-x³ across the whole symmetric interval would incorrectly give zero.",
    interpretation: "A strip has length in y-units and width in x-units, yielding square units. The drawing identifies which difference actually represents that length.",
    trap: "Do not assume the first-named function stays on top. Solve all intersections inside the requested region and split where ordering changes.",
    practice: "Find the area enclosed by y=2x and y=x². Identify the intersection points and state which curve is upper on the bounded interval.",
    solution: "Solve x²=2x to get x=0 and x=2. On (0,2), 2x>x², so A=∫₀²(2x-x²)dx=[x²-x³/3]₀²=4-8/3=4/3 square units. The integrand is nonnegative on the chosen interval.",
    checks: [
      ["What is a vertical strip's area element?", ["(top-bottom) dx", "(right-left) dx", "top+bottom"], 0, "Strip length is vertical separation."],
      ["What should happen when curves cross?", ["Split and recheck their order", "Ignore the crossing", "Always reverse the bounds"], 0, "The top curve can change."],
      ["Can a signed integral cancel two geometric regions?", ["Yes", "No", "Only for circles"], 0, "Area requires positive contributions."],
    ],
  },
  {
    lesson: "math.m7.l2",
    title: "Volumes by slicing and disks",
    premise: "A solid can be understood as a stack of thin cross-sections. Volume is the integral of cross-sectional area, so the first job is to derive that area as a function of position.",
    idea: "If a solid has cross-sectional area A(x) perpendicular to the x-axis, then V=∫ₐᵇ A(x)dx. The integrand must have area units; multiplying by thickness dx gives volume units. For revolution about the x-axis with a region between y=0 and y=f(x)≥0, each cross-section is a disk with radius f(x), so A(x)=π[f(x)]². Find bounds from the region and check whether the radius is a distance to the actual axis of revolution. For other prescribed shapes, such as squares or semicircles, derive their area formula from the base segment before integrating.",
    worked: "Rotate the region under y=x on 0≤x≤2 about the x-axis. At x the disk radius is x, so V=π∫₀² x²dx=π[x³/3]₀²=8π/3 cubic units. This matches a cone of height 2 and base radius 2: (1/3)πr²h=8π/3.",
    interpretation: "The disk formula uses the square of the radius, not the radius itself. A geometric formula gives an independent reasonableness check.",
    trap: "Do not write π∫f(x)dx for a disk, and do not use f(x) as radius when the rotation axis is shifted away from y=0.",
    practice: "A solid has square cross-sections perpendicular to the x-axis for 0≤x≤1. Each square has side length 1+x. Find its volume and state the unit of the integrand.",
    solution: "Cross-sectional area is A(x)=(1+x)². Thus V=∫₀¹(1+2x+x²)dx=[x+x²+x³/3]₀¹=7/3 cubic units. The integrand A has square units; integration over x supplies one more length unit.",
    checks: [
      ["What is integrated to find volume by slicing?", ["Cross-sectional area", "Only a boundary curve", "The derivative of radius"], 0, "A thin slab has volume approximately area times thickness."],
      ["What is the disk area for radius r(x)?", ["πr(x)²", "2πr(x)", "πr(x)"], 0, "A disk is a circle, not its circumference."],
      ["What units should A(x) have?", ["Square length units", "Length units", "Cubic length units"], 0, "Thickness supplies the third dimension."],
    ],
  },
  {
    lesson: "math.m7.l3",
    title: "Washers and shells",
    premise: "Rotating a region with a hole creates washers; rotating strips parallel to the axis creates cylindrical shells. Choosing the method that matches the geometry avoids unnecessary inverse functions.",
    idea: "A washer perpendicular to the axis has area π(R²-r²), where R and r are the outer and inner distances from the rotation axis. Do not replace this by π(R-r)²; squaring a difference is not the difference of squares. A shell parallel to the axis has approximate volume 2π(radius)(height)(thickness), so integrate 2πrh. State the variable and its bounds from the chosen strip orientation. A single solid can often be computed both ways, giving a useful check.",
    worked: "Rotate the region between y=x and y=x² on 0≤x≤1 about the x-axis. Vertical strips make washers: outer radius R=x, inner radius r=x². Thus V=π∫₀¹(x²-x⁴)dx=π(1/3-1/5)=2π/15. Rotating the same region about the y-axis makes vertical shells with radius x and height x-x²: V=2π∫₀¹x(x-x²)dx=2π(1/3-1/4)=π/6. These are different solids because the axes differ.",
    interpretation: "Radius is always a distance to the stated axis. Height or inner radius comes from the bounded region, not merely from one curve in isolation.",
    trap: "Do not compare results from different axes as though they should match. Draw one representative strip and label its distances before integrating.",
    practice: "Rotate the region between y=1 and y=x² for -1≤x≤1 about the x-axis. Compute volume by washers and explain the outer and inner radii.",
    solution: "The region lies between the top y=1 and lower y=x². Rotating around y=0 gives outer radius 1 and inner radius x². V=π∫₋₁¹(1-x⁴)dx=π(2-2/5)=8π/5 cubic units. The squared inner radius is x⁴, not x².",
    checks: [
      ["What is a washer's area?", ["π(R²-r²)", "π(R-r)²", "2πRr"], 0, "Subtract the inner disk area from the outer disk area."],
      ["What three factors form a shell volume element?", ["Circumference, height, thickness", "Radius, radius, radius", "Area, area, width"], 0, "Unroll a thin cylindrical shell."],
      ["How is radius defined for a shifted axis?", ["Distance from the strip to that axis", "Always the y-value", "Always the x-value"], 0, "Use geometric distance, not a memorized symbol."],
    ],
  },
  {
    lesson: "math.m7.l4",
    title: "Average value and physical accumulation",
    premise: "An integral can turn a varying measurement into its average over an interval or accumulate a density into a total. Units reveal which interpretation is appropriate.",
    idea: "For integrable f on [a,b] with a<b, its average value is f_avg=(1/(b-a))∫ₐᵇ f(x)dx. This is the constant height whose rectangle over the interval has the same signed integral. If f is continuous, the integral mean value theorem ensures some c has f(c)=f_avg, though c need not be unique. For a linear density λ(x) in mass per length, a short piece has approximate mass λ(x)dx, so total mass is ∫λ(x)dx. The same structure applies to flow, power, or cost rates when the units and variable are correctly paired.",
    worked: "For f(x)=x² on [0,2], the average value is (1/2)∫₀²x²dx=(1/2)(8/3)=4/3. Since f is continuous, x=sqrt(4/3) is a point in the interval where f equals its average. If a rod has density λ(x)=2+x kilograms per meter on 0≤x≤2, its mass is ∫₀²(2+x)dx=[2x+x²/2]₀²=6 kilograms.",
    interpretation: "Average value retains the units of f; total accumulation multiplies those units by the integration variable's units. This distinction prevents reporting kilograms per meter as kilograms.",
    trap: "Do not divide by b-a when asked for total mass, or omit that division when asked for average density. Verify the mean-value theorem's continuity hypothesis before asserting a matching point.",
    practice: "A rod on 0≤x≤3 has linear density λ(x)=1+2x kg/m. Find its total mass and average density. Identify one position whose density equals that average.",
    solution: "Mass is ∫₀³(1+2x)dx=[x+x²]₀³=12 kg. Average density is 12/3=4 kg/m. Solve 1+2c=4 to get c=1.5 m, which lies inside the rod.",
    checks: [
      ["What is the average value of f on [a,b]?", ["∫ₐᵇ f divided by b-a", "∫ₐᵇ f alone", "f(b)-f(a)"], 0, "Normalize accumulation by interval length."],
      ["What units result from integrating kg/m over meters?", ["kg", "kg/m", "m/kg"], 0, "The length unit cancels."],
      ["When does a continuous f attain its average value?", ["At some point in the interval", "Only at the midpoint", "Never unless constant"], 0, "Apply the integral mean value theorem."],
    ],
  },
  {
    lesson: "math.m7.l5",
    title: "Work and variable force",
    premise: "Mechanical work is accumulated force along displacement. When force varies with position, multiplying one force value by the whole distance misses how the load changes.",
    idea: "For force F(x) acting along the direction of motion, a small displacement dx contributes approximately F(x)dx joules, so W=∫ₐᵇ F(x)dx. Opposing force yields negative work if the direction is retained. Hooke's law for an ideal spring is F(x)=kx in magnitude when stretched x from equilibrium; stretching from a to b requires ∫ₐᵇ kx dx=(k/2)(b²-a²). For lifting a distributed cable, choose a coordinate for each small piece, multiply its weight by the distance that piece travels, and integrate. State what idealizations the model assumes.",
    worked: "A spring with k=200 N/m is stretched from 0.1 m to 0.3 m beyond equilibrium. Required work is ∫₀.₁⁰.₃ 200x dx=100(0.3²-0.1²)=8 joules. Using the force at the final stretch, 60 N, times the whole 0.2 m would overestimate the work as 12 joules.",
    interpretation: "A newton-meter is a joule. The integral tracks the force at every intermediate stretch, and the resulting work is positive for an applied force in the stretch direction.",
    trap: "Do not use F(b)(b-a) for a varying force unless it is explicitly an approximation. Convert centimeters to meters before combining N/m with displacement.",
    practice: "An ideal spring requires 12 N to hold it 0.2 m beyond equilibrium. How much work is needed to stretch it from 0.1 m to 0.4 m?",
    solution: "Hooke's law gives k=12/0.2=60 N/m. Work is ∫₀.₁⁰.₄ 60x dx=30(0.4²-0.1²)=30(0.16-0.01)=4.5 joules. The lower bound is 0.1 m because the question asks for the additional work from an already stretched position.",
    checks: [
      ["What is the work element for a variable force along displacement?", ["F(x) dx", "F'(x) dx", "F(b)(b-a) exactly"], 0, "Work accumulates force times a tiny displacement."],
      ["What are units of N·m?", ["Joules", "Newtons per meter", "Meters per second"], 0, "Force times length is work."],
      ["For Hooke's law, what is k if 12 N is needed at x=0.2 m?", ["60 N/m", "2.4 N/m", "12 N/m"], 0, "Solve F=kx."],
    ],
  },
  {
    lesson: "math.m7.l6",
    title: "Application modeling problems",
    premise: "The same integration technique can answer area, volume, mass, or work questions only after the differential piece has been defined correctly. Modeling is the part that decides the integral.",
    idea: "Follow a repeatable sequence: draw a representative slice, name its position and thickness, derive the slice's contribution with units, determine valid bounds, and then integrate. For area use strip length times width; for volume use cross-sectional area times thickness; for mass use density times length; for work use force times displacement. If a geometry changes partway through, split the integral. After evaluating, compare the result to an easy bound or known formula. A large symbolic expression is not evidence of a correct model if its units or slice meaning are wrong.",
    worked: "A horizontal tank has a rectangular cross-section 2 m wide and holds water to depth 3 m. With water density 1000 kg/m³ and gravitational acceleration 9.8 m/s², pump water over the top rim. Let y be height above the bottom. A thin horizontal layer of tank length 4 m has volume 2·4 dy=8dy m³, weight 9800·8dy N, and lifting distance 3-y m. Work is ∫₀³ 78400(3-y)dy=78400(9/2)=352800 joules. The greater contribution near the bottom reflects its longer lift.",
    interpretation: "The layer model combines volume, weight, and travel distance. Changing the tank's shape would change the slice area even if the same integral technique remained applicable.",
    trap: "Do not assign every water layer the same lifting distance. Track dimensions at each step and state the chosen coordinate clearly.",
    practice: "A vertical cable 5 m long weighs 2 N per meter and hangs straight down from a ledge. Find the work to pull the entire cable to the ledge. Let x be distance below the ledge and model a short piece.",
    solution: "A piece of length dx at depth x weighs 2dx newtons and must travel x meters. Its work is 2x dx joules, so total W=∫₀⁵ 2x dx=[x²]₀⁵=25 joules. A uniform 10 N force times 5 m would be wrong because the hanging weight falls as the cable is retrieved.",
    checks: [
      ["What is the first step in a slicing model?", ["Define one representative piece and its units", "Differentiate the final answer", "Guess an antiderivative"], 0, "The piece determines the integrand."],
      ["Why can a pumping-work integral need variable distance?", ["Layers start at different heights", "Gravity changes with each centimeter", "Water is weightless at the top"], 0, "Each layer travels a different distance."],
      ["What units should the work integrand yield after multiplying by dx?", ["Joules", "Kilograms", "Meters per second"], 0, "Force times displacement is energy."],
    ],
  },
];
