import type { MathLecture } from "./lectures";

/** The first integral unit builds accumulation from sums, then earns the FTC. */
export const MATH_INTEGRAL_LECTURES: MathLecture[] = [
  {
    lesson: "math.m6.l1",
    title: "Antiderivatives and initial conditions",
    premise: "An antiderivative reverses differentiation on an interval. Since derivatives erase constants, the answer to an indefinite integral is a family of functions until an initial condition chooses one member.",
    idea: "If F'=f throughout an interval, then every F+C also differentiates to f. The reverse power rule gives ∫x^n dx=x^(n+1)/(n+1)+C for n≠-1; the exceptional case is ∫1/x dx=ln|x|+C on an interval avoiding zero. Integrate sums term by term, but keep domains and the constant of integration. An initial value F(a)=b gives an equation for C. When the domain has disconnected pieces, constants may be chosen separately on each piece; a formula cannot silently cross a point where f is undefined.",
    worked: "Find F if F'(x)=6x²-4 and F(1)=5. Integrate: F(x)=2x³-4x+C. Substituting x=1 gives 2-4+C=5, so C=7. Differentiation checks F'=6x²-4, and substitution checks F(1)=5.",
    interpretation: "The derivative determines how F changes, while the initial value fixes its vertical position. Neither alone supplies the complete solution.",
    trap: "Do not use the reverse power formula at n=-1; it would divide by zero. Do not omit +C from an indefinite integral, or write ln x for a domain that includes negative x.",
    practice: "Find G on x>0 if G'(x)=3x²+2/x and G(1)=4. Differentiate your answer to verify it.",
    solution: "G(x)=x³+2ln x+C on x>0. Since G(1)=1+C=4, C=3, so G=x³+2ln x+3. Its derivative is 3x²+2/x and its value at 1 is 4.",
    checks: [
      ["Why does an indefinite integral include +C?", ["Constants vanish under differentiation", "The integrand is constant", "Integrals are always positive"], 0, "All vertical translates have the same derivative."],
      ["What is an antiderivative of 1/x on x>0?", ["ln x", "x²/2", "1/x²"], 0, "The reverse power rule excludes exponent -1."],
      ["What does F(a)=b determine?", ["The integration constant", "The derivative formula", "The entire domain automatically"], 0, "Substitute the initial point into the general family."],
    ],
  },
  {
    lesson: "math.m6.l2",
    title: "Riemann sums and signed area",
    premise: "A definite integral is the limit of increasingly fine signed sums. Rectangles explain why it measures accumulation even when the graph lies below the axis.",
    idea: "Partition [a,b] into n pieces, choose one sample point xᵢ* in each, and sum f(xᵢ*)Δxᵢ. If these sums approach the same limit as the largest width shrinks to zero, that limit is ∫ₐᵇ f(x)dx. For equal widths, Δx=(b-a)/n. Right endpoints are a+iΔx, while left endpoints are a+(i-1)Δx. Height carries the sign of f; a negative contribution subtracts from the integral. Geometric area is nonnegative and generally requires integrating |f| or splitting at zeros.",
    worked: "Compute ∫₀¹ x dx from right-endpoint sums. Width is 1/n and the ith endpoint is i/n, so Sₙ=Σᵢ₌₁ⁿ(i/n)(1/n)=(1/n²)·n(n+1)/2=(n+1)/(2n). Taking n→∞ gives 1/2. On [-1,0], ∫x dx=-1/2 even though the triangular region has geometric area 1/2.",
    interpretation: "The sum has units of height times horizontal width. In a velocity graph, that is signed displacement, which differs from total distance when velocity becomes negative.",
    trap: "Do not confuse the finite sum Sₙ with its limit, or drop the sign below the axis. A Riemann sum needs widths as well as sampled heights.",
    practice: "Use equal-width right-endpoint sums to compute ∫₀² x dx. Then find the signed integral ∫₋₂⁰ x dx and the geometric area between y=x and the axis on [-2,2].",
    solution: "On [0,2], Δx=2/n and xᵢ=2i/n, so Sₙ=(4/n²)Σi=2(n+1)/n→2. Symmetry or an analogous sum gives ∫₋₂⁰ x dx=-2. The signed integral over [-2,2] is zero, but geometric area is 2+2=4.",
    checks: [
      ["What happens to the largest partition width in a Riemann integral?", ["It approaches zero", "It approaches infinity", "It stays fixed"], 0, "Refine the partition to take the limit."],
      ["Can a definite integral be negative?", ["Yes, it measures signed accumulation", "No", "Only if the interval is empty"], 0, "Values below the axis contribute negatively."],
      ["What extra factor multiplies each sampled height?", ["Its subinterval width", "The derivative", "The number of roots"], 0, "A rectangle contributes height times width."],
    ],
  },
  {
    lesson: "math.m6.l3",
    title: "Definite integrals and their properties",
    premise: "The bounds of a definite integral matter: reversing them changes sign, splitting at an interior point preserves the total, and symmetry can simplify a calculation.",
    idea: "From the sum definition or the fundamental theorem, ∫ₐᵇ f=-∫ᵇₐ f and ∫ₐᵃ f=0. If c lies between a and b, ∫ₐᵇ f=∫ₐᶜ f+∫𝒸ᵇ f. Linearity gives ∫(αf+βg)=α∫f+β∫g. If f≤g on an interval with a≤b, then ∫f≤∫g. For an odd integrable function, the signed integral on [-a,a] is zero; for an even function it is twice the integral on [0,a]. These properties simplify integrals but do not turn them into nonnegative area automatically.",
    worked: "Let f(x)=x²+x on [-2,2]. The x term is odd, so its integral cancels. The x² term is even, so ∫₋₂² f=2∫₀² x²dx=2·(8/3)=16/3. This does not imply f itself is even; linearity allows its even and odd parts to be handled separately.",
    interpretation: "Properties can reveal a result without computing a new antiderivative, but every sign and bound must stay attached to its expression.",
    trap: "Do not conclude that ∫₋ₐᵃ f=0 merely because the interval is symmetric; the function must be odd. Reversing bounds does not preserve the sign.",
    practice: "Given ∫₀² f=3 and ∫₂⁵ f=-1, find ∫₅⁰ f and ∫₀⁵(2f+1)dx.",
    solution: "Add the adjacent pieces: ∫₀⁵ f=3+(-1)=2. Reversing bounds gives ∫₅⁰ f=-2. Linearity yields ∫₀⁵(2f+1)=2·2+∫₀⁵1dx=4+5=9.",
    checks: [
      ["What is ∫ᵇₐ f if ∫ₐᵇ f=7?", ["-7", "7", "0"], 0, "Reversing the direction changes sign."],
      ["When does ∫₋ₐᵃ f cancel to zero by symmetry?", ["When f is odd", "When f is even", "Always"], 0, "Opposite inputs have opposite values."],
      ["What is ∫ₐᵃ f?", ["0", "f(a)", "1"], 0, "There is no interval width to accumulate."],
    ],
  },
  {
    lesson: "math.m6.l4",
    title: "The fundamental theorem of calculus, part I",
    premise: "Accumulation creates an antiderivative: under continuity, the rate at which an integral grows with its upper bound equals the integrand at the new boundary.",
    idea: "Define A(x)=∫ₐˣ f(t)dt for continuous f. Over a small increment h, A(x+h)-A(x)=∫ₓˣ⁺ʰ f(t)dt. Dividing by h gives an average of f over the short interval; continuity makes that average approach f(x). Therefore A'(x)=f(x). The dummy variable t is only the integration variable; x controls the upper limit. If the upper bound is g(x), the chain rule gives d/dx ∫ₐᵍ⁽ˣ⁾ f(t)dt=f(g(x))g'(x). A changing lower bound contributes a minus sign.",
    worked: "For A(x)=∫₁ˣ(t²+1)dt, A'(x)=x²+1 without evaluating the integral. For B(x)=∫₀ˣ² cos(t)dt, B'(x)=cos(x²)·2x. For C(x)=∫ₓ³ sin(t)dt, C'(x)=-sin x.",
    interpretation: "The first theorem links total accumulation to the instantaneous contribution at its moving edge. It applies to signed accumulation as well as physical area.",
    trap: "Do not replace the dummy variable t with x inside the integral before differentiating, and do not omit the chain factor or lower-limit minus sign.",
    practice: "Differentiate H(x)=∫ₓ²ˣ³ sqrt(1+t²)dt without finding an antiderivative. State where your result is valid.",
    solution: "Split H as ∫₀ˣ³ f(t)dt-∫₀ˣ² f(t)dt with f(t)=sqrt(1+t²). Then H'(x)=3x²sqrt(1+x⁶)-2xsqrt(1+x⁴). The integrand is continuous for all real t, so this formula holds for all real x.",
    checks: [
      ["If A(x)=∫₀ˣ f(t)dt and f is continuous, what is A'(x)?", ["f(x)", "∫₀ˣ f'(t)dt", "x f(x)"], 0, "A small extension adds roughly f(x) times its width."],
      ["What is d/dx ∫₀ˣ² f(t)dt?", ["2x f(x²)", "f(x²)", "2f(x)"], 0, "Use the chain rule on the upper bound."],
      ["What sign comes from a moving lower bound?", ["A minus sign", "A plus sign always", "No contribution"], 0, "Increasing the lower bound removes accumulation."],
    ],
  },
  {
    lesson: "math.m6.l5",
    title: "The fundamental theorem of calculus, part II",
    premise: "Once an antiderivative F of a continuous f is known, a definite integral is the net change F(b)-F(a). This evaluates accumulation without repeating a Riemann-sum limit.",
    idea: "For continuous f on [a,b], the first theorem constructs an accumulation function A with A'=f. Any other antiderivative F differs from A by a constant, so ∫ₐᵇ f(x)dx=F(b)-F(a). The answer is a number with units of f times x; the constant in F cancels. This theorem evaluates signed integrals. If the graph crosses the axis and the question asks geometric area, split at roots and take positive contributions separately. If the integrand or interval violates the hypotheses, first investigate whether an improper integral is required.",
    worked: "Evaluate ∫₁³(2x+1)dx. An antiderivative is F=x²+x. Thus F(3)-F(1)=(9+3)-(1+1)=10. For ∫₋₁¹ x dx, F=x²/2 gives 1/2-1/2=0, although each triangular half has nonzero geometric area.",
    interpretation: "Part I differentiates an accumulation function; Part II evaluates its accumulated change. They are complementary directions of one connection, not interchangeable formulas.",
    trap: "Do not report F(b) alone, and do not confuse signed integral with total area. A candidate antiderivative must actually differentiate back to the integrand on the interval.",
    practice: "Evaluate ∫₀²(3x²-2x)dx. Then find the total geometric area between this graph and the x-axis on [0,2].",
    solution: "An antiderivative is x³-x². The signed integral is (8-4)-0=4. The integrand x(3x-2) is negative on (0,2/3) and positive on (2/3,2). At x=2/3, F=8/27-4/9=-4/27. The negative piece has area 4/27 and the positive piece has area 4-(-4/27)=112/27, so total area is 116/27.",
    checks: [
      ["What evaluates ∫ₐᵇ f when F'=f?", ["F(b)-F(a)", "F(b)+F(a)", "f(b)-f(a)"], 0, "The integral is the antiderivative's net change."],
      ["Does +C affect a definite integral?", ["No, it cancels at the bounds", "Yes, twice", "Only if a=0"], 0, "Subtract the same constant at both endpoints."],
      ["How is geometric area handled when f changes sign?", ["Split at zeros and add positive areas", "Use the signed total unchanged", "Ignore the negative interval"], 0, "Area does not cancel below the axis."],
    ],
  },
  {
    lesson: "math.m6.l6",
    title: "Substitution and change of variables",
    premise: "Substitution reverses the chain rule. It simplifies an integral when one part of the expression is the derivative of another part, up to a constant factor.",
    idea: "If u=g(x), then du=g'(x)dx and ∫f(g(x))g'(x)dx=∫f(u)du. For a definite integral, change both bounds: x=a maps to u=g(a), and x=b maps to u=g(b). Alternatively, return to x before evaluating; never mix u-bounds with an x-antiderivative. A successful substitution accounts for every factor of x and dx. If the derivative of the inner expression is absent, substitution may not apply directly. The resulting antiderivative should be checked by differentiation.",
    worked: "Evaluate ∫₀¹ 2x(1+x²)³dx. Put u=1+x², so du=2x dx; the bounds become u=1 and u=2. The integral is ∫₁²u³du=[u⁴/4]₁²=(16-1)/4=15/4. Keeping the original bounds 0 and 1 after switching to u would give a different, wrong result.",
    interpretation: "The new variable relabels the same accumulation. Changing bounds preserves the represented region and avoids an extra back-substitution step.",
    trap: "Do not declare du=dx or forget the inner derivative. For definite integrals, changing the integrand without changing the bounds breaks the calculation.",
    practice: "Compute ∫₀^(π/2) sin x cos x dx using u=sin x, including the transformed bounds. Check by using a trigonometric identity or a second method.",
    solution: "With u=sin x, du=cos x dx, and bounds u=0 to u=1, the integral is ∫₀¹u du=1/2. Alternatively, sin x cos x=(1/2)sin(2x), whose integral over [0,π/2] is also 1/2.",
    checks: [
      ["What familiar differentiation rule does substitution reverse?", ["The chain rule", "The product rule only", "The quotient rule only"], 0, "Match an inner function with its derivative."],
      ["If u=g(x), what happens to definite-integral bounds?", ["Map them through g", "Keep the original numbers", "Delete them"], 0, "New coordinates require new limits."],
      ["How can an indefinite substitution result be checked?", ["Differentiate it", "Only inspect the sign", "Square it"], 0, "Differentiation should recover the original integrand."],
    ],
  },
  {
    lesson: "math.m6.l7",
    title: "Accumulation functions and motion",
    premise: "Integrating a rate gives net change. In motion, velocity accumulates to displacement, while speed accumulates to total distance; direction makes the two different.",
    idea: "If position is s(t) and velocity v=s', then s(b)-s(a)=∫ₐᵇ v(t)dt. Total distance traveled is ∫ₐᵇ |v(t)|dt, so split at times when velocity changes sign. If acceleration a=v', then v(b)-v(a)=∫ₐᵇ a(t)dt; an initial velocity is needed to recover a specific velocity function. More generally, a rate measured in quantity per time integrates to quantity. Accumulation may decrease where the rate is negative. A graph of A(t)=∫ₐᵗ r(u)du has slope r(t), connecting this lesson to the first fundamental theorem.",
    worked: "Let v(t)=t-2 meters per second on 0≤t≤4. Displacement is ∫₀⁴(t-2)dt=[t²/2-2t]₀⁴=0. The object moves backward for two seconds and forward for two. Distance is -∫₀²(t-2)dt+∫₂⁴(t-2)dt=2+2=4 meters.",
    interpretation: "Zero displacement does not mean the object stood still. Signed contributions canceled while the path length remained four meters.",
    trap: "Do not use the magnitude of the final displacement as total distance. If integrating acceleration, remember the initial velocity constant.",
    practice: "A particle starts at position 5 meters and has velocity v(t)=3t²-6t meters per second for 0≤t≤3. Find its final position and total distance traveled.",
    solution: "An antiderivative of v is t³-3t². The displacement from 0 to 3 is 27-27=0, so final position remains 5 meters. Velocity is 3t(t-2), negative on (0,2) and positive on (2,3). The displacement over [0,2] is 8-12=-4 meters; over [2,3] it is +4 meters. Total distance is 4+4=8 meters.",
    checks: [
      ["What does ∫v(t)dt over a time interval give?", ["Signed displacement", "Always total distance", "Acceleration"], 0, "Velocity carries direction."],
      ["How is total distance computed from velocity?", ["Integrate |v|", "Take |∫v| always", "Integrate acceleration"], 0, "Add path lengths across direction changes."],
      ["What extra datum recovers velocity from acceleration?", ["An initial velocity", "Only the final time", "A graph scale"], 0, "Integration leaves a constant."],
    ],
  },
  {
    lesson: "math.m6.l8",
    title: "Integral interpretation problems",
    premise: "An integral is a statement about what is being accumulated. Before evaluating it, identify the rate, its units, the interval, and whether signed net change or a nonnegative total is wanted.",
    idea: "A continuous rate r(t) in units per hour contributes r(t)dt units over a short time and ∫ₐᵇ r(t)dt over an interval. If r changes sign, the integral is net change; integrating |r| measures total variation. The mean value of an integrable quantity f on [a,b] is (1/(b-a))∫ₐᵇ f(x)dx, which has the same units as f. An initial amount Q(a) is needed to find a final amount: Q(b)=Q(a)+∫ₐᵇ r. Translate the conclusion back to the scenario and check physical constraints, such as nonnegative inventory.",
    worked: "A tank begins with 100 liters. Its net inflow is r(t)=10-2t liters per hour for 0≤t≤8. Integrate: Q(8)=100+[10t-t²]₀⁸=100+80-64=116 liters. The rate becomes negative after five hours, so the final amount is not the peak amount. At t=5 the added amount is 50-25=25 liters, giving a peak of 125 liters on this interval.",
    interpretation: "The sign of r explains rising or falling inventory. The integral changes liters; it is not itself a flow rate.",
    trap: "Do not interpret a negative rate as a negative amount of material, or confuse an average rate with total accumulation. Include the initial amount when asked for a final stock.",
    practice: "A quantity starts at 12 units and changes at rate r(t)=4-t units per minute for 0≤t≤6. Find its final amount, its maximum amount on the interval, and the average rate over the interval.",
    solution: "Q(t)=12+4t-t²/2. At t=6, Q=12+24-18=18 units. Since r>0 until t=4 and r<0 after, the maximum occurs at t=4: Q(4)=12+16-8=20 units. The net change is 6 units over 6 minutes, so average rate is 1 unit per minute.",
    checks: [
      ["What are the units of ∫r(t)dt when r is liters/hour?", ["Liters", "Liters/hour", "Hours/liter"], 0, "Time cancels the denominator."],
      ["How do you find a final amount from a rate?", ["Initial amount plus net integral", "Only the final rate", "Only the integral's absolute value"], 0, "Accumulation changes an initial stock."],
      ["What does (1/(b-a))∫ₐᵇ f represent?", ["The average value of f", "The total change in f", "Its maximum"], 0, "Divide total accumulation by interval length."],
    ],
  },
];
