import type { MathLecture } from "./lectures";

/** Spectral methods and inverse problems, from compact operators to literature. */
export const MATH_INVERSE_SPECTRAL: MathLecture[] = [
  {
    lesson: "math.m35.l1", title: "Compact self-adjoint operators",
    premise: "Compact self-adjoint operators admit a discrete spectral decomposition that resembles symmetric matrices, with zero as the only possible accumulation point.",
    idea: "For compact self-adjoint T on Hilbert H, nonzero spectrum consists of real eigenvalues of finite multiplicity. Eigenvectors for distinct eigenvalues are orthogonal, and the closed span of nonzero eigenspaces is the orthogonal complement of ker T. Nonzero eigenvalues can accumulate only at zero. For any x, T x is reconstructed from eigencomponents as Σλ_n⟨x,e_n⟩e_n, with convergence in H. A compact operator can fail to have a bounded inverse on an infinite-dimensional range because λ_n may approach zero. This is the seed of ill-posed inverse problems: small observed perturbations along high-index modes become large after division by λ_n.",
    worked: "On ℓ² let T e_n=(1/n)e_n. It is compact, positive, and self-adjoint. Given data y_n=1/n², formal inverse gives x_n=n y_n=1/n, which lies in ℓ². But perturb data by δ e_N with tiny δ; inverse perturbation is Nδ e_N, arbitrarily amplified as N increases.",
    interpretation: "Spectral decay explains why an inverse can be sensitive even when forward mapping is smooth and bounded.",
    trap: "Do not claim a compact infinite-dimensional inverse is bounded solely because all displayed eigenvalues are nonzero.",
    practice: "For T e_n=(1/n²)e_n, what amplification does inverse apply to an error δe_N?",
    solution: "It divides the Nth component by 1/N², producing N²δ e_N. Thus high-frequency error is amplified quadratically in N, showing severe instability for large N.",
    checks: [["Where can nonzero compact self-adjoint eigenvalues accumulate?", ["Only at zero", "Any nonzero point", "At infinity only"], 0, "Compactness constrains the spectrum."], ["Why can inversion amplify noise?", ["Division by small eigenvalues", "Multiplication by zero", "Orthogonality fails"], 0, "The inverse scale grows as 1/|λ_n|."], ["Are distinct-eigenvalue eigenvectors orthogonal?", ["Yes", "No", "Only for positive T"], 0, "Self-adjointness implies it."]],
  },
  {
    lesson: "math.m35.l2", title: "Inverse problems and ill-posedness",
    premise: "An inverse problem infers hidden causes from observed effects; existence, uniqueness, and stability can each fail separately.",
    idea: "Hadamard well-posedness asks that a solution exist, be unique, and depend continuously on observations. For y=Ax+noise, nontrivial ker A prevents uniqueness; data outside range A prevent exact existence; small singular values destroy stability. In a compact smoothing operator, singular values often approach zero, so inversion magnifies high-frequency noise. Different priors or regularizers select different solutions. Distinguish model error from measurement noise: an inaccurate forward operator cannot be repaired solely by reducing numerical tolerance. A defensible inverse claim reports what is identifiable under the data and assumptions, not just one fitted reconstruction.",
    worked: "A=diag(1,.001) maps x=(x₁,x₂) to y=(x₁,.001x₂). If the second measurement has additive error .01, naive inversion yields error .01/.001=10 in x₂. The forward map is perfectly defined, yet its inverse is highly sensitive.",
    interpretation: "Small singular values hide directions of the unknown from the instrument.",
    trap: "Do not call a plausible-looking reconstruction uniquely determined unless the null space and noise sensitivity are addressed.",
    practice: "For A=diag(1,.0001), how large is x₂ error from y₂ error .001 under direct inversion?",
    solution: "The inverse divides by .0001, so x₂ error is .001/.0001=10. A data error of one thousandth becomes a parameter error of ten in that direction.",
    checks: [["What are Hadamard's three well-posed properties?", ["Existence, uniqueness, stability", "Speed, color, and size", "Only invertibility"], 0, "Each can fail separately."], ["What does a nontrivial kernel threaten?", ["Uniqueness", "Only runtime", "Measurement units"], 0, "Multiple x can have the same observation."], ["What does a small singular value threaten?", ["Stability", "Matrix multiplication", "Domain definition"], 0, "Inverse noise is amplified."]],
  },
  {
    lesson: "math.m35.l3", title: "Regularization theory",
    premise: "Regularization trades exact data fit for a stable estimate, with a parameter that balances bias against noise amplification.",
    idea: "Tikhonov regularization solves min_x ||Ax-y||²+λ||Lx||² with λ>0; for L=I and finite-dimensional A, the solution is (AᵀA+λI)^{-1}Aᵀy. In singular-vector coordinates, each observed component is filtered by σ/(σ²+λ), limiting blow-up when σ is tiny. Larger λ increases bias but reduces variance; choosing λ by discrepancy principle, cross-validation, or other methods requires noise information and assumptions. Truncated SVD instead discards singular modes below a threshold. Convergence as noise tends to zero needs λ tending to zero at a compatible rate; fixed positive λ leaves regularization bias.",
    worked: "In scalar problem y=.01x+noise, Tikhonov with λ=.0001 estimates x=(.01/(.0001+.0001))y=50y. Direct inversion estimates 100y. Regularization halves noise amplification here but also underestimates a noiseless true x by factor one-half.",
    interpretation: "The method cannot create missing information; it chooses a controlled compromise.",
    trap: "Do not report a regularized estimate without λ, penalty operator, and a reason for choosing them.",
    practice: "For scalar A=2, y=6, λ=1, L=I, solve min_x(2x-6)²+x².",
    solution: "Differentiate: 2·2(2x-6)+2x=0, so 10x=24 and x=2.4. Direct unregularized fit gives x=3; regularization shrinks it toward zero.",
    checks: [["What does larger λ generally increase?", ["Bias and stability", "Exact data fit", "Noise amplification always"], 0, "It shrinks uncertain components."], ["What is the Tikhonov spectral filter?", ["σ/(σ²+λ)", "1/σ always", "σ²+λ"], 0, "It limits small-σ inversion."], ["Does fixed λ>0 remove all bias as noise vanishes?", ["No", "Yes", "Only if A is square"], 0, "The penalty remains active."]],
  },
  {
    lesson: "math.m35.l4", title: "Kernel methods and RKHS",
    premise: "A positive-definite kernel represents inner products in a possibly high-dimensional feature space without constructing features explicitly.",
    idea: "A kernel k is positive semidefinite when every finite Gram matrix K_ij=k(x_i,x_j) is positive semidefinite. An RKHS H has reproducing property f(x)=⟨f,k(x,·)⟩_H. The representer theorem says a regularized empirical-risk minimizer under suitable strictly increasing norm penalty lies in the span of training kernel sections, so f(x)=Σα_i k(x_i,x). Kernel ridge regression solves (K+nλI)α=y under a common normalized objective. Positive semidefiniteness and chosen λ control solvability; centering, feature scaling, and data leakage still matter. A kernel choice encodes inductive bias, and a good training Gram matrix does not guarantee out-of-sample performance.",
    worked: "For linear kernel k(x,z)=xz on real inputs x₁=1,x₂=2, Gram matrix is [[1,2],[2,4]], which is positive semidefinite but rank one. Adding nλI with λ>0 makes the kernel-ridge linear system invertible despite the original rank deficiency.",
    interpretation: "The RKHS connects function evaluation, geometry, and finite training-data computation.",
    trap: "Do not assume an arbitrary similarity score is a valid positive-semidefinite kernel.",
    practice: "Check whether K=[[1,2],[2,1]] can be a Gram matrix of a positive-definite kernel on two points.",
    solution: "Its eigenvalues are 3 and -1, so it is not positive semidefinite. Therefore no positive-semidefinite kernel can yield this exact Gram matrix on those two points.",
    checks: [["What must every kernel Gram matrix satisfy?", ["Positive semidefiniteness", "Positive entries only", "Full rank always"], 0, "Negative eigenvalues invalidate it."], ["Where does a representer solution lie?", ["Span of training kernel sections", "Only raw input space", "The null space always"], 0, "This makes the problem finite dimensional."], ["What is the reproducing identity?", ["f(x)=⟨f,k(x,·)⟩", "f(x)=k(x,x) always", "f is a probability"], 0, "Evaluation is an inner product."]],
  },
  {
    lesson: "math.m35.l5", title: "Spectral graph theory",
    premise: "A graph Laplacian turns connectivity and diffusion on a network into matrix eigenvalue questions.",
    idea: "For weighted undirected graph, L=D-W, with degree diagonal D and symmetric nonnegative edge-weight matrix W. Its quadratic form xᵀLx=(1/2)Σ_{i,j}w_ij(x_i-x_j)²≥0, so L is positive semidefinite. Constant vectors lie in ker L; the multiplicity of eigenvalue zero equals the number of connected components. On a connected graph, second-smallest eigenvalue λ₂ is positive and measures algebraic connectivity. Its eigenvector, the Fiedler vector, can guide cuts, though thresholding it is a heuristic relative to some combinatorial objectives. The normalized Laplacian handles degree variation differently. For directed graphs, these simple symmetric statements need modification.",
    worked: "For two vertices joined by weight one, L=[[1,-1],[-1,1]]. Eigenvector (1,1) has eigenvalue zero; (1,-1) has eigenvalue two. The graph is connected, consistent with exactly one zero eigenvalue.",
    interpretation: "Low eigenmodes vary slowly across edges, making them useful for clustering and diffusion.",
    trap: "Do not apply undirected symmetric Laplacian eigenvalue facts to an arbitrary directed adjacency matrix unchanged.",
    practice: "For three isolated vertices, what are the unnormalized Laplacian and zero-eigenvalue multiplicity?",
    solution: "There are no edges, so D=W=0 and L is the 3×3 zero matrix. Every vector is in its kernel; eigenvalue zero has multiplicity three, matching the three connected components.",
    checks: [["What does zero-eigenvalue multiplicity count for an undirected graph?", ["Connected components", "Edges", "Triangles"], 0, "Each component contributes a constant mode."], ["What is L=D-W?", ["Unnormalized graph Laplacian", "Adjacency inverse", "Covariance matrix"], 0, "It measures edge differences."], ["Is L positive semidefinite for nonnegative undirected weights?", ["Yes", "No", "Only on trees"], 0, "Its quadratic form is sum of squares."]],
  },
  {
    lesson: "math.m35.l6", title: "Low-rank recovery",
    premise: "Low-rank structure reduces degrees of freedom, but incomplete measurements recover it only under identifiability conditions.",
    idea: "A rank-r m×n matrix has roughly r(m+n-r) free parameters, far fewer than mn when r is small. Matrix completion observes selected entries and seeks a low-rank matrix consistent with them; recovery needs sampling and incoherence conditions so information is spread, not hidden in one unseen entry. Nuclear norm ||X||_* is sum of singular values and is a convex surrogate for rank, leading to min_X 1/2||P_Ω(X-Y)||_F²+λ||X||_*. Robust PCA separates a low-rank component from sparse corruptions under assumptions preventing overlap. Neither low rank nor a large number of measurements alone ensures uniqueness if the measurement operator misses a whole direction.",
    worked: "A 2×2 rank-one matrix X=[[1,2],[2,4]] has second row twice the first. If only entries X_11=1,X_12=2,X_21=2 are observed and exact rank one is assumed, X_22 must be 4. If instead an entire row is unobserved, many rank-one completions fit the same data.",
    interpretation: "Structure can fill gaps only when observations touch the unknown directions.",
    trap: "Do not promise exact matrix completion without checking sampling pattern, rank, noise, and incoherence.",
    practice: "Assume a nonzero rank-one 2×2 matrix has entries [[3,6],[5,?]]. Find the missing entry.",
    solution: "Rank one requires determinant zero: 3x-6·5=0, so x=10. This follows because second column is twice first, or second row is 5/3 times first.",
    checks: [["What convex surrogate commonly replaces rank?", ["Nuclear norm", "Entrywise maximum", "Matrix trace always"], 0, "It sums singular values."], ["Can an entirely unseen row be uniquely completed from rank one alone?", ["Not generally", "Always", "Only if square"], 0, "Its scale can be free."], ["What does incoherence broadly prevent?", ["Information concentrated in a few entries", "All noise", "Negative eigenvalues"], 0, "Sampling must see the structure."]],
  },
  {
    lesson: "math.m35.l7", title: "Random matrix intuition",
    premise: "Random matrix results provide baselines for spectral behavior in high-dimensional noise, but their scaling and assumptions matter.",
    idea: "For a symmetric matrix with independent centered off-diagonal entries of variance about 1/n under suitable moment assumptions, eigenvalues typically remain on an O(1) scale; a semicircle law describes their global empirical distribution in a Wigner setting. Sample covariance spectra behave differently and depend on aspect ratio dimension/sample count, with Marchenko–Pastur-type limits under standard assumptions. Large singular values may reflect true low-rank signal or random extremes; detectability depends on signal strength, noise model, and dimensional regime. Independence and identical scaling are modeling conditions, not guaranteed by any observed data matrix. Finite-size deviations and heavy tails can make asymptotic baselines inaccurate.",
    worked: "If an n×n random symmetric noise matrix uses unscaled entries of variance one, row magnitudes grow with n and eigenvalue scale is about sqrt(n), not O(1). Dividing entries by sqrt(n) makes entry variance 1/n and yields an O(1) spectral scale in the standard Wigner regime.",
    interpretation: "Normalization is part of every random-matrix theorem, not a cosmetic plotting choice.",
    trap: "Do not declare an observed top eigenvalue meaningful before comparing it with the correctly scaled noise baseline.",
    practice: "If raw independent noise entries have variance 9, what scale factor makes their variance 1/n?",
    solution: "Divide each entry by 3sqrt(n), since Var(entry/(3sqrt(n)))=9/(9n)=1/n. Symmetry and dependence requirements of a particular theorem must still be checked.",
    checks: [["What is typical entry variance in standard O(1)-spectrum Wigner scaling?", ["About 1/n", "About n", "Always zero"], 0, "It controls total row scale."], ["Does a large eigenvalue always prove signal?", ["No", "Yes", "Only with many samples"], 0, "Noise can produce extremes."], ["Do sample covariance and Wigner spectra have the same law?", ["No", "Yes", "Only for square matrices"], 0, "Their constructions differ."]],
  },
  {
    lesson: "math.m35.l8", title: "Reading current literature",
    premise: "An inverse-problems paper should be checked against its observation model, identifiability assumptions, error metric, and baselines.",
    idea: "Reconstruct the forward operator A, noise distribution, unknown class, and measured data before reading the headline reconstruction. Write the theorem with all quantifiers: uniform over which signals, high probability over which randomness, and error in which norm? Separate optimization error from statistical error and model misspecification. Reproduce a synthetic example with known ground truth, varying singular-value decay, noise level, and regularization parameter independently. Compare against a simple Tikhonov or truncated-SVD baseline at equal computational budget. Seek failure cases where the operator has a null space, the signal violates incoherence, or data are out of distribution. A reproducible negative result may reveal a missing theorem hypothesis or a deployment limit.",
    worked: "Suppose a method reports 1% reconstruction error on noiseless full-rank matrices but is marketed for incomplete measurements. The experiment does not test its claimed inverse setting. A sharper experiment removes a controlled subset of measurements, reports operator rank and singular spectrum, adds known noise, and compares recovered error to a regularized baseline.",
    interpretation: "Evidence must stress the source of difficulty the method claims to solve.",
    trap: "Do not compare different papers' percentage errors without matching normalization, observation operator, and test distribution.",
    practice: "List three details needed to reproduce an inverse reconstruction experiment beyond model code.",
    solution: "At minimum: the forward operator and its discretization; the noise model and random seed; the signal class or ground-truth generation; the regularization parameter-selection rule; and the error metric and baseline budget. Any three of these are essential depending on the claim.",
    checks: [["What must an inverse-problem report specify?", ["Forward operator and observation model", "Only model name", "Only a screenshot"], 0, "Identifiability depends on them."], ["Should optimization and statistical errors be separated?", ["Yes", "No", "Only for linear models"], 0, "They have different sources."], ["What makes a baseline comparison fair?", ["Matched data, metric, and computational budget", "A newer logo", "A different test distribution"], 0, "Otherwise gains are ambiguous."]],
  },
];
