import type { MathLecture } from "./lectures";

/** Graduate statistical learning theory with theorem scope and counterexamples. */
export const MATH_LEARNING_THEORY: MathLecture[] = [
  {
    lesson: "math.m33.l1", title: "Empirical risk minimization",
    premise: "Empirical risk minimization fits a predictor on observed examples; learning theory asks how that choice performs on fresh data.",
    idea: "For hypothesis h and loss ℓ, population risk R(h)=E[ℓ(h(X),Y)] under the deployment distribution. Empirical risk R_n(h)=(1/n)Σℓ(h(X_i),Y_i) on a sample. ERM chooses a minimizer of R_n over class H, possibly approximately. The excess risk R(h_hat)-inf_{h∈H}R(h) measures estimation quality within H; approximation error compares the best H-predictor to the best possible predictor. The simple decomposition R(h_hat)-R(h*) can be bounded via uniform deviations of R_n from R when these hold, but memorization makes empirical risk alone unreliable in rich classes. Samples must reflect the target distribution; covariate shift changes the question.",
    worked: "Suppose H contains two constant binary classifiers, always 0 and always 1. On n labels with 70% ones, zero-one empirical risk is .7 for always 0 and .3 for always 1, so ERM chooses always 1. Its population risk depends on the true future label proportion, not on the training proportion alone.",
    interpretation: "Training optimization and generalization are distinct steps in a learning claim.",
    trap: "Do not call zero training error a population guarantee without class-capacity and sampling assumptions.",
    practice: "A sample has 8 positives and 2 negatives. Find ERM among constant 0 and constant 1 classifiers under zero-one loss.",
    solution: "Always 0 makes 8 errors in 10 cases, risk .8. Always 1 makes 2 errors, risk .2, so ERM chooses always 1. This calculation says nothing exact about its future error without a population model.",
    checks: [["What does empirical risk average over?", ["Observed sample", "All future data exactly", "Only model parameters"], 0, "Population risk uses the distribution."], ["Can training error alone certify generalization?", ["No", "Yes", "Only for a large network"], 0, "Capacity and sampling matter."], ["What is approximation error about?", ["Limits of the chosen hypothesis class", "Only numerical optimizer failure", "The number of epochs"], 0, "It compares best-in-class with a broader optimum."]],
  },
  {
    lesson: "math.m33.l2", title: "Uniform convergence",
    premise: "A uniform risk bound controls every candidate model in a class, including the one selected after looking at training data.",
    idea: "Pointwise concentration for one fixed h is not enough for a data-selected h_hat. If sup_{h∈H}|R_n(h)-R(h)|≤ε, then ERM has excess risk at most 2ε relative to the best H model, assuming minimizers exist. For a finite class of size M and bounded [0,1] losses with i.i.d. samples, Hoeffding plus union bound gives probability at most 2M exp(-2nε²) that the supremum exceeds ε. Solve for ε≈sqrt(log(2M/δ)/(2n)). An infinite H needs a complexity measure or covering argument; merely saying 'uniform convergence' without capacity control is incomplete.",
    worked: "For M=10 and n=100 with δ=.05, the finite-class bound yields ε=sqrt(log(400)/(200))≈.173. The derived ERM excess-risk bound is about .346 with probability at least .95. It is conservative and applies to the specified bounded-loss i.i.d. setup.",
    interpretation: "The logarithm of the number of candidate models appears because the bound protects against selection among them.",
    trap: "Do not apply a one-model confidence interval to the winning model after trying many models on the same data.",
    practice: "If a uniform event gives |R_n(h)-R(h)|≤.1 for every h∈H, what excess-risk bound follows for exact ERM?",
    solution: "Let h* minimize population risk in H. Then R(h_hat)≤R_n(h_hat)+.1≤R_n(h*)+.1≤R(h*)+.2. Thus excess risk is at most .2 on that uniform event.",
    checks: [["Why does a data-selected model need uniform control?", ["It depends on the sample", "Its parameters are fixed in advance", "It is always optimal"], 0, "Selection invalidates a fixed-model shortcut."], ["What ERM excess-risk factor follows from uniform ε deviation?", ["2ε", "ε² always", "No bound"], 0, "Two deviations appear."], ["What does the finite-class union bound involve?", ["log class size in the solved ε bound", "Only input dimension", "No confidence parameter"], 0, "It covers all candidates."]],
  },
  {
    lesson: "math.m33.l3", title: "VC dimension and capacity",
    premise: "VC dimension measures the largest number of points a binary hypothesis class can label in every possible way.",
    idea: "A set of m points is shattered by H if all 2^m binary labelings are realized by members of H. VCdim(H) is the largest such m, or infinity. Threshold classifiers h_t(x)=1{x≥t} on the real line have VC dimension one: one point can receive either label, but on two ordered points the pattern 1 then 0 cannot be realized. Intervals on the line have VC dimension two. Finite VC dimension supports distribution-free uniform convergence for zero-one loss with i.i.d. data, with sample complexity scaling roughly with (d log(n/d)+log(1/δ))/ε² in a standard uniform-bound form. Constants and sharper formulations vary. A low VC dimension does not ensure low approximation error.",
    worked: "Take two points x₁<x₂. A threshold h_t=1{x≥t} realizes labels 00, 01, and 11 as t moves, but never 10. Thus no pair is shattered. A single point can be labeled 0 or 1, so VC dimension is exactly one.",
    interpretation: "Capacity is combinatorial flexibility, not the parameter count alone.",
    trap: "Do not conclude a class shatters m points merely because it realizes many labels on one particular training set; it needs all 2^m patterns on some set.",
    practice: "Why can a class of all intervals [a,b] on R shatter two points x₁<x₂?",
    solution: "Choose an interval containing neither point for 00, one around x₁ for 10, one around x₂ for 01, and one covering both for 11. All four labelings are realized. Three ordered points cannot realize 101 with a single interval, so VC dimension is two.",
    checks: [["What does shattering require?", ["All binary labelings on a chosen set", "One labeling", "Only alternating patterns"], 0, "There are 2^m patterns for m points."], ["What is VC dimension of thresholds on R?", ["One", "Two", "Infinite"], 0, "They cannot realize 10 on two ordered points."], ["Does low capacity guarantee small approximation error?", ["No", "Yes", "Only with zero-one loss"], 0, "The class may be too restrictive."]],
  },
  {
    lesson: "math.m33.l4", title: "Rademacher complexity",
    premise: "Rademacher complexity measures how well a function class can align with random signs on a sample.",
    idea: "For a fixed sample x₁,...,x_n and class F of real-valued functions, empirical Rademacher complexity is E_σ[sup_{f∈F}(1/n)Σσ_i f(x_i)], where independent σ_i are equally likely ±1. A class that can fit arbitrary random signs has high complexity; a constrained class has lower complexity. Symmetrization relates expected uniform generalization deviation to Rademacher complexity under i.i.d. sampling. Contraction inequalities transfer bounds through Lipschitz losses under their conditions. Data-dependent empirical complexity can be tighter than counting every possible function, but it is still a bound, not the actual test error. Norm constraints and feature scales determine rates for linear predictors.",
    worked: "If F contains only the zero function, the supremum random sum is zero for every sign vector, so complexity is zero. If F contains all functions mapping n distinct sample points independently to ±1, choose f(x_i)=σ_i and the supremum sum is n/n=1 for every sign vector, so complexity is one.",
    interpretation: "The random-label thought experiment directly probes a class's memorization ability on the sample.",
    trap: "Do not compare complexity numbers across datasets with different feature scaling without accounting for the function class and normalization.",
    practice: "For F={f_a(x)=a: a∈[-1,1]}, derive the empirical Rademacher expression on any n-point sample.",
    solution: "The supremum over a of (a/n)Σσ_i is |Σσ_i|/n. Therefore complexity is E|Σσ_i|/n, of order 1/sqrt(n), not one. A constant predictor cannot independently fit each random sign.",
    checks: [["What random variables define Rademacher complexity?", ["Independent fair signs", "Gaussian inputs only", "Future labels"], 0, "They test alignment with noise."], ["Can the zero-only class fit random signs?", ["No; complexity zero", "Yes; complexity one", "Only for odd n"], 0, "Its output is fixed."], ["Is empirical complexity identical to test error?", ["No", "Yes", "Only for linear classes"], 0, "It is a capacity measure for a bound."]],
  },
  {
    lesson: "math.m33.l5", title: "PAC-Bayesian bounds",
    premise: "PAC-Bayes bounds compare a data-dependent distribution over predictors with a prior chosen before seeing the training sample.",
    idea: "Choose a prior P over hypotheses independently of the sample and a posterior Q, which may depend on data. A common PAC-Bayes form bounds a divergence between empirical and population Gibbs risks by roughly [KL(Q||P)+log(confidence terms)]/n for bounded loss and i.i.d. sampling. Exact constants and divergence forms depend on the theorem. Gibbs risk samples h from Q to predict; a bound on that randomized predictor is not automatically the same as a majority-vote or posterior-mean predictor bound. The KL penalty charges how far Q moves from P; a data-dependent prior needs a separate valid construction or held-out data. Optimizing Q trades empirical fit against complexity.",
    worked: "If Q=P, KL(Q||P)=0, so the complexity penalty is small but the predictors may fit poorly. If Q concentrates all mass on a rare hypothesis with prior mass 10^{-6}, its KL can be about log(10^6), which increases the bound even if training error falls. The numeric balance depends on n.",
    interpretation: "A posterior's data-driven specialization is explicitly paid for by divergence from a pre-data prior.",
    trap: "Do not set the prior after inspecting the same training labels and then claim a standard sample-independent-prior theorem unchanged.",
    practice: "For a point-mass Q on h with P(h)=.01, compute KL(Q||P) in natural logs.",
    solution: "Only h has Q-mass one, so KL(Q||P)=1·log(1/.01)=log(100)≈4.605. This is the complexity cost of concentrating on h under that prior.",
    checks: [["When is a standard PAC-Bayes prior selected?", ["Before the training sample", "After reading all labels freely", "Only after test data"], 0, "Independence is part of the proof."], ["What does KL(Q||P) charge?", ["Posterior departure from prior", "Raw sample count", "Only model runtime"], 0, "It is the complexity term."], ["Is Gibbs risk automatically majority-vote risk?", ["No", "Yes", "Only for binary labels"], 0, "Randomized and deterministic predictors differ."]],
  },
  {
    lesson: "math.m33.l6", title: "Stability and generalization",
    premise: "An algorithm may generalize because replacing one training example changes its output only slightly.",
    idea: "Uniform stability for loss ℓ says datasets S,S' differing in one example produce models A(S),A(S') with |ℓ(A(S),z)-ℓ(A(S'),z)|≤β for every test point z. Under suitable symmetry and boundedness, expected generalization gap is controlled by β. Strongly convex regularized ERM can have β of order 1/n under Lipschitz and curvature assumptions. A high-capacity hypothesis class can still be learned stably by a restrictive algorithm; conversely an unstable algorithm may overfit even within a compact class. Differential privacy is related to stability but supplies a distinct distributional guarantee. Stability bounds depend on the actual training procedure, not merely its final architecture.",
    worked: "Estimate a mean by A(S)=sample average of n numbers in [0,1]. Replacing one observation changes A(S) by at most 1/n. If evaluation loss is 1-Lipschitz in the predicted mean, loss changes by at most 1/n, so this procedure has a simple uniform-stability bound.",
    interpretation: "The example measures sensitivity to one data point, which is a different perspective from counting all models.",
    trap: "Do not cite a stability guarantee for an optimizer whose initialization, early stopping, or data-order randomness is outside the theorem's assumptions.",
    practice: "For n=50 bounded observations in [0,1], how much can the sample mean change when one value is replaced?",
    solution: "At most 1/50=.02 because only one summand changes and its difference is at most one. For a 2-Lipschitz loss in the predicted mean, the corresponding loss change is at most .04.",
    checks: [["What perturbation defines one-example stability?", ["Replace one training observation", "Change every observation", "Change only a test label"], 0, "It probes algorithm sensitivity."], ["Can stable learning occur with a rich hypothesis class?", ["Yes", "No", "Only with linear models"], 0, "The algorithm can constrain selection."], ["What is the mean estimator sensitivity for n bounded [0,1] samples?", ["At most 1/n", "At most n", "Always zero"], 0, "One term changes by at most one."]],
  },
  {
    lesson: "math.m33.l7", title: "Minimax rates",
    premise: "A minimax rate describes the best worst-case estimation error achievable over a specified class of data-generating processes.",
    idea: "For model class P, parameter θ(P), loss L, and estimator θ_hat, minimax risk is inf_{θ_hat} sup_{P∈P} E_P[L(θ_hat,θ(P))]. An upper bound constructs an estimator and analyzes its worst-case risk. A lower bound shows every estimator fails by at least some amount, often via two-point testing, Fano's inequality, or Assouad's lemma. Matching upper and lower orders identify a rate, while constants and adaptation may remain open. The rate depends on smoothness, dimension, noise, loss, and observation model. A pointwise easy distribution does not refute a worst-case lower bound. A parametric mean under squared error often has n^{-1} risk, while nonparametric rates can be slower.",
    worked: "For n i.i.d. N(μ,σ²) observations with known σ and squared error, sample mean has risk E[(average-μ)²]=σ²/n for every μ. This gives minimax upper bound σ²/n over μ∈R. A matching lower bound follows from normal-location information arguments; the sample mean is minimax in this model.",
    interpretation: "An estimator is rate-optimal only relative to a clearly named model class and loss.",
    trap: "Do not use a worst-case minimax claim as a prediction for one favorable dataset.",
    practice: "If an estimator has uniform squared-error risk at most 4/n and a lower bound for all estimators is c/n with c>0, what rate is established?",
    solution: "The minimax risk lies between c/n and 4/n, so it is of order 1/n. The exact constant is not determined unless sharper bounds match.",
    checks: [["What are the two sides of a minimax-rate proof?", ["Estimator upper bound and universal lower bound", "Only a simulation", "Only one easy example"], 0, "Both are needed to identify optimal order."], ["Does minimax risk depend on the loss?", ["Yes", "No", "Only on n"], 0, "Squared and absolute losses differ."], ["What does sup over P represent?", ["Worst case within the named model class", "Best training run", "Average over all imaginable worlds"], 0, "The class defines the claim."]],
  },
  {
    lesson: "math.m33.l8", title: "Open questions in learning theory",
    premise: "A research question in learning theory needs a precise model, a gap between known bounds, and a plausible route to either proof or counterexample.",
    idea: "Begin with a theorem and list its sampling, loss, architecture, algorithm, and confidence assumptions. Search for a mismatch between practice and theory, but reduce it to a narrow mathematical statement. Derive a baseline upper bound and a simple lower bound on a restricted case; if they coincide there, test which assumption makes the full case harder. Construct distributions with rare events, dependence, or symmetry to probe necessity of hypotheses. Compare rates using the same loss, same data class, and same oracle budget. Reproduce an existing proof lemma before proposing a new one. Record failed conjectures and counterexamples; they sharpen the final question rather than invalidating the research process.",
    worked: "Suppose someone claims low empirical risk guarantees low true risk for every measurable classifier. A classifier can memorize n sampled points with zero loss and predict incorrectly elsewhere under a continuous distribution. This counterexample shows that unrestricted hypothesis classes require some capacity or algorithmic control; the original claim must add assumptions.",
    interpretation: "Strong research starts by finding exactly where a plausible universal claim fails.",
    trap: "Do not call an empirical comparison of two architectures a theorem about all data distributions.",
    practice: "Rewrite 'my network generalizes well' as one testable mathematical question.",
    solution: "For example: under i.i.d. samples from a named distribution class, bounded loss, and a specified training algorithm with fixed regularization, can expected population minus empirical risk be bounded by C/sqrt(n) uniformly in sample size? This names object, assumptions, metric, and rate, though proving it remains separate work.",
    checks: [["What makes a learning-theory question mathematical?", ["Named model, assumptions, metric, and quantifiers", "An attractive plot only", "A model name"], 0, "The claim must be falsifiable."], ["Can a counterexample improve research direction?", ["Yes", "No", "Only if published"], 0, "It isolates missing hypotheses."], ["Should two rates be compared under different losses without adjustment?", ["No", "Yes", "Only if same architecture"], 0, "Metrics must match."]],
  },
];
