import type { MathLecture } from "./lectures";

/** Geometry, factorization, and stability for data and numerical work. */
export const MATH_LINEAR_ALGEBRA_SPECTRAL: MathLecture[] = [
  {
    lesson: "math.m14.l1", title: "Orthogonal projection and least squares",
    premise: "When Ax=b cannot be solved exactly, least squares finds the output in the column space nearest to b.",
    idea: "Minimize ||Ax-b||². At an optimum, the residual r=b-Ax is perpendicular to every column of A, giving the normal equations AᵀAx=Aᵀb. If A has independent columns, AᵀA is invertible and the coefficient vector is unique. Geometrically, Ax is the orthogonal projection of b onto the image of A. For a single nonzero direction u, projection is ((b·u)/(u·u))u. With rank-deficient A, fitted values remain uniquely projected but coefficient vectors may not be unique; the pseudoinverse selects the minimum-norm one. For numerical work, QR or SVD is often more stable than forming AᵀA.",
    worked: "Project b=(2,3) onto the line spanned by u=(1,1). The coefficient is (b·u)/(u·u)=5/2. The projection is (2.5,2.5), with residual (-0.5,0.5). Its dot product with u is zero. No other point on that line is closer in Euclidean distance.",
    interpretation: "Least squares does not make inconsistent data consistent; it separates the part explainable by the chosen column space from the perpendicular residual.",
    trap: "Do not claim (AᵀA)^{-1} exists for dependent columns, and do not call the residual zero unless b lies in the column space.",
    practice: "Fit a constant c to data (1,3,5) by least squares. State the residual vector.",
    solution: "The model vector is c(1,1,1). Orthogonal projection gives c=(1+3+5)/3=3. The fitted vector is (3,3,3) and residual is (-2,0,2), whose entries sum to zero and hence are orthogonal to (1,1,1).",
    checks: [["What is perpendicular to the columns at a least-squares optimum?", ["The residual", "The fitted vector", "The coefficient vector"], 0, "The normal equations express this orthogonality."], ["What equations characterize least squares?", ["AᵀAx=Aᵀb", "Ax=0 always", "AAᵀx=b always"], 0, "Set the gradient of squared residual to zero."], ["Does an inconsistent system become exact after fitting?", ["No", "Yes", "Only for one column"], 0, "The residual generally remains nonzero."]],
  },
  {
    lesson: "math.m14.l2", title: "QR factorization",
    premise: "QR factorization expresses a matrix's columns in an orthonormal coordinate system, making projection and least squares easier and more stable.",
    idea: "For an m-by-n matrix A with independent columns and m≥n, a thin QR factorization writes A=QR, where Q has orthonormal columns and R is upper triangular with positive diagonal under a conventional sign choice. Multiplying Ax≈b by Qᵀ gives Rx≈Qᵀb, a triangular system. Classical Gram-Schmidt constructs Q by subtracting earlier projections, but modified Gram-Schmidt or Householder reflections are preferable numerically. Since QᵀQ=I, lengths within the column-coordinate space are preserved and the residual component orthogonal to col(A) does not affect x.",
    worked: "Take A with columns a₁=(1,0) and a₂=(1,1). The first unit vector is q₁=(1,0). Remove projection of a₂ onto q₁: a₂-(q₁·a₂)q₁=(0,1), so q₂=(0,1). Thus Q=I and R=[[1,1],[0,1]]. Multiplying Q R recovers A.",
    interpretation: "R records how the original columns combine the orthonormal directions. This simple example already shows the triangular structure.",
    trap: "Do not normalize a zero remainder: that signals dependent columns and requires a rank-aware factorization.",
    practice: "Find a thin QR factorization of the single-column matrix A=(3,4)ᵀ.",
    solution: "The column norm is 5. Set Q=(3/5,4/5)ᵀ and R=[5]. Q has unit length, R has positive diagonal, and QR=(3,4)ᵀ.",
    checks: [["What property do columns of Q have?", ["Orthonormality", "All positive entries", "Identical length to A columns"], 0, "QᵀQ=I."], ["What shape is R in thin QR?", ["Upper triangular", "Lower triangular", "Always diagonal"], 0, "Each new column uses earlier orthonormal directions."], ["Why solve with QR rather than forming AᵀA?", ["Better numerical stability", "It always removes noise exactly", "It makes every matrix square"], 0, "Normal equations can square the condition number."]],
  },
  {
    lesson: "math.m14.l3", title: "Eigenvalues and eigenvectors",
    premise: "An eigenvector keeps its direction under a square linear map, while its eigenvalue gives the stretch or sign reversal along that direction.",
    idea: "Solve Av=λv for nonzero v. Equivalently, (A-λI)v=0, so eigenvalues satisfy det(A-λI)=0. For each root, solve the corresponding nullspace; zero vector is not an eigenvector. A real matrix can have complex eigenvalues, and an eigenvalue may have a multidimensional eigenspace. Trace equals the sum of eigenvalues and determinant their product when counted with algebraic multiplicity. Eigenvectors of a non-symmetric matrix need not be orthogonal or form a basis.",
    worked: "For A=diag(2,3), det(A-λI)=(2-λ)(3-λ), so eigenvalues are 2 and 3. The x-axis vectors are eigenvectors for 2, and y-axis vectors for 3. The vector (1,1) is not an eigenvector because A(1,1)=(2,3) is not a scalar multiple of it.",
    interpretation: "Eigenvectors reveal invariant directions; they do not describe every vector individually until a suitable eigenbasis exists.",
    trap: "A root of the characteristic polynomial is an eigenvalue, not a complete eigenvector answer. Solve its nullspace and exclude zero.",
    practice: "Find eigenvalues and one eigenvector for each of A=[[1,1],[0,2]].",
    solution: "The characteristic equation is (1-λ)(2-λ)=0. For λ=1, (A-I)v=0 forces y=0, so (1,0) works. For λ=2, (A-2I)v=0 gives -x+y=0, so (1,1) works. Direct multiplication verifies both.",
    checks: [["Can the zero vector be an eigenvector?", ["No", "Yes", "Only for λ=0"], 0, "The definition explicitly requires nonzero v."], ["What equation identifies eigenvalues?", ["det(A-λI)=0", "det A=λ for every λ", "Av=0 for all v"], 0, "The shifted matrix needs a nontrivial kernel."], ["Must a real matrix have real eigenvalues?", ["No", "Yes", "Only if diagonal"], 0, "Rotations can have complex eigenvalues."]],
  },
  {
    lesson: "math.m14.l4", title: "Diagonalization and invariant subspaces",
    premise: "When enough independent eigenvectors exist, a matrix becomes diagonal in their basis, simplifying repeated applications and dynamics.",
    idea: "If an n-by-n matrix has n independent eigenvectors, place them as columns of invertible P. Then A=PDP^{-1}, where D contains corresponding eigenvalues. Consequently A^k=PD^kP^{-1}; powers act independently on eigen-directions. Distinct eigenvalues provide independent eigenvectors, but a repeated eigenvalue may or may not provide enough. An invariant subspace W satisfies A(W)⊆W; an eigenspace is one example. Non-diagonalizable matrices may require Jordan structure, but numerical algorithms generally avoid forming a fragile eigenvector matrix when it is ill-conditioned.",
    worked: "For A=[[2,1],[0,2]], the only eigenvalue is 2. Solving (A-2I)v=0 forces the second coordinate to zero, leaving a one-dimensional eigenspace. The 2-by-2 matrix has only one independent eigenvector, so it cannot be diagonalized despite its characteristic polynomial having two roots counted with multiplicity.",
    interpretation: "Algebraic multiplicity counts repeated characteristic roots; geometric multiplicity counts independent directions. Diagonalization needs enough of the latter.",
    trap: "Do not treat a repeated eigenvalue as two eigenvectors automatically. Check the dimension of its eigenspace.",
    practice: "Diagonalize A=diag(4,-1) and compute A³ without multiplying A three times.",
    solution: "The standard basis already consists of eigenvectors, so P=I and D=A. Cube the diagonal entries: A³=diag(4³,(-1)³)=diag(64,-1). Both coordinate axes are invariant subspaces.",
    checks: [["What is needed to diagonalize an n-by-n matrix?", ["n independent eigenvectors", "n eigenvalues counted with repetition only", "A nonzero determinant only"], 0, "Their columns form the change-of-basis matrix P."], ["What is A^k when A=PDP^{-1}?", ["PD^kP^{-1}", "P^k D^k P^{-k}", "D^k always"], 0, "Adjacent P^{-1}P factors cancel."], ["Does a repeated eigenvalue guarantee diagonalization?", ["No", "Yes", "Only if positive"], 0, "Its eigenspace may be too small."]],
  },
  {
    lesson: "math.m14.l5", title: "Symmetric matrices and the spectral theorem",
    premise: "Real symmetric matrices have an unusually clean geometry: real eigenvalues and an orthonormal eigenbasis.",
    idea: "If A=Aᵀ is real, the spectral theorem provides A=QΛQᵀ with orthogonal Q and real diagonal Λ. Eigenvectors for distinct eigenvalues are orthogonal; within a repeated eigenspace choose an orthonormal basis. The quadratic form xᵀAx becomes Σλᵢ yᵢ² after y=Qᵀx, so its signs are controlled by eigenvalues. Symmetry is essential: a general real matrix may have complex eigenvalues or fail to diagonalize. This theorem underlies principal components, quadratic optimization, and stable spectral algorithms.",
    worked: "For A=[[2,1],[1,2]], vectors (1,1) and (1,-1) are eigenvectors with eigenvalues 3 and 1. Normalize them to q₁=(1,1)/sqrt(2), q₂=(1,-1)/sqrt(2). With Q=[q₁ q₂], A=Q diag(3,1) Qᵀ. Both eigenvalues are positive, so xᵀAx>0 for every nonzero x.",
    interpretation: "The rotated orthonormal axes decouple the action of A into stretches by 3 and 1.",
    trap: "Do not write Q^{-1}=Qᵀ for an arbitrary eigenvector matrix. That equality follows here because Q is orthogonal.",
    practice: "For S=diag(-2,5), classify xᵀSx and give an orthonormal eigenbasis.",
    solution: "The standard basis is an orthonormal eigenbasis with eigenvalues -2 and 5. The form is -2x₁²+5x₂², positive on the y-axis and negative on the x-axis, so it is indefinite rather than positive or negative definite.",
    checks: [["What kind of eigenvalues does a real symmetric matrix have?", ["Real", "Only positive", "Always distinct"], 0, "The spectral theorem guarantees reality, not positivity."], ["What relation does orthogonal Q satisfy?", ["QᵀQ=I", "QᵀQ=0", "Q=Λ"], 0, "Its columns are orthonormal."], ["Can a symmetric matrix have repeated eigenvalues?", ["Yes", "No", "Only zero"], 0, "Choose an orthonormal basis inside each eigenspace."]],
  },
  {
    lesson: "math.m14.l6", title: "Singular value decomposition",
    premise: "The SVD describes how any real matrix rotates, stretches, and rotates again, even when it is rectangular or singular.",
    idea: "An m-by-n matrix has A=UΣVᵀ with orthogonal U,V and nonnegative singular values on the rectangular diagonal Σ. Right singular vectors are input directions; left singular vectors are output directions. Nonzero singular values are square roots of nonzero eigenvalues of AᵀA, and their count is rank. The operator 2-norm is the largest singular value; the smallest nonzero singular value controls sensitivity on the surviving subspace. Truncating to the top k singular values gives the best rank-k approximation in spectral and Frobenius norm. SVD also constructs the pseudoinverse by reciprocating nonzero singular values.",
    worked: "For A=diag(3,-1), choose V=I, Σ=diag(3,1), and U=diag(1,-1). Then UΣVᵀ=A. Singular values are 3 and 1, both nonnegative, while the negative sign resides in an orthogonal direction change. The best rank-one approximation is diag(3,0).",
    interpretation: "Unlike eigenvalues, singular values exist for every rectangular matrix and quantify its stretching strength.",
    trap: "Do not confuse a negative eigenvalue with a negative singular value; singular values are defined nonnegative.",
    practice: "Find singular values and rank of A=diag(4,0,2).",
    solution: "AᵀA=diag(16,0,4), whose eigenvalues have square roots 4,0,2. Sorted singular values are 4,2,0. There are two nonzero singular values, so rank is 2. A best rank-one approximation keeps only the 4 direction.",
    checks: [["Are singular values negative?", ["No", "Sometimes", "Only for symmetric matrices"], 0, "They are nonnegative square roots of eigenvalues of AᵀA."], ["How many nonzero singular values does A have?", ["Its rank", "Its nullity", "Its row count always"], 0, "Each surviving stretch contributes one dimension."], ["Does SVD apply to rectangular matrices?", ["Yes", "No", "Only square invertible ones"], 0, "Σ itself can be rectangular."]],
  },
  {
    lesson: "math.m14.l7", title: "Positive-definite matrices and quadratic forms",
    premise: "A positive-definite matrix assigns positive quadratic energy to every nonzero direction, which makes many optimization problems well behaved.",
    idea: "For a real symmetric matrix A, positive definiteness means xᵀAx>0 for every x≠0. By the spectral theorem this is equivalent to all eigenvalues being positive. Positive semidefiniteness permits zero but no negative eigenvalues. In two dimensions, a symmetric [[a,b],[b,d]] is positive definite if a>0 and ad-b²>0. If a twice-differentiable objective has a positive-definite Hessian at a stationary point, the point is a strict local minimum. For quadratic q(x)=xᵀAx-2bᵀx with A positive definite, its unique minimizer solves Ax=b. Cholesky factorization A=LLᵀ is a computationally useful consequence.",
    worked: "Let A=[[2,0],[0,5]]. Then xᵀAx=2x₁²+5x₂², strictly positive for every nonzero x. For q(x)=xᵀAx-2(2,5)·x, the gradient is 2Ax-2(2,5). Setting it to zero yields x=(1,1), the unique global minimizer because A is positive definite.",
    interpretation: "Positive curvature in every direction prevents flat or descending directions and produces a stable minimum in this quadratic model.",
    trap: "Positive diagonal entries alone do not prove definiteness; off-diagonal terms can create a negative eigenvalue.",
    practice: "Classify B=[[1,2],[2,1]] and explain why its positive diagonal is misleading.",
    solution: "The determinant is 1-4=-3, so B has eigenvalues of opposite signs and is indefinite. Directly, x=(1,-1) gives xᵀBx=-2, while x=(1,1) gives 6. Positive diagonal entries did not control cross terms.",
    checks: [["What eigenvalue condition characterizes symmetric positive definiteness?", ["All eigenvalues positive", "All diagonal entries positive", "Determinant positive alone"], 0, "The orthonormal eigenbasis diagonalizes the quadratic form."], ["What does positive semidefinite permit?", ["Zero quadratic value for nonzero vectors", "Negative values", "Only invertible matrices"], 0, "Zero eigenvalues can occur."], ["What system minimizes xᵀAx-2bᵀx for positive-definite A?", ["Ax=b", "Ax=0 always", "Aᵀx=-b"], 0, "Set its gradient 2Ax-2b to zero."]],
  },
  {
    lesson: "math.m14.l8", title: "Conditioning and numerical stability",
    premise: "A mathematically unique answer can be highly sensitive to tiny input errors. Conditioning describes the problem; stability describes the algorithm.",
    idea: "For invertible A, the 2-norm condition number is κ₂(A)=σ_max/σ_min. A large ratio means some directions are stretched much more than others, so errors in b or rounding can produce large relative changes in x when solving Ax=b. A backward-stable algorithm returns the exact solution to a nearby problem, but a badly conditioned problem can still have large forward error. Forming normal equations AᵀA squares the condition number when A has full column rank, which helps explain why QR and SVD are preferred for demanding least-squares computations. Always state norms and assumptions when quoting sensitivity bounds.",
    worked: "For A=diag(1,0.001), singular values are 1 and 0.001, so κ₂(A)=1000. The equation Ax=(1,1) gives x=(1,1000). If the second entry of b changes from 1 to 1.001, the second solution entry changes to 1001. Small data variation is magnified along the weakly scaled direction.",
    interpretation: "The example identifies the sensitive direction. The exact amplification depends on how the perturbation aligns with singular vectors, not only on one scalar condition number.",
    trap: "Do not blame every large solution error on an unstable solver; the input problem itself may be ill-conditioned.",
    practice: "Compute κ₂ for diag(4,2) and for diag(4,0.04). Which is more sensitive?",
    solution: "The first ratio is 4/2=2. The second is 4/0.04=100. The second is more sensitive in its weak direction. Both are invertible, so singularity is not required for poor conditioning.",
    checks: [["What ratio defines κ₂ for invertible A?", ["Largest over smallest singular value", "Largest over smallest eigenvalue with signs", "Rank over nullity"], 0, "Use nonnegative singular values."], ["What does poor conditioning describe?", ["Sensitivity of the problem", "Only a program bug", "Always nonuniqueness"], 0, "Unique solutions may still be sensitive."], ["What can normal equations do to conditioning?", ["Square the condition number", "Always halve it", "Make it one"], 0, "Singular values of AᵀA are squared."]],
  },
  {
    lesson: "math.m14.l9", title: "Principal components from the SVD",
    premise: "Principal component analysis finds orthogonal directions of greatest variation in centered data. The SVD provides those directions without explicitly forming a covariance matrix.",
    idea: "Place observations in rows of X and subtract each feature's sample mean to form centered X_c. In X_c=UΣVᵀ, columns of V are principal directions and squared singular values divided by n-1 are sample covariance eigenvalues when n>1. The score matrix X_cV contains coordinates of observations along those directions. Keeping the first k columns yields an orthogonal rank-k reconstruction with minimum squared Frobenius error among rank-k matrices. PCA maximizes captured variance, not predictive usefulness; it is sensitive to feature scaling and outliers. Fit centering and components on training data only to avoid leakage.",
    worked: "Consider observations (1,0), (2,0), and (3,0). Their mean is (2,0), so centered rows are (-1,0), (0,0), and (1,0). All variation lies along the x-axis: the first principal direction is (1,0), its singular value is sqrt(2), and the sample variance is 2/(3-1)=1. The second variance is zero.",
    interpretation: "One component preserves all centered information in this dataset. The mean must be added back after reconstruction.",
    trap: "Do not run PCA on uncentered observations and interpret its first axis as variance about the mean. Also do not use the test set to fit the basis.",
    practice: "For centered rows (-2,0),(0,0),(2,0), identify the leading principal direction and sample variance.",
    solution: "The sole varying direction is the x-axis, so a leading direction is (1,0) up to sign. The squared singular value is (-2)²+0²+2²=8. With n=3, sample variance is 8/(3-1)=4. The second principal variance is zero.",
    checks: [["What preprocessing is essential for standard PCA?", ["Center each feature", "Sort rows", "Square all values"], 0, "Variance is defined about the mean."], ["Where are principal directions in X_c=UΣVᵀ?", ["Columns of V", "Rows of U only", "Diagonal of X_c"], 0, "V spans feature directions."], ["What does PCA optimize?", ["Captured variance or reconstruction error", "Any task's accuracy", "Causal relevance"], 0, "High variance need not mean high predictive value."]],
  },
];
