import type { MathLecture } from "./lectures";

/** Linear systems first, then the vector-space structure behind them. */
export const MATH_LINEAR_ALGEBRA_FOUNDATIONS: MathLecture[] = [
  {
    lesson: "math.m13.l1", title: "Linear systems and Gaussian elimination",
    premise: "Many simultaneous equations are one linear system. Row operations expose whether the system has one solution, none, or infinitely many.",
    idea: "Write the coefficients and constants as an augmented matrix. Swapping rows, scaling a row by a nonzero number, and adding a multiple of one row to another preserve the solution set. Eliminate below pivot positions, then back-substitute; reduced row echelon form also eliminates above pivots. A row [0 0 | 1] means inconsistency. A nonpivot variable is free and parameterizes multiple solutions. Record row operations and interpret the result in the original variables. Numerical computation needs pivoting to avoid dividing by a tiny number, even when exact algebra is straightforward.",
    worked: "Solve x+y=3 and 2x-y=0. The augmented rows are [1,1|3] and [2,-1|0]. Subtract twice the first from the second to get [0,-3|-6], so y=2. Back-substitution gives x=1. Both original equations check: 1+2=3 and 2-2=0.",
    interpretation: "Two independent pivot equations determine two unknowns. If a row had collapsed to [0,0|1], no pair could satisfy both equations.",
    trap: "Do not perform a row operation on coefficients without applying it to the augmented right-hand column too.",
    practice: "Solve x+2y=5 and 2x+4y=10. State whether the solution is unique.",
    solution: "Subtract twice the first equation from the second to obtain 0=0. There is one pivot and one free variable. Let y=t; then x=5-2t for every real t. The equations describe the same line, so solutions are infinite rather than unique.",
    checks: [["What does [0,0|1] mean in an augmented matrix?", ["No solution", "One solution", "A free variable only"], 0, "It asserts 0=1."], ["What is a nonpivot variable called?", ["Free", "Inconsistent", "Always zero"], 0, "It can parameterize the solution set."], ["Which row operation preserves solutions?", ["Add a multiple of one row to another", "Square only one side", "Delete any equation"], 0, "Elementary invertible row operations preserve the system."]],
  },
  {
    lesson: "math.m13.l2", title: "Vectors, subspaces, span, and independence",
    premise: "A collection of vectors can generate a space. Independence tells whether any generator is redundant.",
    idea: "The span of v₁,…,vₖ is every linear combination c₁v₁+…+cₖvₖ. A subspace contains zero and is closed under addition and scalar multiplication. A set is linearly independent when c₁v₁+…+cₖvₖ=0 forces all coefficients to zero; otherwise one vector can be expressed through the others. To test independence, place vectors as columns and solve the homogeneous system. Geometry helps in two or three dimensions, but the equation definition applies to function spaces and matrices too. A translated line missing the origin is not a subspace.",
    worked: "In R², v₁=(1,1) and v₂=(1,-1) are independent: a(1,1)+b(1,-1)=(0,0) gives a+b=0 and a-b=0, hence a=b=0. They span R² because any (x,y) equals ((x+y)/2)v₁+((x-y)/2)v₂. Adding v₃=(2,0)=v₁+v₂ makes the three-vector list dependent.",
    interpretation: "Span asks reachability; independence asks redundancy. A useful coordinate system needs both.",
    trap: "Two nonzero vectors can still be dependent if one is a scalar multiple of the other. Nonzero alone is insufficient.",
    practice: "Are (1,2,0) and (2,4,0) independent? Describe their span and say whether it is a subspace.",
    solution: "The second vector is twice the first, so the pair is dependent. Their span is the line {(t,2t,0): t real}. It contains zero and is closed under addition and scaling, so it is a one-dimensional subspace of R³.",
    checks: [["What does a span contain?", ["All linear combinations", "Only the listed vectors", "Only unit vectors"], 0, "Coefficients may be any scalars."], ["Must a subspace contain zero?", ["Yes", "No", "Only if finite-dimensional"], 0, "Closure under scalar multiplication forces zero."], ["What proves independence?", ["Only the trivial combination gives zero", "Every vector is nonzero", "The list has many vectors"], 0, "Use the homogeneous relation."]],
  },
  {
    lesson: "math.m13.l3", title: "Bases, dimension, and coordinates",
    premise: "A basis is a nonredundant generating set. Its coefficients give a unique coordinate address for every vector in the space.",
    idea: "A basis both spans the space and is linearly independent. In a finite-dimensional space, every basis has the same number of vectors, called its dimension. To find coordinates relative to B=(b₁,…,bₙ), solve v=Σcᵢbᵢ; uniqueness follows from independence. The coordinate column depends on the chosen basis even though the underlying vector does not. A basis of a subspace may have fewer vectors than a basis of its ambient space. Algorithms that retain pivot columns from the original matrix construct a basis for its column space; pivot columns of the reduced matrix need not be the same original vectors.",
    worked: "Let B=((1,1),(1,-1)) and v=(4,2). Solve a+b=4 and a-b=2, giving a=3,b=1. Thus [v]_B=(3,1), while standard coordinates are (4,2). The two basis vectors are independent and span R², so dimension is 2.",
    interpretation: "Coordinates are an encoding under a basis. Changing the basis changes the numbers, not the geometric vector.",
    trap: "Do not call a spanning list a basis if it contains redundant vectors; independence is a separate requirement.",
    practice: "For B=((1,0,1),(0,1,1)), find coordinates of v=(2,-1,1) in span(B).",
    solution: "The combination a(1,0,1)+b(0,1,1)=(a,b,a+b) matches v with a=2,b=-1 and a+b=1. Therefore [v]_B=(2,-1). The two basis vectors are independent because their first two coordinates force zero coefficients in a zero combination.",
    checks: [["Which two properties define a basis?", ["Spanning and independence", "Orthogonality and unit length", "Positive entries and square shape"], 0, "A basis reaches every vector without redundancy."], ["Does [v]_B depend on B?", ["Yes", "No", "Only if v=0"], 0, "Coordinates encode a vector relative to a chosen basis."], ["What is dimension?", ["Number of vectors in any basis", "Number of listed generators even if redundant", "Largest coordinate value"], 0, "All bases of a finite-dimensional space have equal size."]],
  },
  {
    lesson: "math.m13.l4", title: "Linear maps, kernel, and image",
    premise: "A linear map respects combinations. Its kernel records lost directions, while its image records reachable outputs.",
    idea: "A transformation T:V→W is linear if T(au+bv)=aT(u)+bT(v). Relative to chosen bases it can be represented by a matrix A with T(x)=Ax. The kernel is {x:T(x)=0}; the image is {T(x):x∈V}, equivalently the span of matrix columns in standard coordinates. Both are subspaces. Solve Ax=0 for the kernel and identify independent output columns for the image. An injective linear map has zero kernel; a surjective one has image equal to its codomain. Changing bases changes the matrix representation, not these intrinsic properties.",
    worked: "Let T(x,y,z)=(x+y,y+z). The kernel solves x+y=0,y+z=0, so (x,y,z)=t(-1,1,-1). The image is all R² because T(1,0,0)=(1,0) and T(0,0,1)=(0,1). Thus the map loses one input direction but reaches every output.",
    interpretation: "The input dimension is 3; one direction disappears and two independent output directions remain.",
    trap: "The image lives in the output space and the kernel in the input space. They cannot generally be equated as sets.",
    practice: "For S(x,y)=(x+y,2x+2y), describe kernel and image.",
    solution: "Kernel requires x+y=0, giving span{(1,-1)}. Every output has form (t,2t), so image is span{(1,2)}. Both have dimension 1, but they live in different roles: inputs erased versus outputs produced.",
    checks: [["Where does the kernel live?", ["Input space", "Output space only", "Matrix entries"], 0, "It consists of inputs sent to zero."], ["What spans the image of a matrix map?", ["Its columns", "Its rows only", "Its diagonal only"], 0, "Ax is a combination of columns."], ["What kernel condition implies injectivity?", ["Only the zero vector is in it", "It equals the codomain", "It has a basis of two vectors"], 0, "No nonzero input difference can vanish."]],
  },
  {
    lesson: "math.m13.l5", title: "Rank-nullity theorem",
    premise: "Every input direction either survives as an independent output direction or is lost in the kernel. Rank-nullity counts the balance.",
    idea: "For a linear map T:V→W with finite-dimensional domain, dim V=dim ker T+dim im T. Nullity is the kernel dimension and rank the image dimension. To understand the proof, choose a basis of the kernel and extend it to a basis of V; the images of the added basis vectors form a basis of the image. For an m-by-n matrix, rank plus nullity equals n, the number of columns. Rank cannot exceed min(m,n). This theorem gives dimension information without computing every vector, but it does not assert that kernel and image are the same subspace.",
    worked: "For T(x,y,z)=(x+y,y+z), the kernel is span{(-1,1,-1)}, so nullity is 1. Its image is R², so rank is 2. The domain has dimension 3 and 1+2=3. A row reduction would show two pivot columns and one free variable.",
    interpretation: "The theorem is a conservation law for degrees of freedom under a linear transformation.",
    trap: "Use the number of input columns for the sum, not the number of output rows. A 2-by-3 matrix has rank plus nullity equal to 3.",
    practice: "A 4-by-7 matrix has rank 3. Find its nullity. Can its map onto R⁴ be surjective?",
    solution: "Nullity=7-3=4. Its image has dimension 3, smaller than the codomain dimension 4, so it cannot be onto R⁴. Four independent outputs would be needed for surjectivity.",
    checks: [["For an m-by-n matrix, rank plus nullity equals what?", ["n", "m", "m+n"], 0, "The domain is R^n."], ["What does nullity measure?", ["Kernel dimension", "Codomain dimension", "Determinant"], 0, "It counts input directions sent to zero."], ["Can rank exceed the row count?", ["No", "Yes", "Only with a zero kernel"], 0, "The image lies in the row-count-dimensional codomain."]],
  },
  {
    lesson: "math.m13.l6", title: "Matrix multiplication and inverse maps",
    premise: "Matrix multiplication represents composition of linear maps. An inverse matrix undoes a map only when no direction is lost and every output is reached.",
    idea: "If B maps input vectors to an intermediate space and A maps those outputs onward, the composite is AB, with B acting first. Entry (i,j) of AB is row i of A dotted with column j of B. Matrix multiplication is generally not commutative. A square matrix A is invertible when there is A^{-1} satisfying both AA^{-1}=I and A^{-1}A=I; equivalently its columns form a basis, its kernel is zero, and its rank is full. To compute the inverse by elimination, row-reduce [A|I] to [I|A^{-1}]. If the left side cannot become I, no inverse exists.",
    worked: "Let A=[[1,1],[0,1]] and B=[[2,0],[0,3]]. Then AB=[[2,3],[0,3]], while BA=[[2,2],[0,3]]: composition order matters. A maps (x,y) to (x+y,y), so its inverse maps (u,v) to (u-v,v), represented by [[1,-1],[0,1]]. Multiplying A by that inverse gives I.",
    interpretation: "The inverse reflects a reversible coordinate shear. B scales axes, and scaling before versus after the shear creates different results.",
    trap: "An m-by-n non-square matrix cannot have a two-sided inverse of the same type. A numerical solver may still find least-squares or one-sided inverses under separate conditions.",
    practice: "Find the inverse of C=[[2,0],[0,5]] and solve Cx=(6,10).",
    solution: "C^{-1}=[[1/2,0],[0,1/5]] because each independent axis scaling is undone by its reciprocal. Then x=C^{-1}(6,10)=(3,2). Direct substitution gives C(3,2)=(6,10).",
    checks: [["In ABx, which matrix acts first?", ["B", "A", "Both simultaneously"], 0, "Composition reads right to left."], ["Do matrices generally commute?", ["No", "Yes", "Only when square"], 0, "AB and BA can differ."], ["What is required for a square matrix inverse?", ["Full rank", "At least one nonzero entry", "Positive diagonal"], 0, "No input direction may be lost."]],
  },
  {
    lesson: "math.m13.l7", title: "Determinants and orientation",
    premise: "The determinant measures the signed volume scale of a square linear map. Zero determinant marks a collapse into lower dimension.",
    idea: "For a 2-by-2 matrix [[a,b],[c,d]], det A=ad-bc. Its absolute value scales areas; its sign records whether orientation is preserved or reversed. In higher dimensions, determinant scales oriented n-volume. Swapping two rows reverses its sign, scaling one row scales it, and adding a multiple of one row to another leaves it unchanged. A square matrix is invertible exactly when its determinant is nonzero. The multiplicative identity det(AB)=det A·det B connects composition with volume scale. Determinants are not a general-purpose measure of numerical conditioning; a nonzero but tiny determinant does not alone quantify stability without scale context.",
    worked: "For A=[[1,1],[1,-1]], det A=-1-1=-2. The unit square maps to a parallelogram of area 2 and reversed orientation. The columns (1,1) and (1,-1) are independent, consistent with a nonzero determinant.",
    interpretation: "Absolute determinant gives the geometric factor used in coordinate-change integrals; the sign carries orientation information needed for directed integrals.",
    trap: "A negative determinant does not mean negative physical area. Keep signed orientation separate from absolute scale.",
    practice: "Find the determinant of D=[[3,0],[0,-2]]. Describe its area scale and orientation.",
    solution: "det D=3(-2)-0=-6. Areas scale by |det D|=6. One axis reverses, so orientation reverses. Since det D≠0, D is invertible.",
    checks: [["What does |det A| measure in two dimensions?", ["Area scale", "Only angle", "Kernel size"], 0, "A unit square becomes a parallelogram of this area."], ["What does det A=0 mean for a square map?", ["It is singular", "It reverses orientation", "It preserves every area"], 0, "Volume collapses and an inverse cannot exist."], ["What is det(AB)?", ["det A times det B", "det A plus det B", "Always zero"], 0, "Volume scales multiply under composition."]],
  },
  {
    lesson: "math.m13.l8", title: "Inner products and orthogonality",
    premise: "An inner product gives a geometry to a vector space: lengths, angles, and perpendicularity become algebraic quantities.",
    idea: "In Rⁿ, the standard inner product is x·y=Σxᵢyᵢ. Its induced norm is ||x||=sqrt(x·x). Vectors are orthogonal when x·y=0. Cauchy-Schwarz bounds |x·y|≤||x||||y||, making cos θ=(x·y)/(||x||||y||) valid for nonzero vectors. The Pythagorean identity follows when the cross term vanishes: ||x+y||²=||x||²+||y||² for orthogonal x,y. A general inner product must be positive definite, symmetric in the real case, and linear in the specified argument; a raw dot product after an arbitrary coordinate change need not represent the same geometry.",
    worked: "Let u=(1,2) and v=(2,-1). Their dot product is 2-2=0, so they are orthogonal. Both have squared norm 5. Their sum (3,1) has squared norm 10, matching 5+5. Normalizing u gives u/sqrt(5), a unit vector in the same direction.",
    interpretation: "Orthogonality makes independent components geometrically decouple, which later enables projection, least squares, and stable matrix factorization.",
    trap: "A zero dot product means perpendicular only under the chosen inner product. Zero vector has no defined angle even though it is orthogonal to every vector algebraically.",
    practice: "Compute the cosine between a=(1,0,1) and b=(1,1,0), then check Cauchy-Schwarz.",
    solution: "The dot product is 1, and both norms are sqrt(2), so cos θ=1/2. Cauchy-Schwarz says |1|≤sqrt(2)sqrt(2)=2, which holds. The angle is 60 degrees.",
    checks: [["When are two nonzero Euclidean vectors orthogonal?", ["Their dot product is zero", "Their lengths match", "Their sum is zero"], 0, "The inner product defines perpendicularity."], ["What is the norm from an inner product?", ["sqrt(x·x)", "x·x without a square root", "Sum of coordinates"], 0, "Positive definiteness makes this a length."], ["What does Cauchy-Schwarz bound?", ["Absolute inner product by the product of norms", "Every determinant by one", "Rank by nullity"], 0, "It underlies the angle formula."]],
  },
];
