import type { MathLecture } from "./lectures";

/** Geometry, topology, and differential ideas before optimization. */
export const MATH_MULTIVARIABLE_FOUNDATIONS: MathLecture[] = [
  {
    lesson: "math.m11.l1",
    title: "Vectors, lines, and planes",
    premise: "Multivariable calculus begins with geometry in two and three dimensions. A vector has direction and magnitude; dot and cross products encode projection and orientation.",
    idea: "For v=(v₁,v₂,v₃), its length is sqrt(v₁²+v₂²+v₃²). The dot product u·v=|u||v|cos θ detects angle and orthogonality, and projects u onto a nonzero v by [(u·v)/(v·v)]v. In three dimensions, u×v is perpendicular to both, with magnitude equal to the parallelogram area; its sign orientation follows the right-hand rule. A line through p parallel to v has r(t)=p+tv. A plane through p with nonzero normal n satisfies n·(r-p)=0. Distinguish a direction vector for a line from a normal vector for a plane.",
    worked: "Through p=(1,2,0) with direction v=(2,-1,3), the line is (1+2t,2-t,3t). A plane through p with normal n=(1,2,-1) has (x-1)+2(y-2)-z=0, or x+2y-z=5. Substituting p verifies the plane equation. The line is not automatically contained in the plane: n·v=2-2-3=-3, so its direction is not parallel to that plane.",
    interpretation: "Dot products translate geometric constraints into equations. Coordinate expressions are useful only when their vector meaning remains clear.",
    trap: "Do not use a plane normal as though it were a tangent direction. For projection, divide by v·v unless v is already a unit vector.",
    practice: "Find the plane through (1,0,2), (2,1,2), and (1,1,3). Show how two in-plane direction vectors yield a normal.",
    solution: "Take u=(2,1,2)-(1,0,2)=(1,1,0) and v=(1,1,3)-(1,0,2)=(0,1,1). Their cross product is u×v=(1,-1,1). Thus the plane is (x-1)-y+(z-2)=0, or x-y+z=3. Each of the three points satisfies it.",
    checks: [
      ["What does a plane equation require besides a point?", ["A nonzero normal vector", "Only a scalar speed", "A single unrelated line"], 0, "The normal is perpendicular to every in-plane displacement."],
      ["When are u and v orthogonal?", ["u·v=0", "u×v=0", "|u|=|v|"], 0, "The dot product contains cos θ."],
      ["What is the line through p in direction v?", ["p+tv", "p·v", "p×v"], 0, "Scale the direction by a parameter."],
    ],
  },
  {
    lesson: "math.m11.l2",
    title: "Space curves and parametrization",
    premise: "A parametrized curve records position as a function of one parameter. Its derivative is a tangent velocity vector, while its second derivative describes how that velocity changes.",
    idea: "For r(t)=(x(t),y(t),z(t)), differentiate each coordinate: r'(t)=(x',y',z'). Where r'≠0, the unit tangent is T=r'/|r'|. If t is time, speed is |r'|, and arc length from a to b is ∫ₐᵇ|r'(t)|dt. A curve can revisit the same point with different velocities, so a position alone does not determine tangent behavior. Reparametrization changes the speed but can leave the geometric path unchanged; verify parameter range and orientation. The derivative of a vector-valued function obeys the usual sum and product rules componentwise.",
    worked: "For the helix r(t)=(cos t,sin t,t), r'=(-sin t,cos t,1) and |r'|=sqrt(2). The unit tangent is (-sin t,cos t,1)/sqrt(2), and the length from t=0 to t=2π is 2πsqrt(2). Its acceleration r''=(-cos t,-sin t,0) points toward the central axis in the horizontal plane.",
    interpretation: "The curve rises one unit per radian while circling the axis, so its three-dimensional speed exceeds its horizontal unit-circle speed.",
    trap: "Do not integrate |r(b)-r(a)| for arc length; that is only straight-line displacement. A tangent vector requires a nonzero derivative at the parameter value.",
    practice: "For r(t)=(t²,2t,0), 0≤t≤1, find velocity, speed, tangent line at t=1, and an integral expression for arc length.",
    solution: "r'=(2t,2,0), so speed is 2sqrt(t²+1). At t=1, position is (1,2,0) and tangent direction is (2,2,0), giving line (1,2,0)+s(2,2,0). Arc length is ∫₀¹2sqrt(t²+1)dt, not the distance from (0,0,0) to (1,2,0).",
    checks: [
      ["What is speed for a position curve r(t)?", ["|r'(t)|", "|r(t)|", "|r''(t)|"], 0, "Speed is velocity magnitude."],
      ["What is arc length from a to b?", ["∫ₐᵇ|r'(t)|dt", "|r(b)-r(a)| always", "∫ₐᵇ r''(t)dt"], 0, "Add lengths of infinitesimal tangent steps."],
      ["When is r'(t) a valid tangent direction?", ["When it is nonzero", "Only when t=0", "Whenever r(t)=0"], 0, "A zero derivative gives no direction by normalization."],
    ],
  },
  {
    lesson: "math.m11.l3",
    title: "Limits and continuity in several variables",
    premise: "In several variables, a limit must agree along every way of approaching the point. Checking two familiar paths can disprove a limit but cannot generally prove it exists.",
    idea: "The limit of f(x,y) at (a,b) is L if every sufficiently near point in the domain, except possibly the point itself, yields values close to L. For a continuous formula at an interior domain point, direct substitution works. At a suspicious denominator zero, compare distinct approach paths. If two paths yield different limits, the full limit does not exist. If tested paths agree, seek a uniform estimate such as |f(x,y)-L|≤g(sqrt((x-a)²+(y-b)²)) where g(r) approaches zero as r shrinks. Polar coordinates often reveal whether an expression depends on angle as radius tends to zero.",
    worked: "Consider f(x,y)=xy/(x²+y²) away from the origin. Along y=0, f=0. Along y=x with x≠0, f=x²/(2x²)=1/2. Since the path limits differ, the limit at (0,0) does not exist. In contrast, |xy|≤(x²+y²)/2 shows |xy|/sqrt(x²+y²)≤sqrt(x²+y²)/2, so xy/sqrt(x²+y²) approaches zero uniformly as the radius shrinks.",
    interpretation: "Many paths are available in a plane. A path test is a powerful counterexample tool, while a radial bound can provide an all-path proof.",
    trap: "Do not declare a multivariable limit after checking only the x- and y-axes. A diagonal or curved path may behave differently.",
    practice: "Decide whether x²y/(x⁴+y²) has a limit at the origin by comparing y=0 and y=x².",
    solution: "Along y=0 the function is zero. Along y=x² with x≠0, it becomes x⁴/(x⁴+x⁴)=1/2. The two path limits disagree, so there is no limit at the origin. Defining a value at the origin cannot repair the failure of nearby values to settle.",
    checks: [
      ["Can two matching path limits prove a multivariable limit exists?", ["Not generally", "Always", "Only for rational functions"], 0, "Other paths may differ."],
      ["What do two different path limits prove?", ["The full limit does not exist", "The limit is their average", "Continuity"], 0, "One limit cannot have two values."],
      ["What can establish an all-path limit of zero?", ["A uniform bound shrinking with distance", "One numerical table", "Only the x-axis"], 0, "Control every nearby direction at once."],
    ],
  },
  {
    lesson: "math.m11.l4",
    title: "Partial derivatives and gradients",
    premise: "A partial derivative measures response to one coordinate changing while the others are held fixed. The gradient combines all first partials into the direction of steepest local increase.",
    idea: "For f(x,y), f_x is the one-variable derivative of x↦f(x,y) with y fixed, and f_y fixes x instead. The gradient is ∇f=(f_x,f_y). At a differentiable point, a small displacement h changes f by approximately ∇f·h. Cauchy-Schwarz shows this linear change is greatest among unit directions when h points along ∇f, and its magnitude is |∇f|. Gradients are perpendicular to regular level curves because moving tangentially keeps f constant to first order. Existence of partial derivatives alone does not guarantee full differentiability; continuity of the partials nearby is one common sufficient condition.",
    worked: "For f(x,y)=x²y+3y², f_x=2xy and f_y=x²+6y. At (1,2), ∇f=(4,13). A small displacement (0.01,-0.02) predicts Δf≈4(0.01)+13(-0.02)=-0.22. The level curve through (1,2) has gradient (4,13) as a normal, provided this vector is nonzero.",
    interpretation: "Each gradient component has output units per unit of its coordinate. If the coordinates have different physical units, use care before treating raw Euclidean length as a physical speed of increase.",
    trap: "Do not differentiate y as though it changes when taking f_x. Do not claim a nonzero gradient is tangent to a level curve; it is normal.",
    practice: "For g(x,y,z)=x²+yz, find ∇g at (1,2,3) and give a normal vector to the level surface through that point.",
    solution: "The partial derivatives are g_x=2x, g_y=z, and g_z=y. Thus ∇g(1,2,3)=(2,3,2), which is nonzero and therefore normal to the regular level surface g=1+6=7 at that point.",
    checks: [
      ["What is held fixed in f_x?", ["All variables except x", "Only x", "No variables"], 0, "Take an ordinary x derivative along a coordinate line."],
      ["How does a gradient meet a regular level curve?", ["Perpendicularly", "Tangentially", "It never meets it"], 0, "Directional change along a level curve is zero."],
      ["Do existing partial derivatives alone guarantee differentiability?", ["No", "Yes", "Only in three dimensions"], 0, "Full linear approximation needs stronger control."],
    ],
  },
  {
    lesson: "math.m11.l5",
    title: "Directional derivatives and tangent planes",
    premise: "A directional derivative asks how a differentiable function changes along a chosen unit direction. Its tangent plane packages all first-order directional changes at once.",
    idea: "At a differentiable point p, the directional derivative in unit direction u is D_u f(p)=∇f(p)·u. If a vector v is not a unit vector, normalize it first when the question asks for rate per unit distance. For z=f(x,y), the tangent plane at (a,b,f(a,b)) is z=f(a,b)+f_x(a,b)(x-a)+f_y(a,b)(y-b). This is also the linear approximation to nearby function values. Its normal vector can be taken as (-f_x,-f_y,1). If the function is not differentiable at p, blindly taking a gradient dot product may give a false directional derivative.",
    worked: "Let f(x,y)=x²+y² at (1,2). The gradient is (2,4). In direction v=(3,4), the unit vector is (3/5,4/5), so D_u f=2(3/5)+4(4/5)=22/5. The tangent plane at (1,2,5) is z=5+2(x-1)+4(y-2), or z=2x+4y-5.",
    interpretation: "The direction changes which projection of the gradient is observed. The tangent plane predicts the value for every small horizontal step, not just along one selected line.",
    trap: "Do not use an unnormalized direction vector when a unit-direction derivative is requested, and do not forget the plane must pass through the point on the surface.",
    practice: "For h(x,y)=xy at (2,3), find the directional derivative toward (5,7) and the tangent plane to z=h(x,y).",
    solution: "The horizontal direction from (2,3) to (5,7) is (3,4), so u=(3/5,4/5). The gradient is (y,x)=(3,2), hence D_u h=3(3/5)+2(4/5)=17/5. The surface point is (2,3,6), and its tangent plane is z=6+3(x-2)+2(y-3)=3x+2y-6.",
    checks: [
      ["What computes a directional derivative at a differentiable point?", ["Gradient dot unit direction", "Gradient cross direction", "Function value times distance"], 0, "Project the gradient along the direction."],
      ["Why normalize a direction vector?", ["To measure change per unit distance", "To make the function linear", "To remove a denominator in f"], 0, "Length should not scale the requested unit rate."],
      ["What point must a tangent plane pass through?", ["(a,b,f(a,b))", "(f_x,f_y,0)", "The origin always"], 0, "It approximates the actual surface locally."],
    ],
  },
];
