import type { MathLecture } from "./lectures";

/** Multivariable derivatives culminate in local models and constrained extrema. */
export const MATH_MULTIVARIABLE_ADVANCED: MathLecture[] = [
  {
    lesson: "math.m11.l6",
    title: "Chain rule in several variables",
    premise: "When many inputs depend on the same parameter, every path through the dependency graph contributes to the total rate of change.",
    idea: "If z=f(x,y) with x=x(t) and y=y(t), then dz/dt=f_x dx/dt+f_y dy/dt, evaluated at the current x(t),y(t). In vector form this is ∇f(r(t))·r'(t). With several upstream parameters, the Jacobian matrix of a composition is the product of the Jacobians in dependency order. Draw the dependency graph to avoid dropping a branch. If a variable is held fixed, its rate is zero; if it changes indirectly, it still contributes. State where all functions are differentiable before applying the formula.",
    worked: "Let f(x,y)=x²y, x=t², and y=sin t. Then f_x=2xy, f_y=x², x'=2t, and y'=cos t. Thus dz/dt=2(t²)(sin t)(2t)+(t²)² cos t=4t³ sin t+t⁴ cos t. Direct substitution gives z=t⁴ sin t and differentiating confirms the result.",
    interpretation: "The two terms measure change transmitted through x and through y. The Jacobian formulation extends the same accounting to many intermediate layers.",
    trap: "Do not replace dz/dt with f_x+f_y unless both inner variables have unit rate. Evaluate partial derivatives at the current point on the path.",
    practice: "If z=x²+y², x=t+1, and y=2t, compute dz/dt at t=1 by the multivariable chain rule and by direct substitution.",
    solution: "The gradient is (2x,2y), and (x',y')=(1,2). At t=1, (x,y)=(2,2), so dz/dt=(4,4)·(1,2)=12. Directly, z=(t+1)²+4t², whose derivative is 2(t+1)+8t=12 at t=1.",
    checks: [
      ["How many branches contribute when x and y both depend on t?", ["Both f_x x' and f_y y'", "Only f_x", "Only f_y"], 0, "Account for every changing input."],
      ["What is the vector form along r(t)?", ["∇f(r(t))·r'(t)", "∇f+r", "f(r(t))·r(t)"], 0, "Project the gradient onto path velocity."],
      ["How do Jacobians compose?", ["By matrix multiplication in dependency order", "By entrywise addition", "By taking a determinant first"], 0, "Each linear map acts on the previous change."],
    ],
  },
  {
    lesson: "math.m11.l7",
    title: "Multivariable Taylor approximation",
    premise: "Near a point, a differentiable function is approximately its tangent plane. Curvature adds a quadratic correction described by the Hessian matrix.",
    idea: "For h=(h₁,h₂) near p, the first-order approximation is f(p+h)≈f(p)+∇f(p)·h. If f has sufficiently regular second derivatives, the second-order Taylor polynomial is f(p)+∇f(p)·h+(1/2)hᵀH_f(p)h. The Hessian H has entries f_xx, f_xy, f_yx, f_yy; under continuity of mixed second partials, f_xy=f_yx. The quadratic term includes the cross contribution 2f_xy h₁h₂ before multiplication by 1/2. State the expansion point and the size of h. An approximation is local; a quantitative error bound needs control of higher derivatives on a neighborhood.",
    worked: "Take f(x,y)=e^x cos y near (0,0). Here f=1, ∇f=(1,0), and H has diagonal entries 1 and -1 with zero mixed entries. Thus the second-order polynomial is 1+x+(x²-y²)/2. The tangent-plane approximation alone is 1+x; the quadratic term captures both exponential growth in x and cosine decrease in y.",
    interpretation: "The gradient is the linear response and the Hessian is the leading curvature response. Their coefficients have different units and roles.",
    trap: "Do not omit the factor 1/2 or the cross term when f_xy is nonzero. Do not use a Hessian from a different base point.",
    practice: "Find the second-order Taylor polynomial for f(x,y)=x²+xy+2y² at (1,1), using h=x-1 and k=y-1.",
    solution: "At (1,1), f=4 and ∇f=(2x+y,x+4y)=(3,5). The Hessian is [[2,1],[1,4]]. Thus T₂=4+3h+5k+(1/2)(2h²+2hk+4k²)=4+3h+5k+h²+hk+2k². Because f is already quadratic, this expansion equals f exactly everywhere.",
    checks: [
      ["What supplies the linear term in a multivariable Taylor model?", ["Gradient dot displacement", "The Hessian determinant", "Only f(p)"], 0, "The gradient describes first-order change."],
      ["What matrix supplies the quadratic term?", ["The Hessian", "The Jacobian of coordinates only", "A rotation matrix always"], 0, "It collects second partial derivatives."],
      ["What coefficient precedes hᵀHh?", ["1/2", "2", "None"], 0, "It is the second-order Taylor coefficient."],
    ],
  },
  {
    lesson: "math.m11.l8",
    title: "Critical points and Hessians",
    premise: "At an interior differentiable local extremum, the gradient must vanish. The Hessian can classify a nondegenerate critical point by the shape of its quadratic form.",
    idea: "Solve ∇f=0 for interior critical points, while also checking domain boundaries and nondifferentiable points separately. In two variables, set D=f_xx f_yy-(f_xy)² at a critical point. If D>0 and f_xx>0, the Hessian is positive definite and the point is a strict local minimum; if D>0 and f_xx<0, a strict local maximum. If D<0, the point is a saddle. If D=0, this second-derivative test is inconclusive; higher-order terms or direct path comparisons are needed. These conclusions are local, not automatically global.",
    worked: "For f(x,y)=x²+2y², the sole critical point is (0,0). Its Hessian is diagonal with entries 2 and 4, so D=8>0 and f_xx>0: a strict minimum. For g(x,y)=x²-y², the Hessian has entries 2 and -2, giving D=-4<0; along y=0 values rise from zero, while along x=0 they fall, proving a saddle.",
    interpretation: "The determinant reveals whether curvatures have the same sign or opposite signs, while f_xx separates a positive from negative definite shape when D>0.",
    trap: "Do not call D=0 a saddle or an extremum. The test gives no classification in that case, and boundary points need a separate constrained analysis.",
    practice: "Classify the origin for h(x,y)=x⁴+y⁴ and for q(x,y)=x⁴-y⁴. Explain why the Hessian test alone does not decide either.",
    solution: "Both gradients vanish at the origin and both Hessians are zero there, so D=0 and the test is inconclusive. For h, x⁴+y⁴≥0 with equality only at the origin, giving a strict local minimum. For q, values along y=0 are x⁴≥0 while values along x=0 are -y⁴≤0, so the origin is a saddle.",
    checks: [
      ["At a smooth interior local extremum, what must vanish?", ["The gradient", "The function value", "The Hessian"], 0, "Every coordinate directional derivative must be zero."],
      ["What does Hessian determinant D<0 indicate in two dimensions?", ["A saddle", "A strict minimum", "An inconclusive positive-definite test"], 0, "Curvature has opposite signs along directions."],
      ["What does D=0 mean for the standard test?", ["Inconclusive", "Always a saddle", "Always a maximum"], 0, "Higher-order behavior may decide."],
    ],
  },
  {
    lesson: "math.m11.l9",
    title: "Lagrange multipliers and constrained extrema",
    premise: "On a smooth constraint curve, an extremum can occur where the objective gradient is parallel to the constraint gradient. This is a candidate condition that still requires feasibility and comparison.",
    idea: "For objective f(x,y) subject to g(x,y)=c, regular constrained extrema satisfy ∇f=λ∇g together with g=c, provided ∇g≠0 at the point. The reason is that every tangent direction to the constraint has zero directional change in f at an extremum, so both gradients are normal to the same tangent. Solve all equations, then evaluate f at all candidates. If the constraint has corners, endpoints, self-intersections, or singular points where ∇g=0, inspect those separately. A stationary multiplier solution may be a constrained maximum, minimum, or neither without comparison.",
    worked: "Find extrema of f(x,y)=xy on the circle x²+y²=1. Equations (y,x)=λ(2x,2y) plus the circle give candidates x=±y with |x|=|y|=1/sqrt(2). When x and y share sign, xy=1/2; when signs differ, xy=-1/2. The compact circle guarantees absolute extrema, so these are its maximum and minimum values.",
    interpretation: "The constraint removes one degree of freedom; the objective need only be stationary along allowed tangent motions, not in every direction of the plane.",
    trap: "Do not solve ∇f=0 as though movement were unconstrained. Do not divide by x or y without checking zero cases, and inspect singular constraint points separately.",
    practice: "Maximize and minimize f(x,y)=x+y subject to x²+y²=2. Find the points and values, and justify why they are absolute.",
    solution: "The multiplier equations (1,1)=λ(2x,2y) force x=y at regular points. With x²+y²=2, candidates are (1,1) and (-1,-1). Their objective values are 2 and -2. The circle is compact and f is continuous, so absolute extrema exist; these compared candidates give the maximum and minimum. Cauchy-Schwarz independently gives |x+y|≤sqrt(2)·sqrt(x²+y²)=2.",
    checks: [
      ["What equations define regular Lagrange candidates?", ["∇f=λ∇g and g=c", "∇f=0 only", "f=g everywhere"], 0, "The constraint equation stays part of the system."],
      ["What regularity condition is required at a constraint point?", ["∇g≠0", "f=0", "λ=0"], 0, "A nonzero normal defines the tangent direction."],
      ["What must follow candidate solving?", ["Compare feasible values and special points", "Assume every candidate is a maximum", "Discard the constraint"], 0, "The multiplier equation is only necessary under its hypotheses."],
    ],
  },
  {
    lesson: "math.m11.l10",
    title: "The implicit function theorem",
    premise: "An equation F(x,y)=0 can locally describe y as a function of x even when solving it explicitly is difficult. A nonzero partial derivative with respect to y is the key local condition.",
    idea: "Suppose F is continuously differentiable near (a,b), F(a,b)=0, and F_y(a,b)≠0. Then near (a,b), the equation uniquely describes a differentiable branch y=y(x), and differentiating F(x,y(x))=0 gives y'=-F_x/F_y. This conclusion is local: one equation can have several global branches, and the chosen branch depends on the base point. If F_y=0, this theorem gives no local y-as-function conclusion, though x may be expressible as a function of y when F_x≠0. The formula follows from the multivariable chain rule but its applicability rests on the nonzero partial condition.",
    worked: "For F(x,y)=x²+y²-1 at (0,1), F_y=2≠0, so a local upper branch y(x) exists with y'(0)=-2x/(2y)=0. At (1,0), F_y=0, so the theorem does not describe y as a differentiable function of x there; the circle has a vertical tangent. Since F_x=2 at (1,0), one can instead solve locally for x as a function of y.",
    interpretation: "The theorem validates a local coordinate choice and a derivative formula. It does not assert a single-valued global graph for an entire curve.",
    trap: "Do not divide by F_y at a point where it is zero, and do not infer that failure of this hypothesis means no curve exists. It may only require a different local coordinate.",
    practice: "For F(x,y)=y³+xy-2, verify a local y(x) near (1,1), then compute y'(1).",
    solution: "F(1,1)=1+1-2=0. F_y=3y²+x, which equals 4 at (1,1), so the theorem applies. F_x=y, which equals 1 there. Therefore y'(1)=-F_x/F_y=-1/4. The conclusion concerns the branch near (1,1), not every solution of the cubic equation globally.",
    checks: [
      ["What condition allows local y=y(x) from F(x,y)=0?", ["F_y≠0 at the base point", "F_x=F_y=0", "F=1"], 0, "The y direction must be locally solvable."],
      ["What is the derivative of that branch?", ["-F_x/F_y", "F_x/F_y", "-F_y/F_x"], 0, "Differentiate F(x,y(x))=0."],
      ["Is the theorem's branch conclusion global?", ["No, local near the chosen point", "Always global", "Only for lines"], 0, "A curve can have multiple branches elsewhere."],
    ],
  },
];
