import type { MathLecture } from "./lectures";

/** Optimization and information concepts needed for a serious ML course. */
export const MATH_OPTIMIZATION_INFORMATION: MathLecture[] = [
  {
    lesson: "math.m20.l1", title: "Multivariable Taylor approximation",
    premise: "Local quadratic models explain how an ML objective responds to parameter changes and when a gradient step is likely to help.",
    idea: "For a twice continuously differentiable scalar objective f and small displacement h, f(x+h)≈f(x)+∇f(x)·h+(1/2)hᵀH(x)h. The gradient gives first-order change; the Hessian gives curvature, including mixed interactions. A descent direction h has ∇f·h<0 for sufficiently small step when the gradient is nonzero, but the quadratic term can reverse a too-large step. Taylor's theorem requires a controlled remainder to turn approximation into a bound. For positive-definite Hessian, the quadratic model has a unique local minimizer; near an indefinite Hessian, negative-curvature directions exist.",
    worked: "Let f(x,y)=x²+4y² at (1,1). Its gradient is (2,8) and Hessian diag(2,8). For h=(-0.1,-0.1), the exact change is gradient dot h, -1, plus quadratic correction (1/2)(2·0.01+8·0.01)=0.05. Thus f(0.9,0.9)=f(1,1)-0.95=4.05. The second-order Taylor model is exact because f is quadratic.",
    interpretation: "First-order change predicts descent; curvature adjusts the magnitude. In optimization, this guides step size and local trust.",
    trap: "Do not treat the first-order approximation as exact after a large step, or omit cross-Hessian terms for coupled parameters.",
    practice: "For f(x)=x² at x=2, use second-order Taylor expansion to compute f(2+h) exactly.",
    solution: "Here f(2)=4, f'(2)=4, and f''(2)=2. The expansion is 4+4h+(1/2)(2)h²=4+4h+h², equal to (2+h)². The remainder is zero because f is quadratic.",
    checks: [["What supplies the quadratic Taylor term?", ["Hessian", "Gradient only", "Function value only"], 0, "Second derivatives form the local curvature matrix."], ["What signals a first-order descent direction?", ["∇f·h<0", "∇f·h>0", "h=0"], 0, "The directional derivative is negative."], ["Does a negative first-order term guarantee descent for any step size?", ["No", "Yes", "Only for convex functions"], 0, "Higher-order or quadratic effects can dominate a large step."]],
  },
  {
    lesson: "math.m20.l2", title: "Gradient descent and learning rates",
    premise: "Gradient descent repeatedly moves opposite the local slope. The learning rate controls whether those steps converge, crawl, or overshoot.",
    idea: "The update is x_{k+1}=x_k-η∇f(x_k). For an L-smooth function, the descent lemma gives f(x-η∇f(x))≤f(x)-η(1-Lη/2)||∇f(x)||², so 0<η<2/L ensures decrease at nonstationary points under that global smoothness bound. Convexity gives stronger global statements; a nonconvex objective may have saddles and multiple local minima. Stochastic gradient descent uses noisy gradient estimates, trading cheaper steps for variance. Learning-rate schedules, momentum, and adaptive methods change dynamics but do not excuse a malformed objective or leaking validation data into tuning.",
    worked: "For f(x)=x², gradient is 2x and L=2. The update is x_{k+1}=(1-2η)x_k. If 0<η<1, |1-2η|<1 and iterates converge to zero. At η=1, the sign flips without shrinking; for η>1, magnitude grows. With η=1/4 and x₀=4, the sequence is 4,2,1,1/2,… .",
    interpretation: "The exact quadratic model exposes the stability threshold and shows why a large learning rate can fail even when the gradient direction is correct.",
    trap: "Do not infer that a decreasing training loss means good generalization; optimization and evaluation are separate problems.",
    practice: "For f(x)=3x² with x₀=2 and η=0.1, compute two gradient-descent updates.",
    solution: "Gradient is 6x, so multiplier is 1-6(0.1)=0.4. First x₁=0.8, then x₂=0.32. Objective values decrease from 12 to 1.92 to 0.3072.",
    checks: [["What is a gradient-descent update?", ["x-η∇f(x)", "x+η∇f(x)", "ηf(x)"], 0, "Move against local increase."], ["What can a too-large η cause?", ["Overshoot or divergence", "Guaranteed faster convergence", "Zero gradient"], 0, "Curvature sets a stability scale."], ["Does low training loss prove generalization?", ["No", "Yes", "Only with convex loss"], 0, "Evaluate on data independent of fitting decisions."]],
  },
  {
    lesson: "math.m20.l3", title: "Convex sets and convex functions",
    premise: "Convexity turns local minima into global minima and makes an entire segment between feasible points remain feasible.",
    idea: "A set C is convex if θx+(1-θ)y∈C for all x,y∈C and θ∈[0,1]. A function f on convex C is convex if f(θx+(1-θ)y)≤θf(x)+(1-θ)f(y). If differentiable, a first-order characterization is f(y)≥f(x)+∇f(x)·(y-x). If twice differentiable on an open convex domain, a positive-semidefinite Hessian everywhere is sufficient and, under usual regularity, equivalent to convexity. Strict convexity gives at most one minimizer if one exists; convexity alone can have an entire minimizing region. Convexity of an objective says nothing about feasible constraints unless the feasible set is also convex.",
    worked: "f(x)=x² has second derivative 2>0, so it is strictly convex on R. Its stationary point x=0 is the unique global minimum. By contrast, f(x)=|x| is convex but not differentiable at zero; its minimum still occurs at zero, showing differentiability is not required for convexity.",
    interpretation: "The geometry of the epigraph, points above the graph, explains why local dips cannot hide a lower value elsewhere in a convex problem.",
    trap: "Do not call a function convex because one plotted portion curves upward. The inequality must hold across the stated domain.",
    practice: "Is C={x∈R: |x|≥1} convex? If not, supply two points whose midpoint fails.",
    solution: "No. Both -1 and 1 are in C, but their midpoint 0 is not. Thus C is not convex even though its two separate pieces are intervals.",
    checks: [["What must a convex set contain for any two of its points?", ["The full segment between them", "Only their midpoint sometimes", "Every real vector"], 0, "That is the definition of set convexity."], ["What does convexity make a local minimum?", ["Global", "Always unique", "Always at zero"], 0, "A lower point elsewhere would violate the convex geometry."], ["Can a convex function be nondifferentiable?", ["Yes", "No", "Only at endpoints"], 0, "Absolute value is a standard example."]],
  },
  {
    lesson: "math.m20.l4", title: "Optimality conditions and Lagrange multipliers",
    premise: "At a smooth constrained optimum, the objective cannot improve along any feasible tangent direction. A multiplier expresses this alignment algebraically.",
    idea: "For minimize f(x) subject to g(x)=0, a regular candidate with ∇g≠0 satisfies ∇f=λ∇g and g=0. For several regular constraints, ∇f lies in the span of their gradients. These are necessary first-order conditions, not automatic global optimality claims. Inspect constraint singularities and boundaries separately. Second-order conditions test the Hessian of the Lagrangian on feasible tangent directions, while convexity of objective and feasible region can support global conclusions. Multipliers can also quantify sensitivity of the optimum to a small constraint change under suitable regularity, with sign depending on Lagrangian convention.",
    worked: "Minimize f(x,y)=x²+y² subject to x+y=2. Equations (2x,2y)=λ(1,1) imply x=y; the constraint gives x=y=1. The minimum value is 2. Geometrically this is the point on the line closest to the origin, and strict convexity of f along the line makes it the unique global minimum.",
    interpretation: "The objective gradient at (1,1) is parallel to the line's normal, so no first-order improvement is possible while remaining on the line.",
    trap: "Do not set ∇f=0 while ignoring the constraint. The unconstrained minimizer (0,0) is infeasible here.",
    practice: "Maximize xy subject to x+y=10 and x,y≥0.",
    solution: "Substitute y=10-x on 0≤x≤10. The product x(10-x) is a concave quadratic with derivative 10-2x, so its maximum is at x=5,y=5 with value 25. Boundaries give zero. The multiplier equations give the same interior candidate but still require comparison.",
    checks: [["What accompanies ∇f=λ∇g?", ["The constraint g=0", "Only f=0", "A positive determinant"], 0, "Candidates must be feasible."], ["Are multiplier equations by themselves sufficient for a global optimum?", ["No", "Yes", "Only in two dimensions"], 0, "Compare candidates and use appropriate curvature or convexity."], ["What directions matter at a constrained optimum?", ["Feasible tangents", "Every ambient direction", "Only coordinate axes"], 0, "Motion must respect the constraint."]],
  },
  {
    lesson: "math.m20.l5", title: "Constrained optimization and KKT conditions",
    premise: "Inequality constraints introduce active boundaries. KKT conditions track stationarity, feasibility, multiplier signs, and complementary slackness together.",
    idea: "For minimize f(x) subject to g_i(x)≤0, form L=f+Σλ_i g_i with λ_i≥0. Under an appropriate constraint qualification, a local optimum has stationarity ∇f+Σλ_i∇g_i=0, primal feasibility g_i≤0, dual feasibility λ_i≥0, and complementary slackness λ_i g_i=0. An inactive constraint has g_i<0 and thus λ_i=0; an active one may have λ_i>0. For convex differentiable f and g_i, with suitable regularity, KKT can characterize a global optimum. Without a qualification, multipliers may fail to exist, and in nonconvex problems KKT points need not be minima.",
    worked: "Minimize f(x)=(x-2)² subject to x≤1. Write g(x)=x-1≤0. The feasible optimum is x=1, where f'=2(x-2)=-2 and g'=1. Stationarity -2+λ=0 gives λ=2≥0; g=0, so complementary slackness holds. The unconstrained minimizer x=2 is infeasible.",
    interpretation: "The positive multiplier quantifies the active boundary's first-order influence under this sign convention.",
    trap: "Do not assign positive multipliers to strictly inactive constraints, and do not forget the inequality direction when choosing multiplier signs.",
    practice: "Minimize x² subject to x≤1. Identify the optimum and KKT multiplier for g(x)=x-1.",
    solution: "The unconstrained minimizer x=0 is feasible and the constraint is inactive because g(0)=-1<0. Stationarity at zero is 2x+λ=0, so λ=0. Complementary slackness holds. Convexity gives a global minimum.",
    checks: [["What does complementary slackness say?", ["λ_i g_i=0", "λ_i+g_i=0", "Every constraint is active"], 0, "Inactive constraints have zero multiplier."], ["What sign does λ_i have for g_i≤0 in L=f+Σλ_i g_i?", ["Nonnegative", "Nonpositive", "Any sign"], 0, "This convention uses λ_i≥0."], ["Can KKT alone certify every nonconvex candidate globally?", ["No", "Yes", "Only with one variable"], 0, "Additional structure is needed."]],
  },
  {
    lesson: "math.m20.l6", title: "Entropy, cross-entropy, and KL divergence",
    premise: "Information measures distinguish uncertainty in a true distribution from the cost of predicting it with another distribution.",
    idea: "For discrete P, entropy H(P)=-Σ_i p_i log p_i with 0 log 0 interpreted as zero. Cross-entropy H(P,Q)=-Σ_i p_i log q_i is infinite if some p_i>0 but q_i=0. KL divergence D_KL(P||Q)=Σ_i p_i log(p_i/q_i)=H(P,Q)-H(P) is nonnegative when defined and zero exactly when the distributions agree on the relevant support. KL is asymmetric and is not a metric. In classification, empirical cross-entropy with one-hot labels reduces to negative log probability assigned to the observed class. Low training cross-entropy need not imply calibrated probabilities or good out-of-sample performance.",
    worked: "Let P=(1/2,1/2) and Q=(3/4,1/4). Using natural logs, H(P)=log 2≈0.6931. Cross-entropy is -(1/2)log(3/4)-(1/2)log(1/4)≈0.8370. Thus KL≈0.1438 nats, positive because Q differs from P.",
    interpretation: "Cross-entropy exceeds the true entropy by the mismatch cost KL. The logarithm base determines units: natural logs give nats, base-2 logs bits.",
    trap: "Do not swap P and Q in KL and assume the result is unchanged; the divergence is directional.",
    practice: "For one observation of class 2 with predicted probabilities Q=(0.9,0.1), find one-hot cross-entropy using natural logs.",
    solution: "The one-hot target is P=(0,1). Cross-entropy is -log 0.1=log 10≈2.3026 nats. The high probability assigned to the wrong class produces a large penalty.",
    checks: [["What is H(P,Q)-H(P)?", ["D_KL(P||Q)", "D_KL(Q||P) always", "Zero always"], 0, "It is the mismatch cost under P."], ["Is KL symmetric?", ["No", "Yes", "Only with natural logs"], 0, "The expectation is under the first distribution."], ["What happens if q_i=0 where p_i>0?", ["Cross-entropy is infinite", "The term is zero", "Entropy vanishes"], 0, "Predicting impossible for an event that occurs is infinitely costly in this model."]],
  },
  {
    lesson: "math.m20.l7", title: "Numerical precision and stable computation",
    premise: "A correct formula can yield a wrong floating-point answer. Stable computations reformulate the same mathematics to avoid overflow, cancellation, and underflow.",
    idea: "Floating-point numbers have finite precision and range. Subtracting nearly equal numbers can lose significant digits; exponentiating large logits can overflow. For log-sum-exp, use m+log Σ_i exp(x_i-m), where m=max_i x_i, rather than log Σexp(x_i) directly. Softmax probabilities use exp(x_i-m)/Σexp(x_j-m). Summing many tiny terms can accumulate error, and problem conditioning limits how much accuracy any algorithm can promise. Distinguish a stable algorithm from an ill-conditioned problem. Test extreme inputs and compare against a higher-precision or analytically known reference where possible.",
    worked: "For logits (1000,1001), direct exp(1000) and exp(1001) overflow in ordinary floating-point implementations. Subtract m=1001 to get shifted logits (-1,0). Softmax becomes (e^{-1}/(1+e^{-1}),1/(1+e^{-1}))≈(0.269,0.731). The probabilities are unchanged by a common shift because it cancels from numerator and denominator.",
    interpretation: "The reformulation preserves the exact mathematical result while moving intermediate values into a safe numerical range.",
    trap: "Do not interpret finite output from one test input as proof of numerical stability; test extremes and cancellation-prone inputs.",
    practice: "Compute log(exp(700)+exp(701)) using the stable log-sum-exp identity without evaluating those exponentials directly.",
    solution: "Take m=701. The result is 701+log(exp(-1)+1)≈701+0.3133=701.3133. Both exponentials inside the logarithm are safe and at most one.",
    checks: [["What shift stabilizes softmax logits?", ["Subtract their maximum", "Add their maximum", "Square them"], 0, "The common shift cancels mathematically."], ["What is catastrophic cancellation?", ["Loss of relative precision when subtracting close values", "A large exact determinant", "A negative gradient"], 0, "Leading digits cancel in finite precision."], ["Can stable code fix a severely ill-conditioned problem completely?", ["No", "Yes", "Only with softmax"], 0, "Input sensitivity remains a separate limitation."]],
  },
  {
    lesson: "math.m20.l8", title: "ML readiness proof and computation capstone",
    premise: "Machine-learning mathematics becomes useful when assumptions, a derivation, a computation, and an evaluation decision agree. This capstone connects those parts.",
    idea: "Take a binary prediction task and state the sampled population, feature vector, label mechanism, and train-test split. Choose logistic model p_θ(y=1|x)=σ(θ·x), with σ(z)=1/(1+e^{-z}). For independent labeled observations, negative log likelihood is binary cross-entropy. Derive its gradient Σ_i(σ(θ·x_i)-y_i)x_i, optionally scaled by sample count. With L2 penalty λ||θ||²/2, add λθ to the gradient. Compute predictions stably, fit only on training data, and evaluate held-out discrimination and calibration separately. The convex objective in θ for fixed features has no non-global local minima, but separation may prevent an unregularized finite minimizer. A good numerical optimizer cannot repair biased labels or leakage.",
    worked: "For one observation x=(1,2), y=1, and θ=(0,0), the logit is zero and predicted probability is 1/2. Binary cross-entropy is -log(1/2)=log 2. The unscaled gradient is (1/2-1)x=(-1/2,-1). A small descent step with η=0.1 gives θ=(0.05,0.1), raising the logit on this positive example to 0.25.",
    interpretation: "The gradient direction follows directly from likelihood; the step improves this one training example locally but says nothing about generalization by itself.",
    trap: "Do not use the same labeled example to both tune a threshold and claim an unbiased test score. Separate fitting choices from final evaluation.",
    practice: "At θ=0 for one observation x=(2,-1), y=0, compute predicted probability, binary cross-entropy, and unscaled gradient.",
    solution: "The logit is 0, so p=1/2 and loss is -log(1-p)=log 2. Gradient (p-y)x=(1/2)(2,-1)=(1,-1/2). A descent step decreases the logit for this negative example to first order, lowering its predicted positive probability.",
    checks: [["What is the logistic-loss gradient contribution of one case?", ["(p-y)x", "(y-p) only", "p x²"], 0, "Differentiate cross-entropy through the sigmoid."], ["What does L2 penalty add to the gradient?", ["λθ", "λ only", "Nothing"], 0, "Differentiate λ||θ||²/2."], ["Does training improvement establish held-out calibration?", ["No", "Yes", "Only for convex losses"], 0, "Evaluation must use independent data."]],
  },
];
