import type { MathLecture } from "./lectures";

/** PDE course: modeling, exact solutions, weak forms, and numerical checks. */
export const MATH_PARTIAL_DIFFERENTIAL_EQUATIONS: MathLecture[] = [
  {
    lesson: "math.m25.l1", title: "Classifying PDEs and boundary data",
    premise: "A PDE constrains a field across space and time; its type and boundary data determine which solution methods make sense.",
    idea: "For a second-order linear PDE in two spatial variables, A u_xx+2B u_xy+C u_yy+lower terms=0, classify using B²-AC: negative is elliptic, zero parabolic, positive hyperbolic. Laplace, heat, and wave equations are prototypes, though the heat equation has a time derivative and classification needs its principal part. Initial values describe a time slice; Dirichlet conditions prescribe values on a boundary, Neumann conditions prescribe normal derivatives. A well-posed problem needs appropriate data for its equation and domain: existence, uniqueness, and continuous dependence are distinct requirements. Too many or conflicting boundary conditions can make a system inconsistent.",
    worked: "For u_xx+u_yy=0, A=C=1 and B=0, so B²-AC=-1 and the spatial PDE is elliptic. For u_xx-u_yy=0 it is positive and hyperbolic. Solving u_t=κu_xx on 0<x<L usually needs an initial profile u(x,0) plus boundary conditions at x=0 and x=L.",
    interpretation: "Classifying the principal derivatives is a first guide to propagation, smoothing, and suitable data.",
    trap: "Do not transfer a boundary prescription from one PDE to another without checking compatibility and well-posedness.",
    practice: "Classify 2u_xx+4u_xy+u_yy=0 by computing its discriminant.",
    solution: "The convention is A=2, 2B=4 so B=2, and C=1. Then B²-AC=4-2=2>0, hence hyperbolic. Using B=4 would incorrectly classify the coefficients.",
    checks: [["What discriminant classifies the two-variable principal part?", ["B²-AC when mixed coefficient is 2B", "A+B+C", "AC only"], 0, "Use the stated coefficient convention."], ["What is Dirichlet data?", ["Boundary values of the field", "Its normal derivative", "Only initial time values"], 0, "It specifies u on the boundary."], ["Does existence alone make a PDE problem well posed?", ["No", "Yes", "Only on a disk"], 0, "Uniqueness and continuous dependence also matter."]],
  },
  {
    lesson: "math.m25.l2", title: "Heat equation and separation of variables",
    premise: "Diffusion smooths temperature differences; Fourier modes decay at rates set by their spatial frequency.",
    idea: "For u_t=κu_xx on 0<x<L with zero endpoint values, try u=X(x)T(t). Separating gives T'/(κT)=X''/X=-λ. Boundary conditions require X_n=sin(nπx/L), λ_n=(nπ/L)² for n≥1, and T_n=e^{-κλ_n t}. Expand a suitable initial profile f in a Fourier sine series: u(x,t)=Σ b_n sin(nπx/L)e^{-κ(nπ/L)²t}. The coefficients are b_n=(2/L)∫₀ᴸ f(x)sin(nπx/L)dx. Higher-frequency modes decay faster. Endpoint or nonsmooth initial data needs attention to the sense in which the series attains f at t=0.",
    worked: "With L=π, κ=2, and f(x)=3sin x+sin 2x, the solution is u=3e^{-2t}sin x+e^{-8t}sin 2x. Direct substitution gives u_t=2u_xx, and both endpoints are zero for all t.",
    interpretation: "Separation turns a PDE into spatial eigenfunctions multiplied by simple time evolution.",
    trap: "Do not drop boundary conditions when choosing spatial modes; not every separated solution belongs to the problem.",
    practice: "Solve u_t=u_xx on 0<x<π with zero endpoint values and u(x,0)=2sin(3x).",
    solution: "The initial profile is one sine eigenmode, with eigenvalue 3²=9. Its amplitude decays as e^{-9t}, so u(x,t)=2e^{-9t}sin(3x). This satisfies the PDE, boundaries, and initial profile.",
    checks: [["How does the nth zero-boundary sine mode decay?", ["e^{-κ(nπ/L)²t}", "e^{+κnt}", "At the same rate for all n"], 0, "Its Laplacian eigenvalue scales like n²."], ["Which modes decay faster?", ["Higher spatial frequencies", "Lower spatial frequencies", "All identically"], 0, "The exponent contains n²."], ["What fixes the Fourier coefficients?", ["The initial profile", "The name of the variable", "A random seed"], 0, "Match u(x,0) to f(x)."]],
  },
  {
    lesson: "math.m25.l3", title: "Wave equation and energy",
    premise: "Unlike diffusion, waves transport disturbances and conserve an energy under appropriate boundaries.",
    idea: "For u_tt=c²u_xx on a string, specify initial displacement f(x)=u(x,0) and velocity g(x)=u_t(x,0), plus appropriate endpoint conditions. On the infinite line, d'Alembert's formula is u(x,t)=[f(x-ct)+f(x+ct)]/2+(1/(2c))∫_{x-ct}^{x+ct}g(s)ds under suitable regularity. For a fixed-end string, E(t)=1/2∫[u_t²+c²u_x²]dx is constant when boundary flux vanishes: differentiate E, use u_tt=c²u_xx, integrate by parts, and obtain boundary term c²[u_tu_x]. A forced or damped wave may not conserve this E.",
    worked: "With zero initial velocity and initial displacement f(x)=cos x on the line, d'Alembert gives [cos(x-ct)+cos(x+ct)]/2=cos x cos(ct). Differentiating twice verifies u_tt=c²u_xx; at t=0 it restores cos x and zero velocity.",
    interpretation: "A wave equation carries information at finite speed c rather than instantly smoothing all frequencies.",
    trap: "Do not assume energy conservation when boundary work, forcing, or damping contributes energy flux.",
    practice: "On the whole line let f(x)=0 and g(x)=1. Use d'Alembert's formula.",
    solution: "The displacement terms vanish and the integral of 1 over [x-ct,x+ct] is 2ct. Divide by 2c to get u(x,t)=t. It has u(x,0)=0, u_t(x,0)=1, and both second derivatives zero, satisfying the equation.",
    checks: [["What initial data does a second-order-time wave equation need?", ["Displacement and velocity", "Displacement only", "Velocity only"], 0, "Two time derivatives require two initial conditions."], ["What does c represent?", ["Propagation speed", "Heat capacity always", "Boundary length"], 0, "Disturbances travel at speed c on the line."], ["When is the displayed string energy conserved?", ["When boundary flux and forcing vanish", "With arbitrary damping", "With arbitrary boundary work"], 0, "Energy balance includes external terms."]],
  },
  {
    lesson: "math.m25.l4", title: "Laplace and Poisson equations",
    premise: "Steady-state fields often satisfy a Laplace or Poisson equation, whose solutions are shaped by boundary values and sources.",
    idea: "Laplace's equation is Δu=0; Poisson's equation is -Δu=f under one common sign convention. A harmonic u obeys a mean-value property on balls inside its domain and therefore cannot have a strict interior maximum unless constant on a connected domain. With Dirichlet boundary data, uniqueness follows from the maximum principle for suitable bounded connected domains. Poisson's source term changes curvature. Neumann problems prescribe normal derivative and require a compatibility condition: integrating -Δu=f yields -∫∂Ω ∂_n u=∫Ω f by the divergence theorem; a solution is determined only up to an additive constant under pure Neumann data.",
    worked: "On interval (0,1), solve -u''=2 with u(0)=u(1)=0. Integrating gives u=-x²+Cx+D. The first endpoint gives D=0; the second gives C=1; hence u=x(1-x), positive inside and zero at the boundary.",
    interpretation: "The source bends the field, while boundary data select a solution from the differential family.",
    trap: "Do not assert uniqueness for pure Neumann data without fixing the additive constant and checking compatibility.",
    practice: "Solve u''=0 on (0,2) with u(0)=1 and u(2)=5.",
    solution: "A one-dimensional harmonic function is affine: u(x)=Ax+B. u(0)=1 gives B=1, and 2A+1=5 gives A=2, so u(x)=2x+1. Its second derivative is zero and both endpoint values match.",
    checks: [["What is a harmonic function?", ["A solution of Δu=0", "Any periodic function", "A function with positive second derivative"], 0, "It has vanishing Laplacian."], ["What can pure Neumann data leave undetermined?", ["An additive constant", "The entire gradient", "The domain"], 0, "Derivatives ignore constants."], ["Can a nonconstant harmonic function attain a strict interior maximum?", ["No, under maximum-principle hypotheses", "Always", "Only in one dimension"], 0, "The mean-value property rules it out."]],
  },
  {
    lesson: "math.m25.l5", title: "Fourier series and transforms",
    premise: "The Fourier transform replaces spatial differentiation with multiplication by frequency, making many linear PDEs easier to solve.",
    idea: "Use convention F[u](ξ)=∫u(x)e^{-iξx}dx, inverse u(x)=(1/2π)∫F[u](ξ)e^{iξx}dξ for suitable functions. Integration by parts gives F[u_x]=iξF[u] and F[u_xx]=-ξ²F[u] when boundary terms vanish. Transforming the heat equation gives ∂_t û=-κξ² û, hence û(ξ,t)=e^{-κξ²t}û₀(ξ). Inverse transforming yields convolution with a Gaussian heat kernel for t>0. On bounded periodic intervals, discrete Fourier series replace the continuous transform. Constants and regularity depend on convention and function space.",
    worked: "For a periodic mode u₀(x)=cos(3x) and u_t=2u_xx, the second derivative is -9cos(3x), so its coefficient solves a'=-18a. Thus u(x,t)=e^{-18t}cos(3x). This is the discrete-frequency form of the transform equation.",
    interpretation: "Linear constant-coefficient differentiation becomes algebra on each frequency, which reveals smoothing and propagation laws.",
    trap: "Do not mix transform conventions: signs and 2π factors depend on the chosen forward and inverse definitions.",
    practice: "Under the stated convention, what does F[-u_xx] equal, and how does a frequency ξ=4 evolve for u_t=u_xx?",
    solution: "Since F[u_xx]=-ξ²û, F[-u_xx]=ξ²û. For heat flow with κ=1, a frequency 4 has multiplier e^{-ξ²t}=e^{-16t}. These statements assume sufficient decay or an appropriate distributional interpretation.",
    checks: [["What multiplier corresponds to u_xx under the stated Fourier convention?", ["-ξ²", "ξ", "1/ξ"], 0, "Two derivatives each multiply by iξ."], ["What happens to high heat-flow frequencies?", ["They decay faster", "They grow faster", "They stay fixed"], 0, "The exponent is -κξ²t."], ["Are Fourier normalization constants universal?", ["No", "Yes", "Only for sine waves"], 0, "State the convention first."]],
  },
  {
    lesson: "math.m25.l6", title: "Weak formulations",
    premise: "A weak solution satisfies an integrated equation against test functions, allowing derivatives to move from a rough solution onto smoother tests.",
    idea: "For -u''=f on (0,1) with u=0 at endpoints, multiply by a test v with v=0 at endpoints and integrate. Integration by parts yields ∫u'v'=∫fv. This is the weak form. It needs only a first weak derivative u' in L², rather than a classical second derivative. On a domain Ω, Poisson's equation with zero boundary data has weak form ∫Ω ∇u·∇v=∫Ω fv for all v in H₀¹(Ω). Suitable assumptions, Poincaré's inequality, and the Lax-Milgram theorem give existence and uniqueness. Different boundary conditions change the boundary terms and test space.",
    worked: "For f=2 on (0,1), the classical solution u=x(1-x) has u'=1-2x. For any smooth v vanishing at both endpoints, ∫(1-2x)v'=[(1-2x)v]₀¹+2∫v=2∫v. This verifies the weak equation without directly testing u'' pointwise.",
    interpretation: "The integral identity preserves the PDE's content in a space where rough solutions and finite-element approximations can live.",
    trap: "Do not drop the integration-by-parts boundary term unless the test space or boundary condition makes it vanish.",
    practice: "Derive the weak form of -u''=f on (0,L) with u(0)=u(L)=0.",
    solution: "Multiply by smooth v with v(0)=v(L)=0 and integrate: -∫₀ᴸu''v=∫₀ᴸfv. Integration by parts gives ∫₀ᴸu'v' - [u'v]₀ᴸ=∫fv. The boundary term is zero, so ∫u'v'=∫fv for all such v, extended to H₀¹ by density.",
    checks: [["What derivative order of u appears in the weak Poisson form?", ["First", "Second pointwise", "None"], 0, "Integration by parts moves one derivative."], ["Why does the boundary term vanish for H₀¹ tests?", ["Their boundary trace is zero", "Every derivative is zero", "The interval is short"], 0, "The test function vanishes at the boundary."], ["Can weak solutions be less classically smooth?", ["Yes", "No", "Only in one dimension"], 0, "That is a central purpose of weak formulation."]],
  },
  {
    lesson: "math.m25.l7", title: "Finite-difference discretization",
    premise: "Finite differences replace derivatives by local stencils on a grid, producing algebraic systems whose error must be checked.",
    idea: "At interior grid point x_i, centered second difference (u_{i-1}-2u_i+u_{i+1})/h² approximates u''(x_i) with O(h²) local truncation error if u has four derivatives. For -u''=f with Dirichlet endpoints, this gives a tridiagonal linear system with diagonal 2/h² and adjacent entries -1/h². The boundary values move into the right-hand side at first and last interior nodes. Refining h increases accuracy only if the scheme is stable, data are resolved, and solver error is controlled. In multiple dimensions, stencil structure reflects the grid and operator.",
    worked: "For -u''=2 on [0,1] with zero endpoints and a single interior node x=.5, h=.5. The discrete equation is -(0-2u₁+0)/(.5²)=2, so 8u₁=2 and u₁=.25. The exact solution x(1-x) also equals .25 at the node.",
    interpretation: "A simple exact nodal match is a useful sanity check, but convergence needs tests on several grids.",
    trap: "Do not apply an interior stencil at a boundary without inserting the actual boundary condition.",
    practice: "For -u''=0 on [0,1] with u(0)=0,u(1)=1 and one interior node at .5, solve the discrete equation.",
    solution: "The centered discrete equation is -(0-2u₁+1)/(.5²)=0. Thus 2u₁-1=0, giving u₁=.5, consistent with the exact linear solution u(x)=x.",
    checks: [["What is the centered second-difference stencil?", ["(u_{i-1}-2u_i+u_{i+1})/h²", "(u_{i+1}-u_i)/h", "u_i/h²"], 0, "It uses three adjacent nodes."], ["What system arises in one-dimensional Dirichlet Poisson?", ["Tridiagonal", "Always dense", "No system"], 0, "Each node couples only to neighbors."], ["What must be inserted near the boundary?", ["Boundary data", "An arbitrary zero", "A random eigenvalue"], 0, "The stencil depends on the prescribed boundary."]],
  },
  {
    lesson: "math.m25.l8", title: "Stability, consistency, and convergence",
    premise: "A PDE discretization can approximate derivatives locally yet fail globally if errors are amplified by its time-stepping rule.",
    idea: "Consistency means local truncation error tends to zero as grid spacings shrink; stability means perturbations remain controlled under the chosen norm and refinement regime; convergence means numerical solutions approach the PDE solution. For a well-posed linear initial-value problem, a suitable version of the Lax equivalence theorem links consistency plus stability to convergence. For explicit forward-time centered-space heat flow, r=κΔt/Δx² must satisfy r≤1/2 in one dimension for the standard scheme: the update u_i^{n+1}=r u_{i-1}^n+(1-2r)u_i^n+r u_{i+1}^n then has nonnegative averaging weights. Beyond this range, high-frequency modes can grow. Other PDEs and schemes have different stability regions.",
    worked: "Take κ=1, Δx=.1. Then Δx²=.01 and the heat-scheme condition requires Δt≤.005. At Δt=.01, r=1 and the center coefficient 1-2r=-1; a checkerboard mode is amplified rather than smoothed even though the spatial stencil is consistent.",
    interpretation: "A correct local derivative approximation is only one part of a trustworthy time-dependent solver.",
    trap: "Do not apply a heat-equation CFL bound to an unrelated wave scheme; derive or cite the bound for the exact update used.",
    practice: "For κ=2 and Δx=.2, calculate the largest Δt allowed by r≤1/2 for the explicit one-dimensional heat scheme.",
    solution: "r=κΔt/Δx²=2Δt/.04=50Δt. Requiring 50Δt≤.5 gives Δt≤.01. This is a stability bound, not an accuracy guarantee.",
    checks: [["Does consistency alone imply convergence?", ["No", "Yes", "Only for a uniform grid"], 0, "Unstable errors can grow."], ["What is the one-dimensional explicit heat ratio r?", ["κΔt/Δx²", "κΔx/Δt", "Δt+Δx"], 0, "Diffusive time scale is proportional to length squared."], ["What is the standard bound for this scheme?", ["r≤1/2", "r≥2", "No bound"], 0, "Its averaging weights must remain controlled."]],
  },
];
