import type { MathLecture } from "./lectures";

/** Probability foundation before inference and machine-learning objectives. */
export const MATH_PROBABILITY: MathLecture[] = [
  {
    lesson: "math.m18.l1", title: "Sample spaces and events",
    premise: "Probability begins with a defined experiment, an event space, and a rule assigning mass. A story about chance is not enough to justify equal likelihood.",
    idea: "A sample space Ω contains possible elementary outcomes; an event A is a subset of Ω. A probability measure has P(Ω)=1, assigns nonnegative probability, and adds across disjoint events. In a finite equiprobable model, P(A)=|A|/|Ω|; in a weighted discrete model, sum outcome masses instead. Complement gives P(Aᶜ)=1-P(A). Union satisfies P(A∪B)=P(A)+P(B)-P(A∩B), whether or not A and B are independent. State whether outcomes are ordered or unordered and how the random mechanism generates them.",
    worked: "A fair die has Ω={1,2,3,4,5,6}. Let A be even outcomes {2,4,6} and B outcomes at least 5 {5,6}. Then P(A)=3/6, P(B)=2/6, and P(A∩B)=1/6. The union probability is 3/6+2/6-1/6=4/6, matching {2,4,5,6}.",
    interpretation: "Explicit event sets make overlap visible and reveal exactly where the correction term arises.",
    trap: "Do not treat every named event as equally likely or disjoint. The outcome model decides probability, not the wording of event names.",
    practice: "A bag contains 2 red and 3 blue balls. One ball is drawn uniformly. Find P(red), P(not red), and P(red or blue).",
    solution: "Each of 5 physical balls is equally likely. P(red)=2/5 and P(not red)=3/5. Every ball is red or blue, so P(red or blue)=1. The color outcomes themselves are not equally likely.",
    checks: [["What is an event?", ["A subset of the sample space", "Only one outcome", "A probability number"], 0, "An event may contain multiple outcomes."], ["When may we count favorable outcomes over total outcomes?", ["When elementary outcomes are equiprobable", "Always", "Only for two outcomes"], 0, "Otherwise sum assigned masses."], ["What is P(Aᶜ)?", ["1-P(A)", "P(A)", "1+P(A)"], 0, "Event and complement partition Ω."]],
  },
  {
    lesson: "math.m18.l2", title: "Conditional probability and Bayes' rule",
    premise: "New evidence changes the relevant sample space. Bayes' rule reverses a conditional probability by accounting for how common each cause was before the evidence.",
    idea: "For P(B)>0, P(A|B)=P(A∩B)/P(B). Multiplication gives P(A∩B)=P(A|B)P(B). If H₁,…,H_k partition the space, total probability gives P(E)=ΣP(E|H_i)P(H_i). Bayes then gives P(H_j|E)=P(E|H_j)P(H_j)/P(E), provided P(E)>0. Independence means P(A|B)=P(A) where conditioning is defined, not merely that the events have different labels. Separate prevalence from sensitivity and specificity when interpreting a positive test.",
    worked: "Suppose 1% have a condition. A test is positive for 90% with it and for 5% without it. P(positive)=0.90·0.01+0.05·0.99=0.0585. Therefore P(condition|positive)=0.009/0.0585≈0.154, about 15.4%. The result is much lower than 90% because false positives occur among a far larger group.",
    interpretation: "The prior frequency matters. A test's sensitivity is not the probability of disease after a positive result.",
    trap: "Do not swap P(E|H) with P(H|E); Bayes' denominator and prior are essential.",
    practice: "Two boxes are chosen equally often. Box A gives a red ball with probability 3/4; Box B with probability 1/4. After a red draw, what is P(A|red)?",
    solution: "P(red)=0.5(3/4)+0.5(1/4)=1/2. The joint probability of A and red is 0.5(3/4)=3/8. Divide by P(red)=1/2 to get P(A|red)=3/4.",
    checks: [["What is P(A|B) for P(B)>0?", ["P(A∩B)/P(B)", "P(B)/P(A)", "P(A∩B) always"], 0, "Restrict to the B cases."], ["What does Bayes' rule require beyond likelihood?", ["Prior and evidence probability", "Only a test name", "Equal class sizes"], 0, "Posterior is normalized prior times likelihood."], ["Is sensitivity equal to posterior probability after a positive test?", ["Generally no", "Always", "Only when test is accurate"], 0, "Base rates and false positives matter."]],
  },
  {
    lesson: "math.m18.l3", title: "Random variables and distributions",
    premise: "A random variable maps outcomes to numbers. Its distribution records probabilities of those numerical values, regardless of how the original outcomes were labeled.",
    idea: "A discrete random variable X assigns a real number to every outcome. Its probability mass function p_X(x)=P(X=x) has nonnegative values summing to one. The cumulative distribution function F_X(t)=P(X≤t) is nondecreasing, right-continuous, and approaches zero and one at the ends. A continuous variable may have a density f_X with P(a≤X≤b)=∫_a^b f_X(x)dx; a density can exceed one, but total area is one. For a genuinely continuous distribution, P(X=a)=0. Many distributions have both atoms and continuous components, so neither a pure mass table nor a pure density covers every possible law.",
    worked: "Flip two independent fair coins and let X count heads. The four equally likely outcomes TT,TH,HT,HH yield p_X(0)=1/4, p_X(1)=1/2, p_X(2)=1/4. Thus F_X(0)=1/4, F_X(1)=3/4, and F_X(2)=1. The values of X are not equally likely even though the underlying ordered coin outcomes are.",
    interpretation: "The distribution aggregates elementary outcomes with the same numeric count.",
    trap: "Do not treat a density value f_X(x) as P(X=x). For a continuous law, point probability is zero despite a positive density.",
    practice: "If X has mass 0.2 at -1, 0.5 at 0, and 0.3 at 2, compute P(X≤0) and P(X>0).",
    solution: "P(X≤0)=0.2+0.5=0.7. P(X>0)=0.3. They sum to one because the two events partition the possible values.",
    checks: [["What does a random variable map?", ["Outcomes to numbers", "Probabilities to colors", "Only real numbers to events"], 0, "Its distribution is induced by the outcome probability."], ["Must a density stay below one?", ["No", "Yes", "Only for normal laws"], 0, "Area, not point height, is probability."], ["What is F_X(t)?", ["P(X≤t)", "P(X=t) always", "The derivative of X"], 0, "It accumulates probability up to t."]],
  },
  {
    lesson: "math.m18.l4", title: "Expectation, variance, and covariance",
    premise: "Expectation is a probability-weighted average. Variance and covariance describe spread and joint movement around means.",
    idea: "For discrete X, E[X]=Σx p_X(x) when the sum is integrable; for density f, E[X]=∫x f(x)dx when absolutely integrable. Linearity E[aX+bY]=aE[X]+bE[Y] needs no independence. Variance Var(X)=E[(X-E[X])²]=E[X²]-E[X]² when the second moment exists. Cov(X,Y)=E[(X-EX)(Y-EY)]=E[XY]-EX·EY. Independence implies zero covariance when moments exist, but zero covariance does not generally imply independence. For independent X,Y, Var(X+Y)=Var(X)+Var(Y); otherwise add 2Cov(X,Y).",
    worked: "Let X be 1 with probability 1/4 and 3 with probability 3/4. E[X]=1/4+9/4=5/2. E[X²]=1/4+27/4=7. Thus Var(X)=7-(5/2)²=3/4. The standard deviation is sqrt(3)/2, in the same units as X.",
    interpretation: "Expectation need not be a possible outcome: 2.5 is not one of this variable's values. Variance has squared units.",
    trap: "Do not use E[X²] as variance without subtracting the squared mean, and do not infer independence from zero covariance alone.",
    practice: "If independent X and Y have means 2 and -1 and variances 3 and 4, find E[2X+Y] and Var(2X+Y).",
    solution: "Linearity gives E[2X+Y]=2·2-1=3. Independence makes covariance zero, so Var(2X+Y)=2²·3+4=16. Means play no role in this variance sum except through each given variance.",
    checks: [["Does expectation linearity require independence?", ["No", "Yes", "Only for constants"], 0, "It holds whenever expectations exist."], ["What is Var(X) in terms of moments?", ["E[X²]-E[X]²", "E[X²]", "E[X]²"], 0, "Subtract the mean-square term."], ["Does zero covariance always imply independence?", ["No", "Yes", "Only for discrete variables"], 0, "Dependence can be nonlinear."]],
  },
  {
    lesson: "math.m18.l5", title: "Joint, marginal, and conditional laws",
    premise: "A joint law describes two variables together. Marginalization forgets one variable; conditioning restricts the law after learning its value.",
    idea: "For discrete X,Y, the joint mass p(x,y)=P(X=x,Y=y) sums to one. Marginals satisfy p_X(x)=Σ_y p(x,y) and p_Y(y)=Σ_x p(x,y). When p_Y(y)>0, p_{X|Y}(x|y)=p(x,y)/p_Y(y). Independence requires p(x,y)=p_X(x)p_Y(y) for every pair in the support, not merely one coincidence. For continuous variables, replace sums by integrals and condition on Y=y through a conditional density when the marginal density is positive; conditioning on an exact zero-probability point needs this density framework rather than naive division by P(Y=y)=0.",
    worked: "Let (X,Y) have mass 1/4 at (0,0), 1/4 at (0,1), and 1/2 at (1,1). Then P(Y=1)=3/4 and P(X=1)=1/2. Given Y=1, P(X=1|Y=1)=(1/2)/(3/4)=2/3. This differs from P(X=1)=1/2, so X and Y are dependent.",
    interpretation: "Observing Y=1 changes the distribution of X; the joint table contains information absent from either marginal alone.",
    trap: "Do not normalize a row or column by the wrong marginal. A conditional distribution must sum to one over its remaining variable.",
    practice: "For the same joint table, find P(X=0|Y=1) and verify the two conditional X probabilities sum to one.",
    solution: "Joint mass at (0,1) is 1/4 and P(Y=1)=3/4, so P(X=0|Y=1)=1/3. Together with P(X=1|Y=1)=2/3, the probabilities sum to one.",
    checks: [["How is p_X(x) obtained from a discrete joint law?", ["Sum over all y", "Divide by p_Y(y) for one y", "Take the maximum"], 0, "Marginalize the other variable."], ["What denominator defines p_{X|Y}(x|y)?", ["p_Y(y)", "p_X(x)", "One always"], 0, "Restrict to the observed Y value."], ["What equality expresses independence?", ["p(x,y)=p_X(x)p_Y(y) for all pairs", "Equal means", "Zero covariance only"], 0, "The full joint law must factor."]],
  },
  {
    lesson: "math.m18.l6", title: "Common discrete and continuous families",
    premise: "Named distributions encode repeatable experiment structures. Choosing one means checking the process assumptions, not matching a familiar-looking histogram.",
    idea: "A Bernoulli(p) variable takes 1 with probability p and 0 otherwise; a Binomial(n,p) counts successes in n independent identical Bernoulli trials. A Poisson(λ) models counts under a specified rate model and has mean and variance λ. A Uniform(a,b) variable has constant density 1/(b-a) on its interval. A Normal(μ,σ²) variable has bell-shaped density and parameters mean μ and variance σ²; linear combinations of independent normals remain normal. An Exponential(λ) waiting time has density λe^{-λt} for t≥0 and mean 1/λ. Independence, constant rate, and support assumptions must be justified in applications.",
    worked: "If five independent components each fail with probability 0.1, the count X of failures is Binomial(5,0.1). P(X=1)=C(5,1)(0.1)(0.9)^4≈0.32805. Its mean is np=0.5 and variance np(1-p)=0.45. Counting exactly one failure requires selecting which component failed.",
    interpretation: "A count distribution is appropriate because there are a fixed number of independent, identically distributed binary trials.",
    trap: "Do not call a count binomial if success probabilities differ substantially between trials or outcomes are dependent without a model that addresses that dependence.",
    practice: "If T~Exponential(2) with time in hours, find P(T>1) and the mean wait.",
    solution: "The survival function is P(T>t)=e^{-2t} for t≥0, so P(T>1)=e^{-2}≈0.1353. Its mean is 1/2 hour. The rate parameter 2 has units per hour.",
    checks: [["What does Binomial(n,p) assume?", ["Fixed independent identical Bernoulli trials", "Any set of counts", "A continuous waiting time"], 0, "The trial structure defines the family."], ["What is the mean of Exponential(λ)?", ["1/λ", "λ", "λ²"], 0, "Rate and mean waiting time are reciprocals."], ["What is Poisson(λ) variance?", ["λ", "λ²", "1/λ"], 0, "In the basic Poisson model mean and variance both equal λ."]],
  },
  {
    lesson: "math.m18.l7", title: "Law of large numbers",
    premise: "Repeated averages settle near the population mean under suitable assumptions. The law describes convergence as sample size grows, not certainty for any one finite sample.",
    idea: "For independent identically distributed variables with finite mean μ, the weak law says the sample average converges in probability to μ. With finite variance σ², Var(X̄_n)=σ²/n; Chebyshev gives P(|X̄_n-μ|≥ε)≤σ²/(nε²), which tends to zero. The strong law gives almost-sure convergence under suitable integrability conditions. Independence and a common distribution are sufficient classical assumptions, though broader versions exist. The law does not state that individual observations converge to μ, that averages are unbiased under every sampling scheme, or that rare events become impossible.",
    worked: "For independent fair Bernoulli trials, μ=1/2 and σ²=1/4. The average of n outcomes is the observed success fraction with variance 1/(4n). Chebyshev bounds the probability of deviation at least 0.1 by 25/n; this bound becomes informative only for n>25 and tends to zero as n grows.",
    interpretation: "The bound is conservative but shows mathematically why sample averages concentrate under the stated assumptions.",
    trap: "Do not claim a sample of 100 must contain exactly 50 successes. The law is asymptotic and probabilistic.",
    practice: "For independent variables with mean 3 and variance 9, bound P(|X̄_400-3|≥1) using Chebyshev.",
    solution: "Var(X̄_400)=9/400. Chebyshev gives probability at most (9/400)/1²=0.0225. The true probability may be smaller; without more distribution information the bound is all this method provides.",
    checks: [["What converges toward μ in the law of large numbers?", ["The sample average", "Every individual outcome", "The maximum"], 0, "Averages aggregate many observations."], ["What is Var(X̄_n) for independent identical finite-variance data?", ["σ²/n", "nσ²", "σ²"], 0, "Variances add and scaling by 1/n squares."], ["Does LLN guarantee an exact finite-sample mean?", ["No", "Yes", "Only for fair coins"], 0, "It is a limiting statement."]],
  },
  {
    lesson: "math.m18.l8", title: "Central limit theorem",
    premise: "Under suitable conditions, properly standardized sums become approximately normal even when individual observations are not normal.",
    idea: "For independent identically distributed X_i with finite mean μ and positive finite variance σ², the classical central limit theorem says sqrt(n)(X̄_n-μ)/σ converges in distribution to a standard normal variable. This yields an approximate sampling distribution X̄_n≈Normal(μ,σ²/n) for sufficiently large n, but accuracy depends on the original distribution and the probability region considered. Convergence in distribution does not mean observed values themselves turn normal. Heavy-tailed infinite-variance models may fall outside this theorem. The CLT supports approximate confidence intervals and tests when their additional assumptions are met; it is not a substitute for checking sampling bias or dependence.",
    worked: "For independent Bernoulli(0.5) trials, μ=0.5 and σ=0.5. With n=400, the sample proportion has approximate standard error σ/sqrt(n)=0.025. A deviation of 0.05 corresponds to roughly two standard errors. A normal approximation suggests two-sided tail probability around 4.6%, with discrete and approximation caveats.",
    interpretation: "The scale of typical average fluctuation shrinks as 1/sqrt(n), slower than 1/n. Four times as much data roughly halves standard error.",
    trap: "Do not use the CLT to excuse nonrandom or highly dependent sampling, and do not equate a normal sampling distribution with a normal population distribution.",
    practice: "Independent measurements have mean 10 and standard deviation 6. For n=100, state the approximate mean and standard error of their sample average, assuming the CLT conditions.",
    solution: "The sample-average mean is 10 and its standard error is 6/sqrt(100)=0.6. The classical CLT makes the standardized average approximately normal for large n under the stated finite-variance independent identical model. The population itself need not be normal.",
    checks: [["What scale standardizes X̄_n under the classical CLT?", ["σ/sqrt(n)", "σ/n", "nσ"], 0, "Standard deviation of the average shrinks as the square root of n."], ["Must the original population be normal?", ["No", "Yes", "Only for Bernoulli data"], 0, "The theorem concerns the standardized sum's limit."], ["Does CLT correct selection bias?", ["No", "Yes", "Only at large n"], 0, "Sampling design remains important."]],
  },
];
