import type { MathLecture } from "./lectures";

/** Explicit bridge from calculation to defensible mathematical argument. */
export const MATH_PROOF_FOUNDATIONS: MathLecture[] = [
  {
    lesson: "math.m16.l1", title: "Logic, quantifiers, and negation",
    premise: "A theorem's meaning depends on the order of its quantifiers. A proof must match the actual logical claim, not an easier nearby statement.",
    idea: "Write ‘for every x there exists y’ as ∀x∃y P(x,y) and distinguish it from ∃y∀x P(x,y). The first permits y to depend on x; the second demands one y for all x. Negation swaps each quantifier and negates the predicate: not(∀x∃y P) means ∃x∀y not P. An implication P⇒Q is false only when P holds and Q fails; its contrapositive not Q⇒not P is equivalent. A converse Q⇒P is a different claim. Explicit domains matter: ∀x∈R differs from ∀x∈Z.",
    worked: "The claim ∀x∈R∃y∈R such that y>x is true: choose y=x+1. The reversed claim ∃y∈R∀x∈R such that y>x is false: given any proposed y, take x=y+1. To negate the first claim, write ∃x∈R∀y∈R such that y≤x; that negation is false.",
    interpretation: "A witness may depend on earlier universally quantified variables. A counterexample to a universal statement must satisfy the domain and violate its conclusion.",
    trap: "Do not negate ‘for all’ by merely replacing the conclusion with its negation while leaving ‘for all’ in place; it becomes ‘there exists’.",
    practice: "Negate: ‘For every positive ε there exists a positive δ such that every x with |x-a|<δ satisfies |f(x)-L|<ε.’",
    solution: "There exists ε>0 such that for every δ>0 there exists x with |x-a|<δ but |f(x)-L|≥ε. If the original definition also excludes x=a, preserve that exclusion in the negation. Quantifier order is essential: the bad x may depend on δ.",
    checks: [["How does negating ∀x change its quantifier?", ["To ∃x", "It stays ∀x", "It disappears"], 0, "A single counterexample refutes a universal claim."], ["Are ∀x∃y and ∃y∀x equivalent?", ["No", "Yes", "Only over real numbers"], 0, "The latter requires one shared witness."], ["What is equivalent to P⇒Q?", ["not Q⇒not P", "Q⇒P", "not P⇒not Q"], 0, "Use the contrapositive, not the converse."]],
  },
  {
    lesson: "math.m16.l2", title: "Sets, functions, and relations",
    premise: "Precise definitions of sets and maps prevent hidden assumptions about domains, inverses, and equivalence classes.",
    idea: "A function f:A→B assigns exactly one element of B to each element of A; it need not hit every point of B. Its image is f(A), which can be smaller than the codomain B. Injective means equal outputs force equal inputs; surjective means every target has a preimage; bijective means both. A relation on A is a subset of A×A. An equivalence relation is reflexive, symmetric, and transitive; its classes partition A. Prove each property from its definition, and separate set inclusion A⊆B from equality A=B, which requires both inclusions.",
    worked: "Define a~b for integers when a-b is divisible by 3. Reflexivity holds because a-a=0. Symmetry follows because b-a=-(a-b). Transitivity follows by adding a-b and b-c. The classes are the integers congruent to 0, 1, or 2 modulo 3, and they form a partition of Z.",
    interpretation: "The relation groups integers by a property preserved across each class. A quotient set treats each class as one object.",
    trap: "A function can be injective without being surjective. For example n↦n+1 on nonnegative integers misses zero.",
    practice: "For f:R→R, f(x)=x², decide whether it is injective or surjective. What changes if domain and codomain are both [0,infinity)?",
    solution: "On R→R it is neither: f(1)=f(-1), and no real x maps to -1. On nonnegative reals as both domain and codomain, it is strictly increasing and every y≥0 has preimage sqrt(y), so it is bijective with inverse sqrt.",
    checks: [["What is needed for set equality?", ["Inclusion in both directions", "One shared element", "Equal notation"], 0, "Show A⊆B and B⊆A."], ["What three properties define an equivalence relation?", ["Reflexive, symmetric, transitive", "Injective, surjective, continuous", "Closed, bounded, compact"], 0, "These produce a partition into classes."], ["Must a function hit its entire codomain?", ["No", "Yes", "Only if injective"], 0, "That stronger property is surjectivity."]],
  },
  {
    lesson: "math.m16.l3", title: "Direct proof and counterexample",
    premise: "A direct proof starts from hypotheses and reaches a conclusion by justified steps. One valid counterexample disproves a universal claim.",
    idea: "State variables, domains, and hypotheses before doing algebra. To prove an implication, assume its antecedent and derive its consequent, using definitions and already-proved facts. For existence, construct a witness and verify it. To refute ∀x P(x), exhibit one allowed x for which P(x) fails; examples never prove a universal theorem. When claiming two sets are equal, give both inclusion arguments. A computation is a proof only when it covers all allowed cases under the stated assumptions.",
    worked: "Prove the sum of two even integers is even. Let a=2m and b=2n for integers m,n, by the definition of even. Then a+b=2(m+n), and m+n is an integer, so a+b is even. By contrast, the claim ‘every prime is odd’ is false because 2 is prime and even.",
    interpretation: "The algebra matters because it preserves the defining form for every pair of even integers, not merely a few test values.",
    trap: "Do not ‘prove’ a universal claim by checking ten examples, however large they look. A single counterexample has the opposite logical power.",
    practice: "Prove directly that the square of an odd integer is odd, then disprove ‘the square of every integer is odd.’",
    solution: "Write an odd integer n=2k+1. Then n²=4k²+4k+1=2(2k²+2k)+1, an odd integer. The broader claim fails at n=2, whose square 4 is even.",
    checks: [["What proves a universal claim?", ["An argument covering every allowed case", "Many checked examples", "One appealing diagram"], 0, "Quantifiers require a general argument."], ["What disproves a universal claim?", ["One valid counterexample", "A proof of one case", "No calculation"], 0, "Find an allowed input where the predicate fails."], ["What is a witness for existence?", ["A constructed object satisfying the condition", "An arbitrary impossible object", "A universal counterexample"], 0, "Verify the proposed object."]],
  },
  {
    lesson: "math.m16.l4", title: "Contrapositive and contradiction",
    premise: "Some implications are easier to prove from the failure of their conclusion. Contradiction and contrapositive are precise logical tools, not substitutes for clarity.",
    idea: "To prove P⇒Q by contrapositive, assume not Q and derive not P. This is logically equivalent to the original implication. In proof by contradiction, assume all hypotheses plus the negation of the desired conclusion and derive an impossibility, such as 0=1 or conflict with a proved property. State exactly what was assumed and where the contradiction arises. Avoid assuming the desired result somewhere in the derivation. For an existence theorem, the negation often creates a universal condition that can be exploited.",
    worked: "Prove: if n² is even, then n is even. Contrapositive: if n is odd, write n=2k+1. Its square is 2(2k²+2k)+1, odd. Thus a square cannot be even when n is odd, proving the original implication.",
    interpretation: "The proof uses a convenient description of odd numbers and never needs to take a square root of an arbitrary integer.",
    trap: "The converse ‘if n is even then n² is even’ happens to be true here, but proving it alone would not prove the stated implication.",
    practice: "Use contradiction to show sqrt(2) is irrational.",
    solution: "Assume sqrt(2)=p/q in lowest terms with integers p,q and q≠0. Then p²=2q², so p² is even and hence p is even. Write p=2k; then 4k²=2q², so q²=2k² and q is even. Both p and q being even contradicts lowest terms. Therefore sqrt(2) is irrational.",
    checks: [["What is the contrapositive of P⇒Q?", ["not Q⇒not P", "Q⇒P", "not P⇒not Q"], 0, "Reverse and negate both sides."], ["What must a contradiction proof identify?", ["The incompatible consequences of the temporary assumption", "Only a long calculation", "An unrelated example"], 0, "Show exactly why the assumption cannot hold."], ["Does proving the converse prove the original?", ["No", "Yes", "Only for integers"], 0, "Converse is a distinct implication."]],
  },
  {
    lesson: "math.m16.l5", title: "Induction and strong induction",
    premise: "Induction proves infinitely many indexed claims by a valid base case and a step that carries established truth forward.",
    idea: "For P(n) on integers n≥n₀, prove P(n₀). Then, for an arbitrary k≥n₀, assume P(k) and prove P(k+1). Strong induction permits assuming all P(j) from n₀ through k before proving k+1; it is logically equivalent but convenient when a case depends on several earlier ones. If a recursion jumps by two, one base case may be insufficient. State the induction hypothesis explicitly and use it at the exact line where needed. Induction does not prove claims over all real numbers by itself.",
    worked: "Prove 1+2+…+n=n(n+1)/2 for n≥1. Base n=1 gives 1=1. Assume the formula for k. Add k+1: the sum through k+1 is k(k+1)/2+(k+1)=(k+1)(k+2)/2. That is the claimed formula at k+1, completing induction.",
    interpretation: "The induction step proves a conditional bridge for arbitrary k. The base anchors the chain so every later integer follows.",
    trap: "An induction step without a valid base proves nothing about the intended starting set. Check every required initial index.",
    practice: "Prove 2^n≥n+1 for every integer n≥0.",
    solution: "At n=0, the inequality reads 1≥1. Assume it holds at k. Doubling both sides gives 2^{k+1}≥2k+2. Because k≥0, this is at least k+2. Thus the inequality holds at k+1 and, by induction, for every n≥0.",
    checks: [["What anchors an induction proof?", ["A verified base case", "A diagram", "Only the induction hypothesis"], 0, "The chain needs a starting point."], ["What may strong induction assume at step k+1?", ["All earlier claims through k", "The desired k+1 claim", "Claims for real inputs"], 0, "Use already established integer cases."], ["Can the induction hypothesis be assumed for any chosen k without proving the step?", ["No", "Yes", "Only for large k"], 0, "The conditional step must be shown for arbitrary k."]],
  },
  {
    lesson: "math.m16.l6", title: "Equivalence and well-definedness",
    premise: "An equivalence statement needs both directions. A definition on equivalence classes must not depend on which representative is chosen.",
    idea: "To prove P iff Q, prove P⇒Q and Q⇒P separately. For a chain of several equivalent statements, a directed cycle of implications can suffice when every statement is reached. A map on quotient objects is well-defined when equal equivalence classes give the same output; choosing different representatives must not change the answer. This is different from whether an ordinary function gives one output for one input. When a construction uses a representative, write the equivalence relation and explicitly verify representative independence.",
    worked: "On integers modulo 3, define F([a])=[2a]. If [a]=[b], then 3 divides a-b, hence 3 divides 2a-2b, so [2a]=[2b]. Therefore F is well-defined. By contrast, G([a])=a as an ordinary integer is not well-defined: [1]=[4] but 1≠4.",
    interpretation: "The output of F is a class, so equivalence of different representatives is sufficient. G tries to return a representative-dependent integer.",
    trap: "Do not prove a biconditional by showing only one implication, or assume quotient notation automatically makes a rule well-defined.",
    practice: "On integers modulo 5, is H([a])=[a²] well-defined? Justify your answer.",
    solution: "Yes. If a≡b modulo 5, then 5 divides a-b. Since a²-b²=(a-b)(a+b), 5 also divides a²-b². Thus [a²]=[b²] regardless of representative, and H is well-defined.",
    checks: [["How many directions does P iff Q require?", ["Both implications", "Only P⇒Q", "Only Q⇒P"], 0, "Equivalence is two-way."], ["What makes a quotient map well-defined?", ["Representative-independent output", "A short formula", "Positive outputs"], 0, "Equivalent inputs must produce equivalent outputs."], ["Is [a]↦a an integer-valued rule on modulo classes?", ["Not well-defined", "Always well-defined", "Only for prime moduli"], 0, "A class has many integer representatives."]],
  },
  {
    lesson: "math.m16.l7", title: "Countability and the size of infinity",
    premise: "Infinite sets can have different sizes. Countability means their elements can be listed by natural-number indices, even if a particular listing is surprising.",
    idea: "A set is countably infinite if there is a bijection with natural numbers, and at most countable if it is finite or countably infinite. Integers are countable by alternating nonnegative and negative values. Rational numbers are countable by arranging numerator-denominator pairs in a grid, traversing diagonals, and skipping duplicates. A countable union of countable sets is countable under ordinary choice assumptions for selecting enumerations. Real numbers in (0,1) are uncountable by Cantor's diagonal argument: from any proposed list, construct a decimal differing from the nth listed number at its nth digit, choosing digits that avoid ambiguous trailing-nine representations.",
    worked: "Suppose the binary sequences were listed s₁,s₂,… . Define a new sequence d by setting its nth bit opposite the nth bit of sₙ. Then d differs from every sₙ at least at position n, so it is absent from the purported complete list. Therefore the set of infinite binary sequences is uncountable.",
    interpretation: "The diagonal construction is a method of defeating every enumeration, not merely an example of one sequence outside a short list.",
    trap: "A finite but very large set is still finite. Countability concerns the existence of an infinite enumeration, not whether one has been written explicitly in the lesson.",
    practice: "Give an explicit enumeration pattern showing Z is countable.",
    solution: "List 0,1,-1,2,-2,3,-3,… . Every integer appears exactly once: zero first, and each positive n and its negative occur in the pair at stage n. This defines a bijection from natural-number positions to integers.",
    checks: [["Are integers countable?", ["Yes", "No", "Only nonnegative integers"], 0, "Alternate positive and negative values in a list."], ["What does a diagonal sequence do?", ["Differs from each listed sequence at its own index", "Copies every listed sequence", "Lists only finite sequences"], 0, "It defeats any proposed complete enumeration."], ["Are real numbers in (0,1) countable?", ["No", "Yes", "Only rationals are uncountable"], 0, "Diagonalization rules out a complete list."]],
  },
  {
    lesson: "math.m16.l8", title: "Writing and reviewing complete proofs",
    premise: "A correct insight is not yet a complete proof. A reader should be able to identify the claim, hypotheses, logical steps, and exact conclusion without guessing.",
    idea: "Start by translating the statement into quantifiers and definitions. Identify whether the task is universal, existential, implication, or equivalence. Choose a method that matches its logic, then show each nontrivial step with the theorem or algebra that justifies it. Check boundary cases, domain restrictions, and hidden divisions by zero. Review the proof adversarially: could a counterexample fit the hypotheses? Are you proving the converse? Did an induction step use its own conclusion? For a longer result, isolate a lemma and state exactly how it is used. A proof can be concise without skipping indispensable reasoning.",
    worked: "Claim: if a and b are odd integers, ab is odd. A complete proof introduces a=2m+1 and b=2n+1 for integers m,n. Multiply: ab=4mn+2m+2n+1=2(2mn+m+n)+1. The parenthesized quantity is an integer, so ab satisfies the definition of odd. This final sentence connects the algebra to the claim.",
    interpretation: "The worked proof states domains, uses the defining form, performs a reversible calculation, and names why the last expression finishes the argument.",
    trap: "Do not finish a proof at an expression and expect the reader to supply the relevant definition or missing quantifier silently.",
    practice: "Review this attempted proof: ‘If x²=1, then x=1 because 1²=1.’ Find the error and give a correct conclusion over real x.",
    solution: "The example 1²=1 proves one solution but not uniqueness; it ignores x=-1. Factor x²-1=(x-1)(x+1)=0. By the zero-product property over reals, x=1 or x=-1. Substitution verifies both. The attempted argument asserted the converse of a one-case observation as a uniqueness proof.",
    checks: [["What should a proof state before using a variable?", ["Its domain and assumptions", "Only its letter", "Its numerical value"], 0, "The claim's quantifiers determine allowed cases."], ["What does an adversarial proof review check?", ["Boundary cases and hidden assumptions", "Only spelling", "Whether the conclusion sounds plausible"], 0, "Look for valid counterexamples and unjustified steps."], ["Does checking x=1 prove uniqueness for x²=1?", ["No", "Yes", "Only over reals"], 0, "x=-1 is another solution."]],
  },
];
