import type { MathLecture } from "./lectures";

/** The first proof-based analysis block; hypotheses are part of every theorem. */
export const MATH_REAL_ANALYSIS: MathLecture[] = [
  {
    lesson: "math.m21.l1", title: "Completeness of the real numbers",
    premise: "Calculus relies on a property rationals lack: bounded real sets have least upper bounds. Completeness turns approximations into actual limiting points.",
    idea: "An upper bound M for S satisfies s≤M for all s∈S. The supremum sup S is an upper bound no larger than any other upper bound; it need not belong to S. The least-upper-bound property says every nonempty real set bounded above has a supremum in R. It is equivalent to several convergence principles, including Cauchy completeness, in the usual construction of real numbers. Rational numbers are not complete: {q∈Q:q²<2 and q>0} is bounded in Q but has no rational least upper bound. To prove a proposed s is the supremum, show it bounds the set and that for every ε>0 some set element exceeds s-ε.",
    worked: "Let S=(0,1), the open real interval. The number 1 is an upper bound. For every ε>0, choose x=1-min(ε/2,1/2); then x∈S and x>1-ε. No smaller number can bound S, so sup S=1 although 1∉S. The infimum is 0, also absent from S.",
    interpretation: "A supremum is a boundary value of the set's order structure, not necessarily a maximum attained by a member.",
    trap: "Do not infer existence of a maximum from boundedness. Closedness or another attainment argument is needed.",
    practice: "Find sup, inf, maximum, and minimum of S={1-1/n:n is a positive integer}.",
    solution: "The sequence begins 0,1/2,2/3,… and approaches 1 from below. Its infimum and minimum are 0 at n=1. Its supremum is 1 by the ε criterion, but it has no maximum because every term is below 1 and later terms are larger.",
    checks: [["Must sup S belong to S?", ["No", "Yes", "Only for bounded sets"], 0, "An open interval can have a missing endpoint."], ["What property distinguishes real completeness?", ["Nonempty bounded-above sets have real suprema", "Every set has a maximum", "All real numbers are rational"], 0, "The least-upper-bound property is central."], ["How do you show s is the least upper bound?", ["It bounds S and elements approach it from below", "It is merely greater than one element", "It must lie in S"], 0, "Rule out every smaller upper bound."]],
  },
  {
    lesson: "math.m21.l2", title: "Sequences and subsequences",
    premise: "A sequence converges when all sufficiently late terms lie in every prescribed neighborhood of one limit. Subsequences reveal persistent alternative behavior.",
    idea: "The statement that a_n converges to L means for every positive epsilon there exists N such that n≥N implies |a_n-L|<epsilon. A subsequence a_{n_k} uses strictly increasing indices; every subsequence of a convergent sequence has the same limit. Bolzano-Weierstrass says every bounded real sequence has a convergent subsequence. A sequence is Cauchy when its late terms get arbitrarily close to one another; completeness of R makes Cauchy equivalent to convergence. To disprove convergence, two subsequences with different limits suffice. A bounded sequence need not itself converge, and an unbounded one cannot converge to a finite real number.",
    worked: "Let a_n=(-1)^n+1/n. The even-index subsequence approaches 1; the odd-index subsequence approaches -1. If a_n had a limit, both subsequences would have that same limit, a contradiction. The sequence is bounded but not convergent, illustrating why Bolzano-Weierstrass promises only a convergent subsequence.",
    interpretation: "The 1/n perturbation vanishes, but the alternating component remains and prevents a single limiting value.",
    trap: "Do not mistake one convergent subsequence for convergence of the whole sequence. All sufficiently late terms must agree.",
    practice: "Prove that a_n=1/n converges to zero using the epsilon definition.",
    solution: "Given epsilon>0, choose an integer N>1/epsilon. For every n≥N, |1/n-0|=1/n≤1/N<epsilon. Thus the quantifiers in the definition are satisfied and a_n converges to zero.",
    checks: [["What must N depend on in a limit proof?", ["The chosen ε", "The later n individually", "A fixed graph width"], 0, "Choose one N that works for every later n."], ["What do two subsequences with distinct limits prove?", ["The full sequence diverges", "The full sequence converges to both", "It is unbounded"], 0, "A convergent sequence passes its limit to every subsequence."], ["Does boundedness force sequence convergence?", ["No", "Yes", "Only for positive sequences"], 0, "It forces a convergent subsequence, not the whole sequence."]],
  },
  {
    lesson: "math.m21.l3", title: "Limits and continuity from epsilon-delta",
    premise: "An epsilon-delta proof makes ‘nearby inputs yield nearby outputs’ precise, including exactly which inputs are allowed.",
    idea: "A function tending to L as x approaches a means for every epsilon>0 there exists delta>0 such that 0<|x-a|<delta and x in the domain imply |f(x)-L|<epsilon. The puncture 0<|x-a| excludes the value at a. Continuity at a additionally requires a in the domain and f(a)=L. Sequentially, continuity at a means f(x_n) converges to f(a) for every domain sequence x_n converging to a. To prove a limit for a polynomial, factor differences and bound variable coefficients in a chosen neighborhood. A delta may be min of several constraints, one to control the variable and one to hit epsilon.",
    worked: "Prove lim_{x→2}x²=4. If |x-2|<1, then 1<x<3 and |x+2|<5. Since |x²-4|=|x-2||x+2|, choose δ=min(1,ε/5). Then 0<|x-2|<δ implies |x²-4|<5δ≤ε. The explicit neighborhood bound justifies the product estimate.",
    interpretation: "The proof turns the output target ε into an input tolerance δ and states why it works for every permitted nearby x.",
    trap: "Do not let δ depend on the particular x chosen after δ; it must work uniformly for all x within the neighborhood.",
    practice: "Give an epsilon-delta proof that lim_{x→3}(2x+1)=7.",
    solution: "Given ε>0, choose δ=ε/2. Whenever 0<|x-3|<δ, |(2x+1)-7|=2|x-3|<2δ=ε. The choice depends only on ε, completing the proof.",
    checks: [["Why is the condition 0<|x-a| included in a limit?", ["The value at a need not control the limit", "It makes x=a mandatory", "It eliminates all nearby x"], 0, "Limits describe punctured-neighborhood behavior."], ["What extra condition makes a limit continuity?", ["f(a) exists and equals the limit", "The derivative is positive", "The domain is all R"], 0, "Continuity includes the point itself."], ["Can δ depend on the particular x after it is chosen?", ["No", "Yes", "Only for polynomials"], 0, "One δ must cover every nearby x."]],
  },
  {
    lesson: "math.m21.l4", title: "Compactness and connectedness",
    premise: "Compactness prevents sequences from escaping without a convergent subsequence; connectedness prevents a continuous image from jumping across a gap.",
    idea: "In R^n, Heine-Borel says a set is compact exactly when it is closed and bounded. Sequentially, every sequence in a compact set has a subsequence converging to a point still in the set. A continuous image of a compact set is compact, so a continuous real-valued function on a compact nonempty set attains a maximum and minimum. A connected subset of R is an interval, and a continuous image of a connected set is connected, yielding the intermediate value theorem. Closed-and-bounded characterization is special to finite-dimensional Euclidean space; in general metric spaces compactness needs its own definition.",
    worked: "On [0,1], f(x)=x(1-x) is continuous and the domain is compact, so extrema are attained. Differentiate to find critical point 1/2, where f=1/4; endpoints give 0. Thus minimum 0 and maximum 1/4 are actual values. On the open interval (0,1), the infimum 0 is not attained, showing why compactness matters.",
    interpretation: "The extreme-value theorem guarantees existence before computation locates the points. The derivative only identifies candidates.",
    trap: "Do not generalize ‘closed and bounded implies compact’ to arbitrary infinite-dimensional normed spaces.",
    practice: "Explain why f(x)=1/x on (0,1] has no maximum despite continuity on its domain.",
    solution: "The domain (0,1] is not compact because it is not closed in R. As x→0 from the right, 1/x grows without bound, so the function has no finite maximum. Continuity without compactness does not trigger the extreme-value theorem.",
    checks: [["What characterizes compact subsets of R^n?", ["Closed and bounded", "Only bounded", "Only connected"], 0, "This is Heine-Borel in finite dimensions."], ["What does a continuous real function attain on nonempty compact domain?", ["Maximum and minimum", "Only its supremum as an unattained limit", "Every real value"], 0, "Its image is compact in R."], ["What are connected subsets of R?", ["Intervals", "Only singletons", "All bounded sets"], 0, "No gap can separate them."]],
  },
  {
    lesson: "math.m21.l5", title: "Differentiation theorems",
    premise: "Derivative theorems have hypotheses that explain why local slope information controls a function across an interval.",
    idea: "Fermat's theorem says a differentiable function at an interior local extremum has derivative zero. Rolle's theorem adds continuity on [a,b], differentiability on (a,b), and equal endpoint values to guarantee an interior zero derivative. The mean value theorem replaces equal endpoints with a point c where f'(c)=(f(b)-f(a))/(b-a). Consequences include: derivative zero throughout an interval implies constant function, and f'≥0 throughout implies nondecreasing function under continuity and differentiability assumptions. Darboux's theorem says derivatives have the intermediate value property even if the derivative itself is discontinuous.",
    worked: "For f(x)=x² on [1,3], secant slope is (9-1)/(3-1)=4. Since f'=2x, the mean value theorem point is c=2, inside (1,3). The function is continuous on the closed interval and differentiable inside, so the theorem applies.",
    interpretation: "The theorem relates a global average change to some actual instantaneous rate; it does not usually identify the point without solving an equation.",
    trap: "Do not apply mean value theorem across a jump or a corner inside the interval without verifying its continuity and differentiability hypotheses.",
    practice: "If f is continuous on [0,2], differentiable on (0,2), and f'(x)=3 everywhere inside, prove f(2)-f(0)=6.",
    solution: "The mean value theorem gives some c∈(0,2) with [f(2)-f(0)]/2=f'(c)=3. Multiplying by 2 yields f(2)-f(0)=6. No explicit formula for f is needed.",
    checks: [["What does the mean value theorem equate?", ["An interior derivative and endpoint secant slope", "Two endpoint derivatives", "A function and its integral"], 0, "The theorem finds an intermediate instantaneous rate."], ["What does f'=0 throughout an interval imply?", ["f is constant there", "f=0 there", "f is not continuous"], 0, "Apply MVT between any two points."], ["Can a derivative jump over a value?", ["No, by Darboux's theorem", "Yes, always", "Only if f is positive"], 0, "Derivatives have the intermediate value property."]],
  },
  {
    lesson: "math.m21.l6", title: "Riemann integration",
    premise: "Riemann integration formalizes area accumulation through upper and lower sums. Not every bounded function is integrable by this method.",
    idea: "Partition [a,b] into subintervals. Upper sums use each subinterval's supremum times its width; lower sums use infimum. A bounded function is Riemann integrable when upper and lower integrals agree, equivalently when partitions can make upper-minus-lower sum arbitrarily small. Continuous functions and monotone functions on closed intervals are integrable. A bounded function is Riemann integrable exactly when its discontinuity set has Lebesgue measure zero, a deeper criterion. The Dirichlet function that is 1 on rationals and 0 on irrationals has upper sum b-a and lower sum zero for every partition, so it is not Riemann integrable on a nondegenerate interval.",
    worked: "For f(x)=x on [0,1], use n equal pieces. Right-endpoint sum is (1/n)Σ_{k=1}^n(k/n)=(n+1)/(2n), approaching 1/2. Left-endpoint sum is (n-1)/(2n), also approaching 1/2. Their gap is 1/n, so upper and lower sums meet at integral 1/2.",
    interpretation: "Agreement of squeezing sums proves existence of the integral and identifies its value; a single finite sum is only an approximation.",
    trap: "Do not assert boundedness alone implies Riemann integrability. Dense discontinuities can defeat every partition.",
    practice: "Use n equal subintervals to find upper-minus-lower sum for f(x)=x on [0,2].",
    solution: "Each subinterval has width 2/n and the function rises by 2/n there. The difference in upper and lower rectangle heights is 2/n for each of n intervals. Multiply height difference by width and n intervals: n·(2/n)(2/n)=4/n, which approaches zero.",
    checks: [["What proves bounded f is Riemann integrable?", ["Upper-minus-lower sums can be made arbitrarily small", "One midpoint sum exists", "Its graph is bounded"], 0, "Upper and lower integrals must coincide."], ["Is every continuous function on [a,b] Riemann integrable?", ["Yes", "No", "Only if positive"], 0, "Uniform continuity controls oscillation on small pieces."], ["Why is the rational-indicator function not Riemann integrable?", ["Every interval has both rational and irrational values", "It is unbounded", "Its values are negative"], 0, "Upper and lower sums never close the gap."]],
  },
  {
    lesson: "math.m21.l7", title: "Uniform convergence",
    premise: "Pointwise convergence lets the required index depend on x. Uniform convergence demands one index that works simultaneously across the entire domain.",
    idea: "Uniform convergence of f_n to f on D means for every epsilon>0 there is N such that n≥N implies |f_n(x)-f(x)|<epsilon for every x∈D. Equivalently, the supremum over D of |f_n(x)-f(x)| converges to zero when finite. Uniform limits of continuous functions are continuous. On a fixed compact interval, uniform convergence permits interchange of limit and Riemann integral when each function is integrable and the limit is integrable. Pointwise convergence alone does not ensure either conclusion. The Weierstrass M-test gives uniform absolute convergence of a function series when |u_n(x)|≤M_n and ΣM_n converges.",
    worked: "On [0,1], f_n(x)=x^n tends pointwise to 0 for x<1 and to 1 at x=1. The pointwise limit has a jump at 1, so convergence cannot be uniform since every f_n is continuous. Directly, the supremum of |x^n-f(x)| over x<1 is 1 for every n, not a quantity tending to zero.",
    interpretation: "The troublesome x values move closer to 1 as n grows. Pointwise N may depend on that x; no single N controls all of them.",
    trap: "Do not infer uniform convergence from a pointwise formula, even when all terms are smooth and the domain is bounded.",
    practice: "Show f_n(x)=x/n converges uniformly to zero on [0,1]. Does the same argument work on all real x?",
    solution: "On [0,1], sup|x/n|=1/n→0, so convergence is uniform. On R, sup_{x∈R}|x/n| is infinite for every n, so convergence is only pointwise there, not uniform.",
    checks: [["In uniform convergence, may N depend on x?", ["No", "Yes", "Only on compact sets"], 0, "One N must serve every x in the domain."], ["What happens to continuity under uniform limits?", ["It is preserved", "It is always lost", "It requires derivatives"], 0, "Uniform control exchanges the limit with pointwise continuity estimates."], ["Does x^n converge uniformly on [0,1]?", ["No", "Yes", "Only at x=0"], 0, "The pointwise limit is discontinuous at 1."]],
  },
  {
    lesson: "math.m21.l8", title: "Power series and interchange of limits",
    premise: "A power series behaves especially well strictly inside its convergence radius. Boundary points require separate analysis before exchanging sums, derivatives, or integrals.",
    idea: "A power series Σa_n(x-c)^n has a radius R such that it converges absolutely for |x-c|<R and diverges for |x-c|>R. On every compact subinterval strictly inside the radius, convergence is uniform, enabling termwise differentiation and integration there. The differentiated series has the same radius. Endpoint behavior is not determined by R and must be tested separately. More generally, to interchange two limiting operations, cite a theorem with its hypotheses—uniform convergence, dominated convergence in measure theory, or another appropriate condition—instead of moving symbols by analogy. Uniform convergence of functions alone does not justify termwise differentiation; additional control on derivative series is needed.",
    worked: "For |x|<1, Σ_{n=0}∞x^n=1/(1-x). On any [-r,r] with r<1, the geometric tail is bounded by r^{N+1}/(1-r), so convergence is uniform. Differentiate termwise inside the radius: Σ_{n=1}∞n x^{n-1}=1/(1-x)². At x=1, the original series diverges; the interior identity cannot be substituted at the endpoint.",
    interpretation: "The margin r<1 supplies a uniform geometric bound. As r approaches 1, that bound deteriorates, signaling the need for new endpoint reasoning.",
    trap: "Do not differentiate a merely uniformly convergent sequence of functions termwise without further derivative hypotheses.",
    practice: "Integrate Σ_{n=0}∞x^n termwise from 0 to a, where 0≤a<1, and identify the closed form.",
    solution: "Uniform convergence on [0,a] permits termwise integration, giving Σ_{n=0}∞a^{n+1}/(n+1). Integrating 1/(1-x) from 0 to a gives -log(1-a), so the series equals -log(1-a) for 0≤a<1.",
    checks: [["Where is a power series uniformly convergent in the standard interior theorem?", ["On compact subintervals strictly inside its radius", "At every endpoint automatically", "Outside its radius"], 0, "Leave a margin from the boundary."], ["Does a differentiated power series keep the same radius?", ["Yes", "No", "Only for polynomials"], 0, "Coefficient factor n does not change root-test radius."], ["Does uniform convergence alone justify termwise differentiation?", ["No", "Yes", "Only on closed intervals"], 0, "Derivative control is separately required."]],
  },
];
