import type { MathLecture } from "./lectures";

/** A series is the limit of partial sums, never merely a small term. */
export const MATH_SERIES_BASICS: MathLecture[] = [
  {
    lesson: "math.m10.l1",
    title: "Series, partial sums, and divergence test",
    premise: "An infinite series is defined as the limit of its partial sums. Its terms approaching zero is necessary for convergence, but that condition alone does not control the accumulated total.",
    idea: "For terms aₙ, the Nth partial sum is S_N=Σ from n=1 to N of aₙ. The series converges to S when S_N approaches S as N grows; otherwise it diverges. Since aₙ=Sₙ-Sₙ₋₁, convergence of S_N forces aₙ to approach zero. Contrapositively, if aₙ does not approach zero, the series diverges. The reverse implication fails: 1/n approaches zero, yet its partial sums grow without bound. A series can converge conditionally even when absolute values diverge, so keep the question about signed sums separate from the question about total magnitude.",
    worked: "For aₙ=1/[n(n+1)], rewrite as 1/n-1/(n+1). The first N terms cancel to S_N=1-1/(N+1), which approaches 1. For aₙ=n/(n+1), terms approach 1 rather than zero, so the divergence test immediately rejects convergence without computing S_N.",
    interpretation: "A series is a sequence of running totals. A small next term can still produce an unbounded running total if enough such terms remain.",
    trap: "Do not say the divergence test proves convergence when aₙ approaches zero; it only detects divergence when the term limit is nonzero or nonexistent.",
    practice: "Use the divergence test on Σ from n=1 to infinity of (2n+1)/(n+4). Then explain why the same test cannot decide Σ1/n.",
    solution: "The first term formula approaches 2, not zero, so its series diverges by the necessary-condition test. For 1/n, the term limit is zero. The test is inconclusive, even though the harmonic series actually diverges by another argument.",
    checks: [
      ["What defines the value of a convergent series?", ["The limit of partial sums", "The limit of individual terms", "The first term"], 0, "Sum finite prefixes and then take their limit."],
      ["If aₙ approaches a nonzero number, what happens?", ["The series diverges", "The series converges", "No conclusion"], 0, "Convergence requires terms to vanish."],
      ["If aₙ approaches zero, does the divergence test prove convergence?", ["No", "Yes", "Only for positive terms"], 0, "The harmonic series is a counterexample."],
    ],
  },
  {
    lesson: "math.m10.l2",
    title: "Geometric and telescoping series",
    premise: "Some infinite series can be summed exactly because their partial sums have a simple form. Geometric terms repeat a ratio; telescoping terms cancel across neighbors.",
    idea: "For a geometric series Σ from n=0 to infinity of ar^n, the finite sum is S_N=a(1-r^(N+1))/(1-r) when r≠1. It converges to a/(1-r) exactly when |r|<1. If |r|≥1 and a≠0, terms do not approach zero or partial sums fail to settle. A telescoping series rewrites aₙ=bₙ-bₙ₊₁, giving S_N=b₁-bₙ₊₁. Only after writing a finite partial sum should you take the limit. An index shift changes the first term and therefore the sum.",
    worked: "Σ from n=0 to infinity of 3(1/2)^n has sum 3/(1-1/2)=6. For Σ from n=1 to infinity of 1/[n(n+1)], write 1/n-1/(n+1): S_N=1-1/(N+1), so the sum is 1. The patterns differ but both require a finite-sum argument.",
    interpretation: "A ratio of -1/2 also converges, with alternating terms. The criterion depends on the magnitude of r, not on r being positive.",
    trap: "Do not apply a/(1-r) when |r|≥1. Also do not forget whether the series starts at n=0 or n=1.",
    practice: "Find the value of Σ from n=1 to infinity of 4(1/3)^n. Then find Σ from n=1 to infinity of [1/(n+2)-1/(n+3)].",
    solution: "The first series begins at n=1, so its first term is 4/3 and the common ratio is 1/3. Its sum is (4/3)/(1-1/3)=2. For the telescoping series, S_N=1/3-1/(N+3), which approaches 1/3.",
    checks: [
      ["When does a nonzero geometric series converge?", ["|r|<1", "r<1 with no lower bound", "|r|>1"], 0, "Its powers must approach zero."],
      ["What is the sum of a+ar+ar²+… when |r|<1?", ["a/(1-r)", "a/(1+r)", "a·r"], 0, "Take the limit of the finite formula."],
      ["What should be written first in a telescoping proof?", ["A finite partial sum", "An infinite cancellation symbol only", "The ratio test"], 0, "Display the boundary terms that remain."],
    ],
  },
  {
    lesson: "math.m10.l3",
    title: "Integral and comparison tests",
    premise: "For positive terms, a convergent larger benchmark can bound a series. The integral test relates a decreasing sequence of term heights to the area beneath a matching curve.",
    idea: "For aₙ=f(n), the integral test requires f to be continuous, positive, and decreasing eventually. Rectangles bound the tail by neighboring integrals, so Σaₙ and ∫f share convergence behavior; the integral need not equal the sum. Direct comparison says if 0≤aₙ≤bₙ eventually and Σbₙ converges, then Σaₙ converges. If Σaₙ diverges, any larger nonnegative Σbₙ also diverges. The p-series Σ1/n^p converges for p>1 and diverges for p≤1, matching the integral threshold at infinity. A few exceptional initial terms never alter convergence.",
    worked: "For Σ1/n², f(x)=1/x² is positive, continuous, decreasing for x≥1, and ∫₁^∞x^-2 dx=1 is finite, so the series converges. This does not claim the series equals 1. For Σ1/sqrt(n), the corresponding p=1/2 integral diverges, so the series diverges.",
    interpretation: "The integral supplies a convergence classification and, with tail bounds, an error estimate; it is not generally an exact sum.",
    trap: "Do not use the integral test without checking eventual positivity and decrease. Do not infer convergence of a smaller series from divergence of a larger one.",
    practice: "Classify Σ from n=1 to infinity of 1/(n²+1) by direct comparison. Then classify Σ1/(n+1) by comparing it with a familiar divergent series.",
    solution: "Since 0<1/(n²+1)≤1/n² and Σ1/n² converges, the first converges. The second is the harmonic series with its first term removed: Σ from n=1 to N of 1/(n+1)=H_(N+1)-1, which diverges. Alternatively, for n≥1, 1/(n+1)≥1/(2n), and the half-harmonic series diverges.",
    checks: [
      ["Which conditions does the integral test need eventually?", ["Positive, continuous, decreasing f", "Only differentiable f", "Only bounded f"], 0, "Rectangle comparisons depend on these properties."],
      ["Does ∫₁^∞f equal Σf(n) under the integral test?", ["Generally no", "Always", "Only if f is decreasing"], 0, "It classifies and bounds; it rarely gives the exact sum."],
      ["For which p does Σ1/n^p converge?", ["p>1", "p>0", "p≤1"], 0, "Compare with the p-integral."],
    ],
  },
  {
    lesson: "math.m10.l4",
    title: "Limit comparison",
    premise: "A positive series with a complicated formula often behaves like its dominant simpler term. Limit comparison turns that intuition into a precise test.",
    idea: "For eventually positive aₙ and bₙ, if the ratio aₙ/bₙ approaches L with 0<L<∞, then Σaₙ and Σbₙ either both converge or both diverge. The reason is that the ratio eventually lies between two positive constants, so each term is bounded above and below by constant multiples of bₙ. Choose bₙ from the dominant powers, logarithms, or known p-series; verify the ratio limit rather than saying only that expressions 'look similar.' A ratio limit of zero or infinity may still allow one-sided conclusions through comparison, but it is not the basic equivalent-size version.",
    worked: "Let aₙ=(3n+1)/(n³+2) and bₙ=1/n². Then aₙ/bₙ=n²(3n+1)/(n³+2) approaches 3. Because 0<3<∞ and Σ1/n² converges, Σaₙ converges. For aₙ=(2n²+1)/(n³+5), comparing to 1/n gives ratio approaching 2, so that series diverges.",
    interpretation: "The constant L affects approximate size but not the yes-or-no convergence classification. Initial terms do not change that classification.",
    trap: "Do not apply the positive-term theorem to a sign-changing series without addressing signs or absolute values. A ratio approaching zero is not the stated two-way equivalence.",
    practice: "Classify Σ from n=1 to infinity of (n²+3)/(n⁴+n) using limit comparison with a p-series. Show the ratio.",
    solution: "Choose bₙ=1/n². Then aₙ/bₙ=n²(n²+3)/(n⁴+n)=(n⁴+3n²)/(n⁴+n) approaches 1. The terms are positive, the ratio limit is finite and positive, and Σ1/n² converges, so the given series converges.",
    checks: [
      ["What ratio limit gives the standard two-way limit-comparison conclusion?", ["A positive finite number", "Only zero", "Only infinity"], 0, "Eventually the sequences bound each other up to constants."],
      ["What comparison fits (3n+1)/(n³+2)?", ["1/n²", "1/n", "n²"], 0, "Compare dominant powers n over n cubed."],
      ["Why check eventual positivity?", ["The comparison theorem orders positive terms", "It sets the first term", "It makes the sum exactly equal"], 0, "Sign changes need separate treatment."],
    ],
  },
  {
    lesson: "math.m10.l5",
    title: "Ratio and root tests",
    premise: "Factorials and exponential powers often become simpler when adjacent terms or nth roots are compared. The ratio and root tests decide absolute convergence when their limits are away from one.",
    idea: "For a series of terms aₙ, the ratio test examines L=lim |aₙ₊₁/aₙ| where defined; the root test examines L=lim (|aₙ|)^(1/n). If L<1, the series converges absolutely by comparison with a geometric tail. If L>1 or is infinite, the terms fail to approach zero and the series diverges. At L=1, either test is inconclusive; both Σ1/n and Σ1/n² produce 1. The root test is often natural for an entire expression raised to n, while factorial ratios often favor the ratio test. Check whether a test's limit exists; limsup versions require their own statement.",
    worked: "For Σ from n=0 to infinity of 3^n/n!, the adjacent-term magnitude ratio is 3/(n+1), which approaches zero; the series converges absolutely. For Σ from n=1 to infinity of (2n/(3n+1))^n, the nth root approaches 2/3<1, so it converges absolutely. Neither calculation claims the exact sum.",
    interpretation: "A limit below one means the tail eventually contracts like a geometric series. A limit equal to one means the test has reached its decision boundary, not that the series diverges.",
    trap: "Do not announce convergence from L=1. Be careful to take absolute values before applying the tests to signed terms.",
    practice: "Use the ratio test to classify Σ from n=1 to infinity of n!/5^n, and explain what the same test says about Σ1/n².",
    solution: "For aₙ=n!/5^n, aₙ₊₁/aₙ=(n+1)/5 tends to infinity, so terms eventually grow and the series diverges. For aₙ=1/n², aₙ₊₁/aₙ=(n/(n+1))² tends to 1. The ratio test is inconclusive there, even though the p-series converges.",
    checks: [
      ["What does ratio-test limit L<1 imply?", ["Absolute convergence", "Divergence", "No conclusion"], 0, "Compare a sufficiently late tail with a geometric series."],
      ["What does L=1 imply?", ["The test is inconclusive", "Convergence", "Divergence"], 0, "Both harmonic and square-reciprocal series have that limit."],
      ["Which test is often natural for factorials?", ["Ratio test", "Integral test always", "Only divergence test"], 0, "Adjacent factorials cancel cleanly."],
    ],
  },
];
