import type { MathLecture } from "./lectures";

/** Sign, functional convergence, and approximation close the MATH 19B arc. */
export const MATH_SERIES_ADVANCED: MathLecture[] = [
  {
    lesson: "math.m10.l6",
    title: "Alternating series and error bounds",
    premise: "Alternating signs can make a series converge even when the magnitudes alone do not. A decreasing sequence of term magnitudes approaching zero gives both convergence and a useful truncation-error bound.",
    idea: "For Σ(-1)^n bₙ, the alternating-series theorem applies when bₙ≥0, bₙ is eventually nonincreasing, and bₙ approaches zero. Even and odd partial sums then bracket a common limit. If S_N is a partial sum after the conditions hold, the error magnitude is at most the first omitted magnitude b_(N+1), and the error has the sign of that omitted term. This does not estimate the error of an arbitrary signed series. Check the eventual decrease explicitly rather than assuming it from a few values. The theorem proves convergence, not absolute convergence.",
    worked: "The alternating harmonic series 1-1/2+1/3-1/4+… converges because 1/n decreases to zero. Its first four terms sum to 7/12≈0.5833; the true sum differs by at most 1/5=0.2 and lies above this even partial sum. More terms yield a tighter bound. The nonalternating harmonic series diverges, so this convergence depends on sign cancellation.",
    interpretation: "The first omitted term is a guaranteed error ceiling under the theorem's hypotheses, not generally the exact error.",
    trap: "Do not apply the theorem if magnitudes fail to approach zero, and do not infer absolute convergence from alternating convergence.",
    practice: "How many terms of Σ from n=1 to infinity of (-1)^(n+1)/n² guarantee error below 0.001 by the alternating-series bound? State a sufficient N.",
    solution: "After N terms the bound is 1/(N+1)². Require 1/(N+1)²<0.001, so N+1>sqrt(1000)≈31.63. Taking N=31 is sufficient because the first omitted term has index 32 and magnitude 1/1024<0.001. The series also converges absolutely by the p-test, but that is not needed for this error bound.",
    checks: [
      ["What must alternating term magnitudes do?", ["Eventually decrease to zero", "Increase forever", "Stay above a positive number"], 0, "Both conditions support the bracketing proof."],
      ["What bounds the truncation error?", ["The first omitted magnitude", "The first term", "The number of terms"], 0, "Use the alternating-series remainder estimate."],
      ["Does alternating convergence imply absolute convergence?", ["No", "Yes", "Only for rational terms"], 0, "The alternating harmonic series is conditional."],
    ],
  },
  {
    lesson: "math.m10.l7",
    title: "Absolute versus conditional convergence",
    premise: "A signed series can converge because positive and negative contributions cancel. Absolute convergence is stronger: the series of magnitudes converges without relying on that cancellation.",
    idea: "A series Σaₙ converges absolutely if Σ|aₙ| converges. Absolute convergence implies convergence of Σaₙ: the tails of the signed sums are bounded by the corresponding absolute tails. If Σaₙ converges but Σ|aₙ| diverges, it converges conditionally. Test absolute convergence first when possible, using p-series, comparison, ratio, or root tests on magnitudes. If that fails, check the signed series separately, perhaps using the alternating-series theorem. Rearranging a conditionally convergent series can change its sum; absolute convergence is stable under rearrangement.",
    worked: "Σ(-1)^(n+1)/n converges by the alternating-series theorem because 1/n decreases to zero. Its absolute series Σ1/n is harmonic and diverges, so the original convergence is conditional. By contrast, Σ(-1)^n/n² converges absolutely because Σ1/n² converges; its signs are not needed for the convergence proof.",
    interpretation: "The classification describes the robustness of convergence under loss of signs. It does not merely report whether one chosen test succeeded.",
    trap: "Do not call a series conditional just because it alternates. First test the absolute-value series; it may converge.",
    practice: "Classify Σ from n=1 to infinity of (-1)^n/sqrt(n) and Σ from n=1 to infinity of (-1)^n/n³ as divergent, conditional, or absolute.",
    solution: "For the square-root series, magnitudes 1/sqrt(n) decrease to zero, so the signed series converges by the alternating test. The absolute p-series has p=1/2≤1 and diverges, so convergence is conditional. For the cubic series, Σ1/n³ converges because p=3>1, so the signed series converges absolutely.",
    checks: [
      ["What does absolute convergence require?", ["Σ|aₙ| converges", "Only aₙ approaches zero", "Signs alternate"], 0, "Ignore signs and check the total magnitude."],
      ["Does absolute convergence imply signed convergence?", ["Yes", "No", "Only for nonnegative terms"], 0, "Absolute tails bound signed tails."],
      ["What is conditional convergence?", ["Σaₙ converges while Σ|aₙ| diverges", "Both diverge", "Both converge"], 0, "Cancellation is essential in this case."],
    ],
  },
  {
    lesson: "math.m10.l8",
    title: "Power series and radius of convergence",
    premise: "A power series represents a function near a center by adding powers of x-c. Its convergence usually forms an interval whose interior is controlled by a radius; each endpoint needs its own test.",
    idea: "For Σaₙ(x-c)^n, the ratio or root test often yields convergence when |x-c|<R and divergence when |x-c|>R. The radius R may be zero or infinite. At x=c±R, the test commonly returns one, so substitute each endpoint into the original series and classify them separately. Within the open convergence interval, power series can be differentiated and integrated term by term, producing another series with the same radius, though endpoint behavior may change. Never assume a power series represents the intended function outside its interval of convergence.",
    worked: "For Σ from n=1 to infinity of (x-2)^n/n, the ratio of consecutive absolute terms approaches |x-2|. Thus R=1 and the open interval is (1,3). At x=1 the series becomes Σ(-1)^n/n, which converges conditionally. At x=3 it becomes Σ1/n, which diverges. The full interval of convergence is [1,3).",
    interpretation: "A radius is a distance from the center; it does not settle either endpoint. The bracket shape records separate endpoint proofs.",
    trap: "Do not include both endpoints because the inequality is |x-c|≤R. The ratio test is inconclusive exactly at the boundary.",
    practice: "Find the radius and interval of convergence for Σ from n=1 to infinity of (x+1)^n/n². Test both endpoints explicitly.",
    solution: "The root or ratio test gives |x+1|<1, so center -1 and radius 1, with open interval (-2,0). At x=-2 the series is Σ(-1)^n/n², absolutely convergent. At x=0 it is Σ1/n², also convergent. Hence the full interval is [-2,0].",
    checks: [
      ["What must be done at x=c±R?", ["Test each endpoint separately", "Include both automatically", "Exclude both automatically"], 0, "Boundary behavior differs by series."],
      ["What does R measure?", ["Distance from the center to the interior boundary", "The sum of the series", "The first coefficient"], 0, "Convergence holds inside a centered radius."],
      ["Can termwise differentiation change endpoint behavior?", ["Yes", "No", "Only if R=0"], 0, "The radius stays, but boundary tests can change."],
    ],
  },
  {
    lesson: "math.m10.l9",
    title: "Taylor and Maclaurin polynomials",
    premise: "A Taylor polynomial matches a function's value and several derivatives at one center. It is a local approximation whose degree controls how many local behaviors agree.",
    idea: "For a function with enough derivatives at c, its degree-n Taylor polynomial is Tₙ(x)=Σ from k=0 to n of f^(k)(c)(x-c)^k/k!. The coefficient is forced: differentiate k times and evaluate at c. When c=0 the polynomial is called Maclaurin. Compute derivatives systematically, simplify the coefficients, and state the center and degree. A Taylor polynomial is not automatically equal to the function away from c. The remainder f(x)-Tₙ(x) measures the approximation error and needs its own bound when accuracy is claimed.",
    worked: "For f(x)=e^x at c=0, every derivative at zero equals 1. The degree-three Maclaurin polynomial is T₃(x)=1+x+x²/2+x³/6. At x=0.1, it gives 1.1051666…, close to e^0.1. For sin x at zero, even derivatives vanish there and the first nonzero terms are x-x³/6.",
    interpretation: "Matching derivatives explains the near-center accuracy. The polynomial's computation and an error guarantee are related but distinct tasks.",
    trap: "Do not use f^(k)(x) instead of f^(k)(c) in the coefficient, and do not omit k!. A polynomial matching at c need not approximate well far away.",
    practice: "Find the degree-two Taylor polynomial for ln x centered at c=1 and use it to estimate ln(1.1).",
    solution: "For ln x, f(1)=0, f'(1)=1, and f''(1)=-1. Thus T₂(x)=(x-1)-(x-1)²/2. At x=1.1 this is 0.1-0.005=0.095. The exact ln(1.1) is about 0.09531; an error analysis is needed to certify a number of digits.",
    checks: [
      ["What is a Maclaurin polynomial's center?", ["0", "1", "Infinity"], 0, "Maclaurin means Taylor centered at zero."],
      ["What divides the kth derivative coefficient?", ["k!", "k", "2^k always"], 0, "Repeated differentiation of (x-c)^k produces k!."],
      ["Does matching derivatives prove global equality?", ["No", "Yes", "Only for logarithms"], 0, "The polynomial is a local approximation."],
    ],
  },
  {
    lesson: "math.m10.l10",
    title: "Taylor series and approximation error",
    premise: "A Taylor series is the limit of its Taylor polynomials if that limit exists. Even then, proving the series converges is not the same as proving it converges to the original function.",
    idea: "Let Tₙ be the Taylor polynomial at c and Rₙ(x)=f(x)-Tₙ(x). If derivatives are sufficiently well behaved on the interval between c and x, Taylor's theorem gives a Lagrange-form remainder Rₙ(x)=f^(n+1)(ξ)(x-c)^(n+1)/(n+1)! for some intermediate ξ. A bound |f^(n+1)|≤M yields |Rₙ(x)|≤M|x-c|^(n+1)/(n+1)!. If that bound tends to zero for fixed x, the Taylor series represents f there. Bounds must be stated on the entire interval, not just at the center. For some smooth functions, every derivative at c can be zero while f is not zero nearby, so a formal Taylor series need not equal f.",
    worked: "Approximate e^0.2 with T₂(x)=1+x+x²/2, giving 1.22. On [0,0.2], the third derivative e^x is at most e^0.2<1.23, so |R₂(0.2)|<1.23·0.2³/6=0.00164. Thus the true value lies within 0.00164 of 1.22. The bound certifies an interval; a calculator decimal is not the proof.",
    interpretation: "A remainder bound tells how much trust to place in a truncated polynomial. It separates a plausible approximation from a guaranteed accuracy claim.",
    trap: "Do not set the unknown intermediate ξ equal to c or x without justification. Convergence of coefficients alone does not prove equality to f.",
    practice: "Use the degree-one Maclaurin polynomial for sin x to approximate sin(0.1). Bound the error using a degree-one Lagrange remainder on [0,0.1].",
    solution: "T₁(x)=x, so the estimate is 0.1. Since f''(x)=-sin x and |sin x|≤1 on the interval, the degree-one error is at most 1·0.1²/2=0.005. A sharper bound uses |sin x|≤0.1 there, giving at most 0.0005. Both establish that the true sine lies near 0.1; the second is stronger.",
    checks: [
      ["What does a Taylor remainder bound quantify?", ["The approximation error", "The radius alone", "The first coefficient"], 0, "It bounds f(x)-Tₙ(x)."],
      ["Where must a derivative bound hold for Lagrange's estimate?", ["Between the center and evaluation point", "Only at the center", "Only at infinity"], 0, "The unknown ξ lies inside that interval."],
      ["Does a convergent formal Taylor series always equal its smooth function?", ["No", "Yes", "Only at zero"], 0, "The remainder must tend to zero."],
    ],
  },
  {
    lesson: "math.m10.l11",
    title: "Mixed series problems",
    premise: "There is no universal convergence test that is best for every series. Begin with the term limit, identify signs and structure, then choose a test whose hypotheses you can actually verify.",
    idea: "Use a decision sequence. Check whether terms tend to zero; failure proves divergence. For positive terms, inspect geometric form, p-series comparison, integrals, and dominant-size limit comparison. Factorials and nth powers invite ratio or root tests. Alternating signs invite an absolute-value test first, followed by the alternating theorem if absolute convergence fails. For power series, find the open radius and then test both endpoints independently. If the question requests a numerical approximation, state a remainder or truncation bound. When a test gives its inconclusive boundary value, switch methods instead of forcing a conclusion.",
    worked: "Consider Σ from n=1 to infinity of (-1)^(n+1)n/(n²+1). Magnitudes n/(n²+1) behave like 1/n, so the absolute series diverges by limit comparison. The magnitudes approach zero and are decreasing for n≥1 because the corresponding f(x)=x/(x²+1) has nonpositive derivative for x≥1. Thus the signed series converges by the alternating theorem, conditionally. The ratio test would yield one and be inconclusive.",
    interpretation: "A defensible classification often requires two different proofs: one for signed convergence and one for failure of absolute convergence.",
    trap: "Do not call a ratio-test result of one a divergence proof. Do not assert decreasing magnitudes without showing it eventually holds.",
    practice: "Classify Σ from n=1 to infinity of (-1)^n(2n+1)/(n³+4) and state a suitable test for both signed and absolute convergence.",
    solution: "The absolute terms are positive and behave like 2/n²: dividing by 1/n² gives a ratio n²(2n+1)/(n³+4) that approaches 2. Since Σ1/n² converges, the absolute series converges by limit comparison. Therefore the signed series converges absolutely as well; no alternating-series test is needed for the classification.",
    checks: [
      ["What comes before a sophisticated test?", ["Check the term limit and structure", "Assume convergence", "Differentiate the sum"], 0, "A nonzero term limit settles divergence immediately."],
      ["When classifying an alternating series, what is useful to test first?", ["Absolute convergence", "Only its first term", "Only the ratio limit"], 0, "Absolute convergence is the stronger outcome."],
      ["What must be tested separately for a power series?", ["Each boundary endpoint", "Only its center", "Only the first coefficient"], 0, "Radius tests usually say nothing at endpoints."],
    ],
  },
];
