import type { MathLecture } from "./lectures";

/** Time-indexed random processes, from chains to stochastic calculus. */
export const MATH_STOCHASTIC_PROCESSES: MathLecture[] = [
  {
    lesson: "math.m32.l1", title: "Markov chains",
    premise: "A Markov chain predicts its next state from its current state, conditional on the present, without needing the entire past.",
    idea: "For a time-homogeneous discrete chain, P(X_{n+1}=j|X_n=i, past)=P_{ij}. Rows of transition matrix P sum to one, and distribution row vector evolves as π_{n+1}=π_nP. Multi-step transitions are P^k by Chapman–Kolmogorov. A stationary distribution satisfies πP=π, but finding one does not itself prove convergence to it. On a finite irreducible aperiodic chain, the unique stationary law is the limiting distribution; periodic chains can oscillate. Detailed balance π_iP_{ij}=π_jP_{ji} is sufficient for stationarity, not required for every chain.",
    worked: "For P=[[.8,.2],[.3,.7]], stationarity solves π₁(.2)=π₂(.3) plus π₁+π₂=1, giving π=(.6,.4). Starting from state one, the next distribution is (.8,.2), not stationary yet. Since positive entries make this chain irreducible and aperiodic, repeated transitions converge to (.6,.4).",
    interpretation: "A stationary law is an invariant distribution; mixing is an additional dynamic property.",
    trap: "Do not conclude convergence from πP=π alone when reducibility or periodicity may intervene.",
    practice: "For P=[[0,1],[1,0]], find its stationary distribution and describe behavior starting in state one.",
    solution: "π=(.5,.5) satisfies πP=π. Starting from state one, the law alternates between (1,0) and (0,1), so it never converges to π. The chain has period two.",
    checks: [["What property defines a Markov chain?", ["Next-state law depends on the current state given the past", "States must be independent", "Every chain is stationary"], 0, "It is conditional memorylessness."], ["How do k-step transitions appear?", ["P^k", "kP always", "P divided by k"], 0, "Matrix multiplication sums intermediate paths."], ["Does stationary always mean limiting?", ["No", "Yes", "Only for two states"], 0, "Periodicity can prevent convergence."]],
  },
  {
    lesson: "math.m32.l2", title: "Poisson processes",
    premise: "A Poisson process counts random arrivals with independent stationary increments and a constant rate.",
    idea: "A rate-λ Poisson process N(t) begins at zero, has independent increments, and N(t+s)-N(s) is Poisson with mean λt. In small h, one arrival has probability λh+o(h), while two or more have o(h). Waiting times between arrivals are independent exponential(λ), and the kth arrival time has a Gamma/Erlang distribution. The memoryless property belongs to exponential waiting times, not to the accumulated count itself. Superposition of independent Poisson processes has rate equal to the sum; independent thinning with retention probability p yields rate pλ. Real arrival streams with bursts or time-dependent rates may need a different model.",
    worked: "At λ=2 arrivals per hour, probability of no arrivals in 30 minutes is e^{-λt}=e^{-1}. Expected arrivals in that half hour equal λt=1. The probability of exactly two is e^{-1}/2, by the Poisson mass formula.",
    interpretation: "Rate and interval length combine through λt; units must match before using the formula.",
    trap: "Do not model clustered or strongly dependent arrivals as a homogeneous Poisson process merely because counts look random.",
    practice: "With λ=3 per hour, what is the probability of one arrival in 20 minutes?",
    solution: "Twenty minutes is 1/3 hour, so mean count is λt=1. The Poisson probability of exactly one is e^{-1}1^1/1!=e^{-1}. The expected count over that interval is also one.",
    checks: [["What is the mean of N(t) for rate λ?", ["λt", "λ/t", "t/λ"], 0, "Rate times time gives expected count."], ["What law governs interarrival times?", ["Exponential", "Uniform", "Binomial"], 0, "Waiting is memoryless."], ["What does independent thinning do to rate?", ["Multiplies by retention probability", "Squares it", "Leaves it always unchanged"], 0, "Each arrival is retained independently."]],
  },
  {
    lesson: "math.m32.l3", title: "Brownian motion",
    premise: "Brownian motion is a continuous-time process with continuous paths and independent Gaussian increments, yet its paths are almost surely nowhere classically differentiable.",
    idea: "Standard Brownian B_t has B_0=0, independent increments, B_t-B_s distributed N(0,t-s) for t>s, and continuous paths almost surely. Its covariance is Cov(B_s,B_t)=min(s,t). Scaling B_{ct} has the same law as sqrt(c)B_t. Quadratic variation along refining partitions converges to t, unlike differentiable paths whose squared-increment sum vanishes. This nonzero quadratic variation powers Itô calculus. A Brownian path can return and oscillate at every scale; the formula dB/dt as an ordinary function is invalid almost surely.",
    worked: "For B_1 and B_3, Cov(B_1,B_3)=1 because B_3=B_1+(B_3-B_1) and the increment is independent with mean zero. Var(B_3-B_1)=2. The difference is N(0,2), not N(0,3).",
    interpretation: "Brownian dependence across times comes from the shared earlier path, while disjoint increments are independent.",
    trap: "Do not confuse independent increments with independent values B_s and B_t.",
    practice: "For standard B, find the distribution of B_5-B_2 and Cov(B_2,B_5).",
    solution: "The interval length is 3, so B_5-B_2 is N(0,3). Cov(B_2,B_5)=min(2,5)=2. The increment is independent of B_2 but the two level values are correlated.",
    checks: [["What is Var(B_t-B_s)?", ["t-s", "t+s", "Zero"], 0, "It equals elapsed time."], ["Are Brownian sample paths classically differentiable?", ["Almost surely no", "Always yes", "Only at integers"], 0, "They fluctuate at every scale."], ["What is Cov(B_s,B_t)?", ["min(s,t)", "st", "Always zero"], 0, "The earlier path is shared."]],
  },
  {
    lesson: "math.m32.l4", title: "Stochastic integrals",
    premise: "An Itô integral uses adapted left-endpoint information, making stochastic integration distinct from ordinary Riemann–Stieltjes integration.",
    idea: "For an adapted square-integrable simple process H, define ∫₀ᵀH_t dB_t as Σ H_{t_i}(B_{t_{i+1}}-B_{t_i}), then extend by L² limits. Itô isometry gives E[(∫H dB)²]=E[∫H²dt], under the required predictability and integrability. The integral has mean zero for suitable H, and its process is a martingale. Evaluating H at midpoints instead leads to Stratonovich integration, whose chain rule differs. Because Brownian quadratic variation is nonzero, ordinary integration by parts and the usual chain rule need correction terms.",
    worked: "For constant H_t=2 on [0,T], ∫₀ᵀ2dB_t=2B_T. Its mean is zero and variance is 4T. Itô isometry agrees: E∫₀ᵀ4dt=4T.",
    interpretation: "The isometry ties a random integral's variance to an ordinary time integral of its integrand's squared magnitude.",
    trap: "Do not let H look into future Brownian increments while invoking adapted Itô-integral properties.",
    practice: "For deterministic H_t=t on [0,1], compute E[∫₀¹t dB_t] and its variance.",
    solution: "The mean is zero. Itô isometry gives variance ∫₀¹t²dt=1/3. The integral is Gaussian because the deterministic integrand produces a Gaussian linear functional of Brownian motion.",
    checks: [["What does Itô isometry compute?", ["Second moment of a stochastic integral", "A pathwise ordinary derivative", "A Poisson rate"], 0, "It equals E∫H²dt."], ["What information may an adapted integrand use?", ["Present and past", "Future increments", "Only final values"], 0, "It cannot anticipate future noise."], ["Do Itô and Stratonovich obey identical chain rules?", ["No", "Yes", "Only for constants"], 0, "Quadratic variation creates a correction."]],
  },
  {
    lesson: "math.m32.l5", title: "Itô's formula",
    premise: "Itô's formula is the chain rule for Brownian-driven processes, with an extra second-derivative term from quadratic variation.",
    idea: "If dX_t=b(t,X_t)dt+σ(t,X_t)dB_t and f∈C^{1,2}, then df(t,X_t)=[f_t+b f_x+(σ²/2)f_{xx}]dt+σf_xdB_t, under standard regularity. The extra half-variance term is absent from ordinary calculus because (dB_t)² contributes dt in Itô bookkeeping. For multidimensional diffusions, Hessian contraction with covariance σσᵀ replaces σ²f_{xx}. The formula is local and can require stopping or integrability to turn a local martingale expression into a true expectation identity.",
    worked: "Set X_t=B_t and f(x)=x². Then f_x=2x and f_xx=2, so d(B_t²)=2B_t dB_t+dt. Integrating gives B_t²=2∫₀ᵗB_s dB_s+t; therefore E[B_t²]=t because the Itô integral has mean zero under suitable square integrability.",
    interpretation: "The dt correction exactly accounts for Brownian variance growth.",
    trap: "Do not use the ordinary chain rule d(B_t²)=2B_t dB_t in the Itô convention; it misses t.",
    practice: "Use Itô's formula for f(x)=x³ with X_t=B_t.",
    solution: "f_x=3x² and f_xx=6x, so d(B_t³)=3B_t²dB_t+3B_tdt. The drift correction is 3B_tdt, not zero, even though Brownian motion itself has zero drift.",
    checks: [["What extra term appears in one-dimensional Itô's formula?", ["One-half σ² times f_xx dt", "Only f_xx dB", "No correction"], 0, "Quadratic variation supplies it."], ["What is d(B_t²)?", ["2B_t dB_t+dt", "2B_t dB_t only", "dt only"], 0, "The correction is one dt."], ["What regularity is stated for f?", ["One time and two space derivatives", "Only continuity", "No derivatives"], 0, "The classical formula uses C^{1,2}."]],
  },
  {
    lesson: "math.m32.l6", title: "Stochastic differential equations",
    premise: "An SDE specifies both deterministic drift and random diffusion, so its solution is a process rather than one deterministic trajectory.",
    idea: "An Itô SDE dX_t=b(t,X_t)dt+σ(t,X_t)dB_t means X_t=X_0+∫₀ᵗb(s,X_s)ds+∫₀ᵗσ(s,X_s)dB_s. Under global Lipschitz and growth conditions, standard results give a unique strong solution; weaker hypotheses need separate treatment. Euler–Maruyama uses X_{n+1}=X_n+b(t_n,X_n)h+σ(t_n,X_n)ΔB_n with ΔB_n distributed N(0,h). Under typical globally Lipschitz assumptions it has strong order 1/2 and weak order 1 for sufficiently smooth test functions, not universal rates. Monte Carlo error and time discretization error are distinct.",
    worked: "For dX_t=μdt+σdB_t with constant coefficients and X_0=x₀, integrating gives X_t=x₀+μt+σB_t. Thus E[X_t]=x₀+μt and Var(X_t)=σ²t. Euler–Maruyama is exact at grid points if the actual Brownian increments are used for this additive constant-coefficient model.",
    interpretation: "The SDE's integral form clarifies what the noisy differential notation means.",
    trap: "Do not simulate Brownian increments as N(0,1) regardless of step size; their variance must be h.",
    practice: "For dX_t=2dt+3dB_t, X_0=1, find X_4's mean and variance.",
    solution: "X_4=1+2·4+3B_4=9+3B_4. E[X_4]=9 and Var(X_4)=9Var(B_4)=9·4=36. Its distribution is normal N(9,36).",
    checks: [["What is the variance of a Brownian step ΔB over h?", ["h", "1 always", "h²"], 0, "It scales with elapsed time."], ["What does a strong solution use?", ["A specified Brownian motion on the probability space", "Only a marginal law", "No noise"], 0, "It is pathwise adapted to the driver."], ["Is Euler–Maruyama strong order universally one?", ["No", "Yes", "Only with small h"], 0, "Common Lipschitz setting gives one-half."]],
  },
  {
    lesson: "math.m32.l7", title: "Ergodicity",
    premise: "Ergodicity connects averages along one long trajectory to averages under an invariant distribution.",
    idea: "A stationary process has time-shift invariant finite-dimensional distributions. Ergodicity says shift-invariant events are trivial, and under suitable conditions Birkhoff's theorem gives time averages converging almost surely to the invariant expectation. For a finite irreducible Markov chain, empirical visit frequencies converge to its stationary distribution even if the chain is periodic, though the one-time distribution may fail to converge without aperiodicity. A stationary law does not by itself imply ergodicity: a mixture of two noncommunicating regimes preserves its mixture distribution but a single path stays in its regime. Mixing is stronger than basic ergodicity in common formulations.",
    worked: "For deterministic two-state alternating chain, the one-time law from state A oscillates forever, but its empirical fraction of visits to A tends to 1/2. This illustrates that time averages can converge despite no pointwise distributional mixing. A chain with two absorbing states, sampled initially 50-50, has stationary mixture but empirical fraction of A is either 1 or 0, not 1/2, so it is not ergodic under that mixture.",
    interpretation: "Trajectory averages and time-t distributions ask different questions.",
    trap: "Do not treat a stationary mixture of disconnected components as an ergodic process.",
    practice: "A chain starts in one of two absorbing states A or B with probability 1/2 each. Is the mixture stationary, and is the time average of 1_A always 1/2?",
    solution: "The initial mixture is stationary because neither state changes. But along a realized path, 1_A is constantly 1 if started in A and constantly 0 if started in B. Its time average is not always 1/2, so this stationary process is not ergodic.",
    checks: [["What does ergodicity connect?", ["Long-run time and invariant ensemble averages", "Only adjacent differences", "Every path to the same value instantly"], 0, "It justifies trajectory averages."], ["Does stationary imply ergodic?", ["No", "Yes", "Only for finite chains"], 0, "Disconnected mixtures are counterexamples."], ["Can visit frequencies converge in a periodic finite irreducible chain?", ["Yes", "No", "Only if aperiodic"], 0, "Time averaging is weaker than distributional convergence."]],
  },
  {
    lesson: "math.m32.l8", title: "Simulation and inference for processes",
    premise: "Process data are dependent and time ordered, so simulation checks and inference must preserve those structures.",
    idea: "Specify a process model, initial state, time grid, transition or increment law, and observed quantity. Use independent random streams across replications but preserve dependence within each path. For SDEs, separate discretization bias from Monte Carlo standard error by refining step size and increasing path count independently. For Markov chains, account for burn-in and autocorrelation before treating samples as effectively independent; effective sample size may be much smaller than count. For drift or volatility estimation, state the observation interval and whether measurement noise exists. Rolling forecasting validation must use only past information. A good simulation report includes seed, parameter units, numerical tolerance, and a benchmark moment or invariant law.",
    worked: "Simulate dX=μdt+σdB to T=1 with step h=.01. Each increment is μh+σsqrt(h)Z. Across many independent paths, compare sample mean to X_0+μ and variance to σ². If mean matches but variance is about 100 times too large, the code likely used σZ instead of σsqrt(h)Z.",
    interpretation: "Known moments are simple unit tests for a process simulator before fitting it to real data.",
    trap: "Do not shuffle dependent time observations into random train-test folds when evaluating a forecasting model.",
    practice: "For a Brownian simulation with T=2 and 200 equal steps, what variance should each independent increment have?",
    solution: "The step width is h=T/200=.01. Each standard Brownian increment must be N(0,.01), with standard deviation .1. The sum of 200 independent increments then has variance 200·.01=2, matching B_2.",
    checks: [["How should Brownian increment standard deviation scale with h?", ["sqrt(h)", "h²", "One always"], 0, "Increment variance is h."], ["Can autocorrelated process samples be treated as independent without adjustment?", ["No", "Yes", "Only for long paths"], 0, "Dependence reduces effective information."], ["What validation split respects forecasting causality?", ["Chronological past-to-future", "Random shuffling always", "Future-to-past"], 0, "Only past data may train a future predictor."]],
  },
];
