import type { MathStudyGuide } from "./study-guides";

export const MATH_ADVANCED_SERIES_GUIDES: Record<string, MathStudyGuide> = {
  "math.m10.l6": {
    opening: ["Alternating signs can make a series settle even when the positive magnitudes alone would accumulate without bound. For terms +b₁ - b₂ + b₃ - ..., the alternating-series theorem applies when bₙ is nonnegative, eventually decreases, and approaches zero.", "Under those conditions, consecutive partial sums bracket the true total. After N terms, the absolute error is no larger than the first omitted magnitude bₙ₊₁. This is an error guarantee, not usually the exact error."],
    examples: [
      { question: "Does 1 - 1/2 + 1/3 - 1/4 + ... converge?", approach: "Check magnitude decrease and term limit.", steps: ["The magnitudes bₙ = 1/n are positive and decrease as n increases.", "Also bₙ → 0. The alternating-series theorem therefore gives convergence.", "The positive harmonic series Σ1/n diverges, so the signs are essential; this convergence is conditional."], check: "Partial sums alternate above and below the final value while the gap shrinks." },
      { question: "After four terms of that series, what error can you guarantee?", approach: "Use the first omitted magnitude, not the last included one.", steps: ["S₄ = 1 - 1/2 + 1/3 - 1/4 = 7/12.", "The first omitted term has magnitude 1/5.", "Therefore the true sum differs from 7/12 by at most 1/5; the next term is positive, so the sum lies above S₄."], check: "The error bound is intentionally conservative; it does not claim the error equals 1/5." },
    ], practice: [
      { question: "How many terms of Σ(-1)^(n+1)/n² guarantee error below 0.001?", hint: "After N terms, error is at most 1/(N + 1)².", solution: ["Require 1/(N + 1)² < 0.001, or N + 1 > √1000 ≈ 31.63.", "N = 31 suffices, since omitted magnitude 1/32² = 1/1024 < 0.001."] },
      { question: "Does Σ(-1)ⁿ converge?", hint: "Its magnitudes stay at 1.", solution: ["No. The term magnitudes do not approach zero, so the alternating-series theorem does not apply.", "Its partial sums keep oscillating; the term test already proves divergence."] },
    ], takeaway: "Check eventual decrease to zero before using the alternating theorem; the next omitted magnitude bounds the error.",
  },
  "math.m10.l7": {
    opening: ["A signed series converges absolutely when the series of magnitudes Σ|aₙ| converges. Absolute convergence is stronger: then the signed series also converges without needing cancellation. If the signed series converges but Σ|aₙ| diverges, convergence is conditional.", "Test magnitudes first, often with a p-series or comparison. If the magnitude series fails, test the signed one separately. Alternating does not automatically mean conditional—some alternating series converge absolutely."],
    examples: [
      { question: "Classify Σ(-1)^(n+1)/n.", approach: "Test the signed and absolute series separately.", steps: ["Signed magnitudes 1/n decrease to zero, so the alternating-series theorem proves signed convergence.", "The absolute series is Σ1/n, the divergent harmonic series.", "The original series converges conditionally."], check: "Removing signs destroys its convergence, which is exactly what conditional means." },
      { question: "Classify Σ(-1)ⁿ/n².", approach: "Start with magnitudes; their convergence settles the stronger question.", steps: ["The absolute series is Σ1/n², a convergent p-series with p = 2.", "Therefore the signed series converges absolutely. There is no need to rely on the alternating test."], check: "Alternation and absolute convergence can coexist." },
    ], practice: [
      { question: "Classify Σ(-1)ⁿ/√n.", hint: "The signed magnitudes decrease to zero; the absolute p-series has p = 1/2.", solution: ["The alternating test gives signed convergence.", "Σ1/√n diverges because p = 1/2 ≤ 1, so convergence is conditional."] },
      { question: "Classify Σ(-1)ⁿ/n³.", hint: "Test Σ1/n³ first.", solution: ["Σ1/n³ converges since p = 3 > 1.", "Therefore the signed series converges absolutely."] },
    ], takeaway: "Absolute means the magnitudes sum finitely; conditional means only the signed cancellation makes the series converge.",
  },
  "math.m10.l8": {
    opening: ["A power series adds terms aₙ(x - c)ⁿ around a center c. Often it converges for inputs within a radius R and diverges outside. The ratio or root test usually finds the open interval |x - c| < R.", "At the two boundary points c - R and c + R, the ratio/root test commonly returns 1 and is inconclusive. Substitute each endpoint into the original series and test it separately; one may converge while the other diverges."],
    examples: [
      { question: "Find the convergence interval of Σ from n = 1 to ∞ of (x - 2)ⁿ/n.", approach: "Find the radius from an absolute ratio, then examine both endpoints.", steps: ["The absolute adjacent-term ratio approaches |x - 2|. It is below 1 for |x - 2| < 1, so the open interval is (1, 3).", "At x = 1, the series becomes Σ(-1)ⁿ/n, which converges by the alternating test.", "At x = 3, it becomes Σ1/n, which diverges. Full interval: [1, 3)."], check: "The radius is 1 from center 2, but endpoint brackets differ because the two tests differ." },
      { question: "Find the convergence interval of Σ(x + 1)ⁿ/n² for n ≥ 1.", approach: "The radius is again 1, but endpoints need new tests.", steps: ["The ratio/root test gives |x + 1| < 1, or -2 < x < 0.", "At x = -2, terms are (-1)ⁿ/n² and their absolute series converges.", "At x = 0, terms are 1/n², which converge. Full interval: [-2, 0]."], check: "The center is -1, and both endpoints sit distance 1 away." },
    ], practice: [
      { question: "For Σxⁿ/n with n ≥ 1, find radius and full interval.", hint: "Start with |x| < 1, then test x = -1 and x = 1.", solution: ["Radius 1, open interval (-1, 1).", "At -1 the alternating harmonic series converges; at 1 the harmonic series diverges. Full interval [-1, 1)."] },
      { question: "Why does the ratio test not settle endpoints of these examples?", hint: "What value does its ratio limit take when |x - c| = R?", solution: ["At a boundary the ratio limit is 1, where the ratio test is inconclusive.", "Substitution at each endpoint produces a specific numerical series requiring its own test."] },
    ], takeaway: "A radius gives the open convergence interval. Test left and right endpoints separately before choosing brackets.",
  },
  "math.m10.l9": {
    opening: ["A Taylor polynomial is a polynomial built to match a function and its first several derivatives at one center c. Degree n means matching through derivative n. Its coefficient for (x - c)ᵏ is f^(k)(c)/k!, so repeated differentiation recovers the matching derivative.", "When c = 0, it is called a Maclaurin polynomial. Matching at one point makes a local approximation, not a global identity. Accuracy away from the center is a separate question involving the remainder."],
    examples: [
      { question: "Build the degree-three Maclaurin polynomial for eˣ.", approach: "List derivatives at the center and place them over factorials.", steps: ["Every derivative of eˣ is eˣ, so f(0) = f′(0) = f″(0) = f‴(0) = 1.", "Use T₃(x) = f(0) + f′(0)x + f″(0)x²/2! + f‴(0)x³/3!.", "Therefore T₃(x) = 1 + x + x²/2 + x³/6."], check: "At 0, value and first three derivatives of T₃ match those of eˣ." },
      { question: "Find the degree-two Taylor polynomial for ln x centered at 1.", approach: "Evaluate derivatives at c = 1, not at the variable x.", steps: ["f(1) = ln 1 = 0; f′(x) = 1/x, so f′(1) = 1.", "f″(x) = -1/x², so f″(1) = -1.", "T₂(x) = 0 + 1(x - 1) + (-1)(x - 1)²/2 = (x - 1) - (x - 1)²/2."], check: "At x = 1.1 the polynomial gives 0.1 - 0.005 = 0.095, close to ln(1.1)." },
    ], practice: [
      { question: "Find the degree-three Maclaurin polynomial for sin x.", hint: "Values of sin, cos, -sin, and -cos at 0 are 0, 1, 0, -1.", solution: ["f(0) = 0, f′(0) = 1, f″(0) = 0, f‴(0) = -1.", "T₃(x) = x - x³/6."] },
      { question: "Why is the coefficient of (x - c)² equal to f″(c)/2!, not f″(c)?", hint: "Differentiate A(x - c)² twice.", solution: ["The second derivative of A(x - c)² is 2A.", "To make it equal f″(c), set 2A = f″(c), so A = f″(c)/2!."] },
    ], takeaway: "Taylor coefficients come from derivatives evaluated at the center and divided by factorials; the result is local.",
  },
  "math.m10.l10": {
    opening: ["A Taylor polynomial approximates a function; the remainder Rₙ(x) = f(x) - Tₙ(x) is the error. A numerical guess is not a guarantee. Taylor's theorem gives a bound when the next derivative stays bounded between the center c and x.", "If |f^(n+1)(t)| ≤ M throughout that interval, then |Rₙ(x)| ≤ M|x - c|^(n+1)/(n+1)!. The derivative bound must cover the whole segment, not just the center. To prove the infinite Taylor series equals the function, show the remainder tends to zero."],
    examples: [
      { question: "Approximate e^0.2 with T₂(x) = 1 + x + x²/2 and bound the error.", approach: "Evaluate the polynomial, then bound the third derivative over [0, 0.2].", steps: ["T₂(0.2) = 1 + 0.2 + 0.2²/2 = 1.22.", "The third derivative of eˣ is eˣ. On [0, 0.2], it is at most e^0.2 < 1.23.", "The error is below 1.23(0.2)³/3! = 1.23·0.008/6 < 0.00164."], check: "The statement certifies that e^0.2 lies within 0.00164 of 1.22; it does not merely compare calculator decimals." },
      { question: "Approximate sin(0.1) by T₁(x) = x and give an error bound.", approach: "Use the second derivative f″ = -sin x on [0, 0.1].", steps: ["T₁(0.1) = 0.1.", "On [0, 0.1], |sin x| ≤ 1, so the remainder bound is at most 1·0.1²/2 = 0.005.", "A sharper bound uses |sin x| ≤ 0.1 on the interval, giving error at most 0.1·0.1²/2 = 0.0005."], check: "Both bounds are valid; the second uses stronger information about this short interval." },
    ], practice: [
      { question: "Use T₁(x) = 1 + x to estimate e^0.1. Bound error with eˣ < 1.11 on [0, 0.1].", hint: "For degree one, use the second derivative and 2!.", solution: ["The estimate is 1.1.", "Error < 1.11(0.1)²/2 = 0.00555."] },
      { question: "Why is a convergent formal Taylor series not automatically equal to its function?", hint: "What must happen to f(x) - Tₙ(x)?", solution: ["The Taylor polynomials may converge to a value different from f(x).", "Equality requires the remainder Rₙ(x) to approach zero; a convergence proof for the coefficient series alone is not enough."] },
    ], takeaway: "An approximation needs a remainder bound to certify accuracy; equality with an infinite Taylor series needs the remainder to vanish.",
  },
  "math.m10.l11": {
    opening: ["Choose a series test from structure, not habit. First check whether aₙ → 0; if not, stop: the series diverges. For positive terms, consider geometric patterns, p-series, comparison, or integral tests. Factorials suggest ratios; entire nth powers suggest roots.", "With alternating signs, test absolute convergence first, then signed convergence if needed. A ratio or root result of 1 is inconclusive, not a verdict. For power series, find the radius and examine each endpoint separately."],
    examples: [
      { question: "Classify Σ from n = 1 to ∞ of (-1)^(n+1)n/(n² + 1).", approach: "Use one test for signed convergence and another for absolute convergence.", steps: ["Magnitude bₙ = n/(n² + 1) approaches zero. For x ≥ 1, derivative of x/(x² + 1) is (1 - x²)/(x² + 1)² ≤ 0, so bₙ eventually decreases.", "The alternating-series theorem gives signed convergence.", "For the absolute series, compare bₙ with 1/n: bₙ/(1/n) = n²/(n² + 1) → 1. The harmonic series diverges, so the convergence is conditional."], check: "A ratio test on these terms would approach 1 and settle nothing; switching tests is necessary." },
      { question: "Classify Σ from n = 1 to ∞ of (-1)ⁿ(2n + 1)/(n³ + 4).", approach: "Test magnitudes first; they resemble a convergent p-series.", steps: ["Absolute terms are positive. Compare with 1/n².", "Their ratio to 1/n² is n²(2n + 1)/(n³ + 4) → 2, a finite positive number.", "Since Σ1/n² converges, the absolute series converges. Thus the signed series converges absolutely too."], check: "No alternating-series argument is needed once absolute convergence is proved." },
    ], practice: [
      { question: "Classify Σn!/5ⁿ and name a useful test.", hint: "Factorials simplify in adjacent-term ratios.", solution: ["aₙ₊₁/aₙ = (n + 1)/5 → ∞.", "The ratio test gives divergence; terms eventually grow rather than vanish."] },
      { question: "Classify Σ(-1)ⁿ/n² and explain why the alternating test is not the strongest result.", hint: "Test the magnitudes first.", solution: ["Σ1/n² converges by the p-series test.", "Therefore the signed series converges absolutely, which is stronger than merely knowing alternating convergence."] },
    ], takeaway: "Check terms, signs, and dominant structure. If a test is inconclusive, choose another whose hypotheses fit.",
  },
};
