import type { MathLecture } from "./lectures";

/** From general topology to the first language of smooth manifolds. */
export const MATH_TOPOLOGY_MANIFOLDS: MathLecture[] = [
  {
    lesson: "math.m29.l1", title: "Topological spaces and bases",
    premise: "Topology keeps the notion of open neighborhoods while forgetting distances, so continuity can be studied in far more general spaces.",
    idea: "A topology τ on X contains ∅ and X, is closed under arbitrary unions, and under finite intersections. A basis B consists of open building blocks: every x lies in one, and two basis sets containing x have a smaller basis neighborhood of x inside their intersection. Open sets are unions of basis sets. A map f:X to Y is continuous iff preimages of open Y-sets are open in X. The subspace topology intersects ambient open sets with a subset; this may make a set open in the subspace even when it is not ambient-open. The metric topology comes from open balls, but many topological spaces have no specified metric.",
    worked: "On R with ordinary topology, [0,1) is not open. On subspace X=[0,2], it is open because [0,1)=(-1,1)∩X. For f(x)=x², preimage of open interval (1,4) is (-2,-1)∪(1,2), an open set, illustrating the open-preimage test.",
    interpretation: "Relative openness and continuity depend on which spaces and topologies are named.",
    trap: "Do not claim arbitrary intersections of open sets are open; only finite intersections are guaranteed.",
    practice: "Is {0} open in the subspace X={0}∪(1,2) of R? Give an ambient open set witnessing it.",
    solution: "Yes. Choose ambient open interval (-.5,.5). Its intersection with X is exactly {0}. Thus {0} is open in the subspace even though it is not open in R.",
    checks: [["What preimages characterize continuity?", ["Preimages of open sets are open", "Images of open sets always open", "Only preimages of points"], 0, "This is the topological definition."], ["How many open sets can be united and remain open?", ["Arbitrarily many", "Only finitely many", "Exactly two"], 0, "Arbitrary unions are allowed."], ["Can a relatively open set fail to be ambient-open?", ["Yes", "No", "Only in finite spaces"], 0, "Subspace topology changes the ambient context."]],
  },
  {
    lesson: "math.m29.l2", title: "Compactness and connectedness",
    premise: "Compactness turns local open-cover information into finite control, while connectedness rules out a separation into two open pieces.",
    idea: "A space is compact if every open cover has a finite subcover. In Euclidean R^n, Heine–Borel says compact is equivalent to closed and bounded; this equivalence is not universal in arbitrary spaces. Continuous images of compact sets are compact, giving extrema for real-valued continuous functions. A space is connected if it cannot be partitioned into two nonempty disjoint open sets; continuous images remain connected. In R, connected sets are intervals. Path-connected implies connected, but the converse can fail. Compactness and connectedness are independent properties.",
    worked: "[0,1] is compact and connected. The continuous function f(x)=x(1-x) attains maximum 1/4 at x=.5. The set (0,1) is connected but not compact in R: the open cover {(1/n,1):n≥2} covers it with no finite subcover.",
    interpretation: "Theorems about extrema and intermediate values rest on different structural hypotheses.",
    trap: "Do not use closed-and-bounded as the definition of compactness outside Euclidean finite-dimensional spaces.",
    practice: "Is A=[0,1]∪[2,3] compact? Connected? Justify both separately.",
    solution: "A is closed and bounded in R, hence compact by Heine–Borel. It is disconnected: [0,1] and [2,3] are nonempty separated pieces, or note the missing interval (1,2). Compactness does not imply connectedness.",
    checks: [["What is compactness in general topology?", ["Every open cover has a finite subcover", "Closed and bounded everywhere", "Path-connectedness"], 0, "Open covers give the general definition."], ["Are continuous images of connected sets connected?", ["Yes", "No", "Only under differentiability"], 0, "Connectedness is preserved."], ["Does compact imply connected?", ["No", "Yes", "Only on R"], 0, "Two disjoint closed intervals give a counterexample."]],
  },
  {
    lesson: "math.m29.l3", title: "Product and quotient topologies",
    premise: "Products combine spaces coordinatewise; quotients identify points, and the resulting open sets must reflect those constructions.",
    idea: "The product topology on X×Y has basis U×V for open U⊆X,V⊆Y; projections are continuous and a map into the product is continuous exactly when its coordinate maps are. For infinitely many factors, basic open sets restrict only finitely many coordinates. A quotient map q:X to Q is surjective and gives Q the topology where U⊆Q is open iff q^{-1}(U) is open in X. This is the finest topology making q continuous. Gluing endpoints of [0,1] produces a circle-like quotient; the equivalence relation and topology matter. A continuous bijection need not be a homeomorphism unless its inverse is continuous; compact-to-Hausdorff is one useful sufficient setting.",
    worked: "Identify 0 and 1 in [0,1]. The map q(t)=(cos 2πt,sin 2πt) has the same value at endpoints and factors through the quotient. The quotient is compact; the circle is Hausdorff, so the induced continuous bijection is a homeomorphism.",
    interpretation: "A quotient's topology formalizes gluing without assuming the pictured geometry beforehand.",
    trap: "Do not test openness of a quotient set by how it looks in a drawing; test its full preimage under q.",
    practice: "What is the quotient of the two-point discrete space {a,b} when a and b are identified? Describe its topology.",
    solution: "There is one equivalence class, so the quotient has one point. Its only subsets are ∅ and the whole space, both open because their preimages are ∅ and {a,b}. Thus it is the one-point topology.",
    checks: [["What are basic open sets in a two-space product?", ["U×V with U,V open", "Only diagonals", "Only the whole space"], 0, "Rectangles generate the product topology."], ["How is a quotient-open set tested?", ["Its preimage under the quotient map is open", "Its image is bounded", "It has finite points"], 0, "The quotient topology is defined by preimages."], ["Must a continuous bijection have continuous inverse?", ["No", "Yes", "Only if domains match sets"], 0, "A homeomorphism needs both directions."]],
  },
  {
    lesson: "math.m29.l4", title: "Fundamental group",
    premise: "Loops record holes that cannot be removed by continuous deformation while keeping the base point fixed.",
    idea: "A based loop at x₀ is a continuous path γ:[0,1] to X with γ(0)=γ(1)=x₀. Homotopy classes of based loops form π₁(X,x₀), with path concatenation as multiplication. Homotopies keep endpoints fixed. In a convex subset of R^n every loop contracts linearly, so the fundamental group is trivial. The circle has π₁(S¹) isomorphic to the integers, counted by winding number; proving this uses lifting paths through the covering R to S¹. Base points in the same path component yield isomorphic groups, though the isomorphism depends on a connecting path. Simply connected means path-connected with trivial fundamental group.",
    worked: "Loop γ_n(t)=(cos 2πnt,sin 2πnt) winds n times around S¹. Concatenating γ_2 and γ_{-1} gives winding number 1. Neither γ_1 nor γ_{-1} contracts inside S¹, while γ_0 is constant.",
    interpretation: "The integer invariant distinguishes loops despite continuous reshaping of their geometry.",
    trap: "Do not deform a loop through points outside the space; a disk contracts the circle loop, but S¹ itself does not contain the disk interior.",
    practice: "What is the winding number of γ(t)=(cos 6πt,sin 6πt) on 0≤t≤1, and can it contract in S¹?",
    solution: "The angle increases by 6π, which is three full turns, so winding number is 3. It cannot contract in S¹ because a null-homotopic loop would have winding number zero.",
    checks: [["What group is π₁(S¹) isomorphic to?", ["Integers under addition", "Real numbers under multiplication", "The trivial group"], 0, "Winding numbers add."], ["Must based-loop homotopies fix the base point?", ["Yes", "No", "Only for smooth loops"], 0, "The group operation uses based loops."], ["Can a nonzero winding loop contract inside the circle?", ["No", "Yes", "Only if traversed fast"], 0, "Winding number is homotopy invariant."]],
  },
  {
    lesson: "math.m29.l5", title: "Smooth manifolds and charts",
    premise: "A smooth manifold looks locally like Euclidean space even if its global shape bends or loops.",
    idea: "An n-manifold is locally homeomorphic to open subsets of R^n, with standard Hausdorff and second-countability assumptions. A smooth atlas consists of charts whose transition maps are smooth wherever chart domains overlap. A chart is a coordinate description, not the manifold itself. The circle is a one-dimensional manifold needing multiple charts; no single global angle coordinate is continuous and one-to-one all the way around. Smooth maps between manifolds are defined by smooth coordinate representations, and this condition is independent of compatible chart choice. Boundary manifolds use local half-spaces instead of open R^n.",
    worked: "Near the upper semicircle of S¹, x is a coordinate and y=sqrt(1-x²). Near the right semicircle, y is a coordinate and x=sqrt(1-y²). On an overlap away from endpoints, the transition x=sqrt(1-y²) is smooth, showing two local descriptions of the same curve.",
    interpretation: "Calculus on a manifold is local, but the compatibility rules make its results global and coordinate-independent.",
    trap: "Do not assume an entire circle can be represented smoothly by one injective angle chart with no seam.",
    practice: "What is the manifold dimension of the unit sphere S² inside R³? Explain using local coordinates.",
    solution: "S² has dimension two. Near a point with positive z, z=sqrt(1-x²-y²), so x and y vary freely in an open disk and give a local two-coordinate chart. Other charts cover the regions where this one fails.",
    checks: [["What must chart transitions satisfy for a smooth atlas?", ["Smoothness on overlaps", "A constant determinant", "A single global formula"], 0, "They make local calculus compatible."], ["Is S² a two- or three-dimensional manifold?", ["Two", "Three", "One"], 0, "It has two local free coordinates."], ["Does a chart equal the entire manifold?", ["Not necessarily", "Always", "Only for spheres"], 0, "Charts are local."]],
  },
  {
    lesson: "math.m29.l6", title: "Tangent and cotangent spaces",
    premise: "A tangent vector describes an instantaneous direction on a manifold; a cotangent vector measures such directions linearly.",
    idea: "At p∈M, tangent vectors can be defined as velocities of smooth curves through p, modulo equal action on local smooth functions. The tangent space T_pM has dimension equal to the manifold dimension. Coordinate changes transform tangent components by the Jacobian. A cotangent vector is a linear functional on tangent vectors. The differential df_p acts on v by directional differentiation. On the unit sphere, tangent vectors satisfy p·v=0. A Riemannian metric can identify vectors with covectors; without one, they remain distinct spaces.",
    worked: "At north pole p=(0,0,1) of S², the tangent plane is all (a,b,0), since p·v=v_z=0. For ambient function f(x,y,z)=x+2y, df_p(a,b,0)=a+2b. The differential is a covector; its value depends linearly on a tangent direction.",
    interpretation: "Vectors represent directions; covectors represent first-order measurements of those directions.",
    trap: "Do not call a Euclidean gradient intrinsic to an arbitrary manifold before choosing a metric.",
    practice: "At p=(1,0,0) on S², list the tangent-plane condition and evaluate d(y+z)_p on v=(0,2,-1).",
    solution: "Tangency requires p·v=v_x=0; the given v is tangent. The differential of y+z acts by v_y+v_z=2-1=1.",
    checks: [["What is T_p*S?", ["The dual space of tangent vectors", "The same set by definition", "A coordinate grid"], 0, "Covectors act linearly on tangents."], ["What characterizes sphere tangent vectors at p?", ["p·v=0", "p·v=1", "v=p"], 0, "They are orthogonal to the radius."], ["What does df_p(v) compute?", ["Directional derivative", "Global maximum", "Curvature always"], 0, "It is first-order change along v."]],
  },
  {
    lesson: "math.m29.l7", title: "Differential forms",
    premise: "Differential forms integrate naturally over oriented curves, surfaces, and higher-dimensional regions.",
    idea: "A differential k-form assigns an alternating multilinear function to k tangent vectors at each point. A one-form α=P dx+Q dy integrates along a parametrized curve γ as ∫[P(γ)x'(t)+Q(γ)y'(t)]dt. Wedge products are alternating: dx∧dy=-dy∧dx and dx∧dx=0. Exterior derivative d sends k-forms to (k+1)-forms and satisfies d²=0. For a scalar f, df is its differential; for α=P dx+Q dy on the plane, dα=(∂_x Q-∂_y P)dx∧dy. Closed means dα=0; exact means α=dβ. Exact implies closed, but the converse can fail on spaces with holes.",
    worked: "Take α=-y dx+x dy and unit circle γ(t)=(cos t,sin t). Then α(γ')=-sin t(-sin t)+cos t(cos t)=1, so ∮α=2π. Also dα=2 dx∧dy; integrating over unit disk gives 2π, matching the boundary result.",
    interpretation: "Forms encode both orientation and the dimension of what is being integrated.",
    trap: "Do not commute wedge factors without changing sign; orientation is part of the algebra.",
    practice: "Compute dα for α=x²dy on R² and identify whether α is closed.",
    solution: "Here P=0 and Q=x², so dα=(∂_xQ-∂_yP)dx∧dy=2x dx∧dy. It is not closed on all R² because dα is nonzero where x≠0.",
    checks: [["What is dx∧dy relative to dy∧dx?", ["Its negative", "Equal", "Their product"], 0, "Wedge products alternate."], ["What does d² equal?", ["Zero", "Identity", "Always two"], 0, "Exterior derivatives compose to zero."], ["Does exact imply closed?", ["Yes", "No", "Only on a circle"], 0, "d(dβ)=0."]],
  },
  {
    lesson: "math.m29.l8", title: "Stokes' theorem on manifolds",
    premise: "Generalized Stokes turns an integral of a derivative over a region into an integral of the original form on its oriented boundary.",
    idea: "For a compact oriented smooth manifold M with boundary and a suitable smooth (n-1)-form ω, ∫_M dω=∫_{∂M}ω with the induced boundary orientation. The fundamental theorem of calculus, Green's theorem, classical curl Stokes, and divergence theorem are coordinate expressions of this principle. Orientation signs matter; reversing M's orientation reverses both sides. If M has multiple boundary components, every component participates with its induced orientation. Closed manifolds have empty boundary, so the integral of an exact top-degree form over them is zero. The theorem's differentiability, compactness or support, and orientation hypotheses must be checked.",
    worked: "Let M be the oriented unit disk and ω=-y dx+x dy. We computed dω=2 dx∧dy, so ∫_M dω=2·area(M)=2π. The counterclockwise boundary integral ∮ω=2π. Clockwise orientation would negate the boundary integral and correspond to reversing the disk orientation.",
    interpretation: "Interior accumulation and boundary circulation are two descriptions of one oriented relation.",
    trap: "Do not leave out inner boundary components of a region with holes; they carry opposite induced orientation.",
    practice: "For interval M=[a,b] with standard orientation and scalar zero-form f(x)=x², write Stokes' theorem explicitly.",
    solution: "The exterior derivative is df=2x dx, so ∫_a^b2x dx=b²-a². The oriented boundary is {b}-{a}; its integral of f is f(b)-f(a)=b²-a². This is the fundamental theorem of calculus.",
    checks: [["What identity summarizes generalized Stokes?", ["Integral over M of dω equals boundary integral of ω", "Both sides always zero", "Interior equals volume squared"], 0, "Derivative moves to oriented boundary."], ["What happens to an inner boundary?", ["It contributes with induced opposite orientation", "It is ignored", "It always doubles the outer boundary"], 0, "All boundary components count."], ["What familiar theorem is the one-dimensional case?", ["Fundamental theorem of calculus", "Bayes' theorem", "Rank-nullity"], 0, "Integrating df gives endpoint values."]],
  },
];
