import type { MathLecture } from "./lectures";

/** MATH 23B: regions, fields, and the boundary theorems. */
export const MATH_VECTOR_CALCULUS: MathLecture[] = [
  {
    lesson: "math.m12.l1", title: "Double integrals and iterated integrals",
    premise: "A double integral adds a density across a two-dimensional region. Slicing the region turns that limit of small-area sums into ordinary one-variable integrals.",
    idea: "For a continuous function on a rectangle, ∬_R f dA equals either iterated order by Fubini's theorem. On a nonrectangular region, sketch the boundary and express each slice with variable limits. For each x from a to b, let y run from g(x) to h(x). Integrate f(x,y) in y first, then integrate that result in x. Reversing order requires a new description of the same region, not merely swapping the differential symbols. If f is mass per unit area, the integral gives mass; if f=1, it gives area.",
    worked: "Let R be the triangle bounded by y=0, y=x, and x=1. With vertical slices, integrate x+y over y from 0 to x. This gives 3x²/2, whose integral from x=0 to 1 is 1/2. With horizontal slices, y runs from 0 to 1 while x runs from y to 1. The integral is again 1/2.",
    interpretation: "The two iterated integrals represent the same area-weighted sum; the better order is the one with simpler limits or antiderivative.",
    trap: "A triangular region does not have independent rectangular bounds. Draw a representative slice and retain the dependence of its endpoints.",
    practice: "Integrate f(x,y)=x over the triangle under y=x/2 for 0≤x≤2. Give units if f is kilograms per square meter.",
    solution: "The integral is ∫₀²∫₀ˣ⁄² x dy dx=∫₀² x²/2 dx=4/3 kilograms. The inner width x/2 depends on x; replacing it by a constant would integrate a different region.",
    checks: [["What does ∬_R 1 dA measure?", ["Area of R", "Perimeter of R", "Its maximum height"], 0, "The integrand is unit density."], ["What changes when reversing integration order?", ["The slice limits must be rederived", "Only dx and dy swap", "The region disappears"], 0, "Describe the same region using the new slice direction."], ["When can a continuous rectangular integral be iterated in either order?", ["By Fubini's theorem", "Only when f=1", "Only for circles"], 0, "Continuity on a compact rectangle is sufficient here."]],
  },
  {
    lesson: "math.m12.l2", title: "Polar-coordinate integrals",
    premise: "Circular regions are awkward in Cartesian slices but simple in radius and angle. The area element changes when coordinates change.",
    idea: "Set x=r cos θ and y=r sin θ with r≥0. A small polar cell has radial width dr and arc width about r dθ. Therefore its area is approximately r dr dθ. Describe the region by angular and radial bounds before integrating. A full disk has angle from zero to 2π and radius from zero to a. A first-quadrant quarter-disk uses angle from zero to π/2. Transform the integrand too: x²+y²=r². The origin and angle seam cause coordinate overlap only on sets of area zero in ordinary integral applications.",
    worked: "For the unit disk, ∬_D(x²+y²)dA=∫₀²π∫₀¹ r²·r dr dθ. The radial integral is 1/4, and the angular integral multiplies by 2π, giving π/2. The extra r is the coordinate-area factor, not part of the original function.",
    interpretation: "The result is smaller than the disk's area π because r²≤1 throughout the disk; this gives a quick reasonableness check.",
    trap: "Omitting the Jacobian r makes the area of a disk come out as 2πa instead of πa². Check dimensions when unsure.",
    practice: "Find the area of the annulus 1≤x²+y²≤4 using polar coordinates.",
    solution: "Radius runs from 1 to 2, and angle covers a full revolution. Integrate r from 1 to 2 to obtain 3/2. Multiply by the angular span 2π to get area 3π. The annulus formula π(2²-1²) agrees.",
    checks: [["What replaces dA in polar coordinates?", ["r dr dθ", "dr dθ", "r² dr dθ"], 0, "Arc width grows proportionally to radius."], ["What is x²+y² in polar form?", ["r²", "r", "θ²"], 0, "Use the Pythagorean identity."], ["What is the radial interval for 1≤x²+y²≤4?", ["1≤r≤2", "1≤r≤4", "0≤r≤2"], 0, "r is nonnegative and r² lies between 1 and 4."]],
  },
  {
    lesson: "math.m12.l3", title: "Triple and cylindrical-coordinate integrals",
    premise: "A triple integral accumulates a quantity through volume. Cylindrical coordinates retain height while simplifying a circular horizontal footprint.",
    idea: "For density ρ(x,y,z), total mass is ∭_E ρ dV. Slice a solid in z, then integrate over its horizontal footprint. In cylindrical coordinates x=r cos θ, y=r sin θ, z=z, and dV=r dz dr dθ in one common order. Describe lower and upper surfaces z=g(r,θ), h(r,θ) and the footprint limits. A constant density times volume should reproduce the expected mass, and dimensional analysis should return cubic units when integrating 1.",
    worked: "Find the volume of the cylinder with radius 2 and height 3. Height runs from z=0 to z=3, radius from 0 to 2, and angle through a full revolution. Integrating r first over height gives 3r. Its radial integral is 6, and multiplying by 2π gives 12π. The familiar cylinder formula π(2²)(3) agrees.",
    interpretation: "The inner z integral measures column height; the remaining polar integral adds the column volumes over the disk.",
    trap: "The radial factor remains in a triple integral after converting the x-y plane. It is not removed by the extra z integration.",
    practice: "Set up and evaluate the volume under z=4-x²-y² above z=0.",
    solution: "The footprint is r≤2 because 4-r²≥0. Volume=∫₀²π∫₀²∫₀⁴⁻ʳ² r dz dr dθ=2π∫₀²(4r-r³)dr=2π(8-4)=8π.",
    checks: [["What is the cylindrical volume element?", ["r dz dr dθ", "dz dr dθ", "r² dz dr dθ"], 0, "The horizontal polar conversion supplies r."], ["What does integrating 1 over a solid yield?", ["Volume", "Surface area", "Mass regardless of density"], 0, "Unit volume density accumulates volume."], ["Where is 4-r² nonnegative?", ["0≤r≤2", "r≥2", "0≤r≤4"], 0, "Solve r²≤4 with r≥0."]],
  },
  {
    lesson: "math.m12.l4", title: "Change of variables and Jacobians",
    premise: "A coordinate map stretches tiny areas and volumes. Its Jacobian determinant measures that local scale, so an integral must account for it.",
    idea: "For a smooth one-to-one transformation T(u,v)=(x(u,v),y(u,v)) on the region, ∬_R f(x,y)dA=∬_S f(T(u,v))|det DT(u,v)|du dv, subject to the usual regularity assumptions. The absolute value ensures nonnegative area even if orientation reverses. Transform the region as well as the integrand and differential. The map's derivative is the best local linear approximation, so a small parameter rectangle becomes approximately a parallelogram with area scaled by |det DT|. For a many-to-one map, restrict to appropriate pieces or account for multiplicity.",
    worked: "Let x=2u and y=3v, where 0≤u,v≤1. Then DT=diag(2,3) and |det DT|=6. Integrating 1 over the mapped rectangle gives ∫₀¹∫₀¹6 dv du=6, the area of a 2-by-3 rectangle. Integrating x instead gives ∫₀¹∫₀¹(2u)6 dv du=6.",
    interpretation: "The scale factor is geometric. It applies regardless of whether the integrand itself is constant.",
    trap: "Do not use det DT without absolute value for area, and do not assume a map is one-to-one across an entire angular cycle including both endpoints.",
    practice: "Use x=u+v, y=u-v on 0≤u,v≤1 to find the area of the image parallelogram.",
    solution: "DT=[[1,1],[1,-1]], whose determinant is -2, so the area factor is 2. The unit square has area 1, hence the image has area ∫₀¹∫₀¹2 dv du=2. The negative determinant records reversed orientation, not negative area.",
    checks: [["Why take an absolute Jacobian determinant for area?", ["Area is nonnegative even if orientation reverses", "The determinant is always positive", "It removes the integrand"], 0, "Orientation and size are distinct."], ["What else must change besides dA?", ["The integrand and region", "Only the title", "Nothing"], 0, "Everything must be expressed in new variables."], ["What is the scale of x=2u,y=3v?", ["6", "5", "1/6"], 0, "Multiply independent axis stretch factors."]],
  },
  {
    lesson: "math.m12.l5", title: "Improper double integrals",
    premise: "A two-dimensional integral can fail because the region is unbounded or the integrand blows up. Convergence must be justified, not inferred from a finite-looking sketch.",
    idea: "Define an integral over an unbounded region through an increasing family of bounded regions, or remove a singular neighborhood and take a limit. For nonnegative integrands these limits are monotone, although they may be infinite. Polar coordinates reveal radial thresholds: near the origin, r^{-p} with dA=r dr dθ behaves like ∫r^{1-p}dr and converges for p<2. At infinity in two dimensions it converges for p>2. A signed integrand needs extra care: different exhaustion shapes can give different conditional answers, so absolute integrability or an explicitly stated limiting scheme matters.",
    worked: "On the unit disk, integrate 1/sqrt(x²+y²), excluding the origin initially. Polar form is ∫₀²π∫ₑ¹(1/r)r dr dθ=2π(1-ε). Sending ε to zero gives 2π. The function is singular at one point but its two-dimensional integral is finite.",
    interpretation: "The area of thin rings shrinks with r, offsetting this particular singularity. In one dimension, ∫₀¹1/x dx would diverge.",
    trap: "The point singularity being a set of area zero does not by itself prove integrability; 1/r² still diverges because ∫dr/r does.",
    practice: "For which p does ∬ over the unit disk of r^{-p} dA converge near the origin?",
    solution: "Remove r<ε and integrate 2π∫ₑ¹r^{1-p}dr. The lower-end limit is finite exactly when 1-p>-1, or p<2. At p=2 it diverges logarithmically; for p>2 it diverges as a power.",
    checks: [["What radial power results from r^{-p}dA?", ["r^{1-p}", "r^{-p}", "r^{2-p}"], 0, "The polar area element contributes one r."], ["At what p does the origin threshold occur in two dimensions?", ["p=2", "p=1", "p=0"], 0, "Test ∫ near zero of r^{1-p}."], ["Does a zero-area singular set alone imply convergence?", ["No", "Yes", "Only for disks"], 0, "The nearby mass can still diverge."]],
  },
  {
    lesson: "math.m12.l6", title: "Vector fields and line integrals",
    premise: "A vector field assigns a direction and magnitude at every point. A line integral measures how much that field acts along a chosen path.",
    idea: "For a piecewise smooth oriented curve r(t), a work or circulation integral is ∫_C F·dr=∫_a^b F(r(t))·r'(t)dt. Orientation matters: reversing the path changes the sign. By contrast, a scalar line integral ∫_C f ds=∫f(r(t))|r'(t)|dt uses arc length and does not change sign when direction reverses. Parametrize the actual curve, determine its interval and orientation, substitute every field component, and keep the dot product with velocity. Distinguish force-work units from scalar density-length units.",
    worked: "For F(x,y)=(-y,x), take the unit circle counterclockwise as r(t)=(cos t,sin t), 0≤t≤2π. Then F(r)=(-sin t,cos t)=r'(t), so F·r'=1 and ∮_C F·dr=2π. Reversing orientation gives -2π.",
    interpretation: "The field is tangent to the circle and aligned with counterclockwise motion, so positive circulation is expected before calculation.",
    trap: "Do not replace the vector dot product by field magnitude times path length unless the field is tangent and aligned everywhere.",
    practice: "Compute ∫_C (x,y)·dr along the straight path r(t)=(t,2t), 0≤t≤1.",
    solution: "F(r(t))=(t,2t) and r'(t)=(1,2), so the integrand is t+4t=5t. Its integral is 5/2. The potential (x²+y²)/2 gives the same endpoint difference, (1+4)/2.",
    checks: [["What factor accompanies F(r(t)) in a work integral?", ["r'(t) in a dot product", "Only |r'(t)|", "The curvature"], 0, "Work pairs force with directed displacement."], ["What does reversing orientation do to ∫F·dr?", ["Changes its sign", "Never changes it", "Squares it"], 0, "Directed displacement reverses."], ["Which line integral is orientation-independent?", ["∫f ds", "∫F·dr", "Circulation"], 0, "Arc length is nonnegative."]],
  },
  {
    lesson: "math.m12.l7", title: "Conservative fields and potential functions",
    premise: "When a vector field is the gradient of a potential, its work depends on endpoints rather than the path between them.",
    idea: "If F=∇φ on a region containing the path, the fundamental theorem for line integrals gives ∫_C F·dr=φ(B)-φ(A). Therefore every closed-path integral is zero. On a simply connected planar region, continuously differentiable F=(P,Q) with P_y=Q_x is conservative; the mixed-partial condition alone can fail on a region with a hole. To find φ, integrate P with respect to x and add an unknown function of y, then differentiate with respect to y and match Q. Check the resulting gradient and the domain.",
    worked: "For F=(2xy+1,x²+2y), integrate P in x to obtain φ=x²y+x+g(y). Then φ_y=x²+g'(y)=x²+2y, so g(y)=y² plus a constant. From A=(0,0) to B=(1,2), work=φ(1,2)-φ(0,0)=2+1+4=7 regardless of the path.",
    interpretation: "A potential compresses a path-dependent computation into two evaluations, but only after its existence and domain are established.",
    trap: "Do not conclude that matching cross-partials on a punctured domain guarantees a global potential; topological holes can obstruct it.",
    practice: "Find a potential for F=(2x+3y,3x+4y), then compute work from (0,0) to (1,1).",
    solution: "Integrate the first component: φ=x²+3xy+g(y). Matching φ_y=3x+g'(y)=3x+4y gives g=2y². The endpoint difference is φ(1,1)-φ(0,0)=1+3+2=6.",
    checks: [["What determines work for F=∇φ?", ["Potential difference at endpoints", "Only path length", "The region's area"], 0, "Apply the chain rule along the curve."], ["What is a closed-path integral of a conservative field?", ["Zero", "Always positive", "Always 2π"], 0, "Start and end potential values coincide."], ["Why inspect domain topology for the cross-partial test?", ["A hole may obstruct a global potential", "A hole changes derivatives", "All domains are simply connected"], 0, "Local curl-free behavior need not yield a global potential."]],
  },
  {
    lesson: "math.m12.l8", title: "Green's theorem",
    premise: "Green's theorem converts circulation around a planar boundary into accumulated local rotation inside it.",
    idea: "If C is the positively oriented, piecewise smooth boundary of a suitable planar region D and P,Q have continuous first partials nearby, then ∮_C P dx+Q dy=∬_D(Q_x-P_y)dA. Positive orientation means the region stays to the left as the boundary is traversed; outer boundaries run counterclockwise and hole boundaries clockwise. Verify orientation, regularity, and all boundary components before using the theorem. The related flux form uses outward normal flow and divergence P_x+Q_y. This theorem relates a global boundary measurement to a local density, not merely a shortcut for integration.",
    worked: "For F=(-y/2,x/2) on the unit disk, Q_x-P_y=1/2-(-1/2)=1. Green's theorem gives counterclockwise circulation ∬_D1 dA=π. Direct parametrization also gives F(r)·r'=1/2 on 0≤t≤2π, yielding π.",
    interpretation: "Unit curl throughout the disk accumulates to its area. Reverse the boundary direction and the circulation is -π.",
    trap: "Do not omit inner boundaries on a region with holes, and do not call clockwise orientation positive for a simple outer boundary.",
    practice: "Find ∮_C -y dx+x dy around the counterclockwise boundary of the rectangle 0≤x≤2, 0≤y≤3.",
    solution: "Here Q_x=1 and P_y=-1, so curl is 2. Rectangle area is 6; Green's theorem gives 2·6=12. The field is smooth everywhere and the boundary orientation is positive.",
    checks: [["What is the planar curl density for (P,Q)?", ["Q_x-P_y", "P_x+Q_y", "P_y+Q_x"], 0, "It is the integrand in circulation-form Green's theorem."], ["How does the outer boundary run for positive orientation?", ["Counterclockwise", "Clockwise", "Either with no sign change"], 0, "The region remains on the left."], ["How is a hole boundary oriented?", ["Clockwise", "Counterclockwise", "It is omitted"], 0, "The region must stay on the left along every component."]],
  },
  {
    lesson: "math.m12.l9", title: "Surface integrals and flux",
    premise: "A surface integral adds density over a curved sheet; flux measures a vector field crossing that sheet in a chosen normal direction.",
    idea: "For a smooth parametrization r(u,v), the oriented area vector is r_u×r_v du dv. Scalar area is dS=|r_u×r_v|du dv, so ∫_S f dS accumulates scalar density. Flux is ∫_S F·n dS=∫_D F(r(u,v))·(r_u×r_v)du dv for the orientation supplied by that cross product. Reversing orientation negates flux but not scalar area. A graph z=g(x,y), oriented upward, has area vector (-g_x,-g_y,1)dx dy; do not normalize and then forget the area factor.",
    worked: "Take the upward horizontal disk z=2, x²+y²≤1, and field F=(0,0,3). Parametrize r(x,y)=(x,y,2); r_x×r_y=(0,0,1). Flux is ∬_D3 dA=3π. Its scalar area is ∬_D1 dA=π.",
    interpretation: "The field crosses each unit of disk area with normal component 3, so flux is component times area. Downward orientation would produce -3π.",
    trap: "For a graph, use either the unit normal together with dS or the unnormalized cross product with du dv; combining both area factors counts geometry twice.",
    practice: "Find the upward flux of F=(0,0,z) through z=x+y over the unit square 0≤x,y≤1.",
    solution: "The upward area vector is (-1,-1,1)dx dy. On the graph, F=(0,0,x+y), so its dot product with the area vector is x+y. Integrate over the unit square: ∫₀¹∫₀¹(x+y)dy dx=1.",
    checks: [["What vector gives oriented area from r(u,v)?", ["r_u×r_v", "r_u+r_v", "|r_u×r_v| alone"], 0, "The cross product contains both orientation and local scale."], ["Does reversing orientation change scalar area?", ["No", "Yes, its sign reverses", "It becomes zero"], 0, "Scalar area uses a magnitude."], ["What changes sign under reversed orientation?", ["Flux", "Scalar area", "Surface shape"], 0, "The normal direction reverses."]],
  },
  {
    lesson: "math.m12.l10", title: "Stokes' theorem",
    premise: "Stokes' theorem is Green's circulation principle on a curved surface: circulation around the edge equals total normal curl through the surface.",
    idea: "For an orientable smooth surface S with compatible oriented boundary C and a sufficiently smooth field F, ∮_C F·dr=∬_S (∇×F)·n dS. Use the right-hand rule: curled fingers follow the boundary when the thumb points along the selected normal. The surface can often be replaced by an easier one sharing the same boundary, provided the field is smooth on the intervening geometry and orientations match. Check whether a boundary actually exists; a closed surface has no boundary and its total normal curl flux is zero under the theorem's hypotheses.",
    worked: "Let F=(-y/2,x/2,0), and let C be the unit circle in z=0, counterclockwise viewed from above. Curl F=(0,0,1). On the flat unit disk with upward normal, the curl flux is its area π. Therefore ∮_C F·dr=π; this agrees with Green's theorem.",
    interpretation: "The same circulation can be measured on many spanning surfaces. Local curl adds to the boundary's total turning effect.",
    trap: "A clockwise boundary with an upward normal violates compatible orientation; its line integral is -π, so choose the downward normal or reverse the curve.",
    practice: "For F=(-y,x,0), find circulation around the circle x²+y²=4, z=0, counterclockwise from above, using Stokes' theorem.",
    solution: "Curl F=(0,0,2). The upward disk has area 4π, so circulation is 2·4π=8π. The field is smooth and the specified curve orientation matches the upward normal.",
    checks: [["What surface density appears in Stokes' theorem?", ["Normal component of curl", "Divergence", "Field magnitude"], 0, "Curl measures local rotation."], ["What connects the surface normal to boundary direction?", ["Right-hand rule", "Smallest-coordinate rule", "No relationship"], 0, "Orientations must be compatible."], ["What is the boundary of a complete sphere?", ["Empty", "Its equator", "Every latitude"], 0, "A closed surface has no edge."]],
  },
  {
    lesson: "math.m12.l11", title: "The divergence theorem",
    premise: "The divergence theorem balances total outward flow across a closed surface with the sum of local sources and sinks inside it.",
    idea: "For a suitable solid V with outward-oriented closed boundary ∂V and a continuously differentiable field F, ∯_{∂V}F·n dS=∭_V∇·F dV, where ∇·F=P_x+Q_y+R_z. If divergence is positive, a tiny surrounding box has net outward flow to first order. The theorem applies to the entire closed boundary, including caps or inner surfaces. A hole's boundary normal points from the solid into the hole. For an open surface, add a cap and subtract its flux instead of applying the closed-surface theorem directly.",
    worked: "For F=(x,y,z) on a ball of radius a, divergence is 3. Ball volume is 4πa³/3, so outward flux is 3·4πa³/3=4πa³. Directly on the sphere, F is radial, its normal component is a, and sphere area is 4πa², giving the same answer.",
    interpretation: "The equality checks both scaling and units: a field linear in distance gives flux scaling like a³.",
    trap: "Do not apply the theorem to an unclosed hemisphere without including its disk. The disk flux may be nonzero for other fields.",
    practice: "Find outward flux of F=(x,0,0) through the box with side lengths 2, 3, and 4 in the positive coordinate directions.",
    solution: "Divergence is 1 and box volume is 2·3·4=24, so flux is 24. Directly, only the x=2 face contributes: F·n=2 over area 12. The x=0 face contributes zero.",
    checks: [["Which local quantity does the divergence theorem integrate?", ["Divergence over volume", "Curl over volume", "Speed over length"], 0, "It measures net local outflow."], ["What orientation is required on a closed boundary?", ["Outward", "Arbitrary with no sign effect", "Always upward"], 0, "Flux direction sets the sign."], ["Can the theorem directly handle only an open hemisphere?", ["No, close it or account for a cap", "Yes, without modification", "Only if radius is one"], 0, "The stated theorem uses a closed boundary."]],
  },
  {
    lesson: "math.m12.l12", title: "Differential forms and vector calculus",
    premise: "Green, Stokes, and divergence theorems share one idea: integrating a derivative over a region equals integrating the original object over its oriented boundary.",
    idea: "An oriented line integral uses a 1-form P dx+Q dy. Its exterior derivative is (Q_x-P_y)dx∧dy, and Green's theorem says integrating that 2-form over a region equals integrating the 1-form around its boundary. In three dimensions, flux has a corresponding 2-form; its exterior derivative contains divergence times the volume form. The general Stokes theorem writes ∫_M dω=∫_{∂M}ω for an oriented manifold with boundary under suitable smoothness. The identity d(dω)=0 explains why gradients have zero curl and curls have zero divergence where derivatives commute. This language organizes the theorems; it does not remove the need to specify domains and orientation.",
    worked: "Take ω=-y dx+x dy on the unit disk. Its derivative is dω=(1-(-1))dx∧dy=2dx∧dy. The interior integral is 2π, so the counterclockwise boundary integral is 2π. Directly, x=cos t,y=sin t gives -y dx+x dy=(sin²t+cos²t)dt=dt, also totaling 2π.",
    interpretation: "The disk calculation is Green's theorem in differential-form notation. The same boundary principle extends to surfaces and higher-dimensional regions.",
    trap: "The notation does not authorize ignoring orientation or smoothness. Reversing the disk's orientation reverses both sides of the equality.",
    practice: "For ω=x dy on the unit square with counterclockwise boundary, compute dω and both sides of Stokes' boundary identity.",
    solution: "dω=dx∧dy, so its integral over the unit square is 1. On the boundary, bottom and left contribute zero; the right edge has x=1 and y rises from 0 to 1, contributing 1; the top edge has dy=0. The total boundary integral is 1.",
    checks: [["What is d(P dx+Q dy) in the plane?", ["(Q_x-P_y)dx∧dy", "(P_x+Q_y)dx∧dy", "P Q dx∧dy"], 0, "Differentiate coefficients and respect antisymmetry."], ["What does the general Stokes theorem compare?", ["Interior derivative and oriented boundary integral", "Two unrelated volumes", "Only endpoint values"], 0, "Integration and boundary formation are linked."], ["What does d∘d equal for smooth forms?", ["Zero", "One", "The identity"], 0, "Boundary of boundary and commuting mixed derivatives underlie the identity."]],
  },
];
