import type { Concept } from "../types";

/**
 * The concept graph.
 *
 * Everything else in the app is derived from this: the roadmap, prerequisite
 * gating, the diagnostic, what the help ladder refers you to, and what the
 * scheduler thinks you've forgotten. Content units point at these ids; nothing
 * points back. Keep ids stable — they are the primary key of your memory.
 */
export const CONCEPTS: Concept[] = [
  // ------------------------------------------------- module 0, first steps
  {
    id: "js.intro.program",
    title: "How code runs",
    stage: 0,
    kind: "mental-model",
    requires: [],
  },
  {
    id: "js.intro.numbers",
    title: "Numbers and maths",
    stage: 0,
    kind: "syntax",
    requires: ["js.intro.program"],
  },
  {
    id: "js.intro.strings",
    title: "Text and template literals",
    stage: 0,
    kind: "syntax",
    requires: ["js.intro.program"],
  },
  {
    id: "js.intro.collections",
    title: "Arrays and objects, briefly",
    stage: 0,
    kind: "syntax",
    requires: ["js.intro.program"],
  },
  {
    id: "js.intro.errors",
    title: "Reading errors",
    stage: 0,
    kind: "mental-model",
    requires: ["js.intro.program"],
  },

  // ---------------------------------------------------------- stage 0
  {
    id: "js.values.reference",
    title: "Reference vs value",
    stage: 0,
    kind: "mental-model",
    requires: [],
    atom: "atom.reference",
  },
  {
    id: "js.values.coercion",
    title: "Coercion and truthiness",
    stage: 0,
    kind: "mental-model",
    requires: [],
  },
  {
    id: "js.values.declarations",
    title: "let and const",
    stage: 0,
    kind: "syntax",
    requires: [],
  },
  {
    id: "js.values.types",
    title: "Types and typeof",
    stage: 0,
    kind: "mental-model",
    requires: [],
  },
  {
    id: "js.values.truthiness",
    title: "Truthiness",
    stage: 0,
    kind: "mental-model",
    requires: ["js.values.types"],
  },
  {
    id: "js.values.equality",
    title: "Equality",
    stage: 0,
    kind: "mental-model",
    requires: ["js.values.types"],
  },
  {
    id: "js.flow.conditionals",
    title: "if, else, ternary",
    stage: 0,
    kind: "syntax",
    requires: ["js.values.truthiness"],
  },
  {
    id: "js.flow.loops",
    title: "Loops",
    stage: 0,
    kind: "syntax",
    requires: ["js.flow.conditionals"],
  },
  {
    id: "js.flow.iteration-forms",
    title: "for...of vs for...in",
    stage: 0,
    kind: "syntax",
    requires: ["js.flow.loops"],
  },
  {
    id: "js.flow.guards",
    title: "Guard clauses",
    stage: 0,
    kind: "pattern",
    requires: ["js.flow.conditionals"],
  },
  {
    id: "js.functions.params",
    title: "Parameters, defaults, rest",
    stage: 0,
    kind: "syntax",
    requires: ["js.functions.basics"],
  },
  {
    id: "js.functions.arrow",
    title: "Arrow functions",
    stage: 0,
    kind: "syntax",
    requires: ["js.functions.basics"],
  },
  {
    id: "js.functions.as-values",
    title: "Functions as values",
    stage: 1,
    kind: "mental-model",
    requires: ["js.functions.basics"],
  },
  {
    id: "js.functions.pure",
    title: "Pure functions",
    stage: 1,
    kind: "pattern",
    requires: ["js.values.reference"],
  },
  {
    id: "js.array.access",
    title: "Indexing and length",
    stage: 1,
    kind: "syntax",
    requires: [],
  },
  {
    id: "js.array.addremove",
    title: "Adding and removing",
    stage: 1,
    kind: "api",
    requires: ["js.array.access"],
  },
  {
    id: "js.array.search",
    title: "Searching an array",
    stage: 1,
    kind: "api",
    requires: ["js.array.access"],
  },
  {
    id: "js.array.slicing",
    title: "Slicing ranges",
    stage: 1,
    kind: "api",
    requires: ["js.array.access"],
  },
  {
    id: "js.array.map",
    title: "map",
    stage: 1,
    kind: "api",
    requires: ["js.functions.arrow"],
  },
  {
    id: "js.array.filter",
    title: "filter",
    stage: 1,
    kind: "api",
    requires: ["js.functions.arrow"],
  },
  {
    id: "js.array.predicates",
    title: "some and every",
    stage: 1,
    kind: "api",
    requires: ["js.array.filter"],
  },
  {
    id: "js.array.chaining",
    title: "Chaining",
    stage: 1,
    kind: "pattern",
    requires: ["js.array.map", "js.array.filter", "js.array.reduce"],
  },
  {
    id: "js.functions.basics",
    title: "Functions, params, defaults",
    stage: 0,
    kind: "syntax",
    requires: [],
  },
  {
    id: "js.scope.block-scope",
    title: "Block scope, let vs var",
    stage: 0,
    kind: "mental-model",
    requires: ["js.functions.basics"],
  },

  // ---------------------------------------------------------- stage 1
  {
    id: "js.array.iteration",
    title: "map, filter, find",
    stage: 1,
    kind: "api",
    requires: ["js.functions.basics"],
  },
  {
    id: "js.array.reduce",
    title: "reduce",
    stage: 1,
    kind: "api",
    requires: ["js.array.iteration"],
    atom: "atom.reduce",
  },
  {
    id: "js.array.mutation",
    title: "Copies vs mutations",
    stage: 1,
    kind: "api",
    requires: ["js.values.reference"],
    atom: "atom.mutation",
  },
  {
    id: "js.array.sort",
    title: "sort and comparators",
    stage: 1,
    kind: "api",
    requires: ["js.array.mutation"],
    atom: "atom.sort",
  },
  {
    id: "js.object.access",
    title: "Reading and writing properties",
    stage: 1,
    kind: "syntax",
    requires: ["js.intro.collections"],
  },
  {
    id: "js.object.iteration",
    title: "Object keys, values, entries",
    stage: 1,
    kind: "api",
    requires: ["js.array.iteration"],
  },
  {
    id: "js.object.spread",
    title: "Object spread and rest",
    stage: 1,
    kind: "syntax",
    requires: ["js.object.destructuring"],
  },
  {
    id: "js.object.optional",
    title: "Optional chaining",
    stage: 1,
    kind: "syntax",
    requires: ["js.object.access"],
  },
  {
    id: "js.object.lookup",
    title: "Objects as lookup tables",
    stage: 1,
    kind: "pattern",
    requires: ["js.object.access"],
  },
  {
    id: "js.object.destructuring",
    title: "Destructuring and spread",
    stage: 1,
    kind: "syntax",
    requires: ["js.values.reference"],
  },
  {
    id: "js.string.basics",
    title: "Indexing, slicing, immutability",
    stage: 1,
    kind: "syntax",
    requires: ["js.intro.strings", "js.array.slicing"],
  },
  {
    id: "js.string.search",
    title: "Searching and replacing text",
    stage: 1,
    kind: "api",
    requires: ["js.string.basics", "js.array.search"],
  },
  {
    id: "js.string.split",
    title: "split and join",
    stage: 1,
    kind: "api",
    requires: ["js.string.basics", "js.array.access"],
  },
  {
    id: "js.string.methods",
    title: "Building strings",
    stage: 1,
    kind: "api",
    requires: ["js.string.basics"],
  },
  {
    id: "js.string.codes",
    title: "Character codes",
    stage: 1,
    kind: "mental-model",
    requires: ["js.string.basics"],
  },
  {
    id: "js.set",
    title: "Set",
    stage: 1,
    kind: "api",
    requires: ["js.array.search"],
  },
  {
    id: "js.mapset",
    title: "Map and Set",
    stage: 1,
    kind: "api",
    requires: ["js.object.iteration"],
  },
  {
    id: "js.map.counting",
    title: "Counting with a Map",
    stage: 1,
    kind: "pattern",
    requires: ["js.mapset"],
  },
  {
    id: "js.functions.factories",
    title: "Functions returning functions",
    stage: 2,
    kind: "pattern",
    requires: ["js.functions.closures"],
  },
  {
    id: "js.functions.callbacks",
    title: "Callbacks",
    stage: 2,
    kind: "pattern",
    requires: ["js.functions.as-values"],
  },
  {
    id: "js.functions.composition",
    title: "Wrapping and composing",
    stage: 2,
    kind: "pattern",
    requires: ["js.functions.factories"],
  },

  // ---------------------------------------------------------- stage 2
  {
    id: "js.functions.closures",
    title: "Closures",
    stage: 2,
    kind: "mental-model",
    requires: ["js.functions.basics", "js.scope.block-scope"],
    atom: "atom.closures",
  },
  {
    id: "js.functions.private-state",
    title: "Private state without classes",
    stage: 2,
    kind: "pattern",
    requires: ["js.functions.closures"],
  },
  {
    id: "js.functions.hof",
    title: "Higher-order functions",
    stage: 2,
    kind: "pattern",
    requires: ["js.functions.closures"],
  },
  {
    id: "js.functions.this",
    title: "this binding",
    stage: 2,
    kind: "mental-model",
    requires: ["js.functions.basics"],
    atom: "atom.this",
  },
  {
    id: "js.functions.binding",
    title: "call, apply and bind",
    stage: 2,
    kind: "api",
    requires: ["js.functions.this"],
  },
  {
    id: "js.classes",
    title: "Classes",
    stage: 2,
    kind: "syntax",
    requires: ["js.functions.this"],
  },
  {
    id: "js.prototypes",
    title: "Prototypes and the chain",
    stage: 2,
    kind: "mental-model",
    requires: ["js.classes"],
  },
  {
    id: "js.inheritance",
    title: "Inheritance vs composition",
    stage: 2,
    kind: "pattern",
    requires: ["js.prototypes"],
  },
  {
    id: "js.functions.recursion",
    title: "Recursion",
    stage: 2,
    kind: "pattern",
    requires: ["js.functions.basics"],
  },

  // ---------------------------------------------------------- stage 3
  {
    id: "js.async.event-loop",
    title: "The event loop",
    stage: 3,
    kind: "mental-model",
    requires: ["js.functions.basics"],
    atom: "atom.event-loop",
  },
  {
    id: "js.async.promises",
    title: "Promises and async/await",
    stage: 3,
    kind: "api",
    requires: ["js.async.event-loop"],
  },
  {
    id: "js.async.await",
    title: "async and await",
    stage: 3,
    kind: "syntax",
    requires: ["js.async.promises"],
  },
  {
    id: "js.async.errors",
    title: "Async error handling",
    stage: 3,
    kind: "pattern",
    requires: ["js.async.await"],
  },
  {
    id: "js.async.combinators",
    title: "Promise.all and friends",
    stage: 3,
    kind: "api",
    requires: ["js.async.promises"],
  },
  {
    id: "js.async.concurrency",
    title: "Controlling concurrency",
    stage: 3,
    kind: "pattern",
    requires: ["js.async.combinators"],
  },

  // ------------------------------------------- module 12, the odds and ends
  {
    id: "js.errors",
    title: "Throwing and catching",
    stage: 3,
    kind: "pattern",
    requires: ["js.flow.guards"],
  },
  {
    id: "js.modules",
    title: "Modules",
    stage: 3,
    kind: "syntax",
    requires: ["js.functions.basics"],
  },
  {
    id: "js.json",
    title: "JSON and dates",
    stage: 3,
    kind: "api",
    requires: ["js.object.access", "js.errors"],
  },

  // ---------------------------------------------------------- stage 5
  {
    id: "pattern.hash-map",
    title: "Hash map lookup",
    stage: 5,
    kind: "pattern",
    requires: ["js.mapset"],
    atom: "atom.hash-map",
  },
  {
    id: "pattern.two-pointer",
    title: "Two pointers",
    stage: 5,
    kind: "pattern",
    requires: ["js.array.iteration"],
  },
  {
    id: "pattern.sliding-window",
    title: "Sliding window",
    stage: 5,
    kind: "pattern",
    requires: ["pattern.two-pointer", "js.mapset"],
  },
  {
    id: "meta.complexity",
    title: "Big-O analysis",
    stage: 5,
    kind: "mental-model",
    requires: [],
  },

  // ------------------------------------------- part 2, the method
  {
    id: "method.restate",
    title: "Restate and explore",
    stage: 5,
    kind: "pattern",
    requires: [],
  },
  {
    id: "method.brute-force",
    title: "Brute force first",
    stage: 5,
    kind: "pattern",
    requires: ["method.restate"],
  },
  {
    id: "method.bottleneck",
    title: "Find the repeated work",
    stage: 5,
    kind: "mental-model",
    requires: ["method.brute-force"],
  },
  {
    id: "method.constraints",
    title: "Constraints name the target",
    stage: 5,
    kind: "mental-model",
    requires: ["meta.complexity"],
  },
  {
    id: "method.recognition",
    title: "Signal to pattern",
    stage: 5,
    kind: "pattern",
    requires: ["method.bottleneck"],
  },
  {
    id: "method.optimization",
    title: "The optimisation ladder",
    stage: 5,
    kind: "pattern",
    requires: ["method.bottleneck"],
  },
  {
    id: "method.stuck",
    title: "Deriving an unseen problem",
    stage: 5,
    kind: "pattern",
    requires: ["method.recognition"],
  },
  {
    id: "method.verify",
    title: "Verify before running",
    stage: 5,
    kind: "pattern",
    requires: [],
  },
];

export const CONCEPT_BY_ID = new Map(CONCEPTS.map((c) => [c.id, c]));

export const STAGE_NAMES: Record<number, string> = {
  0: "Machine model",
  1: "Data manipulation",
  2: "Functions in depth",
  3: "Async",
  4: "Objects & structure",
  5: "Patterns & algorithms",
  6: "Real engineering",
};
