export type ReelDifficulty = 1 | 2 | 3 | 4 | 5;
export type ReelFormat =
  | "flash"
  | "challenge"
  | "versus"
  | "interview"
  | "underhood"
  | "story"
  | "build"
  | "cheatsheet";
export type ReelPalette =
  | "lime"
  | "violet"
  | "sunset"
  | "cyan"
  | "candy"
  | "ember"
  | "ice"
  | "gold";

export interface ReelBeat {
  narration: string;
  /** Shorter, punchier on-screen wording. Narration is used when omitted. */
  caption?: string;
  kicker?: string;
  code?: string;
  focusLines?: number[];
  output?: string;
  stat?: string;
  labels?: string[];
  visual?: "venn" | "buckets" | "references" | "window" | "queue" | "stack" | "heap" | "pipeline" | "memory";
  tone?: "hook" | "reveal" | "warning" | "win";
}

export interface PythonReel {
  id: string;
  title: string;
  series: string;
  category: "python" | "interview" | "algorithms" | "under-the-hood" | "build";
  difficulty: ReelDifficulty;
  format: ReelFormat;
  palette: ReelPalette;
  voice: "af_heart" | "af_bella" | "af_nicole" | "bf_emma" | "am_michael";
  pace: number;
  tags: string[];
  lessonId?: string;
  beats: ReelBeat[];
}

export const PYTHON_REELS: PythonReel[] = [
  {
    id: "sets-secret-power",
    title: "The set trick hiding in plain sight",
    series: "Python in 30 seconds",
    category: "python",
    difficulty: 1,
    format: "flash",
    palette: "lime",
    voice: "af_heart",
    pace: 1.06,
    tags: ["sets", "membership", "duplicates"],
    lessonId: "py.lesson.sets",
    beats: [
      { narration: "This tiny Python change can turn a slow search into an instant one.", caption: "This tiny change makes search feel instant", kicker: "WAIT FOR IT", tone: "hook", stat: "LOOKUP" },
      { narration: "A list checks membership by walking item after item.", caption: "A list scans... one item at a time", code: "if user_id in user_ids:\n    allow_access()", focusLines: [1], visual: "pipeline" },
      { narration: "Turn those IDs into a set once.", caption: "Convert once", code: "user_ids = set(user_ids)\n\nif user_id in user_ids:\n    allow_access()", focusLines: [1], tone: "reveal" },
      { narration: "Now Python jumps to the right hash bucket instead of scanning the whole collection.", caption: "Hash → bucket → answer", code: "if user_id in user_ids:\n    allow_access()", focusLines: [1], visual: "buckets", tone: "win" },
      { narration: "Use a set when you care whether something exists, but not where it sits.", caption: "Exists? SET. Position? LIST.", kicker: "SAVE THIS RULE", tone: "win" },
    ],
  },
  {
    id: "mutable-default-trap",
    title: "The Python function that remembers too much",
    series: "Python traps",
    category: "python",
    difficulty: 2,
    format: "challenge",
    palette: "sunset",
    voice: "bf_emma",
    pace: 1.02,
    tags: ["functions", "mutability", "interview"],
    lessonId: "py.lesson.functions",
    beats: [
      { narration: "Quick. What does the second call print?", caption: "What does call #2 print?", code: "def add(item, box=[]):\n    box.append(item)\n    return box\n\nprint(add(1))\nprint(add(2))", focusLines: [5, 6], tone: "hook" },
      { narration: "Most people guess it prints a list containing only two.", caption: "Most people guess  [2]", stat: "[2]?", tone: "warning" },
      { narration: "But the default list is created once, when Python defines the function.", caption: "The list is created ONCE", code: "def add(item, box=[]):", focusLines: [1], visual: "memory", tone: "reveal" },
      { narration: "So call two reuses the same list and prints a list containing one and two.", caption: "Same object. Second mutation.", code: "print(add(1))  # [1]\nprint(add(2))  # [1, 2]", focusLines: [2], output: "[1]\n[1, 2]", tone: "warning" },
      { narration: "Use None, then create a fresh list inside.", caption: "The safe pattern", code: "def add(item, box=None):\n    if box is None:\n        box = []\n    box.append(item)\n    return box", focusLines: [1, 2, 3], tone: "win" },
    ],
  },
  {
    id: "dict-under-hood",
    title: "How a dictionary finds anything so fast",
    series: "Under the hood",
    category: "under-the-hood",
    difficulty: 2,
    format: "underhood",
    palette: "violet",
    voice: "am_michael",
    pace: 1.04,
    tags: ["dicts", "hashing", "complexity"],
    lessonId: "py.lesson.dicts",
    beats: [
      { narration: "A Python dictionary does not search every key. So how does it find yours?", caption: "Dicts don't search every key...", visual: "buckets", tone: "hook" },
      { narration: "First, Python hashes the key into a number.", caption: "1. Hash the key", code: "hash(\"email\")", focusLines: [1], output: "an integer (varies by process)", visual: "pipeline" },
      { narration: "That number points toward a slot in an internal table.", caption: "2. Jump toward one slot", code: "profile[\"email\"]", focusLines: [1], visual: "buckets" },
      { narration: "If two keys collide, Python probes nearby slots and still verifies equality.", caption: "Collision? Probe + verify", labels: ["hash", "probe", "=="], visual: "buckets", tone: "warning" },
      { narration: "That is why lookup is average O of one, and why dictionary keys must be hashable.", caption: "Average lookup: O(1)", stat: "O(1)", tone: "win" },
    ],
  },
  {
    id: "two-sum-race",
    title: "Two Sum: brute force versus the interview answer",
    series: "Beat the brute force",
    category: "algorithms",
    difficulty: 2,
    format: "versus",
    palette: "cyan",
    voice: "af_bella",
    pace: 1.07,
    tags: ["two-sum", "hash-map", "leetcode"],
    beats: [
      { narration: "Two Sum looks easy. The interview is really asking whether you can remove this nested loop.", caption: "Can you delete the nested loop?", code: "for i in range(len(nums)):\n    for j in range(i + 1, len(nums)):\n        if nums[i] + nums[j] == target:\n            return [i, j]", focusLines: [1, 2], tone: "hook" },
      { narration: "Brute force tries every pair. That is O of n squared.", caption: "Every pair = O(n²)", stat: "O(n²)", tone: "warning" },
      { narration: "Instead, ask what number would complete the pair.", caption: "needed = target - number", code: "needed = target - number", focusLines: [1], tone: "reveal" },
      { narration: "Store each number you have seen. If needed is already there, you are done.", caption: "Remember → check → return", code: "seen = {}\nfor i, number in enumerate(nums):\n    needed = target - number\n    if needed in seen:\n        return [seen[needed], i]\n    seen[number] = i", focusLines: [2, 3, 4, 5], visual: "buckets" },
      { narration: "One pass. O of n time. This complement idea powers dozens of interview problems.", caption: "One pass. O(n).", stat: "O(n)", tone: "win" },
    ],
  },
  {
    id: "list-alias-copy",
    title: "Why changing B also changed A",
    series: "Python mental models",
    category: "python",
    difficulty: 1,
    format: "story",
    palette: "candy",
    voice: "af_nicole",
    pace: 1.01,
    tags: ["lists", "references", "copying"],
    lessonId: "py.lesson.lists",
    beats: [
      { narration: "You change list B... and list A changes too. Python is not broken.", caption: "You changed B. Why did A move?", code: "a = [1, 2]\nb = a\nb.append(3)\nprint(a)", focusLines: [2, 3], tone: "hook" },
      { narration: "A and B are two names pointing at one list object.", caption: "Two names → one object", code: "a = [1, 2]\nb = a", focusLines: [1, 2], visual: "references" },
      { narration: "Append mutates that shared object, so both names see the three.", caption: "Mutation hits the shared list", code: "b.append(3)\nprint(a)  # [1, 2, 3]", focusLines: [1, 2], output: "[1, 2, 3]", tone: "warning" },
      { narration: "If you need a separate outer list, copy it with dot copy or a full slice.", caption: "Need independence? Copy.", code: "b = a.copy()\n# or: b = a[:]", focusLines: [1, 2], tone: "win" },
    ],
  },
  {
    id: "enumerate-clean",
    title: "Stop writing range len",
    series: "Write cleaner Python",
    category: "python",
    difficulty: 1,
    format: "versus",
    palette: "gold",
    voice: "af_heart",
    pace: 1.08,
    tags: ["loops", "enumerate", "clean-code"],
    lessonId: "py.lesson.loops",
    beats: [
      { narration: "If your Python loop looks like this, there is usually a cleaner version.", caption: "Please stop writing this", code: "for i in range(len(names)):\n    print(i, names[i])", focusLines: [1, 2], tone: "hook" },
      { narration: "Range len makes you fetch the item manually.", caption: "You have an index... then re-index", code: "i = 0\nnames[i]", focusLines: [1, 2], tone: "warning" },
      { narration: "Enumerate gives you the index and value together.", caption: "enumerate gives BOTH", code: "for i, name in enumerate(names):\n    print(i, name)", focusLines: [1, 2], tone: "reveal" },
      { narration: "You can even start counting at one.", caption: "Start at 1 when humans are reading", code: "for rank, name in enumerate(names, start=1):\n    print(rank, name)", focusLines: [1], output: "1 Ada\n2 Linus\n3 Grace", tone: "win" },
    ],
  },
  {
    id: "counter-frequency",
    title: "Python already wrote your frequency map",
    series: "Standard library superpowers",
    category: "python",
    difficulty: 1,
    format: "flash",
    palette: "ember",
    voice: "bf_emma",
    pace: 1.05,
    tags: ["counter", "collections", "frequency"],
    beats: [
      { narration: "You do not need six lines to count things in Python.", caption: "Don't hand-write this every time", code: "counts = {}\nfor item in items:\n    counts[item] = counts.get(item, 0) + 1", focusLines: [1, 2, 3], tone: "hook" },
      { narration: "Counter turns any iterable into a frequency map.", caption: "Counter does it in one line", code: "from collections import Counter\n\ncounts = Counter(items)", focusLines: [1, 3], tone: "reveal" },
      { narration: "And most common gives you the winners immediately.", caption: "Top K is built in", code: "counts.most_common(2)", focusLines: [1], output: "[('python', 7), ('sql', 4)]", tone: "win" },
      { narration: "It is still a dictionary underneath, so normal key lookup works.", caption: "Counter behaves like a dict", code: "counts[\"python\"]  # 7\ncounts[\"missing\"] # 0", focusLines: [1, 2], tone: "win" },
    ],
  },
  {
    id: "generator-million",
    title: "One million numbers without one million objects",
    series: "Memory magic",
    category: "under-the-hood",
    difficulty: 2,
    format: "underhood",
    palette: "ice",
    voice: "am_michael",
    pace: 1.02,
    tags: ["generators", "memory", "yield"],
    lessonId: "py.lesson.iterators",
    beats: [
      { narration: "This list builds one million values before your loop can use even one.", caption: "1,000,000 values. Up front.", code: "squares = [n * n for n in range(1_000_000)]", focusLines: [1], stat: "1M", tone: "hook" },
      { narration: "Swap the brackets for parentheses and you get a generator.", caption: "[ ] → ( )", code: "squares = (n * n for n in range(1_000_000))", focusLines: [1], tone: "reveal" },
      { narration: "It produces one square only when you ask for the next one.", caption: "Lazy: one value at a time", code: "next(squares)  # 0\nnext(squares)  # 1\nnext(squares)  # 4", focusLines: [1, 2, 3], visual: "pipeline" },
      { narration: "Same sequence. Tiny memory footprint. Perfect for streaming data.", caption: "Same idea. Nearly constant memory.", stat: "O(1) memory", tone: "win" },
    ],
  },
  {
    id: "interview-big-o",
    title: "What to say when they ask for complexity",
    series: "Interview answers",
    category: "interview",
    difficulty: 2,
    format: "interview",
    palette: "violet",
    voice: "af_bella",
    pace: 1,
    tags: ["big-o", "communication", "interview"],
    beats: [
      { narration: "Interviewer: what is the time and space complexity? Do not answer with two symbols and stop.", caption: "“What's the complexity?”", kicker: "INTERVIEWER", tone: "hook" },
      { narration: "First, name what drives the work.", caption: "1. Define n", code: "# Let n be the number of input values", focusLines: [1] },
      { narration: "Then connect each loop or data structure to that input.", caption: "2. Point to the work", code: "for value in values:   # n visits\n    seen.add(value)     # O(1) average", focusLines: [1, 2] },
      { narration: "Say average versus worst case when it matters.", caption: "3. State the assumption", labels: ["average", "worst case", "amortized"], tone: "reveal" },
      { narration: "A strong answer sounds like: O of n time because I scan once, and O of n extra space for the set.", caption: "O(n) time — one scan\nO(n) space — the set", stat: "CLEAR > FAST", tone: "win" },
    ],
  },
  {
    id: "chain-comparisons",
    title: "Python reads math like math",
    series: "Python quirks that are actually great",
    category: "python",
    difficulty: 1,
    format: "flash",
    palette: "cyan",
    voice: "af_nicole",
    pace: 1.06,
    tags: ["comparisons", "syntax", "clean-code"],
    beats: [
      { narration: "Python lets you write a range check exactly like you wrote it in math class.", caption: "Python reads math like math", code: "0 <= score <= 100", focusLines: [1], tone: "hook" },
      { narration: "It means score is at least zero and score is at most one hundred.", caption: "Both comparisons must be true", code: "0 <= score and score <= 100", focusLines: [1] },
      { narration: "But Python evaluates the middle expression only once.", caption: "The middle runs ONCE", code: "low < expensive_call() < high", focusLines: [1], tone: "reveal" },
      { narration: "That makes chained comparisons cleaner and sometimes safer than repeating the expression.", caption: "Cleaner. No duplicate call.", code: "if 18 <= age < 65:\n    print(\"working age\")", focusLines: [1], tone: "win" },
    ],
  },
  {
    id: "sort-key-not-comparator",
    title: "The sorting question Python wants you to ask",
    series: "Pythonic thinking",
    category: "python",
    difficulty: 2,
    format: "cheatsheet",
    palette: "lime",
    voice: "af_heart",
    pace: 1.04,
    tags: ["sorting", "key-functions", "lambda"],
    lessonId: "py.lesson.sorting",
    beats: [
      { narration: "In Python, stop asking how two items compare. Ask what sortable value each item should expose.", caption: "Don't compare pairs. Extract a key.", tone: "hook" },
      { narration: "Sort words by length with key equals len.", caption: "By length", code: "sorted(words, key=len)", focusLines: [1], output: "['fig', 'pear', 'banana']" },
      { narration: "Sort records by descending score, then ascending name, with a tuple key.", caption: "Multiple rules? Return a tuple.", code: "sorted(users, key=lambda u: (-u.score, u.name))", focusLines: [1], tone: "reveal" },
      { narration: "The key runs once per item. Python then sorts those decorated values efficiently.", caption: "Key: once per item\nSort: O(n log n)", stat: "DSU", tone: "win" },
    ],
  },
  {
    id: "sliding-window",
    title: "The pattern that deletes an entire loop",
    series: "LeetCode patterns",
    category: "algorithms",
    difficulty: 3,
    format: "underhood",
    palette: "sunset",
    voice: "am_michael",
    pace: 1.05,
    tags: ["sliding-window", "subarrays", "leetcode"],
    beats: [
      { narration: "If you recompute every subarray from scratch, you are paying for the same work again and again.", caption: "You're recomputing almost everything", visual: "window", tone: "hook" },
      { narration: "A sliding window keeps the useful state from the previous range.", caption: "Keep the overlap", code: "window_sum = sum(nums[:k])", focusLines: [1], visual: "window" },
      { narration: "When the window moves, add the new right value and subtract the old left value.", caption: "+ incoming   − outgoing", code: "window_sum += nums[right]\nwindow_sum -= nums[right - k]", focusLines: [1, 2], visual: "window", tone: "reveal" },
      { narration: "Each element enters once and leaves once. The nested-loop idea becomes O of n.", caption: "Enter once. Leave once.", stat: "O(n)", tone: "win" },
    ],
  },
  {
    id: "deque-bfs",
    title: "One innocent method can ruin your BFS",
    series: "Algorithm landmines",
    category: "algorithms",
    difficulty: 3,
    format: "versus",
    palette: "ember",
    voice: "bf_emma",
    pace: 1.03,
    tags: ["bfs", "deque", "graphs"],
    beats: [
      { narration: "Your breadth-first search is correct, but this one line can make it painfully slow.", caption: "Correct BFS. Wrong queue.", code: "node = queue.pop(0)", focusLines: [1], tone: "hook" },
      { narration: "Pop zero from a list shifts every remaining item left. That is O of n per removal.", caption: "pop(0) shifts the whole list", stat: "O(n) each", tone: "warning" },
      { narration: "Use deque and popleft. It removes from the front in O of one.", caption: "deque.popleft()", code: "from collections import deque\n\nqueue = deque([start])\nnode = queue.popleft()", focusLines: [1, 3, 4], visual: "queue", tone: "reveal" },
      { narration: "The algorithm did not change. The data structure made the complexity honest.", caption: "Same BFS. Right structure.", stat: "O(V + E)", tone: "win" },
    ],
  },
  {
    id: "fstring-debug",
    title: "The fastest tiny debugging trick in Python",
    series: "Tiny tools, huge payoff",
    category: "python",
    difficulty: 1,
    format: "flash",
    palette: "candy",
    voice: "af_bella",
    pace: 1.08,
    tags: ["f-strings", "debugging", "productivity"],
    beats: [
      { narration: "Add one equals sign inside an f-string and Python labels your debug value for you.", caption: "One character. Better debugging.", code: "print(f\"{total=}\")", focusLines: [1], tone: "hook" },
      { narration: "Instead of printing a mystery number...", caption: "What is 42?", code: "print(total)", focusLines: [1], output: "42", tone: "warning" },
      { narration: "You get the expression and its value together.", caption: "The label comes free", code: "print(f\"{total=}\")", focusLines: [1], output: "total=42", tone: "reveal" },
      { narration: "It works with full expressions and format specs too.", caption: "Expressions + formatting", code: "print(f\"{price * tax = :.2f}\")", focusLines: [1], output: "price * tax = 7.25", tone: "win" },
    ],
  },
  {
    id: "nan-weird",
    title: "The value that is not equal to itself",
    series: "Python weirdness",
    category: "python",
    difficulty: 2,
    format: "challenge",
    palette: "ice",
    voice: "af_nicole",
    pace: 1,
    tags: ["float", "nan", "data"],
    beats: [
      { narration: "There is a floating-point value in Python that is not even equal to itself.", caption: "A value where x != x", stat: "???", tone: "hook" },
      { narration: "Meet NaN: not a number.", caption: "NaN = Not a Number", code: "x = float(\"nan\")", focusLines: [1], tone: "reveal" },
      { narration: "Every comparison with NaN is unordered, including equality with NaN.", caption: "NaN poisons comparisons", code: "x == x   # False\nx < 10   # False\nx > 10   # False", focusLines: [1, 2, 3], output: "False\nFalse\nFalse", tone: "warning" },
      { narration: "Never detect it with equals. Use math dot isnan.", caption: "The correct check", code: "from math import isnan\n\nisnan(x)  # True", focusLines: [1, 3], tone: "win" },
    ],
  },
  {
    id: "is-versus-equals",
    title: "The Python comparison interviewers love",
    series: "Say this in interviews",
    category: "interview",
    difficulty: 2,
    format: "interview",
    palette: "gold",
    voice: "am_michael",
    pace: 1.02,
    tags: ["identity", "equality", "interview"],
    beats: [
      { narration: "What is the difference between double equals and is? Here is the answer they want.", caption: "== versus is", kicker: "INTERVIEW CLASSIC", tone: "hook" },
      { narration: "Double equals asks whether two objects have equal values.", caption: "== compares VALUE", code: "[1, 2] == [1, 2]  # True", focusLines: [1], output: "True" },
      { narration: "Is asks whether both names point to the exact same object.", caption: "is compares IDENTITY", code: "[1, 2] is [1, 2]  # False", focusLines: [1], visual: "references", output: "False", tone: "reveal" },
      { narration: "Use is with None. Use double equals for normal value comparison.", caption: "x is None\nx == expected_value", code: "if result is None:\n    handle_missing()", focusLines: [1], tone: "win" },
    ],
  },
  {
    id: "any-short-circuit",
    title: "How Python stops a search early",
    series: "Built-ins worth knowing",
    category: "python",
    difficulty: 2,
    format: "underhood",
    palette: "lime",
    voice: "af_heart",
    pace: 1.06,
    tags: ["any", "generators", "short-circuit"],
    beats: [
      { narration: "This line can stop after checking only one item, even if the collection has a million.", caption: "A million items. Maybe one check.", code: "any(user.is_admin for user in users)", focusLines: [1], tone: "hook" },
      { narration: "Any pulls values lazily from the generator.", caption: "Ask for one result at a time", visual: "pipeline" },
      { narration: "The moment it sees True, it returns and never evaluates the rest.", caption: "First True → STOP", code: "False, False, True, ...", focusLines: [1], tone: "reveal" },
      { narration: "Pair any or all with a generator expression when you only need the answer, not the whole list.", caption: "Don't build a list you won't keep", code: "any(check(x) for x in items)", focusLines: [1], stat: "lazy", tone: "win" },
    ],
  },
  {
    id: "top-k-heap",
    title: "Stop sorting everything for the top three",
    series: "Beat the brute force",
    category: "algorithms",
    difficulty: 3,
    format: "versus",
    palette: "violet",
    voice: "bf_emma",
    pace: 1.04,
    tags: ["heap", "top-k", "complexity"],
    beats: [
      { narration: "Need the top three values? Sorting every value does more work than the question asked for.", caption: "Top 3 ≠ sort everything", code: "sorted(values, reverse=True)[:3]", focusLines: [1], tone: "hook" },
      { narration: "A full sort costs O of n log n.", caption: "Full sort", stat: "O(n log n)", tone: "warning" },
      { narration: "A heap keeps only the best k candidates.", caption: "Keep a tiny candidate heap", code: "from heapq import nlargest\n\ntop_three = nlargest(3, values)", focusLines: [1, 3], visual: "heap", tone: "reveal" },
      { narration: "That costs O of n log k, which matters when n is huge and k is tiny.", caption: "Huge n. Tiny k.", stat: "O(n log k)", tone: "win" },
    ],
  },
  {
    id: "cache-one-line",
    title: "Make recursion remember its answers",
    series: "One-line upgrades",
    category: "algorithms",
    difficulty: 3,
    format: "flash",
    palette: "cyan",
    voice: "af_bella",
    pace: 1.03,
    tags: ["caching", "dynamic-programming", "recursion"],
    beats: [
      { narration: "This Fibonacci function recalculates the same answers thousands of times.", caption: "The recursion tree repeats itself", code: "def fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)", focusLines: [4], tone: "hook" },
      { narration: "Fib of three appears here, then appears again in another branch.", caption: "Same input. Same work. Again.", labels: ["fib(5)", "fib(4)", "fib(3)", "fib(3)"], visual: "references", tone: "warning" },
      { narration: "Add cache and Python remembers every completed input.", caption: "One decorator adds memory", code: "from functools import cache\n\n@cache\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)", focusLines: [1, 3], tone: "reveal" },
      { narration: "Exponential repetition collapses into one computation per n.", caption: "From explosive to linear", stat: "O(n)", tone: "win" },
    ],
  },
  {
    id: "valid-parentheses",
    title: "The stack problem everyone should recognize",
    series: "LeetCode pattern speedrun",
    category: "algorithms",
    difficulty: 2,
    format: "challenge",
    palette: "sunset",
    voice: "am_michael",
    pace: 1.06,
    tags: ["stack", "valid-parentheses", "leetcode"],
    beats: [
      { narration: "You see brackets that must close in reverse order. What data structure should flash in your head?", caption: "Last opened = first closed", code: "({[]})", focusLines: [1], tone: "hook" },
      { narration: "A stack. Push every opening bracket.", caption: "Opening bracket? PUSH", code: "if char in \"([{\":\n    stack.append(char)", focusLines: [1, 2], visual: "stack" },
      { narration: "For a closing bracket, the stack top must be its matching opener.", caption: "Closing bracket? Match the TOP", code: "pairs = {')': '(', ']': '[', '}': '{'}\nif not stack or stack.pop() != pairs[char]:\n    return False", focusLines: [1, 2, 3], visual: "stack", tone: "reveal" },
      { narration: "At the end, the stack must be empty. One pass, O of n time.", caption: "Valid only if nothing is left", code: "return not stack", focusLines: [1], stat: "O(n)", tone: "win" },
    ],
  },
  {
    id: "tuple-swap",
    title: "How Python swaps without a temporary variable",
    series: "What Python is really doing",
    category: "under-the-hood",
    difficulty: 2,
    format: "underhood",
    palette: "candy",
    voice: "af_nicole",
    pace: 1.02,
    tags: ["tuples", "unpacking", "bytecode"],
    beats: [
      { narration: "Python can swap two values in one line, with no temporary variable in your code.", caption: "The cleanest swap", code: "left, right = right, left", focusLines: [1], tone: "hook" },
      { narration: "Python evaluates the entire right side first.", caption: "1. Read the right side", code: "right, left", focusLines: [1], labels: ["right", "left"] },
      { narration: "Then it unpacks those two results into the names on the left.", caption: "2. Unpack into the left side", code: "left, right = ...", focusLines: [1], visual: "references", tone: "reveal" },
      { narration: "The same parallel assignment works for rotating three values or unpacking function results.", caption: "Swap. Rotate. Unpack.", code: "a, b, c = c, a, b", focusLines: [1], tone: "win" },
    ],
  },
  {
    id: "context-manager",
    title: "Why with open is more than shorter syntax",
    series: "Python safety",
    category: "python",
    difficulty: 2,
    format: "story",
    palette: "ice",
    voice: "bf_emma",
    pace: 1.01,
    tags: ["files", "context-manager", "exceptions"],
    lessonId: "py.lesson.contexts",
    beats: [
      { narration: "Your code crashes halfway through reading a file. Who closes the file handle?", caption: "An exception happened. Is the file still open?", tone: "hook" },
      { narration: "Manual open and close fails if control jumps away before close.", caption: "close() might never run", code: "file = open(path)\ndata = parse(file.read())  # raises\nfile.close()", focusLines: [2, 3], tone: "warning" },
      { narration: "A with block promises cleanup when you leave the block, even through an exception.", caption: "with guarantees the exit", code: "with open(path) as file:\n    data = parse(file.read())", focusLines: [1, 2], tone: "reveal" },
      { narration: "Context managers are for any resource with setup and cleanup: files, locks, transactions, even timers.", caption: "Acquire → use → always release", labels: ["file", "lock", "transaction", "timer"], tone: "win" },
    ],
  },
  {
    id: "gil-truth",
    title: "The GIL explanation people usually get wrong",
    series: "Python under pressure",
    category: "under-the-hood",
    difficulty: 4,
    format: "interview",
    palette: "ember",
    voice: "am_michael",
    pace: 1,
    tags: ["gil", "threads", "parallelism"],
    beats: [
      { narration: "Does the GIL mean Python threads are useless? No. That answer loses the nuance interviewers want.", caption: "“Python threads are useless.”\nWrong.", kicker: "HOT TAKE", tone: "hook" },
      { narration: "In standard CPython, the GIL lets only one thread execute Python bytecode at a time.", caption: "One thread executes Python bytecode", stat: "1 at a time", tone: "reveal" },
      { narration: "That limits CPU-bound Python work, where every thread wants the interpreter continuously.", caption: "CPU-bound → threads don't scale cores", labels: ["thread A", "GIL", "thread B"], tone: "warning" },
      { narration: "But I O releases the GIL while a thread waits, so threads can overlap network and file latency very well.", caption: "I/O wait → another thread runs", labels: ["request", "wait", "run"], visual: "pipeline" },
      { narration: "Say threads for I O, processes or native code for CPU parallelism, and asyncio for many cooperative I O tasks.", caption: "I/O: threads or asyncio\nCPU: processes or native code", tone: "win" },
    ],
  },
  {
    id: "binary-search-invariant",
    title: "Binary search is not about finding the middle",
    series: "Interview invariants",
    category: "algorithms",
    difficulty: 3,
    format: "underhood",
    palette: "gold",
    voice: "af_heart",
    pace: 1.03,
    tags: ["binary-search", "invariant", "interview"],
    beats: [
      { narration: "Binary search is not really about checking the middle. It is about proving which half cannot contain the answer.", caption: "The middle isn't the point", visual: "window", tone: "hook" },
      { narration: "Keep one invariant: if the target exists, it is inside left through right.", caption: "Invariant: answer ∈ [left, right]", code: "left, right = 0, len(nums) - 1", focusLines: [1] },
      { narration: "If middle is too small, middle and everything left of it are impossible.", caption: "mid too small → discard left half", code: "if nums[mid] < target:\n    left = mid + 1", focusLines: [1, 2], tone: "reveal" },
      { narration: "Every update must preserve the invariant and remove at least one candidate.", caption: "Preserve truth. Shrink the range.", code: "while left <= right:\n    mid = left + (right - left) // 2", focusLines: [1, 2] },
      { narration: "That reasoning, not memorized syntax, prevents infinite loops and off-by-one bugs.", caption: "Reason first. Template second.", stat: "O(log n)", tone: "win" },
    ],
  },
  {
    id: "zip-strict",
    title: "The silent data-loss bug hiding in zip",
    series: "Production Python",
    category: "python",
    difficulty: 2,
    format: "challenge",
    palette: "violet",
    voice: "af_bella",
    pace: 1.03,
    tags: ["zip", "validation", "data"],
    beats: [
      { narration: "These two lists have different lengths. Does zip warn you?", caption: "One value is missing. Does zip care?", code: "names = [\"Ada\", \"Linus\", \"Grace\"]\nscores = [98, 91]\n\nlist(zip(names, scores))", focusLines: [1, 2, 4], tone: "hook" },
      { narration: "No. Normal zip silently stops at the shorter iterable.", caption: "Grace silently disappears", output: "[('Ada', 98), ('Linus', 91)]", tone: "warning" },
      { narration: "In modern Python, strict equals True turns that mismatch into an error.", caption: "Make the contract explicit", code: "zip(names, scores, strict=True)", focusLines: [1], output: "ValueError: arguments have different lengths", tone: "reveal" },
      { narration: "Use strict zip when unequal lengths mean corrupted or incomplete data.", caption: "If mismatch is a bug, fail loudly.", tone: "win" },
    ],
  },
  {
    id: "build-retry",
    title: "Build a retry loop that does not melt the server",
    series: "Build it right",
    category: "build",
    difficulty: 4,
    format: "build",
    palette: "cyan",
    voice: "bf_emma",
    pace: 1.01,
    tags: ["retries", "backoff", "systems"],
    beats: [
      { narration: "A request fails, so you retry instantly. Ten thousand clients do the same. You just created a retry storm.", caption: "Instant retry × 10,000 clients", stat: "THUNDERING HERD", tone: "hook" },
      { narration: "First, cap the number of attempts.", caption: "1. Bound the retries", code: "for attempt in range(max_attempts):\n    try:\n        return request()\n    except TemporaryError:\n        pass", focusLines: [1], tone: "reveal" },
      { narration: "Then use exponential backoff so every failure waits longer.", caption: "2. Back off exponentially", code: "delay = base * 2 ** attempt\ntime.sleep(delay)", focusLines: [1, 2], stat: "1s → 2s → 4s" },
      { narration: "Add random jitter so clients do not wake up together again.", caption: "3. Break synchronization with jitter", code: "delay *= random.uniform(0.5, 1.5)", focusLines: [1], visual: "pipeline" },
      { narration: "And only retry errors that can actually recover. Never retry bad input.", caption: "Retry transient failure—not permanent failure", labels: ["timeout ✓", "503 ✓", "400 ✕", "auth ✕"], tone: "win" },
    ],
  },
  {
    id: "dataclass-slots",
    title: "A tiny class upgrade for millions of objects",
    series: "Performance without ugliness",
    category: "python",
    difficulty: 3,
    format: "versus",
    palette: "lime",
    voice: "af_nicole",
    pace: 1.01,
    tags: ["dataclasses", "slots", "memory"],
    beats: [
      { narration: "If you create millions of small Python objects, each instance dictionary can become real memory overhead.", caption: "Millions of objects. Millions of __dict__ tables.", visual: "memory", tone: "hook" },
      { narration: "A normal data class is wonderfully readable, but instances usually carry a dynamic attribute dictionary.", caption: "Flexible, but not free", code: "@dataclass\nclass Point:\n    x: float\n    y: float", focusLines: [1, 2] },
      { narration: "Slots equals True stores declared fields in fixed slots instead.", caption: "One option changes the layout", code: "@dataclass(slots=True)\nclass Point:\n    x: float\n    y: float", focusLines: [1], tone: "reveal" },
      { narration: "You often save memory and block accidental new attributes. Measure first; use it when instance count is large.", caption: "Less memory. Fewer accidental fields.", stat: "measure first", tone: "win" },
    ],
  },
  {
    id: "bool-is-int",
    title: "Why True plus True equals two",
    series: "Python weirdness",
    category: "under-the-hood",
    difficulty: 2,
    format: "challenge",
    palette: "candy",
    voice: "af_heart",
    pace: 1.06,
    tags: ["booleans", "types", "history"],
    beats: [
      { narration: "Python says True plus True equals two. That is not a typo.", caption: "True + True = 2", code: "True + True", focusLines: [1], output: "2", tone: "hook" },
      { narration: "Bool is a subclass of int. True behaves like one and False behaves like zero.", caption: "bool inherits from int", code: "isinstance(True, int)  # True\nint(True)              # 1\nint(False)             # 0", focusLines: [1, 2, 3], tone: "reveal" },
      { narration: "That lets sum count truthy conditions elegantly.", caption: "Count matches with sum", code: "passed = sum(score >= 70 for score in scores)", focusLines: [1], tone: "win" },
      { narration: "Useful, but do not hide business logic inside clever arithmetic when a clear condition reads better.", caption: "Know the trick. Prefer clarity.", kicker: "PYTHONIC ≠ CLEVER", tone: "win" },
    ],
  },
  {
    id: "union-find",
    title: "The hard graph problem that becomes two tiny operations",
    series: "Hard patterns made visual",
    category: "algorithms",
    difficulty: 5,
    format: "underhood",
    palette: "ember",
    voice: "am_michael",
    pace: 1,
    tags: ["union-find", "graphs", "hard"],
    beats: [
      { narration: "You keep adding connections and need to know whether two nodes are already connected. Re-running graph search every time is wasteful.", caption: "Dynamic connectivity without repeated DFS", tone: "hook" },
      { narration: "Union Find gives every connected group one representative root.", caption: "Each component has a root", labels: ["A → A", "B → A", "C → A", "D → D"], visual: "references" },
      { narration: "Find follows parent links to discover a node's root.", caption: "find(x) → root", code: "def find(x):\n    while x != parent[x]:\n        x = parent[x]\n    return x", focusLines: [1, 2, 3, 4] },
      { narration: "Union connects two roots, usually attaching the smaller tree under the larger one.", caption: "union(a, b) merges roots", code: "root_a = find(a)\nroot_b = find(b)\nparent[root_b] = root_a", focusLines: [1, 2, 3], tone: "reveal" },
      { narration: "Path compression flattens future searches. With union by size, each operation is effectively constant time.", caption: "Compress paths → nearly O(1)", stat: "α(n)", labels: ["before: x → p → root", "after: x → root"], visual: "references", tone: "win" },
    ],
  },
  {
    id: "readable-palindrome",
    title: "The one-liner that should not be a one-liner",
    series: "Code review court",
    category: "interview",
    difficulty: 2,
    format: "versus",
    palette: "gold",
    voice: "bf_emma",
    pace: 1.03,
    tags: ["strings", "clean-code", "interview"],
    beats: [
      { narration: "Yes, this palindrome solution fits on one line. No, that does not automatically make it good.", caption: "Short code ≠ clear code", code: "return (s := ''.join(c.lower() for c in text if c.isalnum())) == s[::-1]", focusLines: [1], tone: "hook" },
      { narration: "It normalizes text, assigns inside an expression, reverses it, and compares it—all at once.", caption: "Four ideas. One crowded line.", labels: ["filter", "lower", "assign", "reverse"] },
      { narration: "Give the transformed value a name, then state the actual test.", caption: "Make the reasoning visible", code: "clean = ''.join(\n    char.lower()\n    for char in text\n    if char.isalnum()\n)\nreturn clean == clean[::-1]", focusLines: [1, 6], tone: "reveal" },
      { narration: "In an interview, optimize for code your interviewer can verify while you speak.", caption: "Readable code is easier to prove correct.", kicker: "SIGNAL > GOLF", tone: "win" },
    ],
  },
  {
    id: "defaultdict-graph",
    title: "Build an adjacency list without the noise",
    series: "Standard library superpowers",
    category: "algorithms",
    difficulty: 2,
    format: "build",
    palette: "ice",
    voice: "af_bella",
    pace: 1.05,
    tags: ["defaultdict", "graphs", "adjacency-list"],
    beats: [
      { narration: "Building a graph should be about edges, not repeatedly checking whether a list exists.", caption: "This setup noise hides the graph", code: "graph = {}\nfor source, target in edges:\n    if source not in graph:\n        graph[source] = []\n    graph[source].append(target)", focusLines: [2, 3, 4, 5], tone: "hook" },
      { narration: "Default dict creates the missing list the first time a key is used.", caption: "Missing key? Make [] automatically.", code: "from collections import defaultdict\n\ngraph = defaultdict(list)", focusLines: [1, 3], tone: "reveal" },
      { narration: "Now the loop says exactly what the data means: add target to source's neighbors.", caption: "The final loop is the idea", code: "for source, target in edges:\n    graph[source].append(target)", focusLines: [1, 2], visual: "references" },
      { narration: "Use default dict when every missing key has one obvious empty starting value.", caption: "list, set, int—pick the natural default", labels: ["defaultdict(list)", "defaultdict(set)", "defaultdict(int)"], tone: "win" },
    ],
  },
  {
    id: "exception-boundary",
    title: "The exception handling rule that keeps bugs visible",
    series: "Production Python",
    category: "build",
    difficulty: 3,
    format: "story",
    palette: "violet",
    voice: "af_nicole",
    pace: 1.01,
    tags: ["exceptions", "debugging", "production"],
    beats: [
      { narration: "This except block can hide a typo, a broken database, and even your attempt to stop the program.", caption: "The bug-eating blanket", code: "try:\n    process_order(order)\nexcept:\n    pass", focusLines: [3, 4], tone: "hook" },
      { narration: "A bare except catches almost everything and throws away the evidence.", caption: "Failure disappears. State may be corrupted.", tone: "warning" },
      { narration: "Catch the narrow error you can actually recover from.", caption: "Catch what you can handle", code: "try:\n    charge(card)\nexcept CardDeclined as error:\n    show_decline(error)", focusLines: [3, 4], tone: "reveal" },
      { narration: "At a system boundary, log unexpected failures with context, then re-raise or convert them deliberately.", caption: "Recover narrowly. Report broadly. Never vanish.", code: "except Exception:\n    logger.exception(\"checkout failed\")\n    raise", focusLines: [1, 2, 3], tone: "win" },
    ],
  },
  {
    id: "monotonic-stack",
    title: "The O(n²) loop hiding a stack pattern",
    series: "Hard patterns made visual",
    category: "algorithms",
    difficulty: 4,
    format: "underhood",
    palette: "sunset",
    voice: "am_michael",
    pace: 1.02,
    tags: ["monotonic-stack", "next-greater", "leetcode"],
    beats: [
      { narration: "For every temperature, find the next warmer day. Scanning right from every index repeats work.", caption: "Next greater value for every position", code: "[73, 74, 75, 71, 69, 72, 76, 73]", focusLines: [1], tone: "hook" },
      { narration: "Keep indices whose answer has not appeared yet in a decreasing stack.", caption: "Stack = unresolved days", labels: ["75", "71", "69"], visual: "stack" },
      { narration: "When a warmer value arrives, it resolves every smaller value on top.", caption: "72 resolves 69, then 71", code: "while stack and temps[stack[-1]] < temp:\n    previous = stack.pop()\n    answer[previous] = day - previous", focusLines: [1, 2, 3], visual: "stack", tone: "reveal" },
      { narration: "Each index is pushed once and popped once. What looked quadratic becomes linear.", caption: "Push once. Pop once.", stat: "O(n)", tone: "win" },
    ],
  },
  {
    id: "match-shapes",
    title: "Python match can unpack data while checking it",
    series: "Modern Python",
    category: "python",
    difficulty: 3,
    format: "cheatsheet",
    palette: "cyan",
    voice: "af_heart",
    pace: 1.03,
    tags: ["match", "pattern-matching", "python-3.10"],
    beats: [
      { narration: "Python match is not just a prettier switch. It can test the shape of data and unpack it at the same time.", caption: "match checks STRUCTURE", tone: "hook" },
      { narration: "This pattern matches a two-item point and binds x and y.", caption: "Sequence pattern", code: "match value:\n    case [x, y]:\n        print(\"point\", x, y)", focusLines: [2, 3], tone: "reveal" },
      { narration: "This one matches a dictionary only when it has a type key equal to click, then captures coordinates.", caption: "Mapping pattern", code: "case {\"type\": \"click\", \"x\": x, \"y\": y}:\n    handle_click(x, y)", focusLines: [1, 2] },
      { narration: "Use a guard for an extra condition, and underscore as the final catch-all.", caption: "Pattern + guard + fallback", code: "case [x, y] if x == y:\n    print(\"diagonal\")\ncase _:\n    print(\"something else\")", focusLines: [1, 3], tone: "win" },
    ],
  },
  {
    id: "decorator-reframe",
    title: "Decorators without the magic",
    series: "Python mental models",
    category: "python",
    difficulty: 3,
    format: "story",
    palette: "candy",
    voice: "bf_emma",
    pace: 1,
    tags: ["decorators", "functions", "closures"],
    lessonId: "py.lesson.decorators",
    beats: [
      { narration: "A decorator is not magic syntax. It is one assignment wearing a convenient hat.", caption: "@decorator = one assignment", tone: "hook" },
      { narration: "This at sign...", caption: "The syntax", code: "@timer\ndef load_data():\n    ...", focusLines: [1, 2] },
      { narration: "Means: define the function, pass it into timer, then replace the name with what timer returns.", caption: "What Python does", code: "def load_data():\n    ...\n\nload_data = timer(load_data)", focusLines: [1, 4], visual: "pipeline", tone: "reveal" },
      { narration: "The returned wrapper can run code before and after calling the original function.", caption: "before → original → after", code: "def wrapper(*args, **kwargs):\n    start = perf_counter()\n    result = function(*args, **kwargs)\n    print(perf_counter() - start)\n    return result", focusLines: [1, 3, 4, 5] },
      { narration: "Once you see the reassignment, decorators become ordinary higher-order functions.", caption: "No magic. Functions transforming functions.", tone: "win" },
    ],
  },
  {
    id: "asyncio-gather",
    title: "Three one-second requests in one second",
    series: "Concurrency made visual",
    category: "under-the-hood",
    difficulty: 4,
    format: "underhood",
    palette: "ice",
    voice: "af_bella",
    pace: 1.02,
    tags: ["asyncio", "gather", "io"],
    beats: [
      { narration: "Three independent one-second requests do not have to take three seconds.", caption: "3 × one-second requests", stat: "3s?", tone: "hook" },
      { narration: "Awaiting them one by one starts the next request only after the previous one finishes.", caption: "Sequential awaits", code: "a = await fetch(url_a)\nb = await fetch(url_b)\nc = await fetch(url_c)", focusLines: [1, 2, 3], output: "≈ 3.0 seconds", tone: "warning" },
      { narration: "Gather schedules all three coroutines, then waits for every result.", caption: "Start together. Wait together.", code: "a, b, c = await asyncio.gather(\n    fetch(url_a),\n    fetch(url_b),\n    fetch(url_c),\n)", focusLines: [1, 2, 3, 4], visual: "pipeline", tone: "reveal" },
      { narration: "While one request waits on the network, the event loop advances another.", caption: "Waiting time overlaps", labels: ["A: wait", "B: wait", "C: wait"], output: "≈ 1.0 second" },
      { narration: "This is concurrency for I O, not free CPU parallelism. Also decide how failures should cancel or propagate.", caption: "Great for I/O. Handle failure deliberately.", tone: "win" },
    ],
  },
];

export const REEL_BY_ID = new Map(PYTHON_REELS.map((reel) => [reel.id, reel]));
