export type SystemDesignDifficulty = "Foundation" | "Intermediate" | "Advanced";

export interface SystemDesignQuestion {
  id: string;
  title: string;
  category: string;
  difficulty: SystemDesignDifficulty;
  minutes: number;
  prompt: string;
  requirements: string[];
  clarify: string[];
  hints: string[];
  solution: string;
}

const q = (
  id: string, title: string, category: string, difficulty: SystemDesignDifficulty, minutes: number,
  prompt: string, requirements: string[], clarify: string[], hints: string[], solution: string,
): SystemDesignQuestion => ({ id: `sd.${id}`, title, category, difficulty, minutes, prompt, requirements, clarify, hints, solution });

export const SYSTEM_DESIGN_QUESTIONS: SystemDesignQuestion[] = [
  q("url-shortener", "Design a URL Shortener", "Foundations", "Foundation", 35,
    "Design a service like Bitly that creates short links and redirects readers with low latency.",
    ["Create a short URL", "Redirect to the original URL", "Custom aliases and expiration", "Basic click analytics"],
    ["How many links and redirects per day?", "Can aliases be changed?", "How long must links live?"],
    ["Estimate read/write ratio before selecting storage.", "Separate the redirect path from analytics writes.", "Compare random keys, hashing, and an ID-to-base62 scheme."],
    "## Shape\nUse an API service to allocate a unique numeric ID, encode it in base62, and store `short_key → long_url` in a replicated key-value store. Cache hot redirects at the edge.\n\n## Write path\nValidate the URL, reserve an ID, persist the mapping, then return the short link. A uniqueness constraint protects custom aliases.\n\n## Read path\nResolve from edge cache, then Redis, then the durable store. Return a `302` when destinations may change or `301` for immutable links. Publish click events asynchronously to a stream so analytics never delays redirects.\n\n## Scale and failure\nPartition by a hash of the key, replicate across zones, rate-limit abusive creators, and use negative caching for missing keys. Monitor redirect latency, cache hit rate, and broken destination rate."),
  q("rate-limiter", "Design a Distributed Rate Limiter", "Foundations", "Foundation", 35,
    "Design a rate limiter shared by thousands of stateless API servers.",
    ["Per-user and per-IP policies", "Burst support", "Low latency decision", "Clear retry metadata"],
    ["Is slight over-admission acceptable?", "Are limits global or regional?", "Who defines and updates policies?"],
    ["Compare token bucket and sliding-window counter.", "Keep policy separate from counters.", "Think about atomic updates and clock skew."],
    "## Shape\nUse a token bucket for burst-friendly limits. API gateways load versioned policies locally and perform an atomic refill-and-consume operation in regional Redis with Lua.\n\n## Request path\nDerive a stable key from subject, route, and policy. The script calculates refill from elapsed time, consumes one token, and returns remaining tokens plus reset time. Fail open only for low-risk routes; fail closed for authentication and billing.\n\n## Scale and correctness\nShard counters by key, keep users sticky to a home region when strict global limits matter, and reconcile asynchronously for looser limits. Bound clock skew by using the datastore clock. Emit allow/deny metrics without logging sensitive identifiers."),
  q("notification", "Design a Notification Service", "Messaging", "Foundation", 40,
    "Design a platform that sends email, SMS, push, and in-app notifications reliably.",
    ["Multiple delivery channels", "User preferences", "Retries and deduplication", "Delivery status"],
    ["Transactional or marketing traffic?", "What delivery guarantees are required?", "What are provider quotas?"],
    ["Model notification intent separately from provider attempts.", "Use an outbox to avoid dual-write loss.", "Retries need idempotency and a dead-letter path."],
    "## Shape\nThe producer writes a notification intent and outbox record in one transaction. A dispatcher publishes to a stream. Preference and template services expand the intent into channel jobs, and channel workers call providers.\n\n## Reliability\nGive every intent and channel attempt an idempotency key. Retry transient errors with exponential backoff and jitter; move permanent failures to a dead-letter queue. Provider webhooks update delivery state.\n\n## Operations\nPartition streams by recipient to preserve ordering where needed. Enforce quiet hours, unsubscribe rules, provider quotas, and per-tenant budgets before enqueueing. Track queue age, send latency, bounce rate, and provider health."),
  q("pastebin", "Design Pastebin", "Foundations", "Foundation", 35,
    "Design a service for storing and sharing text snippets with optional expiration.",
    ["Create and retrieve pastes", "Expiration", "Unlisted and private access", "Large paste support"],
    ["Maximum paste size?", "Can content be edited?", "Is search required?"],
    ["Immutable content simplifies caching.", "Do not put large bodies in a metadata index.", "Consider signed access for private pastes."],
    "## Shape\nStore metadata in a relational or key-value database and immutable bodies in object storage. Generate random, unguessable IDs. Cache public paste bodies at the CDN.\n\n## Lifecycle\nThe write API streams content to object storage, then commits metadata. A lifecycle policy deletes expired objects; reads also enforce expiry so cleanup lag cannot expose content. Private pastes use owner authorization or scoped signed links.\n\n## Safety\nApply size limits, malware and secret scanning, abuse reports, and rate limits. Encrypt private bodies, avoid indexing unlisted content, and keep access logs free of paste contents."),
  q("chat", "Design Real-Time Chat", "Messaging", "Intermediate", 45,
    "Design one-to-one and group chat with presence, delivery state, and multi-device history.",
    ["Real-time messages", "Offline delivery", "Ordering within a conversation", "Read receipts and presence"],
    ["Maximum group size?", "Exactly which ordering guarantee?", "How long is history retained?"],
    ["Assign sequence numbers per conversation.", "Separate durable messages from ephemeral presence.", "A user may have several live connections."],
    "## Shape\nClients hold WebSocket connections to gateway servers. A conversation service assigns a monotonically increasing sequence number and persists each message before publishing it. Gateways fan out to every active device; offline devices catch up from their last acknowledged sequence.\n\n## Data\nPartition messages by conversation ID for ordered writes and efficient pagination. Store membership separately and cache it at gateways. Presence and typing indicators live in an expiring in-memory store because loss is acceptable.\n\n## Reliability\nClient-generated idempotency IDs prevent duplicate sends. Per-device acknowledgements drive delivered and read state. Backpressure slow consumers, cap group fanout, and use push notifications only after a short offline delay."),
  q("news-feed", "Design a Social News Feed", "Feeds", "Intermediate", 45,
    "Design a personalized home feed for a social network with millions of creators and readers.",
    ["Create posts", "Follow users", "Ranked home feed", "Pagination and freshness"],
    ["How many celebrity accounts?", "Chronological or ranked?", "What freshness target?"],
    ["Compare fanout-on-write and fanout-on-read.", "Celebrity fanout is a different workload.", "Cursor pagination must remain stable while new posts arrive."],
    "## Shape\nUse hybrid fanout. Ordinary creators push post IDs into follower inboxes through a stream. High-fanout creators are merged at read time. A feed service gathers candidates, filters visibility, ranks them, and hydrates post data in batches.\n\n## Storage\nKeep posts in a durable store, follow edges in a graph-friendly adjacency store, and inboxes as bounded ordered lists. Use opaque cursors containing rank/time boundaries rather than offsets.\n\n## Quality\nDeduplicate candidates, apply blocks and privacy before ranking, and retain a chronological fallback. Measure feed-generation latency, candidate age, cache hit rate, and ranking diversity."),
  q("search-autocomplete", "Design Search Autocomplete", "Search", "Intermediate", 40,
    "Design low-latency query suggestions that update as a user types.",
    ["Prefix suggestions", "Popularity and freshness ranking", "Personalization", "Typo tolerance"],
    ["Which languages?", "How quickly must trends appear?", "Can sensitive queries become suggestions?"],
    ["The serving index and analytics pipeline have different jobs.", "Precompute top suggestions per prefix.", "Edge caching helps only for non-personalized prefixes."],
    "## Shape\nAggregate normalized query counts through a stream, filter unsafe terms, and periodically build a compact prefix index containing the top candidates at each node. Distribute immutable index versions to regional serving nodes.\n\n## Serving\nNormalize the prefix, fetch top global candidates, merge a small user-history set, and rerank. Cache common prefixes at the edge and cancel stale client requests. Use a fuzzy index only after enough characters to control cost.\n\n## Updates\nPublish small trend overlays every few minutes and rebuild the base index less often. Version and atomically swap indexes so readers never see partial data."),
  q("file-storage", "Design Cloud File Storage", "Storage", "Intermediate", 50,
    "Design a Dropbox-like service with upload, download, folders, sharing, and synchronization.",
    ["Large resumable uploads", "Cross-device sync", "File versioning", "Sharing and permissions"],
    ["Maximum file size?", "Block-level deduplication?", "Conflict behavior?"],
    ["Separate metadata from immutable file chunks.", "Uploads need a commit step.", "Sync clients need an ordered change cursor."],
    "## Shape\nStore folder and version metadata in a transactional database. Split files into content-addressed chunks in object storage. A resumable upload session records received chunks, then atomically creates a new file version.\n\n## Sync\nEvery metadata mutation appends to an ordered per-user change log. Clients poll or stream changes from a durable cursor and download only missing chunks. Conflicting offline edits create sibling versions instead of silently overwriting.\n\n## Security\nUse envelope encryption, short-lived signed transfer URLs, malware scanning, and explicit ACL evaluation. Garbage-collect unreferenced chunks only after a retention window."),
  q("video-streaming", "Design Video Streaming", "Media", "Intermediate", 50,
    "Design an on-demand video platform that supports upload, transcoding, and global playback.",
    ["Reliable upload", "Adaptive bitrate playback", "Global delivery", "Watch progress"],
    ["Live video too, or on demand only?", "Supported resolutions and devices?", "DRM requirements?"],
    ["The upload path and playback path should not share capacity.", "Transcoding is a workflow, not one request.", "Clients adapt using segmented manifests."],
    "## Shape\nUpload directly to object storage through multipart signed URLs. An event starts a durable workflow that probes, transcodes multiple renditions, creates HLS/DASH manifests, generates thumbnails, and publishes only after validation.\n\n## Playback\nServe segments through a CDN with origin shielding. The player selects bitrate using buffer health and measured throughput. Store watch progress separately with coalesced asynchronous writes.\n\n## Operations\nMake every workflow stage idempotent, isolate poison media, and autoscale workers by queue age. Track startup time, rebuffer ratio, encoding failures, and CDN hit rate."),
  q("web-crawler", "Design a Web Crawler", "Search", "Intermediate", 50,
    "Design a polite distributed crawler for billions of pages.",
    ["URL discovery", "Politeness and robots.txt", "Duplicate detection", "Recrawl scheduling"],
    ["Which domains and content types?", "How fresh must the corpus be?", "What is the storage budget?"],
    ["The frontier must schedule by host, not just URL.", "Canonicalization happens before deduplication.", "Content fingerprints catch duplicate bodies."],
    "## Shape\nA URL frontier partitions work by host and schedules eligible fetches according to robots rules and per-host delay. Fetchers resolve DNS through a cache, download within strict limits, and send content to parsing and indexing pipelines.\n\n## Deduplication\nCanonicalize URLs, keep a probabilistic seen set for fast rejection, and confirm in durable storage. Compute content fingerprints to collapse mirrors and parameter variants.\n\n## Freshness\nEstimate change frequency from previous crawls and priority signals. Reschedule important changing pages sooner, use exponential backoff for failures, and prevent crawler traps with depth and pattern budgets."),
  q("metrics", "Design a Metrics Platform", "Observability", "Intermediate", 50,
    "Design a system like Datadog for ingesting, querying, and alerting on time-series metrics.",
    ["High-volume ingestion", "Tags and aggregation", "Dashboards", "Near-real-time alerts"],
    ["Expected series cardinality?", "Retention by resolution?", "Exact or approximate queries?"],
    ["Cardinality is usually harder than raw event volume.", "Downsample older data.", "Alert evaluation should not depend on dashboard traffic."],
    "## Shape\nAgents batch metrics into regional ingestion gateways. A stream partitions by series ID. Consumers validate tags, update alert windows, and write compressed time blocks to a time-series store.\n\n## Query\nA metadata index maps tag predicates to series IDs. Query workers read blocks in parallel, aggregate, and cache common dashboard windows. Roll up older data from raw points to minute and hour resolutions.\n\n## Protection\nEnforce per-tenant series budgets, reject unbounded tag values, shed low-priority data during overload, and expose ingestion lag and dropped-point counters."),
  q("ticketing", "Design a Ticket Booking System", "Transactions", "Advanced", 55,
    "Design concert ticket sales that prevent overselling during extreme traffic spikes.",
    ["Seat discovery", "Temporary holds", "Payment", "Exactly-once ticket issuance"],
    ["Assigned seats or general admission?", "How long is a hold?", "Can payment providers retry callbacks?"],
    ["Availability display may be stale; purchase cannot be.", "A hold is a lease with an expiry.", "Payment and inventory need a saga."],
    "## Shape\nKeep authoritative seat state in a strongly consistent database partitioned by event. A conditional update changes `available → held` with owner and expiry. A queue or waiting room protects the event partition from bursts.\n\n## Checkout\nCreate an idempotent order, place holds, initiate payment, then confirm seats and issue tickets through a saga. Provider callbacks use the order ID as an idempotency key. An expiry worker releases abandoned holds.\n\n## Reads and fairness\nServe seat maps from a cache and clearly treat them as hints. Randomize queue order within a short admission window, rate-limit bots, and audit every seat transition."),
  q("payments", "Design a Payment Processing System", "Transactions", "Advanced", 60,
    "Design a payment platform that authorizes charges, handles retries, refunds, and financial reconciliation.",
    ["Payment intents", "Idempotent charge creation", "Refunds", "Immutable ledger and reconciliation"],
    ["Are funds held or only routed?", "Which currencies and providers?", "What compliance boundary applies?"],
    ["The ledger is the source of financial truth.", "Never retry a provider call without an idempotency key.", "Business state and money movement are related but distinct."],
    "## Shape\nExpose a payment-intent state machine. Store intent transitions transactionally and enqueue provider work through an outbox. Provider adapters normalize responses and webhooks.\n\n## Ledger\nRecord every financial movement as balanced immutable debit and credit entries. Derive balances from entries and add corrective entries rather than editing history. Keep card data inside a tokenized PCI boundary.\n\n## Recovery\nUse idempotency keys on every mutation, reconcile provider settlements against the internal ledger, and route mismatches to an operations queue. Encrypt sensitive data and maintain complete audit trails."),
  q("ride-sharing", "Design a Ride-Sharing Dispatch System", "Geo & Realtime", "Advanced", 60,
    "Design rider matching, live driver locations, trip state, and pricing for a ride-sharing service.",
    ["Nearby driver search", "Low-latency matching", "Live trip updates", "Reliable trip and payment state"],
    ["Maximum pickup radius?", "How stale may locations be?", "Can a driver receive multiple offers?"],
    ["Location updates are high-volume and ephemeral.", "Matching requires a short reservation lease.", "Partitioning only by city may create hotspots."],
    "## Shape\nDrivers stream locations to regional gateways. Store recent positions in an in-memory geospatial index divided into adaptive cells. A dispatch service searches expanding cells, ranks candidates by ETA, and offers the ride using a short exclusive lease.\n\n## Trip state\nPersist the trip as a versioned state machine with conditional transitions. Publish state changes to rider and driver channels. Rebuild ephemeral location indexes from fresh heartbeats after failure.\n\n## Scale\nPartition by metro and cell, apply backpressure to location frequency, and degrade ETA precision before availability. Keep pricing inputs versioned so quoted fares are reproducible."),
  q("maps", "Design a Maps and Navigation Service", "Geo & Realtime", "Advanced", 60,
    "Design route planning, map tiles, traffic updates, and turn-by-turn navigation.",
    ["Map rendering", "Route calculation", "Live traffic", "Route recalculation"],
    ["Driving only or multiple modes?", "Offline support?", "Traffic freshness target?"],
    ["Tiles and routing graphs have different serving patterns.", "Preprocessing makes shortest-path queries practical.", "Traffic updates modify edge weights, not topology."],
    "## Shape\nPreprocess road data into a versioned graph and build vector tiles for CDN distribution. Regional routing services hold graph partitions and use hierarchical shortest-path indexes.\n\n## Traffic\nAggregate anonymized speed observations onto road segments, smooth noisy samples, and publish incremental weight overlays. Navigation clients send location sparingly and request reroutes only when delay crosses a threshold.\n\n## Reliability\nVersion graph, tile, and traffic data together, retain a stable fallback graph, and support offline tile regions. Monitor route latency, ETA error, and map-version mismatch."),
  q("collaborative-editor", "Design a Collaborative Editor", "Collaboration", "Advanced", 60,
    "Design a Google Docs-like editor with concurrent changes, cursors, comments, and offline edits.",
    ["Concurrent text editing", "Offline edits", "Presence", "Version history"],
    ["Text only or rich structured documents?", "Maximum collaborators?", "How long must history remain?"],
    ["Choose OT or CRDT and defend the tradeoff.", "Presence can be lossy; document changes cannot.", "Snapshots keep replay bounded."],
    "## Shape\nRepresent edits as operations over a structured document. Route a document's sessions to one collaboration shard that orders operations, validates permissions, persists them to an append-only log, and broadcasts acknowledgements. OT is compact with a coordinating server; a CRDT better supports decentralized offline merges at greater metadata cost.\n\n## Recovery\nPeriodically store snapshots and replay only the tail of the operation log. Clients retain unacknowledged operations and transform or merge them after reconnect. Presence uses expiring messages outside the durable log.\n\n## Safety\nUse document versions, idempotent operation IDs, per-document backpressure, and ACL checks on connect and mutation."),
  q("distributed-cache", "Design a Distributed Cache", "Infrastructure", "Advanced", 55,
    "Design a Memcached-like in-memory cache with sharding, replication, expiration, and failure recovery.",
    ["Low-latency get/set", "TTL and eviction", "Horizontal scaling", "Node failure tolerance"],
    ["Strong or eventual consistency?", "Object size limit?", "Is persistence required?"],
    ["Consistent hashing reduces remapping.", "Hot keys can defeat even partitioning.", "Eviction policy and memory accounting are core behavior."],
    "## Shape\nClients or proxies route keys through a consistent-hash ring with virtual nodes. Each item stores value, version, size, and expiry. Shards use segmented LRU or TinyLFU admission to protect useful data.\n\n## Failure\nReplicate asynchronously when availability matters, or accept cache loss and repopulate from source. Membership changes are versioned; clients retry against the latest ring. Add request coalescing and stale-while-revalidate to prevent stampedes.\n\n## Hot keys\nReplicate popular reads, cap item size, and detect skew from per-key sampling. Expose hit rate, eviction reasons, memory fragmentation, and p99 latency."),
  q("job-scheduler", "Design a Distributed Job Scheduler", "Infrastructure", "Advanced", 55,
    "Design a system that runs delayed, recurring, and dependency-based jobs across a worker fleet.",
    ["Schedule and cancel jobs", "Retries", "At-least-once execution", "Dependencies and recurring schedules"],
    ["How precise must start time be?", "Maximum job duration?", "Can handlers be idempotent?"],
    ["Scheduling and execution ownership are separate leases.", "Exactly-once side effects require application cooperation.", "A timing wheel avoids scanning every future job."],
    "## Shape\nPersist job definitions and next-run times. Scheduler shards own time ranges or buckets under leases and move due jobs to a durable queue. Workers claim executions with visibility timeouts and heartbeat long jobs.\n\n## Semantics\nProvide at-least-once delivery and require idempotency keys. Store every attempt and transition with optimistic versioning. Retry with bounded exponential backoff, then dead-letter.\n\n## Recurrence\nCompute the next occurrence only after recording the current one, define timezone and missed-run behavior explicitly, and use a hierarchical timing wheel or indexed due-time table for efficient wakeups."),
  q("multi-region-kv", "Design a Multi-Region Key-Value Store", "Distributed Systems", "Advanced", 60,
    "Design a globally distributed key-value database with tunable consistency and regional failover.",
    ["Get, put, delete", "Replication", "Conflict handling", "Regional failover"],
    ["Required consistency per operation?", "Maximum object size?", "Data residency constraints?"],
    ["CAP tradeoffs must be tied to a failure scenario.", "Quorums depend on replica placement.", "Concurrent writes need versions, not arrival timestamps alone."],
    "## Shape\nPartition the keyspace with consistent hashing and place replicas across failure domains. For strong keys, use a leader and consensus per shard. For high-availability keys, accept writes regionally and reconcile version vectors or application-defined CRDTs.\n\n## Reads and repair\nOffer quorum parameters, track logical versions, perform read repair, and run anti-entropy Merkle-tree comparisons. Tombstones must remain until every replica has observed a delete.\n\n## Operations\nRebalance gradually, fence old leaders with epochs, test region loss, and expose replication lag, conflict rate, unavailable shards, and repair backlog."),
];

export const SYSTEM_DESIGN_BY_ID = new Map(SYSTEM_DESIGN_QUESTIONS.map(question => [question.id, question]));
