import type { Problem } from "../../types";

/**
 * LeetCode walkthrough library. GENERATED — source of truth is
 * scratchpad/build_leetcode.py, where every solution is verified against its
 * tests in CPython before this file is written. Do not hand-edit.
 *
 * 39 classic problems across arrays/hashing, two pointers, sliding window,
 * stack, binary search, trees, heap, backtracking, graphs, intervals, DP and bits.
 * Each carries >=3 tests, 3 hints, a Socratic walkthrough and complexity analysis.
 */
export const PYTHON_LEETCODE_PROBLEMS: Problem[] = [
  {
    id: "py.lc.two-sum",
    kind: "problem",
    tier: "problem",
    title: "Two Sum",
    pattern: "Hash map",
    teaches: ["py.hashing"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 2, implementation: 2, recall: 2 },
    estimatedMinutes: 15,
    prompt: "Given a list of integers `values` and an integer `target`, return the indices `[i, j]` of the two numbers that add to `target`. Exactly one answer exists and you may not reuse an index. Aim for O(n).",
    exportName: "two_sum",
    scaffolds: { L1: "def two_sum(values, target):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def two_sum(values, target):\n    pass", L3: "def two_sum(values, target):\n    pass", L4: "" },
    tests: [
    { name: "ordinary", code: "assert fn([2,7,11,15], 9) == [0,1]", hidden: false },
    { name: "later pair", code: "assert fn([3,2,4], 6) == [1,2]", hidden: false },
    { name: "same value", code: "assert fn([3,3], 6) == [0,1]", hidden: false },
    { name: "negatives", code: "assert fn([-1,-2,-3,-4], -6) == [1,3]", hidden: true }
    ],
    hints: [
    { rung: 0, text: "For each number, what single other number would complete the target?" },
    { rung: 1, text: "Walk once, remembering each value's index in a dict as you pass it." },
    { rung: 2, text: "Before storing the current value, check whether its complement target-value is already stored." }
    ],
    walkthrough: ["What is the one number that, added to the current value, hits the target?", "Why does storing value -> index let you answer that in O(1)?", "Why check for the complement BEFORE inserting the current value?", "Why can't the same index be used twice with this order of operations?"],
    solution: "def two_sum(values, target):\n    seen = {}\n    for index, value in enumerate(values):\n        need = target - value\n        if need in seen:\n            return [seen[need], index]\n        seen[value] = index\n    return []",
    language: "python",
    tracks: ["faang", "swe", "quant", "ml"],
    skills: ["hashing", "arrays"],
    analysis: { approach: "One pass; a dict maps each seen value to its index so the complement is an O(1) lookup.", invariant: "`seen` holds every value strictly to the left of the cursor with its index.", time: "O(n)", space: "O(n)" },
  },
  {
    id: "py.lc.contains-duplicate",
    kind: "problem",
    tier: "problem",
    title: "Contains Duplicate",
    pattern: "Set membership",
    teaches: ["py.sets", "py.hashing"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 2, implementation: 1, recall: 2 },
    estimatedMinutes: 8,
    prompt: "Return `True` if any value appears at least twice in `values`, and `False` if every value is distinct.",
    exportName: "contains_duplicate",
    scaffolds: { L1: "def contains_duplicate(values):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def contains_duplicate(values):\n    pass", L3: "def contains_duplicate(values):\n    pass", L4: "" },
    tests: [
    { name: "has dup", code: "assert fn([1,2,3,1]) is True", hidden: false },
    { name: "all unique", code: "assert fn([1,2,3,4]) is False", hidden: false },
    { name: "empty", code: "assert fn([]) is False", hidden: false },
    { name: "immediate", code: "assert fn([5,5]) is True", hidden: true }
    ],
    hints: [
    { rung: 0, text: "You only need to know if a value has been seen before, not how many times." },
    { rung: 1, text: "A set gives O(1) membership; build it as you scan." },
    { rung: 2, text: "Return early the first time a value is already in the set." }
    ],
    walkthrough: ["What is the minimum information you must remember about earlier values?", "Why is a set better here than sorting or a nested loop?", "At what moment can you stop scanning early?", "What does comparing len(set(values)) to len(values) tell you, and why is early-exit still nicer?"],
    solution: "def contains_duplicate(values):\n    seen = set()\n    for value in values:\n        if value in seen:\n            return True\n        seen.add(value)\n    return False",
    language: "python",
    tracks: ["faang", "swe", "quant", "ml"],
    skills: ["hashing", "arrays"],
    analysis: { approach: "Scan once, keeping a set of values already seen; a repeat ends it.", invariant: "`seen` equals the set of values strictly before the cursor.", time: "O(n)", space: "O(n)" },
  },
  {
    id: "py.lc.valid-anagram",
    kind: "problem",
    tier: "problem",
    title: "Valid Anagram",
    pattern: "Frequency count",
    teaches: ["py.hashing", "py.strings"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 2, implementation: 2, recall: 2 },
    estimatedMinutes: 10,
    prompt: "Return `True` if `t` is an anagram of `s` — the same characters with the same counts, reordered. Assume lowercase letters.",
    exportName: "is_anagram",
    scaffolds: { L1: "def is_anagram(s, t):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def is_anagram(s, t):\n    pass", L3: "def is_anagram(s, t):\n    pass", L4: "" },
    tests: [
    { name: "anagram", code: "assert fn('anagram','nagaram') is True", hidden: false },
    { name: "not", code: "assert fn('rat','car') is False", hidden: false },
    { name: "length differs", code: "assert fn('a','ab') is False", hidden: false },
    { name: "empty both", code: "assert fn('','') is True", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Two anagrams have identical character counts and identical length." },
    { rung: 1, text: "Count letters of one string, then spend them down with the other." },
    { rung: 2, text: "If a needed letter is missing or already exhausted, they cannot match." }
    ],
    walkthrough: ["Why is unequal length an instant no?", "What does the counts dict represent after the first loop?", "Why decrement while scanning the second string instead of building a second dict?", "How would sorting both strings solve it, and what does that cost versus counting?"],
    solution: "def is_anagram(s, t):\n    if len(s) != len(t):\n        return False\n    counts = {}\n    for ch in s:\n        counts[ch] = counts.get(ch, 0) + 1\n    for ch in t:\n        if counts.get(ch, 0) == 0:\n            return False\n        counts[ch] -= 1\n    return True",
    language: "python",
    tracks: ["faang", "swe", "quant", "ml"],
    skills: ["hashing", "strings"],
    analysis: { approach: "Tally s's letters, then decrement per t letter; any shortfall fails.", invariant: "`counts` holds s's remaining letters not yet matched by t's prefix.", time: "O(n)", space: "O(1) — bounded alphabet" },
  },
  {
    id: "py.lc.group-anagrams",
    kind: "problem",
    tier: "problem",
    title: "Group Anagrams",
    pattern: "Hash by signature",
    teaches: ["py.hashing", "py.sorting"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 20,
    prompt: "Group the strings in `words` so that anagrams share a group. Return a list of groups. Group order and within-group order do not matter — tests compare as sets of frozensets/sorted structure.",
    exportName: "group_anagrams",
    scaffolds: { L1: "def group_anagrams(words):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def group_anagrams(words):\n    pass", L3: "def group_anagrams(words):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert {frozenset(g) for g in fn(['eat','tea','tan','ate','nat','bat'])} == {frozenset(['eat','tea','ate']), frozenset(['tan','nat']), frozenset(['bat'])}", hidden: false },
    { name: "empty string", code: "assert fn(['']) == [['']]", hidden: false },
    { name: "single", code: "assert fn(['a']) == [['a']]", hidden: false },
    { name: "count", code: "assert len(fn(['abc','bca','xyz'])) == 2", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Anagrams need a shared key that ignores order." },
    { rung: 1, text: "Sorting a word's letters gives every anagram the same signature." },
    { rung: 2, text: "Bucket words in a dict keyed by that signature, then return the buckets." }
    ],
    walkthrough: ["What property must the key have for two anagrams to collide?", "Why does sorted(word) work as that key?", "Could a letter-count tuple be a cheaper key than sorting? What does each cost?", "Why does setdefault avoid a separate 'first time seen' branch?"],
    solution: "def group_anagrams(words):\n    groups = {}\n    for word in words:\n        key = ''.join(sorted(word))\n        groups.setdefault(key, []).append(word)\n    return list(groups.values())",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["hashing", "strings"],
    analysis: { approach: "Key each word by its sorted letters; words with equal keys are anagrams.", invariant: "`groups[key]` holds every word seen so far whose sorted form is `key`.", time: "O(n·k log k) for words of length k", space: "O(n·k)" },
  },
  {
    id: "py.lc.top-k-frequent",
    kind: "problem",
    tier: "problem",
    title: "Top K Frequent Elements",
    pattern: "Count + bucket",
    teaches: ["py.hashing", "py.heap"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 4, recall: 3 },
    estimatedMinutes: 22,
    prompt: "Return the `k` values that appear most often in `values`, in any order. Aim for better than O(n log n).",
    exportName: "top_k_frequent",
    scaffolds: { L1: "def top_k_frequent(values, k):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def top_k_frequent(values, k):\n    pass", L3: "def top_k_frequent(values, k):\n    pass", L4: "" },
    tests: [
    { name: "ordinary", code: "assert set(fn([1,1,1,2,2,3], 2)) == {1,2}", hidden: false },
    { name: "single", code: "assert fn([1], 1) == [1]", hidden: false },
    { name: "all same", code: "assert set(fn([4,4,4], 1)) == {4}", hidden: false },
    { name: "ties allowed", code: "assert len(fn([1,2,3,4], 2)) == 2", hidden: true }
    ],
    hints: [
    { rung: 0, text: "First reduce the data to a value -> count map." },
    { rung: 1, text: "A frequency can be at most n, so index a bucket array by frequency." },
    { rung: 2, text: "Walk buckets from highest frequency down, collecting until you have k." }
    ],
    walkthrough: ["Why does counting first shrink the problem?", "Why is bucketing by frequency O(n) where a full sort is O(n log n)?", "How large must the bucket array be, and why?", "When exactly do you stop collecting, and why is the order across ties irrelevant here?"],
    solution: "def top_k_frequent(values, k):\n    counts = {}\n    for value in values:\n        counts[value] = counts.get(value, 0) + 1\n    buckets = [[] for _ in range(len(values) + 1)]\n    for value, count in counts.items():\n        buckets[count].append(value)\n    result = []\n    for count in range(len(buckets) - 1, 0, -1):\n        for value in buckets[count]:\n            result.append(value)\n            if len(result) == k:\n                return result\n    return result",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["hashing", "arrays"],
    analysis: { approach: "Count values, then bucket by frequency and read buckets from the top down.", invariant: "`buckets[f]` holds every distinct value whose count is exactly f.", time: "O(n)", space: "O(n)" },
  },
  {
    id: "py.lc.valid-palindrome",
    kind: "problem",
    tier: "problem",
    title: "Valid Palindrome",
    pattern: "Two pointers",
    teaches: ["py.two-pointers", "py.strings"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 2, implementation: 2, recall: 2 },
    estimatedMinutes: 12,
    prompt: "Return `True` if `text` reads the same forward and backward, considering only letters and digits and ignoring case.",
    exportName: "is_palindrome",
    scaffolds: { L1: "def is_palindrome(text):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def is_palindrome(text):\n    pass", L3: "def is_palindrome(text):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn('A man, a plan, a canal: Panama') is True", hidden: false },
    { name: "not", code: "assert fn('race a car') is False", hidden: false },
    { name: "empty", code: "assert fn('') is True", hidden: false },
    { name: "only punctuation", code: "assert fn('.,') is True", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Compare from both ends moving inward." },
    { rung: 1, text: "Skip any character that is not a letter or digit before comparing." },
    { rung: 2, text: "Lowercase both sides so case never matters." }
    ],
    walkthrough: ["Why do two pointers beat building a cleaned reversed copy on space?", "What must you do when a pointer lands on punctuation?", "Why is the case fold applied at comparison time, not up front?", "Why is the empty (or all-punctuation) string a palindrome?"],
    solution: "def is_palindrome(text):\n    left, right = 0, len(text) - 1\n    while left < right:\n        while left < right and not text[left].isalnum():\n            left += 1\n        while left < right and not text[right].isalnum():\n            right -= 1\n        if text[left].lower() != text[right].lower():\n            return False\n        left += 1\n        right -= 1\n    return True",
    language: "python",
    tracks: ["faang", "swe", "quant", "ml"],
    skills: ["strings", "two-pointers"],
    analysis: { approach: "Converge two pointers, skipping non-alphanumerics, comparing case-folded.", invariant: "Everything outside [left, right] has already matched as a mirror pair.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.lc.two-sum-sorted",
    kind: "problem",
    tier: "problem",
    title: "Two Sum II (sorted input)",
    pattern: "Two pointers",
    teaches: ["py.two-pointers"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 3, implementation: 2, recall: 3 },
    estimatedMinutes: 14,
    prompt: "`values` is sorted ascending. Return the 1-based indices `[i, j]` (i < j) of the two numbers adding to `target`. Exactly one solution exists. Use O(1) extra space.",
    exportName: "two_sum_sorted",
    scaffolds: { L1: "def two_sum_sorted(values, target):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def two_sum_sorted(values, target):\n    pass", L3: "def two_sum_sorted(values, target):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([2,7,11,15], 9) == [1,2]", hidden: false },
    { name: "far ends", code: "assert fn([1,2,3,4,4,9,56,90], 8) == [4,5]", hidden: false },
    { name: "negatives", code: "assert fn([-8,-3,1,4], -7) == [1,3]", hidden: false },
    { name: "two", code: "assert fn([1,2], 3) == [1,2]", hidden: true }
    ],
    hints: [
    { rung: 0, text: "The sortedness is the whole gift — use it." },
    { rung: 1, text: "Start wide; the sum's direction tells you which end to move." },
    { rung: 2, text: "Too small means the left number must grow; too big means the right must shrink." }
    ],
    walkthrough: ["Why can you discard the left value when the sum is too small?", "Why does moving inward never skip the unique answer?", "How does this reach O(1) space where the hash-map version used O(n)?", "What breaks if the array were not sorted?"],
    solution: "def two_sum_sorted(values, target):\n    left, right = 0, len(values) - 1\n    while left < right:\n        total = values[left] + values[right]\n        if total == target:\n            return [left + 1, right + 1]\n        if total < target:\n            left += 1\n        else:\n            right -= 1\n    return []",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["two-pointers", "arrays"],
    analysis: { approach: "Two pointers at the ends; move the end that pushes the sum toward target.", invariant: "The answer pair, if any remains, lies within [left, right].", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.lc.container-most-water",
    kind: "problem",
    tier: "problem",
    title: "Container With Most Water",
    pattern: "Two pointers",
    teaches: ["py.two-pointers"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 20,
    prompt: "Each `heights[i]` is a vertical line at x=i. Pick two lines that with the x-axis hold the most water. Return that maximum area. Use O(n) time, O(1) space.",
    exportName: "max_area",
    scaffolds: { L1: "def max_area(heights):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def max_area(heights):\n    pass", L3: "def max_area(heights):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([1,8,6,2,5,4,8,3,7]) == 49", hidden: false },
    { name: "two", code: "assert fn([1,1]) == 1", hidden: false },
    { name: "increasing", code: "assert fn([1,2,3,4,5]) == 6", hidden: false },
    { name: "single", code: "assert fn([5]) == 0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Area is width times the shorter of the two lines." },
    { rung: 1, text: "Start at maximum width and move inward." },
    { rung: 2, text: "Moving the taller line can only lose area; move the shorter one." }
    ],
    walkthrough: ["Why is the area capped by the SHORTER line, not the taller?", "Starting wide, why is moving the taller pointer never helpful?", "Why does this examine each index at most once?", "Could two equal-height ends move either way without missing the max?"],
    solution: "def max_area(heights):\n    left, right = 0, len(heights) - 1\n    best = 0\n    while left < right:\n        width = right - left\n        height = min(heights[left], heights[right])\n        best = max(best, width * height)\n        if heights[left] < heights[right]:\n            left += 1\n        else:\n            right -= 1\n    return best",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["two-pointers", "arrays"],
    analysis: { approach: "Widest pair first; always retreat the shorter wall inward.", invariant: "No wider container using a discarded shorter wall can beat what's recorded.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.lc.best-time-stock",
    kind: "problem",
    tier: "problem",
    title: "Best Time to Buy and Sell Stock",
    pattern: "Running minimum",
    teaches: ["py.sliding-window"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 3, implementation: 2, recall: 2 },
    estimatedMinutes: 12,
    prompt: "`prices[i]` is the price on day i. Buy once and sell later once. Return the maximum profit, or 0 if no profit is possible.",
    exportName: "max_profit",
    scaffolds: { L1: "def max_profit(prices):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def max_profit(prices):\n    pass", L3: "def max_profit(prices):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([7,1,5,3,6,4]) == 5", hidden: false },
    { name: "declining", code: "assert fn([7,6,4,3,1]) == 0", hidden: false },
    { name: "empty", code: "assert fn([]) == 0", hidden: false },
    { name: "two up", code: "assert fn([1,2]) == 1", hidden: true }
    ],
    hints: [
    { rung: 0, text: "The best sell day only matters relative to the cheapest day before it." },
    { rung: 1, text: "Track the minimum price seen so far as you sweep left to right." },
    { rung: 2, text: "At each day, the candidate profit is today minus that running minimum." }
    ],
    walkthrough: ["Why must the buy day come before the sell day, and how does one pass respect that?", "What are the only two quantities you need to remember?", "Why is a fresh lower price never a missed sell opportunity?", "Why is 0 the right answer for a strictly decreasing series?"],
    solution: "def max_profit(prices):\n    cheapest = float('inf')\n    best = 0\n    for price in prices:\n        if price < cheapest:\n            cheapest = price\n        elif price - cheapest > best:\n            best = price - cheapest\n    return best",
    language: "python",
    tracks: ["faang", "swe", "quant", "ml"],
    skills: ["arrays", "greedy"],
    analysis: { approach: "Sweep once, tracking the cheapest price so far and the best profit against it.", invariant: "`cheapest` is the min of all prices seen; `best` the max profit sellable today.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.lc.longest-substring-unique",
    kind: "problem",
    tier: "problem",
    title: "Longest Substring Without Repeating Characters",
    pattern: "Sliding window",
    teaches: ["py.sliding-window", "py.hashing"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 4, recall: 4 },
    estimatedMinutes: 24,
    prompt: "Return the length of the longest substring of `text` with no repeated character.",
    exportName: "length_of_longest",
    scaffolds: { L1: "def length_of_longest(text):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def length_of_longest(text):\n    pass", L3: "def length_of_longest(text):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn('abcabcbb') == 3", hidden: false },
    { name: "all same", code: "assert fn('bbbbb') == 1", hidden: false },
    { name: "mixed", code: "assert fn('pwwkew') == 3", hidden: false },
    { name: "empty", code: "assert fn('') == 0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Keep a window that always holds distinct characters." },
    { rung: 1, text: "Remember the last index where each character appeared." },
    { rung: 2, text: "On a repeat inside the window, jump the window start past the earlier copy." }
    ],
    walkthrough: ["What condition must every character in the window satisfy?", "Why check `last[ch] >= start` rather than just `ch in last`?", "Why does start only ever move forward?", "How is the current window length computed at each step?"],
    solution: "def length_of_longest(text):\n    last = {}\n    start = 0\n    best = 0\n    for index, ch in enumerate(text):\n        if ch in last and last[ch] >= start:\n            start = last[ch] + 1\n        last[ch] = index\n        best = max(best, index - start + 1)\n    return best",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["sliding-window", "strings"],
    analysis: { approach: "Grow a right edge; when a repeat falls inside, snap the left edge past it.", invariant: "text[start..index] contains no repeated character.", time: "O(n)", space: "O(min(n, alphabet))" },
  },
  {
    id: "py.lc.char-replacement",
    kind: "problem",
    tier: "challenge",
    title: "Longest Repeating Character Replacement",
    pattern: "Sliding window",
    teaches: ["py.sliding-window", "py.hashing"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 5, implementation: 4, recall: 4 },
    estimatedMinutes: 28,
    prompt: "Given uppercase-letter string `text` and integer `k`, you may replace at most `k` characters with any letters. Return the length of the longest substring that can become all one repeated letter.",
    exportName: "character_replacement",
    scaffolds: { L1: "def character_replacement(text, k):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def character_replacement(text, k):\n    pass", L3: "def character_replacement(text, k):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn('ABAB', 2) == 4", hidden: false },
    { name: "one swap", code: "assert fn('AABABBA', 1) == 4", hidden: false },
    { name: "no budget", code: "assert fn('ABCD', 0) == 1", hidden: false },
    { name: "empty", code: "assert fn('', 2) == 0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "A window is valid when (window length - count of its most common letter) <= k." },
    { rung: 1, text: "That difference is exactly how many replacements the window would need." },
    { rung: 2, text: "Grow right; while the window needs more than k swaps, shrink from the left." }
    ],
    walkthrough: ["What does window_length minus max_count represent?", "Why does the window never need to shrink by more than one per step?", "Why is it acceptable that `most` is not decreased when the window shrinks?", "What makes k=0 collapse to 'longest run of one letter'?"],
    solution: "def character_replacement(text, k):\n    counts = {}\n    start = 0\n    most = 0\n    best = 0\n    for index, ch in enumerate(text):\n        counts[ch] = counts.get(ch, 0) + 1\n        most = max(most, counts[ch])\n        while (index - start + 1) - most > k:\n            counts[text[start]] -= 1\n            start += 1\n        best = max(best, index - start + 1)\n    return best",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["sliding-window", "strings"],
    analysis: { approach: "Keep counts in the window; valid while length - max_count <= k.", invariant: "`most` is the highest count any letter has reached in a window so far.", time: "O(n)", space: "O(1) — 26 letters" },
  },
  {
    id: "py.lc.valid-parentheses",
    kind: "problem",
    tier: "problem",
    title: "Valid Parentheses",
    pattern: "Stack",
    teaches: ["py.stack"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 2, implementation: 2, recall: 2 },
    estimatedMinutes: 12,
    prompt: "Given a string of only the characters `()[]{}`, return `True` if every bracket is closed by the matching type in the correct order.",
    exportName: "is_valid",
    scaffolds: { L1: "def is_valid(text):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def is_valid(text):\n    pass", L3: "def is_valid(text):\n    pass", L4: "" },
    tests: [
    { name: "simple", code: "assert fn('()') is True", hidden: false },
    { name: "nested mix", code: "assert fn('()[]{}') is True", hidden: false },
    { name: "mismatch", code: "assert fn('(]') is False", hidden: false },
    { name: "unclosed", code: "assert fn('([') is False", hidden: true }
    ],
    hints: [
    { rung: 0, text: "The most recently opened bracket must be the first one closed." },
    { rung: 1, text: "That last-in-first-out rule is a stack." },
    { rung: 2, text: "Push openers; on a closer, the top must be its exact match." }
    ],
    walkthrough: ["Why is a stack the right structure for nesting?", "What two ways can a closing bracket fail?", "Why must the stack be empty at the end?", "Why map closer->opener rather than the other direction?"],
    solution: "def is_valid(text):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    stack = []\n    for ch in text:\n        if ch in pairs:\n            if not stack or stack.pop() != pairs[ch]:\n                return False\n        else:\n            stack.append(ch)\n    return not stack",
    language: "python",
    tracks: ["faang", "swe", "quant", "ml"],
    skills: ["stack", "strings"],
    analysis: { approach: "Push openers; each closer must pop its exact match; end empty.", invariant: "The stack holds all still-open brackets, innermost on top.", time: "O(n)", space: "O(n)" },
  },
  {
    id: "py.lc.eval-rpn",
    kind: "problem",
    tier: "problem",
    title: "Evaluate Reverse Polish Notation",
    pattern: "Stack",
    teaches: ["py.stack"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 3, implementation: 3, recall: 3 },
    estimatedMinutes: 18,
    prompt: "Evaluate an arithmetic expression in Reverse Polish Notation given as a list `tokens` of numbers and the operators `+ - * /`. Division truncates toward zero. Return the integer result.",
    exportName: "eval_rpn",
    scaffolds: { L1: "def eval_rpn(tokens):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def eval_rpn(tokens):\n    pass", L3: "def eval_rpn(tokens):\n    pass", L4: "" },
    tests: [
    { name: "basic", code: "assert fn(['2','1','+','3','*']) == 9", hidden: false },
    { name: "division", code: "assert fn(['4','13','5','/','+']) == 6", hidden: false },
    { name: "negative trunc", code: "assert fn(['10','6','9','3','+','-11','*','/','*','17','+','5','+']) == 22", hidden: false },
    { name: "single", code: "assert fn(['42']) == 42", hidden: true }
    ],
    hints: [
    { rung: 0, text: "In RPN an operator acts on the two most recent results." },
    { rung: 1, text: "Push numbers; on an operator pop two, combine, push the result." },
    { rung: 2, text: "Mind the operand order: the first popped is the right-hand side." }
    ],
    walkthrough: ["Why does RPN need no parentheses or precedence rules?", "When you pop two operands, which is the left operand?", "Why does int(a / b) truncate toward zero where a // b would not for negatives?", "What guarantees exactly one value remains at the end?"],
    solution: "def eval_rpn(tokens):\n    stack = []\n    ops = {'+', '-', '*', '/'}\n    for token in tokens:\n        if token in ops:\n            b = stack.pop()\n            a = stack.pop()\n            if token == '+':\n                stack.append(a + b)\n            elif token == '-':\n                stack.append(a - b)\n            elif token == '*':\n                stack.append(a * b)\n            else:\n                stack.append(int(a / b))\n        else:\n            stack.append(int(token))\n    return stack[0]",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["stack"],
    analysis: { approach: "Stack of operands; each operator folds the top two into one.", invariant: "The stack holds the results of every fully-evaluated sub-expression so far.", time: "O(n)", space: "O(n)" },
  },
  {
    id: "py.lc.daily-temperatures",
    kind: "problem",
    tier: "problem",
    title: "Daily Temperatures",
    pattern: "Monotonic stack",
    teaches: ["py.monotonic-stack", "py.stack"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 4, recall: 4 },
    estimatedMinutes: 24,
    prompt: "Given `temps`, return a list `answer` where `answer[i]` is the number of days until a warmer temperature, or 0 if none. Aim for O(n).",
    exportName: "daily_temperatures",
    scaffolds: { L1: "def daily_temperatures(temps):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def daily_temperatures(temps):\n    pass", L3: "def daily_temperatures(temps):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([73,74,75,71,69,72,76,73]) == [1,1,4,2,1,1,0,0]", hidden: false },
    { name: "increasing", code: "assert fn([30,40,50,60]) == [1,1,1,0]", hidden: false },
    { name: "flat", code: "assert fn([30,30,30]) == [0,0,0]", hidden: false },
    { name: "single", code: "assert fn([50]) == [0]", hidden: true }
    ],
    hints: [
    { rung: 0, text: "For each cooler day, you are waiting for the first warmer one." },
    { rung: 1, text: "Keep a stack of unresolved day indices with decreasing temperatures." },
    { rung: 2, text: "A warm day resolves every colder day still on the stack." }
    ],
    walkthrough: ["What does an index on the stack represent?", "Why are stack temperatures always decreasing from bottom to top?", "Why does each index get pushed and popped at most once (giving O(n))?", "Why is the distance simply current_index minus popped_index?"],
    solution: "def daily_temperatures(temps):\n    answer = [0] * len(temps)\n    stack = []  # indices of days awaiting a warmer day\n    for index, temp in enumerate(temps):\n        while stack and temps[stack[-1]] < temp:\n            previous = stack.pop()\n            answer[previous] = index - previous\n        stack.append(index)\n    return answer",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["stack", "arrays"],
    analysis: { approach: "Monotonic decreasing stack of waiting days; a warmer day settles them.", invariant: "Stack holds indices whose warmer day is not yet found, temps strictly decreasing.", time: "O(n)", space: "O(n)" },
  },
  {
    id: "py.lc.binary-search",
    kind: "problem",
    tier: "problem",
    title: "Binary Search",
    pattern: "Binary search",
    teaches: ["py.binary-search"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 2, implementation: 2, recall: 2 },
    estimatedMinutes: 12,
    prompt: "`values` is sorted ascending. Return the index of `target`, or -1 if absent. Use O(log n) time.",
    exportName: "binary_search",
    scaffolds: { L1: "def binary_search(values, target):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def binary_search(values, target):\n    pass", L3: "def binary_search(values, target):\n    pass", L4: "" },
    tests: [
    { name: "found", code: "assert fn([-1,0,3,5,9,12], 9) == 4", hidden: false },
    { name: "absent", code: "assert fn([-1,0,3,5,9,12], 2) == -1", hidden: false },
    { name: "single hit", code: "assert fn([5], 5) == 0", hidden: false },
    { name: "empty", code: "assert fn([], 1) == -1", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Each comparison should halve what remains." },
    { rung: 1, text: "Track an inclusive [low, high] window and probe its middle." },
    { rung: 2, text: "Move the boundary past mid depending on whether mid is too small or too big." }
    ],
    walkthrough: ["Why is the loop condition low <= high rather than low < high?", "Why mid+1 and mid-1 instead of mid when narrowing?", "How does (low + high) // 2 stay correct for large indices in Python?", "What exact state means the target is absent?"],
    solution: "def binary_search(values, target):\n    low, high = 0, len(values) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if values[mid] == target:\n            return mid\n        if values[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1",
    language: "python",
    tracks: ["faang", "swe", "quant", "ml"],
    skills: ["binary-search", "arrays"],
    analysis: { approach: "Halve an inclusive window each step, chasing target by comparison.", invariant: "If present, target lies within [low, high].", time: "O(log n)", space: "O(1)" },
  },
  {
    id: "py.lc.search-rotated",
    kind: "problem",
    tier: "challenge",
    title: "Search in Rotated Sorted Array",
    pattern: "Binary search",
    teaches: ["py.binary-search"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 5, implementation: 4, recall: 4 },
    estimatedMinutes: 28,
    prompt: "`values` is an ascending array rotated at an unknown pivot, with distinct elements. Return the index of `target` or -1, in O(log n).",
    exportName: "search_rotated",
    scaffolds: { L1: "def search_rotated(values, target):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def search_rotated(values, target):\n    pass", L3: "def search_rotated(values, target):\n    pass", L4: "" },
    tests: [
    { name: "right half", code: "assert fn([4,5,6,7,0,1,2], 0) == 4", hidden: false },
    { name: "absent", code: "assert fn([4,5,6,7,0,1,2], 3) == -1", hidden: false },
    { name: "single", code: "assert fn([1], 1) == 0", hidden: false },
    { name: "left half", code: "assert fn([5,1,3], 5) == 0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "At any mid, at least one side [low..mid] or [mid..high] is properly sorted." },
    { rung: 1, text: "Decide which half is sorted, then test whether target lies inside it." },
    { rung: 2, text: "Recurse into the half that must contain target." }
    ],
    walkthrough: ["How do you tell which side of mid is sorted?", "Once a side is known sorted, how do you check if target is in it?", "Why does distinctness matter for the `<=` comparisons?", "Why is this still O(log n) despite the rotation?"],
    solution: "def search_rotated(values, target):\n    low, high = 0, len(values) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if values[mid] == target:\n            return mid\n        if values[low] <= values[mid]:\n            if values[low] <= target < values[mid]:\n                high = mid - 1\n            else:\n                low = mid + 1\n        else:\n            if values[mid] < target <= values[high]:\n                low = mid + 1\n            else:\n                high = mid - 1\n    return -1",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["binary-search", "arrays"],
    analysis: { approach: "Each step one half is sorted; keep the half that can contain target.", invariant: "target, if present, remains within [low, high].", time: "O(log n)", space: "O(1)" },
  },
  {
    id: "py.lc.koko-bananas",
    kind: "problem",
    tier: "challenge",
    title: "Koko Eating Bananas",
    pattern: "Binary search on the answer",
    teaches: ["py.binary-search"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 5, implementation: 4, recall: 4 },
    estimatedMinutes: 28,
    prompt: "`piles[i]` bananas per pile; Koko eats at speed s bananas/hour, finishing at most one pile per hour. Return the minimum integer speed to finish all piles within `hours` hours.",
    exportName: "min_eating_speed",
    scaffolds: { L1: "def min_eating_speed(piles, hours):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def min_eating_speed(piles, hours):\n    pass", L3: "def min_eating_speed(piles, hours):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([3,6,7,11], 8) == 4", hidden: false },
    { name: "tight", code: "assert fn([30,11,23,4,20], 5) == 30", hidden: false },
    { name: "loose", code: "assert fn([30,11,23,4,20], 6) == 23", hidden: false },
    { name: "single", code: "assert fn([312], 312) == 1", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Feasibility is monotonic: if speed s finishes in time, so does any s+1." },
    { rung: 1, text: "Binary-search the smallest speed in [1, max(pile)] that finishes in time." },
    { rung: 2, text: "Hours for a pile at speed s is ceil(pile / s)." }
    ],
    walkthrough: ["Why can you binary-search the ANSWER rather than an array position?", "What makes the feasibility predicate monotonic in speed?", "Why is max(piles) a safe upper bound for speed?", "Why (pile + speed - 1)//speed instead of pile/speed?"],
    solution: "def min_eating_speed(piles, hours):\n    def time_at(speed):\n        return sum((pile + speed - 1) // speed for pile in piles)\n    low, high = 1, max(piles)\n    while low < high:\n        mid = (low + high) // 2\n        if time_at(mid) <= hours:\n            high = mid\n        else:\n            low = mid + 1\n    return low",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["binary-search"],
    analysis: { approach: "Binary-search the least speed whose total hours <= budget.", invariant: "Every speed below `low` is too slow; `high` is known feasible.", time: "O(n log(max pile))", space: "O(1)" },
  },
  {
    id: "py.lc.max-depth",
    kind: "problem",
    tier: "problem",
    title: "Maximum Depth of Binary Tree",
    pattern: "Tree recursion",
    teaches: ["py.trees", "py.recursion"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 3, implementation: 2, recall: 2 },
    estimatedMinutes: 12,
    prompt: "Return the maximum depth (number of nodes on the longest root-to-leaf path) of a binary tree. A tree is `None` or a tuple `(value, left, right)` where left and right are subtrees.",
    exportName: "max_depth",
    scaffolds: { L1: "def max_depth(root):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def max_depth(root):\n    pass", L3: "def max_depth(root):\n    pass", L4: "" },
    tests: [
    { name: "balanced", code: "assert fn((1,(2,None,None),(3,None,None))) == 2", hidden: false },
    { name: "empty", code: "assert fn(None) == 0", hidden: false },
    { name: "left chain", code: "assert fn((1,(2,(3,None,None),None),None)) == 3", hidden: false },
    { name: "single", code: "assert fn((9,None,None)) == 1", hidden: true }
    ],
    hints: [
    { rung: 0, text: "A tree's depth is one more than its deeper subtree." },
    { rung: 1, text: "The empty tree has depth 0 — that is your base case." },
    { rung: 2, text: "Recurse on both children and add one for the current node." }
    ],
    walkthrough: ["What is the depth of the empty tree, and why is that the base case?", "How does a node's depth relate to its children's depths?", "Why does this visit each node exactly once?", "What would change if depth were measured in EDGES instead of nodes?"],
    solution: "def max_depth(root):\n    if root is None:\n        return 0\n    value, left, right = root\n    return 1 + max(max_depth(left), max_depth(right))",
    language: "python",
    tracks: ["faang", "swe", "quant", "ml"],
    skills: ["trees", "recursion"],
    analysis: { approach: "Depth(node) = 1 + max(depth(left), depth(right)); empty = 0.", invariant: "Each call returns the exact height of the subtree rooted at its argument.", time: "O(n)", space: "O(h) recursion" },
  },
  {
    id: "py.lc.invert-tree",
    kind: "problem",
    tier: "problem",
    title: "Invert Binary Tree",
    pattern: "Tree recursion",
    teaches: ["py.trees", "py.recursion"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 3, implementation: 2, recall: 2 },
    estimatedMinutes: 12,
    prompt: "Return the mirror image of a binary tree (every left/right pair swapped). A tree is `None` or a tuple `(value, left, right)` where left and right are subtrees.",
    exportName: "invert_tree",
    scaffolds: { L1: "def invert_tree(root):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def invert_tree(root):\n    pass", L3: "def invert_tree(root):\n    pass", L4: "" },
    tests: [
    { name: "swap", code: "assert fn((1,(2,None,None),(3,None,None))) == (1,(3,None,None),(2,None,None))", hidden: false },
    { name: "empty", code: "assert fn(None) is None", hidden: false },
    { name: "deep", code: "assert fn((1,(2,(4,None,None),None),None)) == (1,None,(2,None,(4,None,None)))", hidden: false },
    { name: "single", code: "assert fn((7,None,None)) == (7,None,None)", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Mirroring a node means swapping its two subtrees." },
    { rung: 1, text: "But each subtree must itself be mirrored first (or as you build)." },
    { rung: 2, text: "Return a new node whose left is the inverted right and vice versa." }
    ],
    walkthrough: ["What single operation mirrors one node?", "Why must the swap apply recursively, not just at the root?", "Why does returning a fresh tuple avoid mutating shared structure?", "What is the mirror of the empty tree?"],
    solution: "def invert_tree(root):\n    if root is None:\n        return None\n    value, left, right = root\n    return (value, invert_tree(right), invert_tree(left))",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["trees", "recursion"],
    analysis: { approach: "Rebuild each node with its inverted children swapped.", invariant: "Each call returns a full mirror of the subtree it was given.", time: "O(n)", space: "O(h)" },
  },
  {
    id: "py.lc.same-tree",
    kind: "problem",
    tier: "problem",
    title: "Same Tree",
    pattern: "Tree recursion",
    teaches: ["py.trees", "py.recursion"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 3, implementation: 2, recall: 2 },
    estimatedMinutes: 12,
    prompt: "Return `True` if two binary trees are structurally identical with equal values at every position. A tree is `None` or a tuple `(value, left, right)` where left and right are subtrees.",
    exportName: "is_same_tree",
    scaffolds: { L1: "def is_same_tree(p, q):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def is_same_tree(p, q):\n    pass", L3: "def is_same_tree(p, q):\n    pass", L4: "" },
    tests: [
    { name: "equal", code: "assert fn((1,(2,None,None),(3,None,None)), (1,(2,None,None),(3,None,None))) is True", hidden: false },
    { name: "value differs", code: "assert fn((1,(2,None,None),None), (1,None,(2,None,None))) is False", hidden: false },
    { name: "both empty", code: "assert fn(None, None) is True", hidden: false },
    { name: "one empty", code: "assert fn((1,None,None), None) is False", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Two trees match when their roots match and both subtree pairs match." },
    { rung: 1, text: "Two empty trees are equal; one empty and one not are unequal." },
    { rung: 2, text: "Compare values, then recurse on left-with-left and right-with-right." }
    ],
    walkthrough: ["What are the three base cases involving None?", "Why compare left-to-left and right-to-right specifically?", "Why does a single value mismatch short-circuit the whole answer?", "How does structure (not just the value multiset) get checked here?"],
    solution: "def is_same_tree(p, q):\n    if p is None and q is None:\n        return True\n    if p is None or q is None:\n        return False\n    return p[0] == q[0] and is_same_tree(p[1], q[1]) and is_same_tree(p[2], q[2])",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["trees", "recursion"],
    analysis: { approach: "Both empty -> equal; one empty -> unequal; else values and both subtrees agree.", invariant: "Each call decides equality of the two subtrees rooted at its arguments.", time: "O(n)", space: "O(h)" },
  },
  {
    id: "py.lc.balanced-tree",
    kind: "problem",
    tier: "problem",
    title: "Balanced Binary Tree",
    pattern: "Tree recursion",
    teaches: ["py.trees", "py.recursion"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 20,
    prompt: "Return `True` if a binary tree is height-balanced: for every node the two subtree heights differ by at most 1. A tree is `None` or a tuple `(value, left, right)` where left and right are subtrees.",
    exportName: "is_balanced",
    scaffolds: { L1: "def is_balanced(root):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def is_balanced(root):\n    pass", L3: "def is_balanced(root):\n    pass", L4: "" },
    tests: [
    { name: "balanced", code: "assert fn((1,(2,None,None),(3,None,None))) is True", hidden: false },
    { name: "skewed", code: "assert fn((1,(2,(3,None,None),None),None)) is False", hidden: false },
    { name: "empty", code: "assert fn(None) is True", hidden: false },
    { name: "single", code: "assert fn((1,None,None)) is True", hidden: true }
    ],
    hints: [
    { rung: 0, text: "A naive check recomputes heights; fold the check into the height computation." },
    { rung: 1, text: "Let the height function return -1 to signal 'already unbalanced below'." },
    { rung: 2, text: "Propagate that -1 upward so the whole tree fails fast." }
    ],
    walkthrough: ["Why is computing height and balance in one pass better than two?", "What does a returned -1 mean, and how does it spread?", "Where exactly is the |left - right| <= 1 rule enforced?", "Why is this O(n) rather than O(n log n)?"],
    solution: "def is_balanced(root):\n    def height(node):\n        if node is None:\n            return 0\n        left = height(node[1])\n        if left == -1:\n            return -1\n        right = height(node[2])\n        if right == -1:\n            return -1\n        if abs(left - right) > 1:\n            return -1\n        return 1 + max(left, right)\n    return height(root) != -1",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["trees", "recursion"],
    analysis: { approach: "Height returns -1 as a sentinel the moment any node is unbalanced.", invariant: "height(node) is the true height, or -1 if some node below is unbalanced.", time: "O(n)", space: "O(h)" },
  },
  {
    id: "py.lc.kth-largest",
    kind: "problem",
    tier: "problem",
    title: "Kth Largest Element in an Array",
    pattern: "Heap",
    teaches: ["py.heap"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 18,
    prompt: "Return the k-th largest element in `values` (k=1 is the maximum). Use a heap of size k for O(n log k).",
    exportName: "find_kth_largest",
    scaffolds: { L1: "import heapq\n\ndef find_kth_largest(values, k):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "import heapq\n\ndef find_kth_largest(values, k):\n    pass", L3: "import heapq\n\ndef find_kth_largest(values, k):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([3,2,1,5,6,4], 2) == 5", hidden: false },
    { name: "dups", code: "assert fn([3,2,3,1,2,4,5,5,6], 4) == 4", hidden: false },
    { name: "k is n", code: "assert fn([7,1,3], 3) == 1", hidden: false },
    { name: "single", code: "assert fn([2], 1) == 2", hidden: true }
    ],
    hints: [
    { rung: 0, text: "You only care about the k biggest values, not a full sort." },
    { rung: 1, text: "Keep a MIN-heap of size k; its root is the smallest of the k biggest." },
    { rung: 2, text: "Push each value; if the heap exceeds k, pop the smallest." }
    ],
    walkthrough: ["Why does a min-heap of size k, not a max-heap, give the k-th largest?", "After processing all values, what does the heap root represent?", "Why is O(n log k) better than sorting's O(n log n) when k is small?", "What happens when k equals the array length?"],
    solution: "import heapq\n\ndef find_kth_largest(values, k):\n    smallest = []\n    for value in values:\n        heapq.heappush(smallest, value)\n        if len(smallest) > k:\n            heapq.heappop(smallest)\n    return smallest[0]",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["heap", "arrays"],
    analysis: { approach: "Maintain the k largest so far in a size-k min-heap; its root is the answer.", invariant: "The heap holds the k largest values seen; its root is the k-th largest.", time: "O(n log k)", space: "O(k)" },
  },
  {
    id: "py.lc.last-stone-weight",
    kind: "problem",
    tier: "problem",
    title: "Last Stone Weight",
    pattern: "Heap simulation",
    teaches: ["py.heap"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 3, implementation: 3, recall: 3 },
    estimatedMinutes: 16,
    prompt: "Repeatedly smash the two heaviest stones in `stones`: they either both vanish (equal) or leave the difference. Return the weight of the last remaining stone, or 0 if none remain.",
    exportName: "last_stone_weight",
    scaffolds: { L1: "import heapq\n\ndef last_stone_weight(stones):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "import heapq\n\ndef last_stone_weight(stones):\n    pass", L3: "import heapq\n\ndef last_stone_weight(stones):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([2,7,4,1,8,1]) == 1", hidden: false },
    { name: "one", code: "assert fn([1]) == 1", hidden: false },
    { name: "cancel all", code: "assert fn([2,2]) == 0", hidden: false },
    { name: "empty", code: "assert fn([]) == 0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "You always need the current two heaviest — that is a max-heap." },
    { rung: 1, text: "Python's heapq is a min-heap; negate values to simulate a max-heap." },
    { rung: 2, text: "Push back the difference only when the two differ." }
    ],
    walkthrough: ["Why does this problem call for a heap rather than re-sorting each round?", "How do negated weights turn heapq into a max-heap?", "When do zero stones get pushed back, and why avoid it?", "What are the two possible end states of the loop?"],
    solution: "import heapq\n\ndef last_stone_weight(stones):\n    heap = [-s for s in stones]\n    heapq.heapify(heap)\n    while len(heap) > 1:\n        first = -heapq.heappop(heap)\n        second = -heapq.heappop(heap)\n        if first != second:\n            heapq.heappush(heap, -(first - second))\n    return -heap[0] if heap else 0",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["heap"],
    analysis: { approach: "Max-heap via negation; smash the top two until one or none remain.", invariant: "The heap always contains the current multiset of stone weights.", time: "O(n log n)", space: "O(n)" },
  },
  {
    id: "py.lc.subsets",
    kind: "problem",
    tier: "problem",
    title: "Subsets",
    pattern: "Backtracking",
    teaches: ["py.backtracking", "py.recursion"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 20,
    prompt: "Return all subsets (the power set) of a list `values` of distinct integers. Any order of subsets is accepted — tests compare as a set of frozensets.",
    exportName: "subsets",
    scaffolds: { L1: "def subsets(values):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def subsets(values):\n    pass", L3: "def subsets(values):\n    pass", L4: "" },
    tests: [
    { name: "three", code: "assert {frozenset(s) for s in fn([1,2,3])} == {frozenset(x) for x in [[],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3]]}", hidden: false },
    { name: "count", code: "assert len(fn([1,2,3,4])) == 16", hidden: false },
    { name: "empty", code: "assert fn([]) == [[]]", hidden: false },
    { name: "single", code: "assert {frozenset(s) for s in fn([7])} == {frozenset([]), frozenset([7])}", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Each element is either in a subset or not — a binary choice." },
    { rung: 1, text: "Grow a partial subset; record it, then extend with later elements only." },
    { rung: 2, text: "Use a start index so you never reuse or reorder earlier elements." }
    ],
    walkthrough: ["Why does passing `start` prevent duplicate subsets like [1,2] and [2,1]?", "Why append a COPY path[:] rather than path itself?", "How does the pop() after recursion restore state for the next choice?", "Why are there exactly 2^n subsets?"],
    solution: "def subsets(values):\n    result = []\n    path = []\n    def backtrack(start):\n        result.append(path[:])\n        for index in range(start, len(values)):\n            path.append(values[index])\n            backtrack(index + 1)\n            path.pop()\n    backtrack(0)\n    return result",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["backtracking"],
    analysis: { approach: "DFS choosing each later element in or out, recording every partial path.", invariant: "`path` is the subset chosen along the current root-to-node route.", time: "O(n·2^n)", space: "O(n) recursion" },
  },
  {
    id: "py.lc.combination-sum",
    kind: "problem",
    tier: "challenge",
    title: "Combination Sum",
    pattern: "Backtracking",
    teaches: ["py.backtracking", "py.recursion"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 5, implementation: 4, recall: 4 },
    estimatedMinutes: 26,
    prompt: "Given distinct positive `candidates` and a `target`, return all unique combinations that sum to target. Each candidate may be reused unlimited times. Tests compare as a set of sorted tuples.",
    exportName: "combination_sum",
    scaffolds: { L1: "def combination_sum(candidates, target):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def combination_sum(candidates, target):\n    pass", L3: "def combination_sum(candidates, target):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert {tuple(sorted(c)) for c in fn([2,3,6,7], 7)} == {(7,), (2,2,3)}", hidden: false },
    { name: "multi", code: "assert {tuple(sorted(c)) for c in fn([2,3,5], 8)} == {(3,5),(2,3,3),(2,2,2,2)}", hidden: false },
    { name: "none", code: "assert fn([2], 1) == []", hidden: false },
    { name: "exact single", code: "assert {tuple(sorted(c)) for c in fn([5], 5)} == {(5,)}", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Reduce the target as you spend candidates; success is remaining == 0." },
    { rung: 1, text: "Allow reuse by recursing with the SAME index, not index+1." },
    { rung: 2, text: "Avoid duplicate combinations by never stepping to an earlier index." }
    ],
    walkthrough: ["Why recurse with `index` (not index+1) to permit reuse?", "Why does starting the loop at `start` kill permutation duplicates?", "What does `remaining` represent at any point?", "Why prune the branch when value > remaining?"],
    solution: "def combination_sum(candidates, target):\n    result = []\n    path = []\n    def backtrack(start, remaining):\n        if remaining == 0:\n            result.append(path[:])\n            return\n        for index in range(start, len(candidates)):\n            value = candidates[index]\n            if value <= remaining:\n                path.append(value)\n                backtrack(index, remaining - value)\n                path.pop()\n    backtrack(0, target)\n    return result",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["backtracking"],
    analysis: { approach: "DFS spending candidates (reuse allowed) until the remaining target hits zero.", invariant: "`path` sums to target - remaining and uses only candidates from `start` on.", time: "exponential in target/min(candidate)", space: "O(target/min) recursion" },
  },
  {
    id: "py.lc.permutations",
    kind: "problem",
    tier: "problem",
    title: "Permutations",
    pattern: "Backtracking",
    teaches: ["py.backtracking", "py.recursion"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 4, recall: 3 },
    estimatedMinutes: 22,
    prompt: "Return all permutations of a list `values` of distinct integers. Tests compare as a set of tuples.",
    exportName: "permutations",
    scaffolds: { L1: "def permutations(values):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def permutations(values):\n    pass", L3: "def permutations(values):\n    pass", L4: "" },
    tests: [
    { name: "three", code: "assert {tuple(p) for p in fn([1,2,3])} == {(1,2,3),(1,3,2),(2,1,3),(2,3,1),(3,1,2),(3,2,1)}", hidden: false },
    { name: "count", code: "assert len(fn([1,2,3,4])) == 24", hidden: false },
    { name: "single", code: "assert fn([9]) == [[9]]", hidden: false },
    { name: "two", code: "assert {tuple(p) for p in fn([0,1])} == {(0,1),(1,0)}", hidden: true }
    ],
    hints: [
    { rung: 0, text: "A permutation uses every element exactly once, so order matters." },
    { rung: 1, text: "Track which indices are already placed with a used[] flags array." },
    { rung: 2, text: "At each depth try every unused element, then undo the choice." }
    ],
    walkthrough: ["Why do permutations need a `used` array where subsets used a start index?", "What is the base case that records a complete permutation?", "Why must both path.pop() and used[index]=False run after recursion?", "Why are there n! permutations?"],
    solution: "def permutations(values):\n    result = []\n    path = []\n    used = [False] * len(values)\n    def backtrack():\n        if len(path) == len(values):\n            result.append(path[:])\n            return\n        for index in range(len(values)):\n            if used[index]:\n                continue\n            used[index] = True\n            path.append(values[index])\n            backtrack()\n            path.pop()\n            used[index] = False\n    backtrack()\n    return result",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["backtracking"],
    analysis: { approach: "DFS placing each still-unused element at the next position, undoing on return.", invariant: "`path` is a permutation of the elements currently marked used.", time: "O(n·n!)", space: "O(n) recursion" },
  },
  {
    id: "py.lc.num-islands",
    kind: "problem",
    tier: "problem",
    title: "Number of Islands",
    pattern: "Grid DFS/flood fill",
    teaches: ["py.graphs", "py.grid-dp"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 4, recall: 3 },
    estimatedMinutes: 24,
    prompt: "`grid` is a list of equal-length rows of '1' (land) and '0' (water). Return the number of islands — maximal groups of land connected horizontally or vertically. You may modify `grid`.",
    exportName: "num_islands",
    scaffolds: { L1: "def num_islands(grid):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def num_islands(grid):\n    pass", L3: "def num_islands(grid):\n    pass", L4: "" },
    tests: [
    { name: "one big", code: "assert fn([list('11110'),list('11010'),list('11000'),list('00000')]) == 1", hidden: false },
    { name: "three", code: "assert fn([list('11000'),list('11000'),list('00100'),list('00011')]) == 3", hidden: false },
    { name: "all water", code: "assert fn([list('000'),list('000')]) == 0", hidden: false },
    { name: "empty", code: "assert fn([]) == 0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Each unvisited land cell you meet starts exactly one new island." },
    { rung: 1, text: "Flood-fill from it, sinking all connected land so it is not counted again." },
    { rung: 2, text: "Only the four orthogonal neighbours count as connected." }
    ],
    walkthrough: ["Why does incrementing the count only when you START a fill give the island total?", "Why sink (overwrite) visited land instead of keeping a separate visited set?", "What are the base cases that stop the recursive fill?", "Why do diagonals NOT merge islands here?"],
    solution: "def num_islands(grid):\n    if not grid:\n        return 0\n    rows, cols = len(grid), len(grid[0])\n    def sink(r, c):\n        if r < 0 or c < 0 or r >= rows or c >= cols or grid[r][c] != '1':\n            return\n        grid[r][c] = '0'\n        sink(r + 1, c); sink(r - 1, c); sink(r, c + 1); sink(r, c - 1)\n    count = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == '1':\n                count += 1\n                sink(r, c)\n    return count",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["graphs", "grid"],
    analysis: { approach: "Scan cells; each new land cell is one island — flood-fill to erase it.", invariant: "Every '1' reachable from a counted cell has been turned to '0'.", time: "O(rows·cols)", space: "O(rows·cols) worst-case recursion" },
  },
  {
    id: "py.lc.merge-intervals",
    kind: "problem",
    tier: "problem",
    title: "Merge Intervals",
    pattern: "Sort + sweep",
    teaches: ["py.intervals", "py.sorting"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 20,
    prompt: "Given `intervals` as `[start, end]` pairs, merge every overlapping pair and return the non-overlapping intervals sorted by start.",
    exportName: "merge_intervals",
    scaffolds: { L1: "def merge_intervals(intervals):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def merge_intervals(intervals):\n    pass", L3: "def merge_intervals(intervals):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([[1,3],[2,6],[8,10],[15,18]]) == [[1,6],[8,10],[15,18]]", hidden: false },
    { name: "touching", code: "assert fn([[1,4],[4,5]]) == [[1,5]]", hidden: false },
    { name: "nested", code: "assert fn([[1,10],[2,3],[4,5]]) == [[1,10]]", hidden: false },
    { name: "single", code: "assert fn([[5,7]]) == [[5,7]]", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Overlap is easy to reason about once intervals are sorted by start." },
    { rung: 1, text: "Sweep left to right, extending the last kept interval when the next one overlaps." },
    { rung: 2, text: "Two intervals overlap when the next start is within the current end." }
    ],
    walkthrough: ["Why is sorting by start the enabling first step?", "After sorting, why do you only ever compare against the LAST merged interval?", "Why use max(end, ...) when extending rather than just the new end?", "Do touching intervals like [1,4],[4,5] count as overlapping here?"],
    solution: "def merge_intervals(intervals):\n    order = sorted(intervals, key=lambda pair: pair[0])\n    merged = []\n    for start, end in order:\n        if merged and start <= merged[-1][1]:\n            merged[-1][1] = max(merged[-1][1], end)\n        else:\n            merged.append([start, end])\n    return merged",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["intervals", "sorting"],
    analysis: { approach: "Sort by start; extend the last kept interval whenever the next overlaps it.", invariant: "`merged` holds disjoint intervals covering every interval processed so far.", time: "O(n log n)", space: "O(n)" },
  },
  {
    id: "py.lc.insert-interval",
    kind: "problem",
    tier: "problem",
    title: "Insert Interval",
    pattern: "Interval sweep",
    teaches: ["py.intervals"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 4, recall: 3 },
    estimatedMinutes: 22,
    prompt: "Given non-overlapping `intervals` sorted by start and a `new` interval `[start, end]`, insert it and merge as needed, returning the result still sorted and non-overlapping.",
    exportName: "insert_interval",
    scaffolds: { L1: "def insert_interval(intervals, new):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def insert_interval(intervals, new):\n    pass", L3: "def insert_interval(intervals, new):\n    pass", L4: "" },
    tests: [
    { name: "middle", code: "assert fn([[1,3],[6,9]], [2,5]) == [[1,5],[6,9]]", hidden: false },
    { name: "spanning", code: "assert fn([[1,2],[3,5],[6,7],[8,10],[12,16]], [4,8]) == [[1,2],[3,10],[12,16]]", hidden: false },
    { name: "empty base", code: "assert fn([], [5,7]) == [[5,7]]", hidden: false },
    { name: "append end", code: "assert fn([[1,2]], [3,4]) == [[1,2],[3,4]]", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Three phases: intervals entirely before, intervals that overlap, intervals entirely after." },
    { rung: 1, text: "Copy the strictly-before ones untouched." },
    { rung: 2, text: "Absorb every overlapping interval into a growing merged interval, then append the rest." }
    ],
    walkthrough: ["How do you detect an interval that ends before `new` starts?", "What condition marks an interval as overlapping the growing one?", "Why can the tail be copied verbatim once merging stops?", "Why does sorted, non-overlapping input make the three-phase sweep valid?"],
    solution: "def insert_interval(intervals, new):\n    result = []\n    start, end = new\n    i, n = 0, len(intervals)\n    while i < n and intervals[i][1] < start:\n        result.append(intervals[i]); i += 1\n    while i < n and intervals[i][0] <= end:\n        start = min(start, intervals[i][0])\n        end = max(end, intervals[i][1])\n        i += 1\n    result.append([start, end])\n    while i < n:\n        result.append(intervals[i]); i += 1\n    return result",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["intervals"],
    analysis: { approach: "Emit befores, merge all overlappers into one, emit afters.", invariant: "`result` is sorted and disjoint over everything processed.", time: "O(n)", space: "O(n)" },
  },
  {
    id: "py.lc.max-subarray",
    kind: "problem",
    tier: "problem",
    title: "Maximum Subarray (Kadane)",
    pattern: "Kadane / DP",
    teaches: ["py.dynamic-programming"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 2, recall: 3 },
    estimatedMinutes: 16,
    prompt: "Return the largest sum obtainable from a contiguous non-empty subarray of `values`.",
    exportName: "max_subarray",
    scaffolds: { L1: "def max_subarray(values):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def max_subarray(values):\n    pass", L3: "def max_subarray(values):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([-2,1,-3,4,-1,2,1,-5,4]) == 6", hidden: false },
    { name: "all negative", code: "assert fn([-3,-1,-2]) == -1", hidden: false },
    { name: "all positive", code: "assert fn([1,2,3,4]) == 10", hidden: false },
    { name: "single", code: "assert fn([5]) == 5", hidden: true }
    ],
    hints: [
    { rung: 0, text: "At each index, the best subarray ending here either extends the previous or restarts." },
    { rung: 1, text: "running = max(value, running + value) captures that choice." },
    { rung: 2, text: "Track the best running total ever seen." }
    ],
    walkthrough: ["What are the only two options for the best subarray ENDING at index i?", "Why does `running` reset to `value` when the prefix would only hurt?", "Why must `best` be tracked separately from `running`?", "Why does initializing to values[0] handle the all-negative case?"],
    solution: "def max_subarray(values):\n    best = values[0]\n    running = values[0]\n    for value in values[1:]:\n        running = max(value, running + value)\n        best = max(best, running)\n    return best",
    language: "python",
    tracks: ["faang", "swe", "quant", "ml"],
    skills: ["dp", "arrays", "greedy"],
    analysis: { approach: "Best-ending-here is max(start fresh, extend previous); keep the global best.", invariant: "`running` is the max sum of a subarray ending at the current index.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.lc.jump-game",
    kind: "problem",
    tier: "problem",
    title: "Jump Game",
    pattern: "Greedy reachability",
    teaches: ["py.method"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 2, recall: 3 },
    estimatedMinutes: 16,
    prompt: "Each `nums[i]` is the maximum forward jump from index i. Starting at index 0, return `True` if you can reach the last index.",
    exportName: "can_jump",
    scaffolds: { L1: "def can_jump(nums):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def can_jump(nums):\n    pass", L3: "def can_jump(nums):\n    pass", L4: "" },
    tests: [
    { name: "reachable", code: "assert fn([2,3,1,1,4]) is True", hidden: false },
    { name: "stuck", code: "assert fn([3,2,1,0,4]) is False", hidden: false },
    { name: "single", code: "assert fn([0]) is True", hidden: false },
    { name: "first zero", code: "assert fn([0,1]) is False", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Track the farthest index reachable so far." },
    { rung: 1, text: "If your current index ever exceeds that reach, you are stranded." },
    { rung: 2, text: "Otherwise extend the reach by index + jump." }
    ],
    walkthrough: ["What single number summarizes everything about where you can be?", "What condition proves the last index is unreachable?", "Why is a greedy farthest-reach correct without trying every jump length?", "Why does a lone [0] still succeed?"],
    solution: "def can_jump(nums):\n    reach = 0\n    for index, value in enumerate(nums):\n        if index > reach:\n            return False\n        reach = max(reach, index + value)\n    return True",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["greedy", "arrays"],
    analysis: { approach: "Sweep, keeping the farthest reachable index; fail if the cursor outruns it.", invariant: "`reach` is the farthest index reachable using indices 0..current.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.lc.climb-stairs",
    kind: "problem",
    tier: "problem",
    title: "Climbing Stairs",
    pattern: "1-D DP (Fibonacci)",
    teaches: ["py.dynamic-programming"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 3, implementation: 2, recall: 2 },
    estimatedMinutes: 12,
    prompt: "You climb a staircase of `n` steps, taking 1 or 2 steps at a time. Return the number of distinct ways to reach the top.",
    exportName: "climb_stairs",
    scaffolds: { L1: "def climb_stairs(n):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def climb_stairs(n):\n    pass", L3: "def climb_stairs(n):\n    pass", L4: "" },
    tests: [
    { name: "three", code: "assert fn(3) == 3", hidden: false },
    { name: "five", code: "assert fn(5) == 8", hidden: false },
    { name: "one", code: "assert fn(1) == 1", hidden: false },
    { name: "two", code: "assert fn(2) == 2", hidden: true }
    ],
    hints: [
    { rung: 0, text: "The last move to step n came from step n-1 or n-2." },
    { rung: 1, text: "So ways(n) = ways(n-1) + ways(n-2) — Fibonacci." },
    { rung: 2, text: "Roll two variables forward instead of storing the whole array." }
    ],
    walkthrough: ["Why does ways(n) equal ways(n-1) + ways(n-2)?", "What are the base cases, and why n<=2 returning n is correct?", "How do the two rolling variables replace an O(n) table?", "How would you generalize to steps of size 1, 2, or 3?"],
    solution: "def climb_stairs(n):\n    if n <= 2:\n        return n\n    prev, curr = 1, 2\n    for _ in range(3, n + 1):\n        prev, curr = curr, prev + curr\n    return curr",
    language: "python",
    tracks: ["faang", "swe", "quant", "ml"],
    skills: ["dp"],
    analysis: { approach: "Ways(n)=ways(n-1)+ways(n-2); iterate with two rolling totals.", invariant: "(prev, curr) hold ways to reach the previous two step counts.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.lc.house-robber",
    kind: "problem",
    tier: "problem",
    title: "House Robber",
    pattern: "1-D DP",
    teaches: ["py.dynamic-programming"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 2, recall: 3 },
    estimatedMinutes: 16,
    prompt: "`nums[i]` is money in house i. You cannot rob two adjacent houses. Return the maximum you can rob.",
    exportName: "rob",
    scaffolds: { L1: "def rob(nums):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def rob(nums):\n    pass", L3: "def rob(nums):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([1,2,3,1]) == 4", hidden: false },
    { name: "bigger", code: "assert fn([2,7,9,3,1]) == 12", hidden: false },
    { name: "empty", code: "assert fn([]) == 0", hidden: false },
    { name: "single", code: "assert fn([5]) == 5", hidden: true }
    ],
    hints: [
    { rung: 0, text: "At each house you either rob it (and skip the previous) or skip it." },
    { rung: 1, text: "Carry two totals: best if you skip this house, best if you take it." },
    { rung: 2, text: "Taking this house builds on the 'skip previous' total." }
    ],
    walkthrough: ["What are the two states you track at each house?", "Why does `take` add to the previous `skip`, not the previous `take`?", "Why is the answer max(skip, take) at the end?", "How does this avoid an explicit dp array?"],
    solution: "def rob(nums):\n    skip, take = 0, 0\n    for value in nums:\n        skip, take = max(skip, take), skip + value\n    return max(skip, take)",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["dp"],
    analysis: { approach: "Two rolling optima: best skipping vs best taking the current house.", invariant: "After house i, (skip, take) are the best totals ending with i skipped/robbed.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.lc.coin-change",
    kind: "problem",
    tier: "challenge",
    title: "Coin Change",
    pattern: "Unbounded knapsack DP",
    teaches: ["py.dynamic-programming"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 5, implementation: 3, recall: 4 },
    estimatedMinutes: 26,
    prompt: "Given coin denominations `coins` and an `amount`, return the fewest coins that sum to amount, or -1 if it cannot be made. Each coin is unlimited.",
    exportName: "coin_change",
    scaffolds: { L1: "def coin_change(coins, amount):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def coin_change(coins, amount):\n    pass", L3: "def coin_change(coins, amount):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([1,2,5], 11) == 3", hidden: false },
    { name: "impossible", code: "assert fn([2], 3) == -1", hidden: false },
    { name: "zero", code: "assert fn([1], 0) == 0", hidden: false },
    { name: "exact coin", code: "assert fn([2,5,10,1], 27) == 4", hidden: true }
    ],
    hints: [
    { rung: 0, text: "best[a] = fewest coins to make amount a." },
    { rung: 1, text: "To make a, try each coin c and reuse best[a-c] plus one coin." },
    { rung: 2, text: "Build best[] from 0 upward; INF marks 'not yet makeable'." }
    ],
    walkthrough: ["What does best[a] mean and what is best[0]?", "Why iterate amounts outward and try every coin at each?", "Why can the same coin be reused freely in this recurrence?", "How is 'impossible' represented and detected?"],
    solution: "def coin_change(coins, amount):\n    INF = amount + 1\n    best = [0] + [INF] * amount\n    for value in range(1, amount + 1):\n        for coin in coins:\n            if coin <= value:\n                best[value] = min(best[value], best[value - coin] + 1)\n    return best[amount] if best[amount] != INF else -1",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["dp"],
    analysis: { approach: "Bottom-up table: best[a]=min over coins of best[a-coin]+1.", invariant: "best[a] is the minimum coins for amount a using all denominations.", time: "O(amount·len(coins))", space: "O(amount)" },
  },
  {
    id: "py.lc.lis",
    kind: "problem",
    tier: "challenge",
    title: "Longest Increasing Subsequence",
    pattern: "Patience / binary search DP",
    teaches: ["py.dynamic-programming", "py.binary-search"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 5, implementation: 4, recall: 4 },
    estimatedMinutes: 30,
    prompt: "Return the length of the longest strictly increasing subsequence of `values`. Aim for O(n log n).",
    exportName: "length_of_lis",
    scaffolds: { L1: "import bisect\n\ndef length_of_lis(values):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "import bisect\n\ndef length_of_lis(values):\n    pass", L3: "import bisect\n\ndef length_of_lis(values):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([10,9,2,5,3,7,101,18]) == 4", hidden: false },
    { name: "increasing", code: "assert fn([1,2,3,4]) == 4", hidden: false },
    { name: "all equal", code: "assert fn([5,5,5]) == 1", hidden: false },
    { name: "empty", code: "assert fn([]) == 0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Keep `tails[k]` = smallest possible tail of an increasing subsequence of length k+1." },
    { rung: 1, text: "For each value, replace the first tail >= it, or append if it beats all tails." },
    { rung: 2, text: "The answer is the length of `tails`, though its contents are not a real subsequence." }
    ],
    walkthrough: ["What exactly does tails[k] store, and why smallest?", "Why does bisect_left give the position to overwrite or extend?", "Why does keeping tails minimal never reduce the achievable length?", "Why is the O(n^2) dp[i] version correct but slower?"],
    solution: "import bisect\n\ndef length_of_lis(values):\n    tails = []\n    for value in values:\n        index = bisect.bisect_left(tails, value)\n        if index == len(tails):\n            tails.append(value)\n        else:\n            tails[index] = value\n    return len(tails)",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["dp", "binary-search"],
    analysis: { approach: "Maintain minimal tails of each achievable length; binary-search each insert.", invariant: "tails[k] is the smallest tail among increasing subsequences of length k+1.", time: "O(n log n)", space: "O(n)" },
  },
  {
    id: "py.lc.unique-paths",
    kind: "problem",
    tier: "problem",
    title: "Unique Paths",
    pattern: "Grid DP",
    teaches: ["py.grid-dp", "py.dynamic-programming"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 18,
    prompt: "A robot at the top-left of an `m` x `n` grid moves only right or down to the bottom-right. Return the number of distinct paths.",
    exportName: "unique_paths",
    scaffolds: { L1: "def unique_paths(m, n):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def unique_paths(m, n):\n    pass", L3: "def unique_paths(m, n):\n    pass", L4: "" },
    tests: [
    { name: "3x7", code: "assert fn(3, 7) == 28", hidden: false },
    { name: "3x2", code: "assert fn(3, 2) == 3", hidden: false },
    { name: "1xn", code: "assert fn(1, 5) == 1", hidden: false },
    { name: "square", code: "assert fn(3, 3) == 6", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Paths to a cell = paths from above + paths from the left." },
    { rung: 1, text: "The top row and left column each have exactly one path." },
    { rung: 2, text: "One rolling row suffices since you only need the row above." }
    ],
    walkthrough: ["Why is paths(cell) = paths(up) + paths(left)?", "Why do the first row and column initialize to 1?", "How does the single `row` array encode both 'above' and 'left'?", "What closed-form binomial also answers this, and why?"],
    solution: "def unique_paths(m, n):\n    row = [1] * n\n    for _ in range(1, m):\n        for c in range(1, n):\n            row[c] += row[c - 1]\n    return row[n - 1]",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["dp", "grid"],
    analysis: { approach: "DP where each cell sums the cell above and to the left; roll one row.", invariant: "Before updating column c, row[c] is 'above' and row[c-1] is 'left'.", time: "O(m·n)", space: "O(n)" },
  },
  {
    id: "py.lc.lcs",
    kind: "problem",
    tier: "challenge",
    title: "Longest Common Subsequence",
    pattern: "2-D DP",
    teaches: ["py.dynamic-programming"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 5, implementation: 4, recall: 4 },
    estimatedMinutes: 28,
    prompt: "Return the length of the longest subsequence common to strings `a` and `b` (characters in order, not necessarily contiguous).",
    exportName: "longest_common_subsequence",
    scaffolds: { L1: "def longest_common_subsequence(a, b):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def longest_common_subsequence(a, b):\n    pass", L3: "def longest_common_subsequence(a, b):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn('abcde','ace') == 3", hidden: false },
    { name: "none", code: "assert fn('abc','def') == 0", hidden: false },
    { name: "equal", code: "assert fn('abc','abc') == 3", hidden: false },
    { name: "empty", code: "assert fn('','abc') == 0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Compare prefixes: dp[i][j] is the LCS of a[:i] and b[:j]." },
    { rung: 1, text: "On a matching character, extend the diagonal dp[i-1][j-1] by one." },
    { rung: 2, text: "Otherwise take the better of dropping one character from either string." }
    ],
    walkthrough: ["What does dp[i][j] mean in terms of prefixes?", "Why does a character match use the DIAGONAL cell plus one?", "Why does a mismatch take max of the top and left cells?", "How do the two rolling rows replace the full 2-D table?"],
    solution: "def longest_common_subsequence(a, b):\n    prev = [0] * (len(b) + 1)\n    for ca in a:\n        curr = [0] * (len(b) + 1)\n        for j, cb in enumerate(b, 1):\n            if ca == cb:\n                curr[j] = prev[j - 1] + 1\n            else:\n                curr[j] = max(prev[j], curr[j - 1])\n        prev = curr\n    return prev[len(b)]",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["dp", "strings"],
    analysis: { approach: "Prefix DP: match extends the diagonal, mismatch keeps the better neighbor.", invariant: "curr[j] is the LCS length of the current a-prefix with b[:j].", time: "O(len(a)·len(b))", space: "O(len(b))" },
  },
  {
    id: "py.lc.single-number",
    kind: "problem",
    tier: "problem",
    title: "Single Number",
    pattern: "XOR",
    teaches: ["py.numbers"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 3, implementation: 1, recall: 3 },
    estimatedMinutes: 10,
    prompt: "Every value in `values` appears twice except one that appears once. Return that single value in O(n) time and O(1) space.",
    exportName: "single_number",
    scaffolds: { L1: "def single_number(values):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def single_number(values):\n    pass", L3: "def single_number(values):\n    pass", L4: "" },
    tests: [
    { name: "classic", code: "assert fn([2,2,1]) == 1", hidden: false },
    { name: "longer", code: "assert fn([4,1,2,1,2]) == 4", hidden: false },
    { name: "single", code: "assert fn([7]) == 7", hidden: false },
    { name: "negatives", code: "assert fn([-1,-1,5]) == 5", hidden: true }
    ],
    hints: [
    { rung: 0, text: "XOR of a number with itself is 0, and with 0 is itself." },
    { rung: 1, text: "XOR is commutative, so pairs cancel regardless of order." },
    { rung: 2, text: "Fold XOR across everything; only the lonely value survives." }
    ],
    walkthrough: ["What are the two identities x^x=0 and x^0=x buying you?", "Why does order not matter when folding XOR?", "Why do all the paired values vanish?", "How does this beat a hash set on space?"],
    solution: "def single_number(values):\n    result = 0\n    for value in values:\n        result ^= value\n    return result",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["bit-manipulation"],
    analysis: { approach: "XOR every value; identical pairs cancel, leaving the unique one.", invariant: "`result` is the XOR of all values seen so far.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.lc.count-bits",
    kind: "problem",
    tier: "problem",
    title: "Counting Bits",
    pattern: "DP on bits",
    teaches: ["py.dynamic-programming", "py.numbers"],
    requires: ["py.method", "py.complexity"],
    difficulty: { concept: 4, implementation: 2, recall: 3 },
    estimatedMinutes: 16,
    prompt: "Return a list `answer` of length `n+1` where `answer[i]` is the number of set bits in the binary representation of `i`.",
    exportName: "count_bits",
    scaffolds: { L1: "def count_bits(n):\n    pass\n\n# Plan the brute force, its wasted work, and the loop invariant before coding.", L2: "def count_bits(n):\n    pass", L3: "def count_bits(n):\n    pass", L4: "" },
    tests: [
    { name: "to five", code: "assert fn(5) == [0,1,1,2,1,2]", hidden: false },
    { name: "to two", code: "assert fn(2) == [0,1,1]", hidden: false },
    { name: "zero", code: "assert fn(0) == [0]", hidden: false },
    { name: "to eight", code: "assert fn(8) == [0,1,1,2,1,2,2,3,1]", hidden: true }
    ],
    hints: [
    { rung: 0, text: "The bit count of i relates to the bit count of i without its lowest bit." },
    { rung: 1, text: "i >> 1 drops the last bit; i & 1 is whether that bit was set." },
    { rung: 2, text: "So answer[i] = answer[i>>1] + (i&1)." }
    ],
    walkthrough: ["How does i relate to i>>1 in binary?", "What does i & 1 tell you?", "Why is answer[i>>1] already computed when you need it?", "Why is this O(n) versus O(n log n) for popcount-per-number?"],
    solution: "def count_bits(n):\n    answer = [0] * (n + 1)\n    for value in range(1, n + 1):\n        answer[value] = answer[value >> 1] + (value & 1)\n    return answer",
    language: "python",
    tracks: ["faang", "swe", "quant"],
    skills: ["bit-manipulation", "dp"],
    analysis: { approach: "answer[i] = answer[i>>1] + (i&1), reusing the already-filled smaller value.", invariant: "answer[k] holds the exact popcount of k for every k < i.", time: "O(n)", space: "O(n)" },
  },
];
