import type { Lesson, Problem } from "../../types";

/**
 * Practice for the Algo and ML mastery lectures — GENERATED by
 * scratchpad/build_mastery_exercises.py, where every solution is executed
 * against its own tests in CPython before this file is written.
 *
 * Each exercise belongs to exactly one lecture and drills that lecture's
 * specific takeaway, so a lesson reads: watch, then do. Do not hand-edit.
 */
export const MASTERY_EXERCISES: Problem[] = [
  {
    id: "py.ex.ac.m1_1.l1",
    kind: "problem",
    tier: "rep",
    lesson: "py.ac.m1_1.l1",
    title: "The linear duplicate check",
    teaches: ["py.algo.scale"],
    requires: [],
    difficulty: { concept: 2, implementation: 2, recall: 2 },
    estimatedMinutes: 8,
    prompt: "The lecture compared two correct duplicate checks: a pair scan whose work grows quadratically, and a one-pass version that remembers what it has seen.\n\nWrite the **one-pass** version. Return `True` if any value appears twice in `values`, otherwise `False`.\n\nA hidden test feeds in 20,000 distinct values. The pair-scan version would need about 200 million comparisons there; the one-pass version needs 20,000.",
    exportName: "has_duplicate",
    scaffolds: { L1: "def has_duplicate(values):\n    pass", L2: "def has_duplicate(values):\n    pass", L3: "def has_duplicate(values):\n    pass", L4: "" },
    tests: [
      { name: "finds a duplicate", code: "assert fn([4, 1, 7, 4]) is True", hidden: false },
      { name: "all distinct", code: "assert fn([4, 1, 7, 9]) is False", hidden: false },
      { name: "empty list", code: "assert fn([]) is False", hidden: false },
      { name: "adjacent repeat", code: "assert fn([2, 2]) is True", hidden: false },
      { name: "stays fast on 20,000 values", code: "assert fn(list(range(20000))) is False", hidden: true }
    ],
    hints: [
      { rung: 0, text: "You should only need to look at each value once." },
      { rung: 1, text: "Remember every value you have already passed, then ask whether the current value is among them." },
      { rung: 2, text: "A set answers membership in expected constant time: check `value in seen` before adding it." }
    ],
    solution: "def has_duplicate(values):\n    seen = set()\n    for value in values:\n        if value in seen:\n            return True\n        seen.add(value)\n    return False",
    language: "python",
  },
  {
    id: "py.ex.ac.m1_1.l2",
    kind: "problem",
    tier: "rep",
    lesson: "py.ac.m1_1.l2",
    title: "Count the work exactly",
    teaches: ["py.algo.operation-count"],
    requires: [],
    difficulty: { concept: 3, implementation: 2, recall: 3 },
    estimatedMinutes: 10,
    prompt: "The lecture's counting rules: consecutive regions **add**, truly nested ranges **multiply**.\n\nA routine does two things for a list of length `n`:\n\n1. one pass that touches each element once, then\n2. a nested pass comparing every element with every element to its right.\n\nReturn the exact total number of steps as a function of `n` — not the Big-O class, the real count. For `n = 4` that is `4 + 6 = 10`.",
    exportName: "count_steps",
    scaffolds: { L1: "def count_steps(n):\n    pass", L2: "def count_steps(n):\n    pass", L3: "def count_steps(n):\n    pass", L4: "" },
    tests: [
      { name: "four elements", code: "assert fn(4) == 10", hidden: false },
      { name: "one element", code: "assert fn(1) == 1", hidden: false },
      { name: "empty input", code: "assert fn(0) == 0", hidden: false },
      { name: "ten elements", code: "assert fn(10) == 55", hidden: false },
      { name: "large n stays exact", code: "assert fn(1000) == 500500", hidden: true }
    ],
    hints: [
      { rung: 0, text: "Work out each region separately, then add them." },
      { rung: 1, text: "The single pass is n steps. How many ordered pairs (left, right) with right strictly after left exist?" },
      { rung: 2, text: "The nested region counts each unordered pair once: n*(n-1)//2. Add the n from the first pass." }
    ],
    solution: "def count_steps(n):\n    return n + n * (n - 1) // 2",
    language: "python",
  },
  {
    id: "py.ex.ac.m1_1.l3",
    kind: "problem",
    tier: "rep",
    lesson: "py.ac.m1_1.l3",
    title: "Simplify to the dominant growth",
    teaches: ["py.algo.asymptotics"],
    requires: [],
    difficulty: { concept: 3, implementation: 3, recall: 3 },
    estimatedMinutes: 10,
    prompt: "Asymptotic notation keeps only the fastest-growing term and drops its constant.\n\nYou are given `terms`, a list of `(coefficient, exponent)` pairs describing a step count. `[(3, 2), (5, 1), (9, 0)]` means `3n^2 + 5n + 9`.\n\nReturn the **exponent of the dominant term** — the largest exponent whose coefficient is not zero. Terms with coefficient `0` contribute nothing. If every coefficient is zero, return `0`.",
    exportName: "dominant_exponent",
    scaffolds: { L1: "def dominant_exponent(terms):\n    pass", L2: "def dominant_exponent(terms):\n    pass", L3: "def dominant_exponent(terms):\n    pass", L4: "" },
    tests: [
      { name: "quadratic dominates", code: "assert fn([(3, 2), (5, 1), (9, 0)]) == 2", hidden: false },
      { name: "zero coefficient is ignored", code: "assert fn([(0, 3), (7, 1)]) == 1", hidden: false },
      { name: "all zero", code: "assert fn([(0, 2), (0, 1)]) == 0", hidden: false },
      { name: "constant only", code: "assert fn([(12, 0)]) == 0", hidden: false },
      { name: "unordered input", code: "assert fn([(1, 1), (2, 4), (6, 2)]) == 4", hidden: true }
    ],
    hints: [
      { rung: 0, text: "A term with coefficient zero is not part of the function at all." },
      { rung: 1, text: "Among the surviving terms, which exponent grows fastest?" },
      { rung: 2, text: "Filter out zero-coefficient terms, then take the maximum exponent — guarding the empty case." }
    ],
    solution: "def dominant_exponent(terms):\n    live = [exponent for coefficient, exponent in terms if coefficient != 0]\n    if not live:\n        return 0\n    return max(live)",
    language: "python",
  },
  {
    id: "py.ex.ac.m1_1.l4",
    kind: "problem",
    tier: "rep",
    lesson: "py.ac.m1_1.l4",
    title: "Halving the search space",
    teaches: ["py.algo.growth-classes"],
    requires: [],
    difficulty: { concept: 3, implementation: 2, recall: 3 },
    estimatedMinutes: 10,
    prompt: "The lecture separated growth classes by what each algorithm does to the input: a scan preserves it, binary search **shrinks** it.\n\nReturn how many probes binary search makes in the worst case on a sorted list of length `n` — that is, how many times you can halve `n` before nothing is left.\n\n`n = 1` needs 1 probe, `n = 8` needs 4, and `n = 0` needs 0.",
    exportName: "binary_search_probes",
    scaffolds: { L1: "def binary_search_probes(n):\n    pass", L2: "def binary_search_probes(n):\n    pass", L3: "def binary_search_probes(n):\n    pass", L4: "" },
    tests: [
      { name: "empty range", code: "assert fn(0) == 0", hidden: false },
      { name: "single element", code: "assert fn(1) == 1", hidden: false },
      { name: "eight elements", code: "assert fn(8) == 4", hidden: false },
      { name: "thousand elements", code: "assert fn(1000) == 10", hidden: false },
      { name: "million elements", code: "assert fn(1000000) == 20", hidden: true }
    ],
    hints: [
      { rung: 0, text: "Each probe discards half of what is left." },
      { rung: 1, text: "Count how many times you can integer-divide n by 2 before reaching zero." },
      { rung: 2, text: "Loop while n > 0: add one probe and set n = n // 2." }
    ],
    solution: "def binary_search_probes(n):\n    probes = 0\n    while n > 0:\n        probes += 1\n        n //= 2\n    return probes",
    language: "python",
  },
  {
    id: "py.ex.ac.m1_1.l5",
    kind: "problem",
    tier: "rep",
    lesson: "py.ac.m1_1.l5",
    title: "Find the crossover point",
    teaches: ["py.algo.dominant-growth"],
    requires: [],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 12,
    prompt: "Constants are dropped when comparing growth, but the lecture kept them for one job: finding the **crossover** — the size where the asymptotically better algorithm actually wins.\n\nAlgorithm A costs `a * n * n` steps. Algorithm B costs `b * n` steps. B has the better growth, but a large `b` can make it slower for small `n`.\n\nReturn the smallest positive integer `n` where A costs **strictly more** than B. For `a = 1, b = 10` that is `11`.",
    exportName: "crossover",
    scaffolds: { L1: "def crossover(a, b):\n    pass", L2: "def crossover(a, b):\n    pass", L3: "def crossover(a, b):\n    pass", L4: "" },
    tests: [
      { name: "b is ten times a", code: "assert fn(1, 10) == 11", hidden: false },
      { name: "equal constants", code: "assert fn(1, 1) == 2", hidden: false },
      { name: "quadratic already loses", code: "assert fn(5, 1) == 1", hidden: false },
      { name: "large linear constant", code: "assert fn(2, 100) == 51", hidden: false },
      { name: "crossover is strict", code: "assert fn(1, 3) == 4", hidden: true }
    ],
    hints: [
      { rung: 0, text: "You are looking for the first n where the quadratic cost overtakes the linear cost." },
      { rung: 1, text: "Start at n = 1 and step upward while A is still cheaper than or equal to B." },
      { rung: 2, text: "Loop while `a*n*n <= b*n`, incrementing n; return n when the loop ends." }
    ],
    solution: "def crossover(a, b):\n    n = 1\n    while a * n * n <= b * n:\n        n += 1\n    return n",
    language: "python",
  },
  {
    id: "py.ex.ac.m1_1.l6",
    kind: "problem",
    tier: "rep",
    lesson: "py.ac.m1_1.l6",
    title: "Reverse with constant auxiliary space",
    teaches: ["py.algo.space-cost"],
    requires: [],
    difficulty: { concept: 3, implementation: 3, recall: 3 },
    estimatedMinutes: 10,
    prompt: "The lecture separated **auxiliary** space (temporary working memory) from the space the output itself must occupy.\n\nReverse `values` in place and return the same list object. You may use only a constant amount of auxiliary space — no slicing into a new list, no `reversed()` copy, no second list.\n\nA test checks `fn(data) is data`, so returning a new list will fail.",
    exportName: "reverse_in_place",
    scaffolds: { L1: "def reverse_in_place(values):\n    pass", L2: "def reverse_in_place(values):\n    pass", L3: "def reverse_in_place(values):\n    pass", L4: "" },
    tests: [
      { name: "reverses the values", code: "assert fn([1, 2, 3, 4]) == [4, 3, 2, 1]", hidden: false },
      { name: "returns the same object", code: "data = [1, 2, 3]\nassert fn(data) is data", hidden: false },
      { name: "mutates the caller's list", code: "data = [1, 2, 3]\nfn(data)\nassert data == [3, 2, 1]", hidden: false },
      { name: "empty and single", code: "assert fn([]) == [] and fn([7]) == [7]", hidden: false },
      { name: "odd length keeps the middle", code: "assert fn([1, 2, 3, 4, 5]) == [5, 4, 3, 2, 1]", hidden: true }
    ],
    hints: [
      { rung: 0, text: "Walk two indices toward each other from both ends." },
      { rung: 1, text: "Swap the pair at those indices, then step both inward." },
      { rung: 2, text: "`values[left], values[right] = values[right], values[left]` swaps without a temporary list." }
    ],
    solution: "def reverse_in_place(values):\n    left, right = 0, len(values) - 1\n    while left < right:\n        values[left], values[right] = values[right], values[left]\n        left += 1\n        right -= 1\n    return values",
    language: "python",
  },
  {
    id: "py.ex.ac.m1_1.l7",
    kind: "problem",
    tier: "rep",
    lesson: "py.ac.m1_1.l7",
    title: "The true cost of growing an array",
    teaches: ["py.algo.amortized-cost"],
    requires: [],
    difficulty: { concept: 4, implementation: 3, recall: 4 },
    estimatedMinutes: 12,
    prompt: "A dynamic array appends in amortized O(1): most appends are cheap, and the rare resize that copies everything is paid for by the cheap appends around it.\n\nSimulate it. The array starts with capacity 1. Appending into a full array first doubles the capacity, copying every element already stored.\n\nReturn the **total number of element copies** performed while appending `n` items. For `n = 5` the copies happen at sizes 1, 2 and 4, giving `1 + 2 + 4 = 7`.",
    exportName: "total_copy_cost",
    scaffolds: { L1: "def total_copy_cost(n):\n    pass", L2: "def total_copy_cost(n):\n    pass", L3: "def total_copy_cost(n):\n    pass", L4: "" },
    tests: [
      { name: "five appends", code: "assert fn(5) == 7", hidden: false },
      { name: "no appends", code: "assert fn(0) == 0", hidden: false },
      { name: "first append is free", code: "assert fn(1) == 0", hidden: false },
      { name: "power of two boundary", code: "assert fn(8) == 7", hidden: false },
      { name: "total copies stay linear", code: "assert fn(1000) == 1023 and fn(1000) < 2 * 1000", hidden: true }
    ],
    hints: [
      { rung: 0, text: "Track three things: current capacity, current size, and copies so far." },
      { rung: 1, text: "A resize happens only when the array is already full — and it copies exactly `size` elements." },
      { rung: 2, text: "On resize add `size` to the total, then double the capacity before storing the new item." }
    ],
    solution: "def total_copy_cost(n):\n    if n <= 0:\n        return 0\n    capacity = 1\n    size = 0\n    copies = 0\n    for _ in range(n):\n        if size == capacity:\n            copies += size\n            capacity *= 2\n        size += 1\n    return copies",
    language: "python",
  },
  {
    id: "py.ex.ac.m1_1.l8",
    kind: "problem",
    tier: "rep",
    lesson: "py.ac.m1_1.l8",
    title: "Best case, worst case, same function",
    teaches: ["py.algo.analysis-cases"],
    requires: [],
    difficulty: { concept: 3, implementation: 2, recall: 3 },
    estimatedMinutes: 10,
    prompt: "Best, worst, and expected case are claims about **which input** you are analyzing, not about different algorithms.\n\nReturn how many comparisons a left-to-right linear search performs on `values` looking for `target`: one comparison per element inspected, stopping as soon as it matches.\n\nA hit at the front is the best case (1). An absent target is the worst case (`len(values)`).",
    exportName: "search_comparisons",
    scaffolds: { L1: "def search_comparisons(values, target):\n    pass", L2: "def search_comparisons(values, target):\n    pass", L3: "def search_comparisons(values, target):\n    pass", L4: "" },
    tests: [
      { name: "best case is one", code: "assert fn([5, 6, 7], 5) == 1", hidden: false },
      { name: "worst case scans all", code: "assert fn([5, 6, 7], 9) == 3", hidden: false },
      { name: "middle hit", code: "assert fn([5, 6, 7], 6) == 2", hidden: false },
      { name: "empty list", code: "assert fn([], 1) == 0", hidden: false },
      { name: "stops at the first match", code: "assert fn([4, 4, 4], 4) == 1", hidden: true }
    ],
    hints: [
      { rung: 0, text: "Count every element you look at, including the one that matches." },
      { rung: 1, text: "Return as soon as the target is found — the count so far is the answer." },
      { rung: 2, text: "If the loop finishes without a match you inspected every element, so return that count." }
    ],
    solution: "def search_comparisons(values, target):\n    comparisons = 0\n    for value in values:\n        comparisons += 1\n        if value == target:\n            return comparisons\n    return comparisons",
    language: "python",
  },
];

export const MASTERY_EXERCISE_LESSON_CONTENT: Record<string, Pick<Lesson, "repIds">> = {
  "py.ac.m1_1.l1": { repIds: ["py.ex.ac.m1_1.l1"] },
  "py.ac.m1_1.l2": { repIds: ["py.ex.ac.m1_1.l2"] },
  "py.ac.m1_1.l3": { repIds: ["py.ex.ac.m1_1.l3"] },
  "py.ac.m1_1.l4": { repIds: ["py.ex.ac.m1_1.l4"] },
  "py.ac.m1_1.l5": { repIds: ["py.ex.ac.m1_1.l5"] },
  "py.ac.m1_1.l6": { repIds: ["py.ex.ac.m1_1.l6"] },
  "py.ac.m1_1.l7": { repIds: ["py.ex.ac.m1_1.l7"] },
  "py.ac.m1_1.l8": { repIds: ["py.ex.ac.m1_1.l8"] },
};
