import type { Problem } from "../../types";

/**
 * ML track: implement-from-scratch coding exercises. GENERATED — source of
 * truth is scratchpad/build_ml.py, where every pure-Python solution is verified
 * against its tests in CPython before this file is written. Do not hand-edit.
 *
 * 25 problems: linear algebra, calculus, optimization, statistics,
 * probability, regression, kNN, k-means, decision trees, metrics, and a small
 * neural network with softmax, cross-entropy and backprop.
 */
export const PYTHON_ML_PROBLEMS: Problem[] = [
  {
    id: "py.ml.dot-product",
    kind: "problem",
    tier: "problem",
    title: "Dot Product",
    pattern: "Vectors",
    teaches: ["py.ml.vectors"],
    requires: ["py.functions"],
    difficulty: { concept: 3, implementation: 1, recall: 2 },
    estimatedMinutes: 10,
    prompt: "Return the dot product of two equal-length numeric vectors `a` and `b`: the sum of `a[i]*b[i]`. The dot product is the workhorse of ML — every neuron computes one.",
    exportName: "dot_product",
    scaffolds: { L1: "def dot_product(a, b):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def dot_product(a, b):\n    pass", L3: "def dot_product(a, b):\n    pass", L4: "" },
    tests: [
    { name: "basic", code: "assert fn([1,2,3],[4,5,6]) == 32", hidden: false },
    { name: "orthogonal", code: "assert fn([1,0],[0,1]) == 0", hidden: false },
    { name: "empty", code: "assert fn([],[]) == 0", hidden: false },
    { name: "negatives", code: "assert fn([-1,2],[3,-4]) == -11", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Pair up matching positions with zip." },
    { rung: 1, text: "Multiply each pair and add the products." },
    { rung: 2, text: "An empty vector has dot product 0." }
    ],
    walkthrough: ["What does zip(a,b) give you here?", "Why is the dot product of perpendicular axis vectors zero?", "Geometrically, what does a·b measure about the two vectors?", "Why is this the core of a linear layer?"],
    solution: "def dot_product(a, b):\n    return sum(x * y for x, y in zip(a, b))",
    language: "python",
    tracks: ["ml"],
    skills: ["linear-algebra"],
    analysis: { approach: "Sum of elementwise products via zip.", invariant: "The running sum equals the dot product of the prefixes seen so far.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.ml.vector-norm",
    kind: "problem",
    tier: "problem",
    title: "Vector Norm (L2)",
    pattern: "Vectors",
    teaches: ["py.ml.vectors"],
    requires: ["py.functions"],
    difficulty: { concept: 3, implementation: 1, recall: 2 },
    estimatedMinutes: 10,
    prompt: "Return the Euclidean (L2) length of vector `v`: sqrt(sum of squares). This is the distance from the origin, and the basis of most distance and regularization terms.",
    exportName: "vector_norm",
    scaffolds: { L1: "import math\n\ndef vector_norm(v):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "import math\n\ndef vector_norm(v):\n    pass", L3: "import math\n\ndef vector_norm(v):\n    pass", L4: "" },
    tests: [
    { name: "three-four-five", code: "assert abs(fn([3,4]) - 5.0) < 1e-9", hidden: false },
    { name: "zero", code: "assert fn([0,0,0]) == 0.0", hidden: false },
    { name: "unit", code: "assert abs(fn([1,0,0]) - 1.0) < 1e-9", hidden: false },
    { name: "negatives", code: "assert abs(fn([-3,-4]) - 5.0) < 1e-9", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Square every component." },
    { rung: 1, text: "Sum the squares." },
    { rung: 2, text: "Take the square root of that sum." }
    ],
    walkthrough: ["Why square before summing rather than taking absolute values?", "What is the norm of the zero vector?", "How does the L2 norm relate to the dot product of v with itself?", "Where does this appear in L2 regularization?"],
    solution: "import math\n\ndef vector_norm(v):\n    return math.sqrt(sum(x * x for x in v))",
    language: "python",
    tracks: ["ml"],
    skills: ["linear-algebra"],
    analysis: { approach: "Square, sum, square-root.", invariant: "sum accumulates the squared length of the prefix of v.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.ml.transpose",
    kind: "problem",
    tier: "problem",
    title: "Matrix Transpose",
    pattern: "Matrices",
    teaches: ["py.ml.matrices"],
    requires: ["py.functions"],
    difficulty: { concept: 3, implementation: 2, recall: 2 },
    estimatedMinutes: 12,
    prompt: "Return the transpose of `matrix` (a list of equal-length rows): the matrix whose row i is the original column i. Return `[]` for an empty matrix.",
    exportName: "transpose",
    scaffolds: { L1: "def transpose(matrix):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def transpose(matrix):\n    pass", L3: "def transpose(matrix):\n    pass", L4: "" },
    tests: [
    { name: "rect", code: "assert fn([[1,2,3],[4,5,6]]) == [[1,4],[2,5],[3,6]]", hidden: false },
    { name: "square", code: "assert fn([[1,2],[3,4]]) == [[1,3],[2,4]]", hidden: false },
    { name: "empty", code: "assert fn([]) == []", hidden: false },
    { name: "single row", code: "assert fn([[1,2,3]]) == [[1],[2],[3]]", hidden: true }
    ],
    hints: [
    { rung: 0, text: "The result has as many rows as the input has columns." },
    { rung: 1, text: "Result cell [i][j] is input cell [j][i]." },
    { rung: 2, text: "Loop columns on the outside, rows on the inside." }
    ],
    walkthrough: ["How do the dimensions swap under transpose?", "What does result[i][j] equal in terms of the input?", "Why guard the empty matrix separately?", "Why is transpose its own inverse?"],
    solution: "def transpose(matrix):\n    if not matrix:\n        return []\n    return [[row[i] for row in matrix] for i in range(len(matrix[0]))]",
    language: "python",
    tracks: ["ml"],
    skills: ["linear-algebra"],
    analysis: { approach: "For each original column index, collect that column as a new row.", invariant: "result[i] is the i-th column of the input.", time: "O(rows·cols)", space: "O(rows·cols)" },
  },
  {
    id: "py.ml.matmul",
    kind: "problem",
    tier: "problem",
    title: "Matrix Multiplication",
    pattern: "Matrices",
    teaches: ["py.ml.matrices"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 18,
    prompt: "Multiply matrices `A` (m×k) and `B` (k×n), returning the m×n product where result[i][j] = sum over t of A[i][t]*B[t][j]. This is a forward pass through a linear layer, batched.",
    exportName: "matmul",
    scaffolds: { L1: "def matmul(A, B):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def matmul(A, B):\n    pass", L3: "def matmul(A, B):\n    pass", L4: "" },
    tests: [
    { name: "2x2", code: "assert fn([[1,2],[3,4]],[[5,6],[7,8]]) == [[19,22],[43,50]]", hidden: false },
    { name: "identity", code: "assert fn([[1,2],[3,4]],[[1,0],[0,1]]) == [[1,2],[3,4]]", hidden: false },
    { name: "rect", code: "assert fn([[1,2,3]],[[1],[0],[1]]) == [[4]]", hidden: false },
    { name: "zeros", code: "assert fn([[0,0]],[[1],[1]]) == [[0]]", hidden: true }
    ],
    hints: [
    { rung: 0, text: "result[i][j] pairs row i of A with column j of B." },
    { rung: 1, text: "That pairing is a dot product." },
    { rung: 2, text: "Three nested loops: output row, output column, shared inner dimension." }
    ],
    walkthrough: ["Which dimension of A must match which dimension of B?", "What is result[i][j] as a dot product?", "Why does the identity matrix leave A unchanged?", "Why is naive matmul O(m·n·k)?"],
    solution: "def matmul(A, B):\n    rows, inner, cols = len(A), len(B), len(B[0])\n    result = [[0] * cols for _ in range(rows)]\n    for i in range(rows):\n        for j in range(cols):\n            total = 0\n            for t in range(inner):\n                total += A[i][t] * B[t][j]\n            result[i][j] = total\n    return result",
    language: "python",
    tracks: ["ml"],
    skills: ["linear-algebra"],
    analysis: { approach: "Each output cell is the dot product of an A-row and a B-column.", invariant: "result[i][j] holds the completed dot product of A row i and B column j.", time: "O(m·n·k)", space: "O(m·n)" },
  },
  {
    id: "py.ml.matvec",
    kind: "problem",
    tier: "problem",
    title: "Matrix-Vector Product",
    pattern: "Matrices",
    teaches: ["py.ml.matrices"],
    requires: ["py.functions"],
    difficulty: { concept: 3, implementation: 2, recall: 2 },
    estimatedMinutes: 12,
    prompt: "Return the product of matrix `M` (m×n) and column vector `v` (length n): a length-m vector whose i-th entry is the dot product of row i with v. This is exactly what one dense layer computes before adding a bias.",
    exportName: "matvec",
    scaffolds: { L1: "def matvec(M, v):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def matvec(M, v):\n    pass", L3: "def matvec(M, v):\n    pass", L4: "" },
    tests: [
    { name: "basic", code: "assert fn([[1,2],[3,4]],[1,1]) == [3,7]", hidden: false },
    { name: "identity", code: "assert fn([[1,0],[0,1]],[5,9]) == [5,9]", hidden: false },
    { name: "single", code: "assert fn([[2,0,1]],[3,3,4]) == [10]", hidden: false },
    { name: "negatives", code: "assert fn([[1,-1]],[4,7]) == [-3]", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Each output entry corresponds to one row of M." },
    { rung: 1, text: "That entry is the dot product of the row with v." },
    { rung: 2, text: "Map the dot product over the rows." }
    ],
    walkthrough: ["How many entries does the output have and why?", "What is output[i] in terms of M and v?", "How does adding a bias vector turn this into a full layer?", "Why must len(v) equal the number of columns of M?"],
    solution: "def matvec(M, v):\n    return [sum(a * b for a, b in zip(row, v)) for row in M]",
    language: "python",
    tracks: ["ml"],
    skills: ["linear-algebra"],
    analysis: { approach: "Dot each row of M with v.", invariant: "output[i] is the dot product of M's row i with v.", time: "O(m·n)", space: "O(m)" },
  },
  {
    id: "py.ml.numerical-gradient",
    kind: "problem",
    tier: "problem",
    title: "Numerical Gradient",
    pattern: "Calculus",
    teaches: ["py.ml.calculus"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 18,
    prompt: "Given a function `f` mapping a list of numbers to a single number, and a `point`, return the gradient at that point estimated by central differences: for each coordinate i, (f(point+h in i) - f(point-h in i)) / (2h). Default h=1e-5. This is how you sanity-check any hand-derived gradient.",
    exportName: "numerical_gradient",
    scaffolds: { L1: "def numerical_gradient(f, point, h=1e-5):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def numerical_gradient(f, point, h=1e-5):\n    pass", L3: "def numerical_gradient(f, point, h=1e-5):\n    pass", L4: "" },
    tests: [
    { name: "paraboloid", code: "def f(p):\n    return p[0]**2 + p[1]**2\ng = fn(f, [3.0, 4.0])\nassert abs(g[0]-6) < 1e-3 and abs(g[1]-8) < 1e-3", hidden: false },
    { name: "linear", code: "def f(p):\n    return 2*p[0] + 5*p[1]\ng = fn(f, [1.0, 1.0])\nassert abs(g[0]-2) < 1e-4 and abs(g[1]-5) < 1e-4", hidden: false },
    { name: "single var", code: "def f(p):\n    return p[0]**3\ng = fn(f, [2.0])\nassert abs(g[0]-12) < 1e-2", hidden: false },
    { name: "constant", code: "def f(p):\n    return 7.0\ng = fn(f, [1.0,2.0,3.0])\nassert all(abs(v) < 1e-6 for v in g)", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Perturb one coordinate at a time, up and down by h." },
    { rung: 1, text: "The slope in that coordinate is the symmetric difference quotient." },
    { rung: 2, text: "Copy the point before nudging so other coordinates stay fixed." }
    ],
    walkthrough: ["Why nudge only ONE coordinate for each partial derivative?", "Why is the central difference more accurate than a one-sided one?", "What does the gradient vector tell you about f at the point?", "Why must you copy `point` before mutating it?"],
    solution: "def numerical_gradient(f, point, h=1e-5):\n    grad = []\n    for i in range(len(point)):\n        up = list(point); up[i] += h\n        down = list(point); down[i] -= h\n        grad.append((f(up) - f(down)) / (2 * h))\n    return grad",
    language: "python",
    tracks: ["ml"],
    skills: ["calculus"],
    analysis: { approach: "Central difference per coordinate to build the gradient vector.", invariant: "grad holds the estimated partial derivatives for coordinates processed so far.", time: "O(len(point)·cost(f))", space: "O(len(point))" },
  },
  {
    id: "py.ml.sigmoid",
    kind: "problem",
    tier: "problem",
    title: "Sigmoid Activation",
    pattern: "Activations",
    teaches: ["py.ml.neural-nets"],
    requires: ["py.functions"],
    difficulty: { concept: 3, implementation: 2, recall: 2 },
    estimatedMinutes: 10,
    prompt: "Return the logistic sigmoid 1/(1+e^-x). It squashes any real number into (0,1), turning a score into a probability — the output unit of logistic regression.",
    exportName: "sigmoid",
    scaffolds: { L1: "import math\n\ndef sigmoid(x):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "import math\n\ndef sigmoid(x):\n    pass", L3: "import math\n\ndef sigmoid(x):\n    pass", L4: "" },
    tests: [
    { name: "zero", code: "assert abs(fn(0) - 0.5) < 1e-12", hidden: false },
    { name: "large positive", code: "assert fn(20) > 0.999", hidden: false },
    { name: "large negative", code: "assert fn(-20) < 0.001", hidden: false },
    { name: "symmetry", code: "assert abs(fn(2) + fn(-2) - 1.0) < 1e-9", hidden: true }
    ],
    hints: [
    { rung: 0, text: "e^-x is math.exp(-x)." },
    { rung: 1, text: "At x=0 the value is exactly 0.5." },
    { rung: 2, text: "Large positive x approaches 1; large negative approaches 0." }
    ],
    walkthrough: ["Why does sigmoid map the whole real line into (0,1)?", "What is sigmoid(0) and why?", "What symmetry relates sigmoid(x) and sigmoid(-x)?", "Why is a probability-shaped output useful for classification?"],
    solution: "import math\n\ndef sigmoid(x):\n    return 1.0 / (1.0 + math.exp(-x))",
    language: "python",
    tracks: ["ml"],
    skills: ["deep-learning"],
    analysis: { approach: "Direct logistic formula.", invariant: "Output always lies strictly between 0 and 1.", time: "O(1)", space: "O(1)" },
  },
  {
    id: "py.ml.mse",
    kind: "problem",
    tier: "problem",
    title: "Mean Squared Error",
    pattern: "Loss",
    teaches: ["py.ml.optimization"],
    requires: ["py.functions"],
    difficulty: { concept: 3, implementation: 2, recall: 2 },
    estimatedMinutes: 10,
    prompt: "Return the mean squared error between equal-length lists `y_true` and `y_pred`: the average of (true-pred)^2. This is the loss regression minimizes.",
    exportName: "mse",
    scaffolds: { L1: "def mse(y_true, y_pred):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def mse(y_true, y_pred):\n    pass", L3: "def mse(y_true, y_pred):\n    pass", L4: "" },
    tests: [
    { name: "perfect", code: "assert fn([1,2,3],[1,2,3]) == 0", hidden: false },
    { name: "off by one", code: "assert abs(fn([1,2,3],[2,3,4]) - 1.0) < 1e-9", hidden: false },
    { name: "mixed", code: "assert abs(fn([0,0],[1,3]) - 5.0) < 1e-9", hidden: false },
    { name: "single", code: "assert abs(fn([4],[1]) - 9.0) < 1e-9", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Take the difference at each position." },
    { rung: 1, text: "Square each difference so sign does not matter and big errors dominate." },
    { rung: 2, text: "Average over all positions." }
    ],
    walkthrough: ["Why square the errors instead of averaging raw differences?", "What MSE does a perfect prediction give?", "Why do large errors influence MSE disproportionately?", "How does squaring make the loss differentiable and convex for linear models?"],
    solution: "def mse(y_true, y_pred):\n    n = len(y_true)\n    return sum((t - p) ** 2 for t, p in zip(y_true, y_pred)) / n",
    language: "python",
    tracks: ["ml"],
    skills: ["optimization"],
    analysis: { approach: "Average of squared residuals.", invariant: "The sum accumulates squared residuals over the processed pairs.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.ml.minimize-quadratic",
    kind: "problem",
    tier: "problem",
    title: "Gradient Descent on x^2",
    pattern: "Gradient descent",
    teaches: ["py.ml.optimization"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 2, recall: 3 },
    estimatedMinutes: 16,
    prompt: "Minimize f(x) = x^2 by gradient descent. Its derivative is 2x, so each step is x <- x - learning_rate * 2x. Start at `start`, take `steps` iterations at `learning_rate`, and return the final x. With a sensible rate it should approach 0.",
    exportName: "minimize_quadratic",
    scaffolds: { L1: "def minimize_quadratic(start, learning_rate, steps):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def minimize_quadratic(start, learning_rate, steps):\n    pass", L3: "def minimize_quadratic(start, learning_rate, steps):\n    pass", L4: "" },
    tests: [
    { name: "converges", code: "assert abs(fn(10.0, 0.1, 100)) < 1e-3", hidden: false },
    { name: "already there", code: "assert fn(0.0, 0.1, 50) == 0.0", hidden: false },
    { name: "from negative", code: "assert abs(fn(-5.0, 0.1, 100)) < 1e-3", hidden: false },
    { name: "one step", code: "assert abs(fn(1.0, 0.1, 1) - 0.8) < 1e-9", hidden: true }
    ],
    hints: [
    { rung: 0, text: "The gradient of x^2 at x is 2x." },
    { rung: 1, text: "Step against the gradient: x -= lr*2x." },
    { rung: 2, text: "Repeat for the given number of steps." }
    ],
    walkthrough: ["Why do you move OPPOSITE the gradient to minimize?", "What happens to x each step when the rate is small and positive?", "What would too large a learning rate do here?", "Why does starting at 0 leave x unchanged?"],
    solution: "def minimize_quadratic(start, learning_rate, steps):\n    x = start\n    for _ in range(steps):\n        gradient = 2 * x\n        x = x - learning_rate * gradient\n    return x",
    language: "python",
    tracks: ["ml"],
    skills: ["optimization"],
    analysis: { approach: "Repeatedly step x against its gradient 2x.", invariant: "x holds the current estimate of the minimizer after each step.", time: "O(steps)", space: "O(1)" },
  },
  {
    id: "py.ml.mean-std",
    kind: "problem",
    tier: "problem",
    title: "Mean and Standard Deviation",
    pattern: "Statistics",
    teaches: ["py.ml.statistics"],
    requires: ["py.functions"],
    difficulty: { concept: 3, implementation: 2, recall: 2 },
    estimatedMinutes: 12,
    prompt: "Return a tuple `(mean, std)` for the numbers `xs`, using the POPULATION standard deviation (divide by n, not n-1). std is sqrt of the average squared deviation from the mean.",
    exportName: "mean_std",
    scaffolds: { L1: "import math\n\ndef mean_std(xs):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "import math\n\ndef mean_std(xs):\n    pass", L3: "import math\n\ndef mean_std(xs):\n    pass", L4: "" },
    tests: [
    { name: "basic", code: "m,s = fn([2,4,4,4,5,5,7,9]); assert m == 5.0 and abs(s-2.0) < 1e-9", hidden: false },
    { name: "constant", code: "m,s = fn([3,3,3]); assert m == 3.0 and s == 0.0", hidden: false },
    { name: "two", code: "m,s = fn([1,3]); assert m == 2.0 and abs(s-1.0) < 1e-9", hidden: false },
    { name: "single", code: "m,s = fn([7]); assert m == 7.0 and s == 0.0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "The mean is the sum over the count." },
    { rung: 1, text: "Variance is the average of squared deviations from that mean." },
    { rung: 2, text: "Std is the square root of variance." }
    ],
    walkthrough: ["Why compute the mean before the variance?", "What does a std of 0 tell you about the data?", "Why divide by n (population) rather than n-1 (sample) here?", "How does std summarize spread in the data's own units?"],
    solution: "import math\n\ndef mean_std(xs):\n    n = len(xs)\n    mean = sum(xs) / n\n    variance = sum((x - mean) ** 2 for x in xs) / n\n    return (mean, math.sqrt(variance))",
    language: "python",
    tracks: ["ml"],
    skills: ["statistics"],
    analysis: { approach: "Mean, then root of the average squared deviation.", invariant: "mean is finalized before any deviation is measured.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.ml.standardize",
    kind: "problem",
    tier: "problem",
    title: "Standardize (z-scores)",
    pattern: "Feature scaling",
    teaches: ["py.ml.statistics"],
    requires: ["py.functions"],
    difficulty: { concept: 3, implementation: 2, recall: 3 },
    estimatedMinutes: 14,
    prompt: "Return the z-scored version of `xs`: each value becomes (x-mean)/std using the population std. If std is 0, return a list of zeros. Standardizing features is what lets gradient descent converge quickly.",
    exportName: "standardize",
    scaffolds: { L1: "import math\n\ndef standardize(xs):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "import math\n\ndef standardize(xs):\n    pass", L3: "import math\n\ndef standardize(xs):\n    pass", L4: "" },
    tests: [
    { name: "basic", code: "r = fn([1,2,3]); assert abs(r[0]+1.2247) < 1e-3 and abs(r[1]) < 1e-9 and abs(r[2]-1.2247) < 1e-3", hidden: false },
    { name: "constant", code: "assert fn([5,5,5]) == [0.0,0.0,0.0]", hidden: false },
    { name: "mean zero std one", code: "r = fn([-1,1]); assert abs(r[0]+1) < 1e-9 and abs(r[1]-1) < 1e-9", hidden: false },
    { name: "length", code: "assert len(fn([2,4,6,8])) == 4", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Compute the mean and population std first." },
    { rung: 1, text: "Subtract the mean and divide by the std for each value." },
    { rung: 2, text: "Guard against a zero std to avoid dividing by zero." }
    ],
    walkthrough: ["What mean and std does the standardized output itself have?", "Why does unequal feature scale slow gradient descent?", "What is the right output when every value is identical?", "Why standardize using training statistics only, to avoid leakage?"],
    solution: "import math\n\ndef standardize(xs):\n    n = len(xs)\n    mean = sum(xs) / n\n    variance = sum((x - mean) ** 2 for x in xs) / n\n    std = math.sqrt(variance)\n    if std == 0:\n        return [0.0 for _ in xs]\n    return [(x - mean) / std for x in xs]",
    language: "python",
    tracks: ["ml"],
    skills: ["statistics", "preprocessing"],
    analysis: { approach: "Subtract the mean, divide by the std, with a zero-std guard.", invariant: "Each output is the signed number of standard deviations from the mean.", time: "O(n)", space: "O(n)" },
  },
  {
    id: "py.ml.pearson",
    kind: "problem",
    tier: "problem",
    title: "Pearson Correlation",
    pattern: "Statistics",
    teaches: ["py.ml.statistics"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 18,
    prompt: "Return the Pearson correlation coefficient between equal-length lists `xs` and `ys`: covariance divided by the product of the two population standard deviations. It lies in [-1, 1]. Return 0.0 if either has zero variance.",
    exportName: "pearson",
    scaffolds: { L1: "import math\n\ndef pearson(xs, ys):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "import math\n\ndef pearson(xs, ys):\n    pass", L3: "import math\n\ndef pearson(xs, ys):\n    pass", L4: "" },
    tests: [
    { name: "perfect positive", code: "assert abs(fn([1,2,3],[2,4,6]) - 1.0) < 1e-9", hidden: false },
    { name: "perfect negative", code: "assert abs(fn([1,2,3],[6,4,2]) + 1.0) < 1e-9", hidden: false },
    { name: "constant", code: "assert fn([1,2,3],[5,5,5]) == 0.0", hidden: false },
    { name: "uncorrelated-ish", code: "assert -1.0 <= fn([1,2,3,4],[1,3,2,4]) <= 1.0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Center both variables by subtracting their means." },
    { rung: 1, text: "Covariance sums the product of centered pairs." },
    { rung: 2, text: "Divide by the geometric mean of the two spreads to normalize into [-1,1]." }
    ],
    walkthrough: ["What does a coefficient of +1 versus -1 mean?", "Why divide covariance by the product of the standard deviations?", "Why is correlation undefined (here 0) when a variable is constant?", "Why does correlation not imply causation?"],
    solution: "import math\n\ndef pearson(xs, ys):\n    n = len(xs)\n    mx = sum(xs) / n\n    my = sum(ys) / n\n    cov = sum((x - mx) * (y - my) for x, y in zip(xs, ys))\n    vx = sum((x - mx) ** 2 for x in xs)\n    vy = sum((y - my) ** 2 for y in ys)\n    if vx == 0 or vy == 0:\n        return 0.0\n    return cov / math.sqrt(vx * vy)",
    language: "python",
    tracks: ["ml"],
    skills: ["statistics"],
    analysis: { approach: "Normalized covariance of the centered variables.", invariant: "cov, vx, vy accumulate centered products and squares in one pass each.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.ml.bayes-posterior",
    kind: "problem",
    tier: "problem",
    title: "Bayes' Theorem",
    pattern: "Probability",
    teaches: ["py.ml.probability"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 2, recall: 3 },
    estimatedMinutes: 16,
    prompt: "A test for a condition has true-positive rate `tpr` (P(positive|has it)) and false-positive rate `fpr` (P(positive|does not)). Given `prior` = P(has it), return the posterior P(has it | positive) via Bayes' theorem. This is the surprising 'most positives are false' result.",
    exportName: "bayes_posterior",
    scaffolds: { L1: "def bayes_posterior(prior, tpr, fpr):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def bayes_posterior(prior, tpr, fpr):\n    pass", L3: "def bayes_posterior(prior, tpr, fpr):\n    pass", L4: "" },
    tests: [
    { name: "rare disease", code: "assert abs(fn(0.01, 0.99, 0.05) - 0.166666) < 1e-4", hidden: false },
    { name: "certain test", code: "assert abs(fn(0.5, 1.0, 0.0) - 1.0) < 1e-9", hidden: false },
    { name: "useless test", code: "assert abs(fn(0.3, 0.5, 0.5) - 0.3) < 1e-9", hidden: false },
    { name: "zero prior", code: "assert fn(0.0, 0.9, 0.1) == 0.0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Posterior = P(positive and has) / P(positive)." },
    { rung: 1, text: "P(positive) sums the true positives and the false positives across the population." },
    { rung: 2, text: "Weight each branch by how much of the population it covers." }
    ],
    walkthrough: ["Why can a 99%-accurate test still be usually wrong on a positive for a rare condition?", "What two paths lead to a positive result?", "How does the prior (base rate) drive the answer?", "When a test's tpr equals its fpr, why does the posterior equal the prior?"],
    solution: "def bayes_posterior(prior, tpr, fpr):\n    positive_and_has = tpr * prior\n    positive_total = tpr * prior + fpr * (1 - prior)\n    if positive_total == 0:\n        return 0.0\n    return positive_and_has / positive_total",
    language: "python",
    tracks: ["ml"],
    skills: ["probability"],
    analysis: { approach: "Divide the true-positive mass by the total positive mass.", invariant: "Numerator is a part of the denominator, so the result stays in [0,1].", time: "O(1)", space: "O(1)" },
  },
  {
    id: "py.ml.linear-regression",
    kind: "problem",
    tier: "problem",
    title: "Simple Linear Regression",
    pattern: "Regression",
    teaches: ["py.ml.linear-regression"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 20,
    prompt: "Fit `y = slope*x + intercept` to paired data `xs`, `ys` by least squares. The closed form is slope = cov(x,y)/var(x) and intercept = mean(y) - slope*mean(x). Return `(slope, intercept)`.",
    exportName: "simple_linear_regression",
    scaffolds: { L1: "def simple_linear_regression(xs, ys):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def simple_linear_regression(xs, ys):\n    pass", L3: "def simple_linear_regression(xs, ys):\n    pass", L4: "" },
    tests: [
    { name: "exact line", code: "s,b = fn([1,2,3],[3,5,7]); assert abs(s-2) < 1e-9 and abs(b-1) < 1e-9", hidden: false },
    { name: "flat", code: "s,b = fn([1,2,3],[4,4,4]); assert abs(s) < 1e-9 and abs(b-4) < 1e-9", hidden: false },
    { name: "negative slope", code: "s,b = fn([0,1,2],[10,8,6]); assert abs(s+2) < 1e-9 and abs(b-10) < 1e-9", hidden: false },
    { name: "noisy", code: "s,b = fn([1,2,3,4],[2,4,5,9]); assert 1.5 < s < 2.5", hidden: true }
    ],
    hints: [
    { rung: 0, text: "The slope is the covariance of x and y over the variance of x." },
    { rung: 1, text: "The line must pass through the point (mean x, mean y)." },
    { rung: 2, text: "Use that to solve for the intercept once slope is known." }
    ],
    walkthrough: ["Why does the best-fit line pass through the mean of the data?", "What does slope = cov(x,y)/var(x) represent?", "How would you extend this to many features (the normal equation)?", "Why is squared error, not absolute error, minimized by this closed form?"],
    solution: "def simple_linear_regression(xs, ys):\n    n = len(xs)\n    mx = sum(xs) / n\n    my = sum(ys) / n\n    cov = sum((x - mx) * (y - my) for x, y in zip(xs, ys))\n    var = sum((x - mx) ** 2 for x in xs)\n    slope = cov / var\n    intercept = my - slope * mx\n    return (slope, intercept)",
    language: "python",
    tracks: ["ml"],
    skills: ["regression"],
    analysis: { approach: "Closed-form least squares from covariance and variance.", invariant: "cov and var accumulate the centered cross- and self-products.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.ml.r2-score",
    kind: "problem",
    tier: "problem",
    title: "R-squared",
    pattern: "Regression metric",
    teaches: ["py.ml.linear-regression"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 2, recall: 3 },
    estimatedMinutes: 14,
    prompt: "Return the coefficient of determination R^2 between `y_true` and `y_pred`: 1 - SS_res/SS_tot, where SS_res = sum (true-pred)^2 and SS_tot = sum (true-mean)^2. It is the fraction of variance the model explains. If SS_tot is 0, return 0.0.",
    exportName: "r2_score",
    scaffolds: { L1: "def r2_score(y_true, y_pred):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def r2_score(y_true, y_pred):\n    pass", L3: "def r2_score(y_true, y_pred):\n    pass", L4: "" },
    tests: [
    { name: "perfect", code: "assert abs(fn([1,2,3],[1,2,3]) - 1.0) < 1e-9", hidden: false },
    { name: "mean model", code: "assert abs(fn([1,2,3],[2,2,2])) < 1e-9", hidden: false },
    { name: "worse than mean", code: "assert fn([1,2,3],[3,2,1]) < 0", hidden: false },
    { name: "constant truth", code: "assert fn([5,5],[4,6]) == 0.0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "SS_res is the model's leftover squared error." },
    { rung: 1, text: "SS_tot is the error of always guessing the mean." },
    { rung: 2, text: "R^2 is one minus their ratio." }
    ],
    walkthrough: ["What baseline model does SS_tot correspond to?", "Why is R^2 = 1 a perfect fit?", "How can R^2 be negative, and what does that mean?", "Why does R^2 = 0 for a model that always predicts the mean?"],
    solution: "def r2_score(y_true, y_pred):\n    n = len(y_true)\n    mean = sum(y_true) / n\n    ss_res = sum((t - p) ** 2 for t, p in zip(y_true, y_pred))\n    ss_tot = sum((t - mean) ** 2 for t in y_true)\n    if ss_tot == 0:\n        return 0.0\n    return 1 - ss_res / ss_tot",
    language: "python",
    tracks: ["ml"],
    skills: ["regression", "metrics"],
    analysis: { approach: "Compare model residuals against the variance of the truth.", invariant: "ss_res and ss_tot accumulate the two competing error sums.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.ml.knn-classify",
    kind: "problem",
    tier: "problem",
    title: "k-Nearest Neighbors",
    pattern: "Instance-based",
    teaches: ["py.ml.knn"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 4, recall: 3 },
    estimatedMinutes: 22,
    prompt: "Classify `query` by majority vote of its k nearest neighbors among `train_x` (list of equal-length feature vectors) with labels `train_y`. Use squared Euclidean distance. Break ties by the smallest label value. Return the predicted label.",
    exportName: "knn_classify",
    scaffolds: { L1: "def knn_classify(train_x, train_y, query, k):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def knn_classify(train_x, train_y, query, k):\n    pass", L3: "def knn_classify(train_x, train_y, query, k):\n    pass", L4: "" },
    tests: [
    { name: "obvious", code: "assert fn([[0,0],[0,1],[10,10],[10,9]],[0,0,1,1],[0,0],1) == 0", hidden: false },
    { name: "vote", code: "assert fn([[0],[0],[10]],[0,0,1],[1],3) == 0", hidden: false },
    { name: "tie smaller label", code: "assert fn([[0],[2]],[1,0],[1],2) == 0", hidden: false },
    { name: "k1 nearest", code: "assert fn([[1],[5]],[7,9],[4],1) == 9", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Rank all training points by distance to the query." },
    { rung: 1, text: "Take the k closest and tally their labels." },
    { rung: 2, text: "On a vote tie, prefer the smaller label." }
    ],
    walkthrough: ["Why can you skip the square root when only comparing distances?", "What does k control in the bias-variance tradeoff?", "How is a tie in the vote resolved here?", "Why does kNN need no training but slow prediction?"],
    solution: "def knn_classify(train_x, train_y, query, k):\n    def dist2(a, b):\n        return sum((p - q) ** 2 for p, q in zip(a, b))\n    order = sorted(range(len(train_x)), key=lambda i: (dist2(train_x[i], query), train_y[i]))\n    votes = {}\n    for i in order[:k]:\n        label = train_y[i]\n        votes[label] = votes.get(label, 0) + 1\n    best = max(votes.values())\n    return min(label for label, count in votes.items() if count == best)",
    language: "python",
    tracks: ["ml"],
    skills: ["classification"],
    analysis: { approach: "Sort neighbors by distance, majority-vote the closest k.", invariant: "order lists training indices from nearest to farthest, ties by label.", time: "O(n·d + n log n)", space: "O(n)" },
  },
  {
    id: "py.ml.kmeans-step",
    kind: "problem",
    tier: "challenge",
    title: "k-Means: one Lloyd iteration",
    pattern: "Clustering",
    teaches: ["py.ml.kmeans"],
    requires: ["py.functions"],
    difficulty: { concept: 5, implementation: 4, recall: 4 },
    estimatedMinutes: 26,
    prompt: "Perform one k-means update: assign each point in `points` to its nearest centroid in `centroids` (squared Euclidean), then return NEW centroids, each the componentwise mean of its assigned points. A centroid with no points keeps its old position. Break assignment ties toward the smaller centroid index.",
    exportName: "kmeans_step",
    scaffolds: { L1: "def kmeans_step(points, centroids):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def kmeans_step(points, centroids):\n    pass", L3: "def kmeans_step(points, centroids):\n    pass", L4: "" },
    tests: [
    { name: "splits", code: "assert fn([[0,0],[0,2],[10,10],[10,12]],[[0,0],[10,10]]) == [[0.0,1.0],[10.0,11.0]]", hidden: false },
    { name: "empty keeps", code: "assert fn([[0,0],[0,0]],[[0,0],[9,9]]) == [[0.0,0.0],[9,9]]", hidden: false },
    { name: "one cluster", code: "assert fn([[2,2],[4,4]],[[3,3]]) == [[3.0,3.0]]", hidden: false },
    { name: "tie to lower index", code: "assert fn([[1,0]],[[0,0],[2,0]]) == [[1.0,0.0],[2,0]]", hidden: true }
    ],
    hints: [
    { rung: 0, text: "First assign every point to the nearest centroid." },
    { rung: 1, text: "Then move each centroid to the average of its members." },
    { rung: 2, text: "An empty cluster has no mean — leave that centroid where it was." }
    ],
    walkthrough: ["What two alternating steps make up Lloyd's algorithm?", "Why does the mean minimize within-cluster squared distance?", "What should happen to a centroid that captures no points?", "Why is k-means sensitive to the initial centroids?"],
    solution: "def kmeans_step(points, centroids):\n    def dist2(a, b):\n        return sum((p - q) ** 2 for p, q in zip(a, b))\n    groups = [[] for _ in centroids]\n    for point in points:\n        best = min(range(len(centroids)), key=lambda c: (dist2(point, centroids[c]), c))\n        groups[best].append(point)\n    new_centroids = []\n    for index, group in enumerate(groups):\n        if not group:\n            new_centroids.append(list(centroids[index]))\n        else:\n            dims = len(group[0])\n            new_centroids.append([sum(p[d] for p in group) / len(group) for d in range(dims)])\n    return new_centroids",
    language: "python",
    tracks: ["ml"],
    skills: ["clustering"],
    analysis: { approach: "Assign to nearest centroid, then recompute centroids as group means.", invariant: "groups[c] holds every point whose nearest centroid is c.", time: "O(points·k·d)", space: "O(points)" },
  },
  {
    id: "py.ml.entropy",
    kind: "problem",
    tier: "problem",
    title: "Entropy of a Label Set",
    pattern: "Decision trees",
    teaches: ["py.ml.decision-trees"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 18,
    prompt: "Return the Shannon entropy (in bits) of the label distribution in `labels`: -sum p*log2(p) over each label's proportion p. Pure sets score 0; a 50/50 split scores 1. An empty list scores 0.",
    exportName: "entropy",
    scaffolds: { L1: "import math\n\ndef entropy(labels):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "import math\n\ndef entropy(labels):\n    pass", L3: "import math\n\ndef entropy(labels):\n    pass", L4: "" },
    tests: [
    { name: "pure", code: "assert fn([1,1,1,1]) == 0.0", hidden: false },
    { name: "even split", code: "assert abs(fn([0,1,0,1]) - 1.0) < 1e-9", hidden: false },
    { name: "empty", code: "assert fn([]) == 0.0", hidden: false },
    { name: "three way", code: "assert abs(fn([0,1,2]) - 1.5849625007211562) < 1e-9", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Count each label, then turn counts into proportions." },
    { rung: 1, text: "Entropy sums -p*log2(p) over the proportions." },
    { rung: 2, text: "A pure set has one proportion of 1, contributing 0." }
    ],
    walkthrough: ["What does entropy measure about a label set?", "Why is a pure set's entropy exactly 0?", "Why does an even two-class split give exactly 1 bit?", "How will a decision tree use this to choose splits?"],
    solution: "import math\n\ndef entropy(labels):\n    n = len(labels)\n    if n == 0:\n        return 0.0\n    counts = {}\n    for label in labels:\n        counts[label] = counts.get(label, 0) + 1\n    total = 0.0\n    for count in counts.values():\n        p = count / n\n        total -= p * math.log2(p)\n    return total",
    language: "python",
    tracks: ["ml"],
    skills: ["decision-trees", "information-theory"],
    analysis: { approach: "Convert counts to proportions and sum -p*log2(p).", invariant: "counts holds the frequency of every label seen.", time: "O(n)", space: "O(distinct labels)" },
  },
  {
    id: "py.ml.information-gain",
    kind: "problem",
    tier: "challenge",
    title: "Information Gain",
    pattern: "Decision trees",
    teaches: ["py.ml.decision-trees"],
    requires: ["py.functions"],
    difficulty: { concept: 5, implementation: 3, recall: 4 },
    estimatedMinutes: 22,
    prompt: "Given `parent` labels and a `subsets` list (the label lists a split produces), return the information gain: entropy(parent) minus the size-weighted average entropy of the subsets. A decision tree picks the split with the highest gain.",
    exportName: "information_gain",
    scaffolds: { L1: "import math\n\ndef information_gain(parent, subsets):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "import math\n\ndef information_gain(parent, subsets):\n    pass", L3: "import math\n\ndef information_gain(parent, subsets):\n    pass", L4: "" },
    tests: [
    { name: "perfect split", code: "assert abs(fn([0,0,1,1], [[0,0],[1,1]]) - 1.0) < 1e-9", hidden: false },
    { name: "useless split", code: "assert abs(fn([0,0,1,1], [[0,1],[0,1]])) < 1e-9", hidden: false },
    { name: "pure parent", code: "assert fn([1,1,1], [[1],[1,1]]) == 0.0", hidden: false },
    { name: "nonneg", code: "assert fn([0,0,0,1], [[0,0],[0,1]]) >= 0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Compute the parent's entropy before splitting." },
    { rung: 1, text: "Each subset's entropy is weighted by its share of the rows." },
    { rung: 2, text: "Gain is the drop in entropy from parent to weighted children." }
    ],
    walkthrough: ["Why weight each subset's entropy by its size?", "What split maximizes information gain?", "Why can a split that preserves the class mix give zero gain?", "Why is information gain always non-negative?"],
    solution: "import math\n\ndef _entropy(labels):\n    n = len(labels)\n    if n == 0:\n        return 0.0\n    counts = {}\n    for label in labels:\n        counts[label] = counts.get(label, 0) + 1\n    total = 0.0\n    for count in counts.values():\n        p = count / n\n        total -= p * math.log2(p)\n    return total\n\ndef information_gain(parent, subsets):\n    n = len(parent)\n    if n == 0:\n        return 0.0\n    weighted = sum((len(part) / n) * _entropy(part) for part in subsets)\n    return _entropy(parent) - weighted",
    language: "python",
    tracks: ["ml"],
    skills: ["decision-trees"],
    analysis: { approach: "Parent entropy minus the weighted entropy of the split parts.", invariant: "weighted accumulates each part's entropy scaled by its row share.", time: "O(rows)", space: "O(distinct labels)" },
  },
  {
    id: "py.ml.precision-recall-f1",
    kind: "problem",
    tier: "problem",
    title: "Precision, Recall, F1",
    pattern: "Classification metrics",
    teaches: ["py.ml.metrics"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 20,
    prompt: "For binary labels (1 = positive, 0 = negative) in `y_true` and `y_pred`, return `(precision, recall, f1)`. precision = TP/(TP+FP), recall = TP/(TP+FN), f1 = harmonic mean 2*p*r/(p+r). Any metric whose denominator is 0 is 0.0.",
    exportName: "precision_recall_f1",
    scaffolds: { L1: "def precision_recall_f1(y_true, y_pred):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def precision_recall_f1(y_true, y_pred):\n    pass", L3: "def precision_recall_f1(y_true, y_pred):\n    pass", L4: "" },
    tests: [
    { name: "perfect", code: "p,r,f = fn([1,0,1,0],[1,0,1,0]); assert p==1.0 and r==1.0 and f==1.0", hidden: false },
    { name: "half precision", code: "p,r,f = fn([1,0],[1,1]); assert p==0.5 and r==1.0 and abs(f-0.6667)<1e-3", hidden: false },
    { name: "no positives predicted", code: "p,r,f = fn([1,1],[0,0]); assert p==0.0 and r==0.0 and f==0.0", hidden: false },
    { name: "recall half", code: "p,r,f = fn([1,1,0],[1,0,0]); assert p==1.0 and r==0.5", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Count true positives, false positives, and false negatives." },
    { rung: 1, text: "Precision asks: of predicted positives, how many were right?" },
    { rung: 2, text: "Recall asks: of actual positives, how many were caught? F1 balances the two." }
    ],
    walkthrough: ["What is the difference between precision and recall in one sentence each?", "When does optimizing precision hurt recall?", "Why use the harmonic mean for F1 rather than the arithmetic mean?", "Why guard every denominator against zero?"],
    solution: "def precision_recall_f1(y_true, y_pred):\n    tp = fp = fn = 0\n    for t, p in zip(y_true, y_pred):\n        if p == 1 and t == 1:\n            tp += 1\n        elif p == 1 and t == 0:\n            fp += 1\n        elif p == 0 and t == 1:\n            fn += 1\n    precision = tp / (tp + fp) if (tp + fp) else 0.0\n    recall = tp / (tp + fn) if (tp + fn) else 0.0\n    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0\n    return (precision, recall, f1)",
    language: "python",
    tracks: ["ml"],
    skills: ["metrics"],
    analysis: { approach: "Tally TP/FP/FN, then form the three metrics with zero-guards.", invariant: "tp, fp, fn count the confusion-matrix cells over processed pairs.", time: "O(n)", space: "O(1)" },
  },
  {
    id: "py.ml.softmax",
    kind: "problem",
    tier: "problem",
    title: "Softmax",
    pattern: "Activations",
    teaches: ["py.ml.softmax"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 18,
    prompt: "Return the softmax of `logits`: subtract the max for numerical stability, exponentiate, and normalize to sum to 1. This turns raw class scores into a probability distribution.",
    exportName: "softmax",
    scaffolds: { L1: "import math\n\ndef softmax(logits):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "import math\n\ndef softmax(logits):\n    pass", L3: "import math\n\ndef softmax(logits):\n    pass", L4: "" },
    tests: [
    { name: "uniform", code: "r = fn([0,0,0]); assert all(abs(v-1/3) < 1e-9 for v in r)", hidden: false },
    { name: "sums to one", code: "r = fn([1,2,3]); assert abs(sum(r) - 1.0) < 1e-9", hidden: false },
    { name: "monotonic", code: "r = fn([1,2,3]); assert r[0] < r[1] < r[2]", hidden: false },
    { name: "stable big", code: "r = fn([1000,1000]); assert abs(r[0]-0.5) < 1e-9", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Subtract the maximum logit before exponentiating to avoid overflow." },
    { rung: 1, text: "Exponentiate each shifted logit." },
    { rung: 2, text: "Divide by the total so the outputs sum to 1." }
    ],
    walkthrough: ["Why subtract the max — what does it prevent, and why is the result unchanged?", "Why must the outputs sum to 1?", "Why does a larger logit always get a larger probability?", "How does softmax generalize the sigmoid to many classes?"],
    solution: "import math\n\ndef softmax(logits):\n    shift = max(logits)\n    exps = [math.exp(z - shift) for z in logits]\n    total = sum(exps)\n    return [e / total for e in exps]",
    language: "python",
    tracks: ["ml"],
    skills: ["deep-learning"],
    analysis: { approach: "Shifted exponentials normalized to a distribution.", invariant: "Every output is positive and the outputs sum to 1.", time: "O(n)", space: "O(n)" },
  },
  {
    id: "py.ml.cross-entropy",
    kind: "problem",
    tier: "problem",
    title: "Cross-Entropy Loss",
    pattern: "Loss",
    teaches: ["py.ml.softmax"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 2, recall: 3 },
    estimatedMinutes: 16,
    prompt: "Given a probability distribution `probs` over classes and the correct class index `label`, return the categorical cross-entropy loss -ln(probs[label]) using the natural logarithm. This is the loss classifiers minimize after softmax.",
    exportName: "cross_entropy",
    scaffolds: { L1: "import math\n\ndef cross_entropy(probs, label):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "import math\n\ndef cross_entropy(probs, label):\n    pass", L3: "import math\n\ndef cross_entropy(probs, label):\n    pass", L4: "" },
    tests: [
    { name: "confident right", code: "assert fn([0.99,0.01], 0) < 0.02", hidden: false },
    { name: "uniform two", code: "assert abs(fn([0.5,0.5], 0) - 0.6931471805599453) < 1e-9", hidden: false },
    { name: "confident wrong", code: "assert fn([0.01,0.99], 0) > 4", hidden: false },
    { name: "perfect", code: "assert fn([1.0,0.0], 0) == 0.0", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Only the probability assigned to the TRUE class matters." },
    { rung: 1, text: "Loss is the negative natural log of that probability." },
    { rung: 2, text: "Guard against log(0) with a tiny floor." }
    ],
    walkthrough: ["Why does only probs[label] enter the loss?", "Why does a confident wrong answer incur a large loss?", "What loss does a perfectly confident correct answer give?", "How does this pair with softmax to give clean gradients?"],
    solution: "import math\n\ndef cross_entropy(probs, label):\n    p = probs[label]\n    if p <= 0:\n        p = 1e-12\n    return -math.log(p)",
    language: "python",
    tracks: ["ml"],
    skills: ["deep-learning"],
    analysis: { approach: "Negative log-probability of the true class.", invariant: "Loss is 0 only when the true class has probability 1.", time: "O(1)", space: "O(1)" },
  },
  {
    id: "py.ml.dense-forward",
    kind: "problem",
    tier: "problem",
    title: "Dense Layer Forward Pass",
    pattern: "Neural networks",
    teaches: ["py.ml.neural-nets"],
    requires: ["py.functions"],
    difficulty: { concept: 4, implementation: 3, recall: 3 },
    estimatedMinutes: 18,
    prompt: "Compute one dense (fully connected) layer with NO activation: given `inputs` (length n), `weights` (a list of output rows, each length n), and `biases` (length = number of outputs), return the output vector where output[j] = dot(weights[j], inputs) + biases[j].",
    exportName: "dense_forward",
    scaffolds: { L1: "def dense_forward(inputs, weights, biases):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "def dense_forward(inputs, weights, biases):\n    pass", L3: "def dense_forward(inputs, weights, biases):\n    pass", L4: "" },
    tests: [
    { name: "basic", code: "assert fn([1,2],[[1,0],[0,1]],[0,0]) == [1,2]", hidden: false },
    { name: "with bias", code: "assert fn([1,1],[[1,1]],[3]) == [5]", hidden: false },
    { name: "two neurons", code: "assert fn([2,3],[[1,1],[2,0]],[1,-1]) == [6,3]", hidden: false },
    { name: "negatives", code: "assert fn([1,-1],[[1,1]],[0]) == [0]", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Each output neuron owns one weight row and one bias." },
    { rung: 1, text: "Its pre-activation is the dot product of that row with the inputs." },
    { rung: 2, text: "Add the neuron's bias to that dot product." }
    ],
    walkthrough: ["What does each row of `weights` represent?", "Why is a layer just a matrix-vector product plus a bias?", "Where would an activation function be applied?", "How does stacking these with activations build a network?"],
    solution: "def dense_forward(inputs, weights, biases):\n    outputs = []\n    for row, bias in zip(weights, biases):\n        total = sum(w * x for w, x in zip(row, inputs))\n        outputs.append(total + bias)\n    return outputs",
    language: "python",
    tracks: ["ml"],
    skills: ["deep-learning"],
    analysis: { approach: "Per output neuron: dot its weight row with inputs, add its bias.", invariant: "outputs[j] is the completed pre-activation of neuron j.", time: "O(outputs·inputs)", space: "O(outputs)" },
  },
  {
    id: "py.ml.logistic-neuron-gradient",
    kind: "problem",
    tier: "challenge",
    title: "Logistic Neuron Gradient",
    pattern: "Backprop",
    teaches: ["py.ml.backprop"],
    requires: ["py.functions"],
    difficulty: { concept: 5, implementation: 4, recall: 4 },
    estimatedMinutes: 26,
    prompt: "For one logistic (sigmoid) neuron with weights `w`, bias `b`, input `features`, and binary target `label`, compute the gradient of the binary cross-entropy loss. The clean result is: prediction p = sigmoid(w·features + b); error = p - label; grad_w[i] = error*features[i]; grad_b = error. Return `(grad_w, grad_b)`.",
    exportName: "logistic_neuron_gradient",
    scaffolds: { L1: "import math\n\ndef logistic_neuron_gradient(features, label, w, b):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "import math\n\ndef logistic_neuron_gradient(features, label, w, b):\n    pass", L3: "import math\n\ndef logistic_neuron_gradient(features, label, w, b):\n    pass", L4: "" },
    tests: [
    { name: "zero weights", code: "gw,gb = fn([1,2], 1, [0,0], 0); assert abs(gb+0.5) < 1e-9 and abs(gw[0]+0.5) < 1e-9 and abs(gw[1]+1.0) < 1e-9", hidden: false },
    { name: "already correct pos", code: "gw,gb = fn([1.0], 1, [100.0], 0.0); assert abs(gb) < 1e-9", hidden: false },
    { name: "gradient sign", code: "gw,gb = fn([2.0], 0, [0.0], 0.0); assert gb > 0 and gw[0] > 0", hidden: false },
    { name: "shape", code: "gw,gb = fn([1,2,3], 1, [0,0,0], 0); assert len(gw) == 3", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Compute the neuron's output probability with the sigmoid." },
    { rung: 1, text: "The magic simplification: the gradient signal is just (prediction - label)." },
    { rung: 2, text: "Distribute that error onto each weight by multiplying by its input; the bias gets it directly." }
    ],
    walkthrough: ["Why does the sigmoid + cross-entropy pairing collapse the gradient to (p - label)?", "What does grad_w[i] = error*features[i] say about which weights change most?", "Why is grad_b simply the error?", "How would a gradient-descent step use these gradients?"],
    solution: "import math\n\ndef logistic_neuron_gradient(features, label, w, b):\n    z = sum(wi * xi for wi, xi in zip(w, features)) + b\n    p = 1.0 / (1.0 + math.exp(-z))\n    error = p - label\n    grad_w = [error * xi for xi in features]\n    grad_b = error\n    return (grad_w, grad_b)",
    language: "python",
    tracks: ["ml"],
    skills: ["deep-learning", "optimization"],
    analysis: { approach: "Forward to a probability, then backprop the error (p-label) onto weights and bias.", invariant: "error is the shared upstream signal distributed to every parameter.", time: "O(len(features))", space: "O(len(features))" },
  },
  {
    id: "py.ml.train-logistic",
    kind: "problem",
    tier: "challenge",
    title: "Train Logistic Regression",
    pattern: "Training loop",
    teaches: ["py.ml.logistic-regression", "py.ml.backprop"],
    requires: ["py.functions"],
    difficulty: { concept: 6, implementation: 5, recall: 5 },
    estimatedMinutes: 35,
    prompt: "Train a logistic regression classifier by full-batch gradient descent. `X` is a list of feature vectors, `y` their binary labels. Start weights and bias at 0. For `epochs` iterations, average the per-sample gradients (prediction - label, distributed onto weights) over all samples and step against them by `lr`. Return `(weights, bias)`.",
    exportName: "train_logistic",
    scaffolds: { L1: "import math\n\ndef train_logistic(X, y, lr, epochs):\n    pass\n\n# Plan the shapes, the math, and one worked example before coding.", L2: "import math\n\ndef train_logistic(X, y, lr, epochs):\n    pass", L3: "import math\n\ndef train_logistic(X, y, lr, epochs):\n    pass", L4: "" },
    tests: [
    { name: "separates 1d", code: "w,b = fn([[0.0],[1.0],[2.0],[3.0]], [0,0,1,1], 0.5, 2000)\ndef pred(x):\n    z = w[0]*x + b\n    return 1 if z >= 0 else 0\nassert [pred(0),pred(1),pred(2),pred(3)] == [0,0,1,1]", hidden: false },
    { name: "bias learns", code: "w,b = fn([[0.0],[0.0]], [0,1], 0.1, 10)\nassert isinstance(b, float)", hidden: false },
    { name: "weight shape", code: "w,b = fn([[1.0,2.0],[3.0,4.0]], [0,1], 0.1, 5)\nassert len(w) == 2", hidden: false },
    { name: "and gate", code: "w,b = fn([[0,0],[0,1],[1,0],[1,1]], [0,0,0,1], 0.5, 3000)\ndef pred(f):\n    z = sum(wi*fi for wi,fi in zip(w,f)) + b\n    return 1 if z >= 0 else 0\nassert [pred([0,0]),pred([0,1]),pred([1,0]),pred([1,1])] == [0,0,0,1]", hidden: true }
    ],
    hints: [
    { rung: 0, text: "Each epoch: accumulate gradients over every sample, then take one averaged step." },
    { rung: 1, text: "Per sample the gradient signal is (sigmoid(w·x+b) - label)." },
    { rung: 2, text: "Divide the summed gradient by n before stepping so the learning rate is scale-stable." }
    ],
    walkthrough: ["Why average the gradient over the batch before stepping?", "What role does the learning rate play in convergence?", "Why can logistic regression separate the AND gate but not XOR?", "How does this loop generalize to a full neural network's training?"],
    solution: "import math\n\ndef train_logistic(X, y, lr, epochs):\n    n = len(X)\n    dim = len(X[0])\n    w = [0.0] * dim\n    b = 0.0\n    for _ in range(epochs):\n        grad_w = [0.0] * dim\n        grad_b = 0.0\n        for features, label in zip(X, y):\n            z = sum(wi * xi for wi, xi in zip(w, features)) + b\n            p = 1.0 / (1.0 + math.exp(-z))\n            error = p - label\n            for i in range(dim):\n                grad_w[i] += error * features[i]\n            grad_b += error\n        for i in range(dim):\n            w[i] -= lr * grad_w[i] / n\n        b -= lr * grad_b / n\n    return (w, b)",
    language: "python",
    tracks: ["ml"],
    skills: ["deep-learning", "optimization"],
    analysis: { approach: "Repeatedly average per-sample logistic gradients and descend.", invariant: "(w, b) hold the current parameters; each epoch reduces average loss.", time: "O(epochs·n·dim)", space: "O(dim)" },
  },
];
